/* Formatted on 12-15-2018 9:41:51 AM (QP5 v5.126.903.23003) */
DROP TABLE PRS.LEAVE_DOC_ATTCHMNTS  CASCADE CONSTRAINTS PURGE;

CREATE TABLE PRS.LEAVE_DOC_ATTCHMNTS (
   ATTCHMNT_ID         NUMBER NOT NULL,
   PLAN_EXECUTION_ID   NUMBER NOT NULL,
   ATTCHMNT_DESC       VARCHAR2 (500) NOT NULL,
   FILE_NAME           VARCHAR2 (300) NOT NULL,
   CREATED_BY          NUMBER NOT NULL,
   CREATION_DATE       VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY      NUMBER NOT NULL,
   LAST_UPDATE_DATE    VARCHAR2 (21) NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX PRS.IDX_LVE_ATTCHMNT_ID
   ON PRS.LEAVE_DOC_ATTCHMNTS (ATTCHMNT_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE PRS.LEAVE_DOC_ATTCHMNTS ADD (
CONSTRAINT PK_LVE_ATTCHMNT_ID
PRIMARY KEY
(ATTCHMNT_ID));


CREATE INDEX PRS.IDX_LVE_PLAN_EXECUTION_ID
   ON PRS.LEAVE_DOC_ATTCHMNTS (PLAN_EXECUTION_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PRS.IDX_LVE_ATTCHMNT_DESC
   ON PRS.LEAVE_DOC_ATTCHMNTS (ATTCHMNT_DESC)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE PRS.LEAVE_DOC_ATTCHMNTS_SEQ;

CREATE SEQUENCE PRS.LEAVE_DOC_ATTCHMNTS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER PRS.LEAVE_DOC_ATTCHMNTS_TRG
   BEFORE INSERT
   ON PRS.LEAVE_DOC_ATTCHMNTS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.ATTCHMNT_ID IS NULL)
DECLARE
   V_ID   PRS.LEAVE_DOC_ATTCHMNTS.ATTCHMNT_ID%TYPE;
BEGIN
   SELECT   PRS.LEAVE_DOC_ATTCHMNTS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.ATTCHMNT_ID := V_ID;
END LEAVE_DOC_ATTCHMNTS_TRG;