/* Formatted on 12-15-2018 10:12:00 AM (QP5 v5.126.903.23003) */
DROP TABLE PRS.PRSN_EXTRA_DATA_COLS  CASCADE CONSTRAINTS PURGE;

CREATE TABLE PRS.PRSN_EXTRA_DATA_COLS (
   EXTRA_DATA_COLS_ID     NUMBER NOT NULL,
   COLUMN_NO              NUMBER,
   COLUMN_LABEL           VARCHAR2 (300 BYTE),
   ATTCHD_LOV_NAME        VARCHAR2 (300 BYTE),
   COLUMN_DATA_TYPE       VARCHAR2 (100 BYTE),                      -- E.G....
   COLUMN_DATA_CATEGORY   VARCHAR2 (300 BYTE),
   DATA_LENGTH            NUMBER,
   DATA_DSPLY_TYPE        VARCHAR2 (1 BYTE),                    -- E.G. T OR D
   ORG_ID                 NUMBER NOT NULL,
   NO_COLS_TBLR_DSPLY     NUMBER,
   COL_ORDER              NUMBER DEFAULT 1 NOT NULL,
   CSV_TBLR_COL_NMS       CLOB,
   CREATED_BY             NUMBER DEFAULT (-1) NOT NULL,
   CREATION_DATE          VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY         NUMBER DEFAULT (-1) NOT NULL,
   LAST_UPDATE_DATE       VARCHAR2 (21 BYTE) NOT NULL,
   IS_REQUIRED            VARCHAR2 (1 BYTE) DEFAULT '0' NOT NULL,
   CONSTRAINT PK_EXTR_DTA_COL_ID PRIMARY KEY (EXTRA_DATA_COLS_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX PRS.IDX_COLUMN_NO
   ON PRS.PRSN_EXTRA_DATA_COLS (COLUMN_NO)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE PRS.PRSN_EXTRA_DATA_COLS_SEQ;

CREATE SEQUENCE PRS.PRSN_EXTRA_DATA_COLS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER PRS.PRSN_EXTRA_DATA_COLS_TRG
   BEFORE INSERT
   ON PRS.PRSN_EXTRA_DATA_COLS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.EXTRA_DATA_COLS_ID IS NULL)
DECLARE
   V_ID   PRS.PRSN_EXTRA_DATA_COLS.EXTRA_DATA_COLS_ID%TYPE;
BEGIN
   SELECT   PRS.PRSN_EXTRA_DATA_COLS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.EXTRA_DATA_COLS_ID := V_ID;
END PRSN_EXTRA_DATA_COLS_TRG;