/* Formatted on 12-15-2018 9:36:32 AM (QP5 v5.126.903.23003) */
DROP TABLE PRS.HR_PERSON_ABSENCES  CASCADE CONSTRAINTS PURGE;

CREATE TABLE PRS.HR_PERSON_ABSENCES (
   ABSENCE_ID           NUMBER NOT NULL,
   PLAN_EXECUTION_ID    NUMBER NOT NULL,
   PERSON_ID            NUMBER NOT NULL,
   ABSENCE_START_DATE   VARCHAR2 (21) NOT NULL,
   NO_OF_DAYS           INTEGER NOT NULL,
   ABSENCE_END_DATE     VARCHAR2 (21) NOT NULL,
   ABSENCE_REASON       VARCHAR2 (500) NOT NULL,
   ABSENCE_STATUS       VARCHAR2 (10) NOT NULL,   -- SCHEDULED,TAKEN,REQUESTED
   CREATED_BY           NUMBER DEFAULT -1 NOT NULL,
   CREATION_DATE        VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY       NUMBER DEFAULT -1 NOT NULL,
   LAST_UPDATE_DATE     VARCHAR2 (21) NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX PRS.IDX_AB_ABSENCE_ID
   ON PRS.HR_PERSON_ABSENCES (ABSENCE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE PRS.HR_PERSON_ABSENCES ADD (
CONSTRAINT PK_AB_ABSENCE_ID
PRIMARY KEY
(ABSENCE_ID));


CREATE INDEX PRS.IDX_AB_PLAN_EXECUTION_ID
   ON PRS.HR_PERSON_ABSENCES (PLAN_EXECUTION_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PRS.IDX_AB_PERSON_ID
   ON PRS.HR_PERSON_ABSENCES (PERSON_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PRS.IDX_AB_ABSENCE_START_DATE
   ON PRS.HR_PERSON_ABSENCES (ABSENCE_START_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PRS.IDX_AB_ABSENCE_END_DATE
   ON PRS.HR_PERSON_ABSENCES (ABSENCE_END_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PRS.IDX_AB_ABSENCE_STATUS
   ON PRS.HR_PERSON_ABSENCES (ABSENCE_STATUS)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE PRS.HR_PERSON_ABSENCES_SEQ;

CREATE SEQUENCE PRS.HR_PERSON_ABSENCES_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER PRS.HR_PERSON_ABSENCES_TRG
   BEFORE INSERT
   ON PRS.HR_PERSON_ABSENCES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.ABSENCE_ID IS NULL)
DECLARE
   V_ID   PRS.HR_PERSON_ABSENCES.ABSENCE_ID%TYPE;
BEGIN
   SELECT   PRS.HR_PERSON_ABSENCES_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.ABSENCE_ID := V_ID;
END HR_PERSON_ABSENCES_TRG;