/* Formatted on 12-15-2018 9:43:29 AM (QP5 v5.126.903.23003) */
DROP TABLE PRS.PRSN_ALL_OTHER_INFO_TABLE  CASCADE CONSTRAINTS PURGE;

CREATE TABLE PRS.PRSN_ALL_OTHER_INFO_TABLE (
   DFLT_ROW_ID               NUMBER NOT NULL,
   TBL_OTHR_INF_COMBNTN_ID   NUMBER NOT NULL,
   ROW_PK_ID_VAL             NUMBER NOT NULL,
   OTHER_INFO_VALUE          CLOB,
   CREATED_BY                NUMBER NOT NULL,
   CREATION_DATE             VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY            NUMBER NOT NULL,
   LAST_UPDATE_DATE          VARCHAR2 (21 BYTE) NOT NULL,
   OTHER_INFO_LABEL          CLOB,
   OTHER_INFO_CATEGORY       VARCHAR2 (200)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX PRS.IDX_DFLT_ROW_ID_OI
   ON PRS.PRSN_ALL_OTHER_INFO_TABLE (DFLT_ROW_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE PRS.PRSN_ALL_OTHER_INFO_TABLE ADD (
CONSTRAINT PK_DFLT_ROW_ID_OI
PRIMARY KEY
(DFLT_ROW_ID));


CREATE INDEX PRS.IDX_ROW_PK_ID_VAL
   ON PRS.PRSN_ALL_OTHER_INFO_TABLE (ROW_PK_ID_VAL)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PRS.IDX_TBL_OTHR_INF_COMBNTN_ID
   ON PRS.PRSN_ALL_OTHER_INFO_TABLE (TBL_OTHR_INF_COMBNTN_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE PRS.PRSN_ALL_OTHER_INFO_TABLE_SEQ;

CREATE SEQUENCE PRS.PRSN_ALL_OTHER_INFO_TABLE_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER PRS.PRSN_ALL_OTHER_INFO_TABLE_TRG
   BEFORE INSERT
   ON PRS.PRSN_ALL_OTHER_INFO_TABLE
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.DFLT_ROW_ID IS NULL)
DECLARE
   V_ID   PRS.PRSN_ALL_OTHER_INFO_TABLE.DFLT_ROW_ID%TYPE;
BEGIN
   SELECT   PRS.PRSN_ALL_OTHER_INFO_TABLE_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.DFLT_ROW_ID := V_ID;
END PRSN_ALL_OTHER_INFO_TABLE_TRG;