/* Formatted on 12-15-2018 9:48:22 AM (QP5 v5.126.903.23003) */
DROP TABLE PRS.PRSN_EDUCATION  CASCADE CONSTRAINTS PURGE;

CREATE TABLE PRS.PRSN_EDUCATION (
   PERSON_ID            NUMBER NOT NULL,
   COURSE_NAME          VARCHAR2 (200 BYTE),
   SCHOOL_INSTITUTION   VARCHAR2 (200 BYTE),
   SCHOOL_LOCATION      VARCHAR2 (200 BYTE),
   CERT_OBTAINED        VARCHAR2 (200 BYTE),
   COURSE_START_DATE    VARCHAR2 (12 BYTE) NOT NULL,
   COURSE_END_DATE      VARCHAR2 (12 BYTE) NOT NULL,
   DATE_CERT_AWARDED    VARCHAR2 (12 BYTE),
   CREATED_BY           NUMBER NOT NULL,
   CREATION_DATE        VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY       NUMBER NOT NULL,
   LAST_UPDATE_DATE     VARCHAR2 (21 BYTE) NOT NULL,
   CERT_TYPE            VARCHAR2 (200 BYTE),
   EDUC_ID              NUMBER NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX PRS.IDX_EDUC_ID
   ON PRS.PRSN_EDUCATION (EDUC_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE PRS.PRSN_EDUCATION ADD (
CONSTRAINT PK_EDUC_ID
PRIMARY KEY
(EDUC_ID));

CREATE INDEX PRS.IDX_CERT_OBTAINED
   ON PRS.PRSN_EDUCATION (CERT_OBTAINED)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE INDEX PRS.IDX_CERT_TYPE
   ON PRS.PRSN_EDUCATION (CERT_TYPE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE INDEX PRS.IDX_COURSE_NAME
   ON PRS.PRSN_EDUCATION (COURSE_NAME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE INDEX PRS.IDX_ED_PERSON_ID
   ON PRS.PRSN_EDUCATION (PERSON_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE INDEX PRS.IDX_SCHOOL_INSTITUTION
   ON PRS.PRSN_EDUCATION (SCHOOL_INSTITUTION)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE PRS.PRSN_EDUCATION_SEQ;

CREATE SEQUENCE PRS.PRSN_EDUCATION_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER PRS.PRSN_EDUCATION_TRG
   BEFORE INSERT
   ON PRS.PRSN_EDUCATION
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.EDUC_ID IS NULL)
DECLARE
   V_ID   PRS.PRSN_EDUCATION.EDUC_ID%TYPE;
BEGIN
   SELECT   PRS.PRSN_EDUCATION_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.EDUC_ID := V_ID;
END PRSN_EDUCATION_TRG;