/* Formatted on 12-15-2018 10:14:31 AM (QP5 v5.126.903.23003) */
DROP TABLE PRS.PRSN_NAMES_NOS  CASCADE CONSTRAINTS PURGE;

CREATE TABLE PRS.PRSN_NAMES_NOS (
   PERSON_ID           NUMBER NOT NULL,
   CREATED_BY          NUMBER NOT NULL,
   CREATION_DATE       VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY      NUMBER NOT NULL,
   LAST_UPDATE_DATE    VARCHAR2 (21 BYTE) NOT NULL,
   FIRST_NAME          VARCHAR2 (100 BYTE),
   SUR_NAME            VARCHAR2 (100 BYTE),
   OTHER_NAMES         VARCHAR2 (100 BYTE),
   TITLE               VARCHAR2 (100 BYTE),
   LOCAL_ID_NO         VARCHAR2 (100 BYTE) DEFAULT 0 NOT NULL,
   ORG_ID              INTEGER DEFAULT (-1) NOT NULL,
   GENDER              VARCHAR2 (20 BYTE),
   MARITAL_STATUS      VARCHAR2 (30 BYTE),
   DATE_OF_BIRTH       VARCHAR2 (12 BYTE),
   PLACE_OF_BIRTH      VARCHAR2 (300 BYTE),
   RELIGION            VARCHAR2 (300 BYTE),
   RES_ADDRESS         VARCHAR2 (200 BYTE),
   PSTL_ADDRS          VARCHAR2 (200 BYTE),
   EMAIL               VARCHAR2 (100 BYTE),
   CNTCT_NO_TEL        VARCHAR2 (100 BYTE),
   CNTCT_NO_MOBL       VARCHAR2 (100 BYTE),
   CNTCT_NO_FAX        VARCHAR2 (100 BYTE),
   IMG_LOCATION        VARCHAR2 (500 BYTE),
   HOMETOWN            VARCHAR2 (300 BYTE),
   NATIONALITY         VARCHAR2 (300 BYTE),
   LNKD_FIRM_ORG_ID    NUMBER DEFAULT -1 NOT NULL, -- LINKED CUSTOMER/SUPPLIER
   LNKD_FIRM_SITE_ID   NUMBER DEFAULT -1 NOT NULL,
   NEW_COMPANY         VARCHAR2 (300),
   NEW_COMPANY_LOC     VARCHAR2 (300)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX PRS.IDX_PERSON_ID
   ON PRS.PRSN_NAMES_NOS (PERSON_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE PRS.PRSN_NAMES_NOS ADD (
CONSTRAINT PK_PERSON_ID
PRIMARY KEY
(PERSON_ID));

CREATE INDEX PRS.IDX_FIRST_NAME
   ON PRS.PRSN_NAMES_NOS (FIRST_NAME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE UNIQUE INDEX PRS.IDX_LOCAL_ID_NO
   ON PRS.PRSN_NAMES_NOS (LOCAL_ID_NO)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PRS.IDX_OTHER_NAMES
   ON PRS.PRSN_NAMES_NOS (OTHER_NAMES)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE INDEX PRS.IDX_SUR_NAME
   ON PRS.PRSN_NAMES_NOS (SUR_NAME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PRS.IDX_TITLE
   ON PRS.PRSN_NAMES_NOS (TITLE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE PRS.PRSN_NAMES_NOS_SEQ;

CREATE SEQUENCE PRS.PRSN_NAMES_NOS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER PRS.PRSN_NAMES_NOS_TRG
   BEFORE INSERT
   ON PRS.PRSN_NAMES_NOS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.PERSON_ID IS NULL)
DECLARE
   V_ID   PRS.PRSN_NAMES_NOS.PERSON_ID%TYPE;
BEGIN
   SELECT   PRS.PRSN_NAMES_NOS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PERSON_ID := V_ID;
END PRSN_NAMES_NOS_TRG;