/* Formatted on 12-15-2018 9:45:56 AM (QP5 v5.126.903.23003) */
DROP TABLE PRS.PRSN_DOC_ATTCHMNTS  CASCADE CONSTRAINTS PURGE;

CREATE TABLE PRS.PRSN_DOC_ATTCHMNTS (
   ATTCHMNT_ID        NUMBER NOT NULL,
   PERSON_ID          NUMBER NOT NULL,
   ATTCHMNT_DESC      VARCHAR2 (500 BYTE) NOT NULL,
   FILE_NAME          VARCHAR2 (50 BYTE) NOT NULL,
   CREATED_BY         NUMBER NOT NULL,
   CREATION_DATE      VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY     NUMBER NOT NULL,
   LAST_UPDATE_DATE   VARCHAR2 (21 BYTE) NOT NULL,
   CONSTRAINT PK_ATTCHMNT_ID PRIMARY KEY (ATTCHMNT_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX PRS.IDX_ATTCHMNT_DESC
   ON PRS.PRSN_DOC_ATTCHMNTS (ATTCHMNT_DESC)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PRS.IDX_ATTCHMT_PERSON_ID
   ON PRS.PRSN_DOC_ATTCHMNTS (PERSON_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE PRS.PRSN_DOC_ATTCHMNTS_SEQ;

CREATE SEQUENCE PRS.PRSN_DOC_ATTCHMNTS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER PRS.PRSN_DOC_ATTCHMNTS_TRG
   BEFORE INSERT
   ON PRS.PRSN_DOC_ATTCHMNTS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.ATTCHMNT_ID IS NULL)
DECLARE
   V_ID   PRS.PRSN_DOC_ATTCHMNTS.ATTCHMNT_ID%TYPE;
BEGIN
   SELECT   PRS.PRSN_DOC_ATTCHMNTS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.ATTCHMNT_ID := V_ID;
END PRSN_DOC_ATTCHMNTS_TRG;