/* Formatted on 12-15-2018 9:29:06 AM (QP5 v5.126.903.23003) */
DROP TABLE PRS.HR_ACCRUAL_PLANS  CASCADE CONSTRAINTS PURGE;

CREATE TABLE PRS.HR_ACCRUAL_PLANS (
   ACCRUAL_PLAN_ID             NUMBER NOT NULL,
   ACCRUAL_PLAN_NAME           VARCHAR2 (200) NOT NULL,
   ACCRUAL_PLAN_DESC           VARCHAR2 (300) NOT NULL,
   PLAN_EXECUTION_INTRVLS      VARCHAR2 (50) NOT NULL,
   ACCRUAL_START_DATE          VARCHAR2 (21) NOT NULL,
   ACCRUAL_END_DATE            VARCHAR2 (21) NOT NULL,
   LNKD_BALANCE_ITEM_ID        INTEGER NOT NULL,
   LNKD_BALNC_ADD_ITEM_ID      INTEGER NOT NULL,
   LNKD_BALNC_SBTRCT_ITEM_ID   INTEGER NOT NULL,
   CAN_EXCD_ENTLTLMNT          VARCHAR2 (1) DEFAULT 0 NOT NULL,
   ORG_ID                      INTEGER NOT NULL,
   CREATED_BY                  NUMBER DEFAULT -1 NOT NULL,
   CREATION_DATE               VARCHAR2 (200) NOT NULL,
   LAST_UPDATE_BY              NUMBER DEFAULT -1 NOT NULL,
   LAST_UPDATE_DATE            VARCHAR2 (21) NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX PRS.IDX_AP_ACCRUAL_PLAN_ID
   ON PRS.HR_ACCRUAL_PLANS (ACCRUAL_PLAN_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE PRS.HR_ACCRUAL_PLANS ADD (
CONSTRAINT pk_ap_accrual_plan_id
PRIMARY KEY
(ACCRUAL_PLAN_ID));


CREATE INDEX PRS.IDX_AP_ACCRUAL_PLAN_NAME
   ON PRS.HR_ACCRUAL_PLANS (ACCRUAL_PLAN_NAME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PRS.IDX_AP_ACCRUAL_PLAN_DESC
   ON PRS.HR_ACCRUAL_PLANS (ACCRUAL_PLAN_DESC)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE PRS.HR_ACCRUAL_PLANS_SEQ;

CREATE SEQUENCE PRS.HR_ACCRUAL_PLANS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER PRS.HR_ACCRUAL_PLANS_TRG
   BEFORE INSERT
   ON PRS.HR_ACCRUAL_PLANS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.ACCRUAL_PLAN_ID IS NULL)
DECLARE
   V_ID   PRS.HR_ACCRUAL_PLANS.ACCRUAL_PLAN_ID%TYPE;
BEGIN
   SELECT   PRS.HR_ACCRUAL_PLANS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.ACCRUAL_PLAN_ID := V_ID;
END HR_ACCRUAL_PLANS_TRG;