/* Formatted on 12-15-2018 10:17:40 AM (QP5 v5.126.903.23003) */
DROP TABLE PRS.PRSN_NATIONAL_IDS  CASCADE CONSTRAINTS PURGE;

CREATE TABLE PRS.PRSN_NATIONAL_IDS (
   PERSON_ID          NUMBER NOT NULL,
   NATIONALITY        VARCHAR2 (100 BYTE),
   ID_NUMBER          VARCHAR2 (100 BYTE),
   CREATED_BY         NUMBER NOT NULL,
   CREATION_DATE      VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY     NUMBER NOT NULL,
   LAST_UPDATE_DATE   VARCHAR2 (21 BYTE) NOT NULL,
   NTNLTY_ID          NUMBER NOT NULL,
   NATIONAL_ID_TYP    VARCHAR2 (100),
   DATE_ISSUED        VARCHAR2 (12),
   EXPIRY_DATE        VARCHAR2 (12),
   OTHER_INFO         VARCHAR2 (500),
   CONSTRAINT PK_NTNLTY_ID PRIMARY KEY (NTNLTY_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX PRS.IDX_ID_NUMBER
   ON PRS.PRSN_NATIONAL_IDS (ID_NUMBER)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PRS.IDX_N_PERSON_ID
   ON PRS.PRSN_NATIONAL_IDS (PERSON_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PRS.IDX_NATIONALITY
   ON PRS.PRSN_NATIONAL_IDS (NATIONALITY)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE PRS.PRSN_NATIONAL_IDS_SEQ;

CREATE SEQUENCE PRS.PRSN_NATIONAL_IDS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER PRS.PRSN_NATIONAL_IDS_TRG
   BEFORE INSERT
   ON PRS.PRSN_NATIONAL_IDS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.NTNLTY_ID IS NULL)
DECLARE
   V_ID   PRS.PRSN_NATIONAL_IDS.NTNLTY_ID%TYPE;
BEGIN
   SELECT   PRS.PRSN_NATIONAL_IDS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.NTNLTY_ID := V_ID;
END PRSN_NATIONAL_IDS_TRG;