/* Formatted on 12-15-2018 10:22:52 AM (QP5 v5.126.903.23003) */
DROP TABLE PRS.PRSN_SKILLS_NATURE  CASCADE CONSTRAINTS PURGE;

CREATE TABLE PRS.PRSN_SKILLS_NATURE (
   PERSON_ID          NUMBER NOT NULL,
   LANGUAGES          VARCHAR2 (300 BYTE),
   HOBBIES            VARCHAR2 (300 BYTE),
   INTERESTS          VARCHAR2 (300 BYTE),
   CONDUCT            VARCHAR2 (300 BYTE),
   ATTITUDE           VARCHAR2 (300 BYTE),
   VALID_START_DATE   VARCHAR2 (12 BYTE) NOT NULL,
   VALID_END_DATE     VARCHAR2 (12 BYTE) NOT NULL,
   CREATED_BY         NUMBER NOT NULL,
   CREATION_DATE      VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY     NUMBER NOT NULL,
   LAST_UPDATE_DATE   VARCHAR2 (21 BYTE) NOT NULL,
   SKILLS_ID          NUMBER NOT NULL,
   CONSTRAINT PK_SKILLS_ID PRIMARY KEY (SKILLS_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX PRS.IDX_ATTITUDE
   ON PRS.PRSN_SKILLS_NATURE (ATTITUDE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PRS.IDX_CONDUCT
   ON PRS.PRSN_SKILLS_NATURE (CONDUCT)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PRS.IDX_HOBBIES
   ON PRS.PRSN_SKILLS_NATURE (HOBBIES)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PRS.IDX_INTERESTS
   ON PRS.PRSN_SKILLS_NATURE (INTERESTS)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PRS.IDX_LANGUAGES
   ON PRS.PRSN_SKILLS_NATURE (LANGUAGES)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PRS.IDX_SK_PERSON_ID
   ON PRS.PRSN_SKILLS_NATURE (PERSON_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PRS.IDX_VALID_END_DATE
   ON PRS.PRSN_SKILLS_NATURE (VALID_END_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE INDEX PRS.IDX_VALID_START_DATE
   ON PRS.PRSN_SKILLS_NATURE (VALID_START_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE PRS.PRSN_SKILLS_NATURE_SEQ;

CREATE SEQUENCE PRS.PRSN_SKILLS_NATURE_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER PRS.PRSN_SKILLS_NATURE_TRG
   BEFORE INSERT
   ON PRS.PRSN_SKILLS_NATURE
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.SKILLS_ID IS NULL)
DECLARE
   V_ID   PRS.PRSN_SKILLS_NATURE.SKILLS_ID%TYPE;
BEGIN
   SELECT   PRS.PRSN_SKILLS_NATURE_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.SKILLS_ID := V_ID;
END PRSN_SKILLS_NATURE_TRG;