/* Formatted on 9/13/2014 9:29:43 PM (QP5 v5.126.903.23003) */
CREATE TABLE GST.GEN_STP_AUDIT_TRAIL_TBL (
   USER_ID          NUMBER NOT NULL,
   ACTION_TYPE      VARCHAR2 (30 BYTE),
   ACTION_DETAILS   CLOB,
   ACTION_TIME      VARCHAR2 (21 BYTE),
   LOGIN_NUMBER     NUMBER,
   DFLT_ROW_ID      NUMBER NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX GST.IDX_ADT_DFLT_ROW_ID
   ON GST.GEN_STP_AUDIT_TRAIL_TBL (DFLT_ROW_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE SEQUENCE GST.GEN_STP_AUDIT_TRAIL_TBL_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

ALTER TABLE GST.GEN_STP_AUDIT_TRAIL_TBL ADD (
  CONSTRAINT PK_DFLT_ROW_ID
 PRIMARY KEY
 (DFLT_ROW_ID));

CREATE INDEX GST.IDX_LOGIN_NUMBER
   ON GST.GEN_STP_AUDIT_TRAIL_TBL (LOGIN_NUMBER)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

--DROP INDEX GST.IDX_USER_ID;

CREATE INDEX GST.IDX_USER_ID
   ON GST.GEN_STP_AUDIT_TRAIL_TBL (USER_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE OR REPLACE TRIGGER GST.GEN_STP_AUDIT_TRAIL_TBL_TRG
   BEFORE INSERT
   ON GST.GEN_STP_AUDIT_TRAIL_TBL
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.DFLT_ROW_ID IS NULL)
DECLARE
   V_ID   GST.GEN_STP_AUDIT_TRAIL_TBL.DFLT_ROW_ID%TYPE;
BEGIN
   SELECT   GST.GEN_STP_AUDIT_TRAIL_TBL_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.DFLT_ROW_ID := V_ID;
END GEN_STP_AUDIT_TRAIL_TBL_TRG;