/* Formatted on 12-13-2018 9:06:41 AM (QP5 v5.126.903.23003) */
-- TABLE: GST.GEN_STP_LOV_VALUES
DROP TABLE GST.GEN_STP_LOV_VALUES  CASCADE CONSTRAINTS PURGE;

CREATE TABLE GST.GEN_STP_LOV_VALUES (
   PSSBL_VALUE_ID     NUMBER NOT NULL,
   VALUE_LIST_ID      NUMBER NOT NULL,
   PSSBL_VALUE        VARCHAR2 (500 BYTE),
   PSSBL_VALUE_DESC   VARCHAR2 (500 BYTE),
   CREATED_BY         NUMBER NOT NULL,
   CREATION_DATE      VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_DATE   VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY     NUMBER NOT NULL,
   IS_ENABLED         VARCHAR2 (1 BYTE) NOT NULL,
   ALLOWED_ORG_IDS    CLOB
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX GST.IDX_PSSBL_VALUE_ID
   ON GST.GEN_STP_LOV_VALUES (PSSBL_VALUE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE GST.GEN_STP_LOV_VALUES_SEQ;
CREATE SEQUENCE GST.GEN_STP_LOV_VALUES_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

ALTER TABLE GST.GEN_STP_LOV_VALUES ADD (
  CONSTRAINT PK_PSSBL_VALUE_ID
 PRIMARY KEY
 (PSSBL_VALUE_ID));


CREATE INDEX GST.IDX_P_VALUE_LIST_ID
   ON GST.GEN_STP_LOV_VALUES (VALUE_LIST_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: GST.IDX_PSSBL_VALUE

-- DROP INDEX GST.IDX_PSSBL_VALUE;

CREATE INDEX GST.IDX_PSSBL_VALUE
   ON GST.GEN_STP_LOV_VALUES (PSSBL_VALUE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX GST.IDX_PSSBL_VALUE_DESC
   ON GST.GEN_STP_LOV_VALUES (PSSBL_VALUE_DESC)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE OR REPLACE TRIGGER GST.GEN_STP_LOV_VALS_TRG
   BEFORE INSERT
   ON GST.GEN_STP_LOV_VALUES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.PSSBL_VALUE_ID IS NULL)
DECLARE
   V_ID   GST.GEN_STP_LOV_VALUES.PSSBL_VALUE_ID%TYPE;
BEGIN
   SELECT   GST.GEN_STP_LOV_VALUES_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PSSBL_VALUE_ID := V_ID;
END GEN_STP_LOV_VALS_TRG;