/* Formatted on 12-19-2018 2:06:34 PM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION SCM.GET_CSTMR_SPLR_ID (
   P_CSTMRSPLRNM    CHARACTER VARYING,
   P_ORGID          INTEGER
)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200 BYTE);
BEGIN
   SELECT   CUST_SUP_ID
     INTO   L_RESULT
     FROM   SCM.SCM_CSTMR_SUPLR
    WHERE   UPPER (CUST_SUP_NAME) LIKE UPPER (P_CSTMRSPLRNM)
            AND ORG_ID = P_ORGID;

   RETURN COALESCE (L_RESULT, -1);
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/