/* Formatted on 10/6/2014 3:09:31 AM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION APLAPPS.GET_USR_NAME (P_USRID NUMBER)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200 BYTE);
BEGIN
   L_RESULT := '';

   SELECT   USER_NAME
     INTO   L_RESULT
     FROM   SEC.SEC_USERS
    WHERE   USER_ID = P_USRID;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/