/* Formatted on 12-19-2018 2:12:35 PM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION SCM.GET_CSTMR_SPLR_NAME (P_CSTMRSPLRID NUMBER)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200 BYTE);
BEGIN
   SELECT   CUST_SUP_NAME
     INTO   L_RESULT
     FROM   SCM.SCM_CSTMR_SUPLR
    WHERE   CUST_SUP_ID = P_CSTMRSPLRID;

   RETURN COALESCE (L_RESULT, '');
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/