/* Formatted on 12-19-2018 2:25:16 PM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION SCM.GET_CSTMR_SPLR_SITE_ID (
   P_CSTMRSPLRSITENM    VARCHAR2,
   P_CUSTMRID           INTEGER
)
   RETURN INTEGER
AS
   L_RESULT   INTEGER := -1;
BEGIN
   SELECT   CUST_SUP_SITE_ID
     INTO   L_RESULT
     FROM   SCM.SCM_CSTMR_SUPLR_SITES
    WHERE   UPPER (SITE_NAME) LIKE UPPER (P_CSTMRSPLRSITENM)
            AND cust_supplier_id = P_CUSTMRID;

   RETURN COALESCE (L_RESULT, -1);
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN -1;
END;
/