/* Formatted on 12-15-2018 8:54:35 AM (QP5 v5.126.903.23003) */
DROP TABLE PASN.PRSN_DIVS_GROUPS  CASCADE CONSTRAINTS PURGE;

CREATE TABLE PASN.PRSN_DIVS_GROUPS (
   PERSON_ID          NUMBER NOT NULL,
   DIV_ID             NUMBER,
   VALID_START_DATE   VARCHAR2 (21 BYTE) NOT NULL,
   VALID_END_DATE     VARCHAR2 (21 BYTE) NOT NULL,
   CREATED_BY         NUMBER NOT NULL,
   CREATION_DATE      VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY     NUMBER NOT NULL,
   LAST_UPDATE_DATE   VARCHAR2 (21 BYTE) NOT NULL,
   PRSN_DIV_ID        NUMBER NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX PASN.IDX_PRSN_DIV_ID
   ON PASN.PRSN_DIVS_GROUPS (PRSN_DIV_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE PASN.PRSN_DIVS_GROUPS ADD (
  CONSTRAINT PK_PRSN_DIV_ID
 PRIMARY KEY
 (PRSN_DIV_ID));

CREATE INDEX PASN.IDX_DIV_ID
   ON PASN.PRSN_DIVS_GROUPS (DIV_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PASN.IDX_PERSON_ID
   ON PASN.PRSN_DIVS_GROUPS (PERSON_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE PASN.PRSN_DIVS_GROUPS_SEQ;

CREATE SEQUENCE PASN.PRSN_DIVS_GROUPS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER PASN.PRSN_DIVS_GROUPS_TRG
   BEFORE INSERT
   ON PASN.PRSN_DIVS_GROUPS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.PRSN_DIV_ID IS NULL)
DECLARE
   V_ID   PASN.PRSN_DIVS_GROUPS.PRSN_DIV_ID%TYPE;
BEGIN
   SELECT   PASN.PRSN_DIVS_GROUPS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PRSN_DIV_ID := V_ID;
END PRSN_DIVS_GROUPS_TRG;