/* Formatted on 12-15-2018 9:05:51 AM (QP5 v5.126.903.23003) */
DROP TABLE PASN.PRSN_LOCATIONS  CASCADE CONSTRAINTS PURGE;

CREATE TABLE PASN.PRSN_LOCATIONS (
   PERSON_ID          NUMBER NOT NULL,
   LOCATION_ID        NUMBER,
   VALID_START_DATE   VARCHAR2 (21 BYTE) NOT NULL,
   VALID_END_DATE     VARCHAR2 (21 BYTE) NOT NULL,
   CREATED_BY         NUMBER NOT NULL,
   CREATION_DATE      VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY     NUMBER NOT NULL,
   LAST_UPDATE_DATE   VARCHAR2 (21 BYTE) NOT NULL,
   PRSN_LOC_ID        NUMBER NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX PASN.IDX_LOC_ROW_ID
   ON PASN.PRSN_LOCATIONS (PRSN_LOC_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE PASN.PRSN_LOCATIONS ADD (
  CONSTRAINT PK_PRSN_LOC_ID
 PRIMARY KEY
 (PRSN_LOC_ID));

CREATE INDEX PASN.IDX_LOC_PERSON_ID
   ON PASN.PRSN_LOCATIONS (PERSON_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PASN.IDX_LOCATION_ID
   ON PASN.PRSN_LOCATIONS (LOCATION_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE PASN.PRSN_LOCATIONS_SEQ;

CREATE SEQUENCE PASN.PRSN_LOCATIONS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER PASN.PRSN_LOCATIONS_TRG
   BEFORE INSERT
   ON PASN.PRSN_LOCATIONS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.PRSN_LOC_ID IS NULL)
DECLARE
   V_ID   PASN.PRSN_LOCATIONS.PRSN_LOC_ID%TYPE;
BEGIN
   SELECT   PASN.PRSN_LOCATIONS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PRSN_LOC_ID := V_ID;
END PRSN_LOCATIONS_TRG;