/* Formatted on 12-15-2018 9:12:59 AM (QP5 v5.126.903.23003) */
DROP TABLE PASN.PRSN_POSITIONS  CASCADE CONSTRAINTS PURGE;

CREATE TABLE PASN.PRSN_POSITIONS (
   PERSON_ID          NUMBER NOT NULL,
   POSITION_ID        NUMBER,
   VALID_START_DATE   VARCHAR2 (21 BYTE) NOT NULL,
   VALID_END_DATE     VARCHAR2 (21 BYTE) NOT NULL,
   CREATED_BY         NUMBER NOT NULL,
   CREATION_DATE      VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY     NUMBER NOT NULL,
   LAST_UPDATE_DATE   VARCHAR2 (21 BYTE) NOT NULL,
   ROW_ID             NUMBER NOT NULL,
   DIV_ID             NUMBER DEFAULT (-1) NOT NULL,
   DIV_SUB_CAT_ID1    NUMBER DEFAULT (-1) NOT NULL,
   DIV_SUB_CAT_ID2    NUMBER DEFAULT (-1) NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX PASN.IDX_POS_ROW_ID
   ON PASN.PRSN_POSITIONS (ROW_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE PASN.PRSN_POSITIONS ADD (
  CONSTRAINT PK_POS_ROW_ID
 PRIMARY KEY
 (ROW_ID));

CREATE INDEX PASN.IDX_POS_PERSON_ID
   ON PASN.PRSN_POSITIONS (PERSON_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PASN.IDX_POSITION_ID
   ON PASN.PRSN_POSITIONS (POSITION_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE PASN.PRSN_POSITIONS_SEQ;

CREATE SEQUENCE PASN.PRSN_POSITIONS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;


CREATE OR REPLACE TRIGGER PASN.PRSN_POSITIONS_TRG
   BEFORE INSERT
   ON PASN.PRSN_POSITIONS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.ROW_ID IS NULL)
DECLARE
   V_ID   PASN.PRSN_POSITIONS.ROW_ID%TYPE;
BEGIN
   SELECT   PASN.PRSN_POSITIONS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.ROW_ID := V_ID;
END PRSN_POSITIONS_TRG;