/* Formatted on 12-15-2018 8:53:19 AM (QP5 v5.126.903.23003) */
DROP TABLE PASN.PRSN_BNFTS_CNTRBTNS  CASCADE CONSTRAINTS PURGE;

CREATE TABLE PASN.PRSN_BNFTS_CNTRBTNS (
   ROW_ID                NUMBER NOT NULL,
   PERSON_ID             NUMBER,
   ITEM_ID               NUMBER,
   ITEM_PSSBL_VALUE_ID   NUMBER,
   VALID_START_DATE      VARCHAR2 (12 BYTE) NOT NULL,
   VALID_END_DATE        VARCHAR2 (12 BYTE) NOT NULL,
   CREATED_BY            NUMBER NOT NULL,
   CREATION_DATE         VARCHAR2 (21 BYTE),
   LAST_UPDATE_BY        NUMBER NOT NULL,
   LAST_UPDATE_DATE      VARCHAR2 (21 BYTE) NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX PASN.IDX_BNFTS_ROW_ID
   ON PASN.PRSN_BNFTS_CNTRBTNS (ROW_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE PASN.PRSN_BNFTS_CNTRBTNS ADD (
  CONSTRAINT PK_BNFTS_ROWID
 PRIMARY KEY
 (ROW_ID));

CREATE INDEX PASN.IDX_BNFTS_ITEM_ID
   ON PASN.PRSN_BNFTS_CNTRBTNS (ITEM_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PASN.IDX_BNFTS_PERSON_ID
   ON PASN.PRSN_BNFTS_CNTRBTNS (PERSON_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PASN.IDX_ITEM_PSSBL_VALUE_ID
   ON PASN.PRSN_BNFTS_CNTRBTNS (ITEM_PSSBL_VALUE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE PASN.PRSN_BNFTS_CNTRBTNS_SEQ;

CREATE SEQUENCE PASN.PRSN_BNFTS_CNTRBTNS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER PASN.PRSN_BNFTS_CNTRBTNS_TRG
   BEFORE INSERT
   ON PASN.PRSN_BNFTS_CNTRBTNS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.ROW_ID IS NULL)
DECLARE
   V_ID   PASN.PRSN_BNFTS_CNTRBTNS.ROW_ID%TYPE;
BEGIN
   SELECT   PASN.PRSN_BNFTS_CNTRBTNS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.ROW_ID := V_ID;
END PRSN_BNFTS_CNTRBTNS_TRG;