/* Formatted on 12-15-2018 9:17:58 AM (QP5 v5.126.903.23003) */
DROP TABLE PASN.PRSN_WORK_ID  CASCADE CONSTRAINTS PURGE;

CREATE TABLE PASN.PRSN_WORK_ID (
   PERSON_ID          NUMBER NOT NULL,
   WORK_HOUR_ID       NUMBER NOT NULL,
   VALID_START_DATE   VARCHAR2 (21 BYTE) NOT NULL,
   VALID_END_DATE     VARCHAR2 (21 BYTE) NOT NULL,
   CREATED_BY         NUMBER NOT NULL,
   CREATION_DATE      VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY     NUMBER NOT NULL,
   LAST_UPDATE_DATE   VARCHAR2 (21 BYTE) NOT NULL,
   ROW_ID             NUMBER NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX PASN.IDX_WKH_ROW_ID
   ON PASN.PRSN_WORK_ID (ROW_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE PASN.PRSN_WORK_ID ADD (
CONSTRAINT PK_WKH_ROW_ID
PRIMARY KEY
(ROW_ID));

CREATE INDEX PASN.IDX_WK_PERSON_ID
   ON PASN.PRSN_WORK_ID (PERSON_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE INDEX PASN.IDX_WORK_HOUR_ID
   ON PASN.PRSN_WORK_ID (WORK_HOUR_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE PASN.PRSN_WORK_ID_SEQ;

CREATE SEQUENCE PASN.PRSN_WORK_ID_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER PASN.PRSN_WORK_ID_TRG
   BEFORE INSERT
   ON PASN.PRSN_WORK_ID
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.ROW_ID IS NULL)
DECLARE
   V_ID   PASN.PRSN_WORK_ID.ROW_ID%TYPE;
BEGIN
   SELECT   PASN.PRSN_WORK_ID_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.ROW_ID := V_ID;
END PRSN_WORK_ID_TRG;