/* Formatted on 12-15-2018 9:14:28 AM (QP5 v5.126.903.23003) */
DROP TABLE PASN.PRSN_PRSNTYPS  CASCADE CONSTRAINTS PURGE;

CREATE TABLE PASN.PRSN_PRSNTYPS (
   PERSON_ID             NUMBER NOT NULL,
   PRN_TYP_ASGNMNT_RSN   VARCHAR2 (200 BYTE),
   VALID_START_DATE      VARCHAR2 (21 BYTE) NOT NULL,
   VALID_END_DATE        VARCHAR2 (21 BYTE) NOT NULL,
   CREATED_BY            NUMBER NOT NULL,
   CREATION_DATE         VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY        NUMBER NOT NULL,
   LAST_UPDATE_DATE      VARCHAR2 (21 BYTE) NOT NULL,
   FURTHER_DETAILS       VARCHAR2 (500 BYTE),
   PRSN_TYPE             VARCHAR2 (100 BYTE) NOT NULL,
   PRSNTYPE_ID           NUMBER NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX PASN.IDX_PRSNTYPE_ID
   ON PASN.PRSN_PRSNTYPS (PRSNTYPE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE PASN.PRSN_PRSNTYPS ADD (
  CONSTRAINT PK_PRSNTYPE_ID
 PRIMARY KEY
 (PRSNTYPE_ID));

CREATE INDEX PASN.IDX_PRN_TYP_ASGNMNT_RSN
   ON PASN.PRSN_PRSNTYPS (PRN_TYP_ASGNMNT_RSN)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PASN.IDX_PRS_PERSON_ID
   ON PASN.PRSN_PRSNTYPS (PERSON_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PASN.IDX_PRSN_TYPE
   ON PASN.PRSN_PRSNTYPS (PRSN_TYPE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE PASN.PRSN_PRSNTYPS_SEQ;

CREATE SEQUENCE PASN.PRSN_PRSNTYPS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER PASN.PRSN_PRSNTYPS_TRG
   BEFORE INSERT
   ON PASN.PRSN_PRSNTYPS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.PRSNTYPE_ID IS NULL)
DECLARE
   V_ID   PASN.PRSN_PRSNTYPS.PRSNTYPE_ID%TYPE;
BEGIN
   SELECT   PASN.PRSN_PRSNTYPS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PRSNTYPE_ID := V_ID;
END PRSN_PRSNTYPS_TRG;