/* Formatted on 10/1/2014 4:51:52 PM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION APLAPPS.GET_ACCNT_NAME (P_ACCNTID VARCHAR2)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2(100);
BEGIN
   L_RESULT := '';

   SELECT   A.ACCNT_NAME
     INTO   L_RESULT
     FROM   ACCB.ACCB_CHART_OF_ACCNTS A
    WHERE   A.ACCNT_ID = P_ACCNTID;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/