/* Formatted on 10/6/2014 2:26:16 AM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION APLAPPS.GET_BATCH_ID (P_BATCHNAME    VARCHAR2,
                                                 P_ORGIDNO      NUMBER)
   RETURN NUMBER
AS
   L_RESULT   NUMBER;
BEGIN
   L_RESULT := -1;

   SELECT   A.BATCH_ID
     INTO   L_RESULT
     FROM   ACCB.ACCB_TRNSCTN_BATCHES A
    WHERE   A.BATCH_NAME = P_BATCHNAME;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN -1;
END;
/