/* Formatted on 10/3/2014 4:02:18 PM (QP5 v5.126.903.23003) */
-- FUNCTION: APLAPPS.GET_TODYSBATCH_ID(CHARACTER VARYING, INTEGER)

-- DROP FUNCTION APLAPPS.GET_TODYSBATCH_ID(CHARACTER VARYING, INTEGER);

CREATE OR REPLACE FUNCTION APLAPPS.GET_TODYSBATCH_ID (P_BATCHNAME    VARCHAR2,
                                                   P_ORGIDNO      NUMBER)
   RETURN NUMBER
AS
   L_RESULT   NUMBER := -1;
BEGIN
   SELECT   TBL1.BATCH_ID
     INTO   L_RESULT
     FROM   (  SELECT   A.BATCH_ID
                 FROM   ACCB.ACCB_TRNSCTN_BATCHES A
                WHERE   (LOWER (A.BATCH_NAME) LIKE
                            '%' || LOWER (P_BATCHNAME) || '%'
                         AND ORG_ID = P_ORGIDNO
                         AND BATCH_STATUS = '0')
             ORDER BY   A.BATCH_ID DESC) TBL1
    WHERE   ROWNUM = 1;

   RETURN L_RESULT;
END;