/* Formatted on 10/3/2014 4:07:24 PM (QP5 v5.126.903.23003) */
-- FUNCTION: APLAPPS.GETPRDCLSEUNPSTDTRNSCNT(INTEGER, CHARACTER VARYING, BIGINT)

-- DROP FUNCTION APLAPPS.GETPRDCLSEUNPSTDTRNSCNT(INTEGER, CHARACTER VARYING, BIGINT);

CREATE OR REPLACE FUNCTION APLAPPS.GETPRDCLSEUNPSTDTRNSCNT (
   P_ORGIDNO      NUMBER,
   P_CLOSEDATE    VARCHAR2,
   P_BTCHID       NUMBER
)
   RETURN NUMBER
AS
   L_RESULT   NUMBER := -1;
BEGIN
   SELECT   COUNT (A.TRANSCTN_ID)
     INTO   L_RESULT
     FROM   ACCB.ACCB_TRNSCTN_DETAILS A,
            ACCB.ACCB_CHART_OF_ACCNTS B,
            ACCB.ACCB_TRNSCTN_BATCHES C
    WHERE       A.ACCNT_ID = B.ACCNT_ID
            AND A.TRNS_STATUS = '0'
            AND A.BATCH_ID = C.BATCH_ID
            AND C.BATCH_ID = P_BTCHID
            AND C.BATCH_SOURCE = 'Period Close Process'
            AND TO_DATE (A.TRNSCTN_DATE, 'YYYY-MM-DD HH24:MI:SS') <=
                  TO_DATE (P_CLOSEDATE, 'YYYY-MM-DD HH24:MI:SS')
            AND B.ORG_ID = P_ORGIDNO;

   RETURN L_RESULT;
END;