/* Formatted on 10/6/2014 12:52:20 AM (QP5 v5.126.903.23003) */
-- FUNCTION: APLAPPS.GETUNPSTDTRNSCNT(INTEGER, CHARACTER VARYING)

-- DROP FUNCTION APLAPPS.GETUNPSTDTRNSCNT(INTEGER, CHARACTER VARYING);

CREATE OR REPLACE FUNCTION APLAPPS.GETUNPSTDTRNSCNT (P_ORGIDNO      NUMBER,
                                                     P_CLOSEDATE    NUMBER)
   RETURN NUMBER
AS
   L_RESULT   NUMBER := 0;
BEGIN
   SELECT   COUNT (A.TRANSCTN_ID)
     INTO   L_RESULT
     FROM   ACCB.ACCB_TRNSCTN_DETAILS A, ACCB.ACCB_CHART_OF_ACCNTS B
    WHERE   A.ACCNT_ID = B.ACCNT_ID AND A.TRNS_STATUS = '0'
            AND TO_DATE (A.TRNSCTN_DATE, 'YYYY-MM-DD HH24:MI:SS') <=
                  TO_DATE (P_CLOSEDATE, 'YYYY-MM-DD HH24:MI:SS')
            AND B.ORG_ID = P_ORGIDNO;

   RETURN L_RESULT;
END;