/* Formatted on 10/3/2014 3:57:47 PM (QP5 v5.126.903.23003) */
-- FUNCTION: APLAPPS.GET_SRC_DOC_NUM(BIGINT, CHARACTER VARYING)

--DROP FUNCTION APLAPPS.GET_ACCB_SRC_DOC_NUM;

CREATE OR REPLACE FUNCTION APLAPPS.GET_ACCB_SRC_DOC_NUM (P_SRCDOCID      NUMBER,
                                                 P_SRCDOCTYPE    VARCHAR2)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200) := '';
BEGIN
   IF P_SRCDOCTYPE LIKE '%Supplier%'
   THEN
      SELECT   PYBLS_INVC_NUMBER
        INTO   L_RESULT
        FROM   ACCB.ACCB_PYBLS_INVC_HDR
       WHERE   PYBLS_INVC_HDR_ID = P_SRCDOCID
               AND PYBLS_INVC_TYPE = P_SRCDOCTYPE;
   ELSE
      SELECT   RCVBLS_INVC_NUMBER
        INTO   L_RESULT
        FROM   ACCB.ACCB_RCVBLS_INVC_HDR
       WHERE   RCVBLS_INVC_HDR_ID = P_SRCDOCID
               AND RCVBLS_INVC_TYPE = P_SRCDOCTYPE;
   END IF;

   RETURN L_RESULT;
END;