/* Formatted on 10/6/2014 2:11:31 AM (QP5 v5.126.903.23003) */
-- FUNCTION: APLAPPS.GET_LTST_PRNT_ACCNT_BALS(INTEGER, CHARACTER VARYING)

-- DROP FUNCTION APLAPPS.GET_LTST_PRNT_ACCNT_BALS(INTEGER, CHARACTER VARYING);

CREATE OR REPLACE FUNCTION APLAPPS.GET_LTST_PRNT_ACCNT_BALS1 (
   P_ACCNTID    NUMBER,
   P_BALSDTE    VARCHAR2
)
   RETURN NUMBER
AS
   L_RESULT   NUMERIC := 0.00;
BEGIN
   SELECT   SUM (APLAPPS.GET_LTST_ACCNT_BALS1 (A.ACCNT_ID, P_BALSDTE))
     INTO   L_RESULT
     FROM   ACCB.ACCB_CHART_OF_ACCNTS A
    WHERE   A.PRNT_ACCNT_ID = P_ACCNTID;

   RETURN NVL (L_RESULT, 0);
END;