/* Formatted on 10/6/2014 7:46:37 PM (QP5 v5.126.903.23003) */
-- TABLE: INV.INV_CONSGMT_ADJSTMNT_DET

-- DROP TABLE INV.INV_CONSGMT_ADJSTMNT_DET;

CREATE TABLE INV.INV_CONSGMT_ADJSTMNT_DET (
   LINE_ID            NUMBER NOT NULL,
   CONSGMT_ID         NUMBER,
   NEW_TTL_QTY_OLD    NUMBER,
   REASON             CLOB,
   ADJSTMNT_HDR_ID    NUMBER,
   REMARKS            CLOB,
   NEW_EXPIRY_DATE    VARCHAR2 (21 BYTE),
   NEW_COST_PRICE     NUMBER,
   CREATED_BY         NUMBER,
   CREATION_DATE      VARCHAR2 (21 BYTE),
   LAST_UPDATE_BY     NUMBER,
   LAST_UPDATE_DATE   VARCHAR2 (21 BYTE),
   NEW_TTL_QTY        VARCHAR2 (20 BYTE)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE INV.INV_CONSGMT_ADJSTMNT_DET
 ADD(CONSTRAINT PK_CONSGMT_ADJSTMT_DET PRIMARY KEY (LINE_ID ));
-- INDEX: INV.IDX_ADJSTMNT_HDR_ID1

-- DROP INDEX INV.IDX_ADJSTMNT_HDR_ID1;

CREATE INDEX INV.IDX_ADJSTMNT_HDR_ID1
   ON INV.INV_CONSGMT_ADJSTMNT_DET (ADJSTMNT_HDR_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.IDX_CONSGMT_ID1

-- DROP INDEX INV.IDX_CONSGMT_ID1;

CREATE INDEX INV.IDX_CONSGMT_ID1
   ON INV.INV_CONSGMT_ADJSTMNT_DET (CONSGMT_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

   /*
-- INDEX: INV.IDX_LINE_ID1

-- DROP INDEX INV.IDX_LINE_ID1;

CREATE UNIQUE INDEX INV.IDX_LINE_ID1
   ON INV.INV_CONSGMT_ADJSTMNT_DET (LINE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;
*/

CREATE SEQUENCE INV.INV_CONSGMT_ADJSTMNT_DET_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER INV.INV_CONSGMT_ADJSTMNT_DET_TRG
   BEFORE INSERT
   ON INV.INV_CONSGMT_ADJSTMNT_DET
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.LINE_ID IS NULL)
DECLARE
   V_ID   INV.INV_CONSGMT_ADJSTMNT_DET.LINE_ID%TYPE;
BEGIN
   SELECT   INV.INV_CONSGMT_ADJSTMNT_DET_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.LINE_ID := V_ID;
END INV_CONSGMT_ADJSTMNT_DET_TRG;