/* Formatted on 10/6/2014 7:49:57 PM (QP5 v5.126.903.23003) */
-- TABLE: INV.INV_CONSGMT_RCPT_DET

-- DROP TABLE INV.INV_CONSGMT_RCPT_DET;

CREATE TABLE INV.INV_CONSGMT_RCPT_DET (
   CONSGMT_ID            NUMBER,
   STOCK_ID              NUMBER,
   QUANTITY_RCVD         NUMBER,
   COST_PRICE            NUMBER,
   RCPT_ID               NUMBER,
   CREATED_BY            NUMBER,
   CREATION_DATE         VARCHAR2 (21 BYTE),
   LAST_UPDATE_BY        NUMBER,
   LAST_UPDATE_DATE      VARCHAR2 (21 BYTE),
   EXPIRY_DATE           VARCHAR2 (21 BYTE),
   MANFCT_DATE           VARCHAR2 (21 BYTE),
   LIFESPAN              VARCHAR2 (21 BYTE),
   TAG_NUMBER            VARCHAR2 (100 BYTE),
   SERIAL_NUMBER         VARCHAR2 (100 BYTE),
   PO_LINE_ID            NUMBER,
   CONSIGNMT_CONDITION   VARCHAR2 (50 BYTE),
   REMARKS               CLOB,
   ITM_ID                NUMBER,
   SUBINV_ID             NUMBER,
   LINE_ID               NUMBER NOT NULL,
   QTY_RTRND             NUMBER,
   QTY_TO_B_RTRND        NUMBER
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE INV.INV_CONSGMT_RCPT_DET
  ADD(CONSTRAINT PK_CONSGMT_RCPT_DET PRIMARY KEY (LINE_ID ));
-- INDEX: INV.INV.IDX_CONSGMT_ID3

-- DROP INDEX INV.INV.IDX_CONSGMT_ID3;

CREATE INDEX INV.IDX_CONSGMT_ID3
   ON INV.INV_CONSGMT_RCPT_DET (CONSGMT_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.INV.IDX_CONSIGNMT_CONDITION

-- DROP INDEX INV.INV.IDX_CONSIGNMT_CONDITION;

CREATE INDEX INV.IDX_CONSIGNMT_CONDITION
   ON INV.INV_CONSGMT_RCPT_DET (CONSIGNMT_CONDITION)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.INV.IDX_EXPIRY_DATE

-- DROP INDEX INV.INV.IDX_EXPIRY_DATE;

CREATE INDEX INV.IDX_EXPIRY_DATE
   ON INV.INV_CONSGMT_RCPT_DET (EXPIRY_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.INV.IDX_ITM_ID

-- DROP INDEX INV.INV.IDX_ITM_ID;

CREATE INDEX INV.IDX_ITM_ID
   ON INV.INV_CONSGMT_RCPT_DET (ITM_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

   /*
-- INDEX: INV.INV.IDX_LINE_ID2

-- DROP INDEX INV.INV.IDX_LINE_ID2;

CREATE UNIQUE INDEX INV.IDX_LINE_ID2
   ON INV.INV_CONSGMT_RCPT_DET (LINE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;
*/
-- INDEX: INV.INV.IDX_PO_LINE_ID

-- DROP INDEX INV.INV.IDX_PO_LINE_ID;

CREATE INDEX INV.IDX_PO_LINE_ID
   ON INV.INV_CONSGMT_RCPT_DET (PO_LINE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.INV.IDX_RCPT_ID1

-- DROP INDEX INV.INV.IDX_RCPT_ID1;

CREATE INDEX INV.IDX_RCPT_ID1
   ON INV.INV_CONSGMT_RCPT_DET (RCPT_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.INV.IDX_SERIAL_NUMBER

-- DROP INDEX INV.INV.IDX_SERIAL_NUMBER;

CREATE INDEX INV.IDX_SERIAL_NUMBER
   ON INV.INV_CONSGMT_RCPT_DET (SERIAL_NUMBER)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.INV.IDX_STOCK_ID1

-- DROP INDEX INV.INV.IDX_STOCK_ID1;

CREATE INDEX INV.IDX_STOCK_ID1
   ON INV.INV_CONSGMT_RCPT_DET (STOCK_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.INV.IDX_SUBINV_ID

-- DROP INDEX INV.INV.IDX_SUBINV_ID;

CREATE INDEX INV.IDX_SUBINV_ID
   ON INV.INV_CONSGMT_RCPT_DET (SUBINV_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.INV.IDX_TAG_NUMBER

-- DROP INDEX INV.INV.IDX_TAG_NUMBER;

CREATE INDEX INV.IDX_TAG_NUMBER
   ON INV.INV_CONSGMT_RCPT_DET (TAG_NUMBER)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE SEQUENCE INV.INV_CONSGMT_RCPT_DET_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER INV.INV_CONSGMT_RCPT_DET_TRG
   BEFORE INSERT
   ON INV.INV_CONSGMT_RCPT_DET
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.LINE_ID IS NULL)
DECLARE
   V_ID   INV.INV_CONSGMT_RCPT_DET.LINE_ID%TYPE;
BEGIN
   SELECT   INV.INV_CONSGMT_RCPT_DET_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.LINE_ID := V_ID;
END INV_CONSGMT_RCPT_DET_TRG;


CREATE SEQUENCE INV.INV_RCPT_DET_CONSGMT_ID_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;


CREATE OR REPLACE TRIGGER INV.INV_RCPT_DET_CONSGMT_ID_TRG
   BEFORE INSERT
   ON INV.INV_CONSGMT_RCPT_DET
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.CONSGMT_ID IS NULL)
DECLARE
   V_ID   INV.INV_CONSGMT_RCPT_DET.CONSGMT_ID%TYPE;
BEGIN
   SELECT   INV.INV_RCPT_DET_CONSGMT_ID_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.CONSGMT_ID := V_ID;
END INV_RCPT_DET_CONSGMT_ID_TRG;