/* Formatted on 10/6/2014 7:50:50 PM (QP5 v5.126.903.23003) */
-- TABLE: INV.INV_CONSGMT_RCPT_HDR

-- DROP TABLE INV.INV_CONSGMT_RCPT_HDR;

CREATE TABLE INV.INV_CONSGMT_RCPT_HDR (
   RCPT_ID                NUMBER NOT NULL,
   PO_ID                  NUMBER,
   DATE_RECEIVED          VARCHAR2 (50 BYTE),
   RECEIVED_BY            NUMBER,
   SUPPLIER_ID            NUMBER,
   CREATED_BY             NUMBER,
   CREATION_DATE          VARCHAR2 (50 BYTE),
   LAST_UPDATE_BY         NUMBER,
   LAST_UPDATE_DATE       VARCHAR2 (50 BYTE),
   APPROVAL_STATUS        VARCHAR2 (50 BYTE),
   NEXT_APPROVAL_STATUS   VARCHAR2 (50 BYTE),
   DESCRIPTION            CLOB,
   ORG_ID                 NUMBER,
   SITE_ID                NUMBER,
   RETURN_STATUS          VARCHAR2 (50 BYTE)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE INV.INV_CONSGMT_RCPT_HDR
  ADD(  CONSTRAINT PK_CONSGMT_RCPT_HDR PRIMARY KEY (RCPT_ID ));
-- INDEX: INV.INV.IDX_APPROVAL_STATUS

-- DROP INDEX INV.INV.IDX_APPROVAL_STATUS;

CREATE INDEX INV.IDX_APPROVAL_STATUS
   ON INV.INV_CONSGMT_RCPT_HDR (APPROVAL_STATUS)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.INV.IDX_DATE_RECEIVED

-- DROP INDEX INV.INV.IDX_DATE_RECEIVED;

CREATE INDEX INV.IDX_DATE_RECEIVED
   ON INV.INV_CONSGMT_RCPT_HDR (DATE_RECEIVED)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.INV.IDX_NEXT_APPROVAL_STATUS

-- DROP INDEX INV.INV.IDX_NEXT_APPROVAL_STATUS;

CREATE INDEX INV.IDX_NEXT_APPROVAL_STATUS
   ON INV.INV_CONSGMT_RCPT_HDR (NEXT_APPROVAL_STATUS)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.INV.IDX_ORG_ID2

-- DROP INDEX INV.INV.IDX_ORG_ID2;

CREATE INDEX INV.IDX_ORG_ID2
   ON INV.INV_CONSGMT_RCPT_HDR (ORG_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.INV.IDX_PO_ID

-- DROP INDEX INV.INV.IDX_PO_ID;

CREATE INDEX INV.IDX_PO_ID
   ON INV.INV_CONSGMT_RCPT_HDR (PO_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

   /*
-- INDEX: INV.INV.IDX_RCPT_ID

-- DROP INDEX INV.INV.IDX_RCPT_ID;

CREATE UNIQUE INDEX INV.IDX_RCPT_ID
   ON INV.INV_CONSGMT_RCPT_HDR (RCPT_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;
*/
-- INDEX: INV.INV.IDX_RECEIVED_BY

-- DROP INDEX INV.INV.IDX_RECEIVED_BY;

CREATE INDEX INV.IDX_RECEIVED_BY
   ON INV.INV_CONSGMT_RCPT_HDR (RECEIVED_BY)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.INV.IDX_RETURN_STATUS

-- DROP INDEX INV.INV.IDX_RETURN_STATUS;

CREATE INDEX INV.IDX_RETURN_STATUS
   ON INV.INV_CONSGMT_RCPT_HDR (RETURN_STATUS)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.INV.IDX_SITE_ID

-- DROP INDEX INV.INV.IDX_SITE_ID;

CREATE INDEX INV.IDX_SITE_ID
   ON INV.INV_CONSGMT_RCPT_HDR (SITE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.INV.IDX_SUPPLIER_ID

-- DROP INDEX INV.INV.IDX_SUPPLIER_ID;

CREATE INDEX INV.IDX_SUPPLIER_ID
   ON INV.INV_CONSGMT_RCPT_HDR (SUPPLIER_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE INV.INV_CONSGMT_RCPT_HDR_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER INV.INV_CONSGMT_RCPT_HDR_TRG
   BEFORE INSERT
   ON INV.INV_CONSGMT_RCPT_HDR
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.RCPT_ID IS NULL)
DECLARE
   V_ID   INV.INV_CONSGMT_RCPT_HDR.RCPT_ID%TYPE;
BEGIN
   SELECT   INV.INV_CONSGMT_RCPT_HDR_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.RCPT_ID := V_ID;
END INV_CONSGMT_RCPT_HDR_TRG;