/* Formatted on 10/6/2014 7:55:47 PM (QP5 v5.126.903.23003) */
-- TABLE: INV.INV_CONSGMT_RCPT_RTNS_HDR

-- DROP TABLE INV.INV_CONSGMT_RCPT_RTNS_HDR;

CREATE TABLE INV.INV_CONSGMT_RCPT_RTNS_HDR (
   RCPT_RTNS_ID           NUMBER NOT NULL,
   CREATION_DATE          VARCHAR2 (50 BYTE),
   CREATED_BY             NUMBER,
   LAST_UPDATE_BY         NUMBER,
   LAST_UPDATE_DATE       VARCHAR2 (21 BYTE),
   RCPT_ID                NUMBER,
   APPROVAL_STATUS        VARCHAR2 (50),
   NEXT_APPROVAL_STATUS   VARCHAR2 (50 BYTE),
   DESCRIPTION            CLOB,
   DATE_RETURNED          VARCHAR2 (21 BYTE),
   ORG_ID                 NUMBER,
   SUPPLIER_ID            NUMBER,
   SITE_ID                NUMBER,
   RETURNED_BY            NUMBER
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE INV.INV_CONSGMT_RCPT_RTNS_HDR
ADD(  CONSTRAINT PK_CONSGMT_RCPT_RTNS_HDR PRIMARY KEY (RCPT_RTNS_ID ));

-- INDEX: INV.IDX_APPROVAL_STATUS1

-- DROP INDEX INV.IDX_APPROVAL_STATUS1;

CREATE INDEX INV.IDX_APPROVAL_STATUS1
   ON INV.INV_CONSGMT_RCPT_RTNS_HDR (APPROVAL_STATUS)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.IDX_DATE_RETURNED

-- DROP INDEX INV.IDX_DATE_RETURNED;

CREATE INDEX INV.IDX_DATE_RETURNED
   ON INV.INV_CONSGMT_RCPT_RTNS_HDR (DATE_RETURNED)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.IDX_NEXT_APPROVAL_STATUS1

-- DROP INDEX INV.IDX_NEXT_APPROVAL_STATUS1;

CREATE INDEX INV.IDX_NEXT_APPROVAL_STATUS1
   ON INV.INV_CONSGMT_RCPT_RTNS_HDR (NEXT_APPROVAL_STATUS)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.IDX_ORG_ID4

-- DROP INDEX INV.IDX_ORG_ID4;

CREATE INDEX INV.IDX_ORG_ID4
   ON INV.INV_CONSGMT_RCPT_RTNS_HDR (ORG_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.IDX_RCPT_ID2

-- DROP INDEX INV.IDX_RCPT_ID2;

CREATE INDEX INV.IDX_RCPT_ID2
   ON INV.INV_CONSGMT_RCPT_RTNS_HDR (RCPT_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

   /*
-- INDEX: INV.IDX_RCPT_RTNS_ID

-- DROP INDEX INV.IDX_RCPT_RTNS_ID;

CREATE UNIQUE INDEX INV.IDX_RCPT_RTNS_ID
   ON INV.INV_CONSGMT_RCPT_RTNS_HDR (RCPT_RTNS_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;
*/
-- INDEX: INV.IDX_RETURNED_BY1

-- DROP INDEX INV.IDX_RETURNED_BY1;

CREATE INDEX INV.IDX_RETURNED_BY1
   ON INV.INV_CONSGMT_RCPT_RTNS_HDR (RETURNED_BY)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.IDX_SITE_ID1

-- DROP INDEX INV.IDX_SITE_ID1;

CREATE INDEX INV.IDX_SITE_ID1
   ON INV.INV_CONSGMT_RCPT_RTNS_HDR (SITE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.IDX_SUPPLIER_ID1

-- DROP INDEX INV.IDX_SUPPLIER_ID1;

CREATE INDEX INV.IDX_SUPPLIER_ID1
   ON INV.INV_CONSGMT_RCPT_RTNS_HDR (SUPPLIER_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;



CREATE SEQUENCE INV.INV_CONSGMT_RCPT_RTNS_HDR_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER INV.INV_CONSGMT_RCPT_RTNS_HDR_TRG
   BEFORE INSERT
   ON INV.INV_CONSGMT_RCPT_RTNS_HDR
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.RCPT_RTNS_ID IS NULL)
DECLARE
   V_ID   INV.INV_CONSGMT_RCPT_RTNS_HDR.RCPT_RTNS_ID%TYPE;
BEGIN
   SELECT   INV.INV_CONSGMT_RCPT_RTNS_HDR_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.RCPT_RTNS_ID := V_ID;
END INV_CONSGMT_RCPT_RTNS_HDR_TRG;