/* Formatted on 10/6/2014 7:57:20 PM (QP5 v5.126.903.23003) */
-- TABLE: INV.INV_DRUG_INTERACTIONS

-- DROP TABLE INV.INV_DRUG_INTERACTIONS;

CREATE TABLE INV.INV_DRUG_INTERACTIONS (
   FIRST_DRUG_ID      NUMBER,
   SECOND_DRUG_ID     NUMBER,
   INTRCTN_EFFECT     CLOB,
   ACTION             VARCHAR2 (100 BYTE),
   CREATED_BY         NUMBER,
   CREATION_DATE      VARCHAR2 (21 BYTE),
   LAST_UPDATE_BY     NUMBER,
   LAST_UPDATE_DATE   VARCHAR2 (21 BYTE),
   DRUG_INTRCTN_ID    NUMBER NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE INV.INV_DRUG_INTERACTIONS
ADD(  CONSTRAINT PK_DRUG_INTRCTN_ID PRIMARY KEY (DRUG_INTRCTN_ID ));

/*
-- INDEX: INV.IDX_DRUG_INTRCTN_ID

-- DROP INDEX INV.IDX_DRUG_INTRCTN_ID;

CREATE UNIQUE INDEX INV.IDX_DRUG_INTRCTN_ID
   ON INV.INV_DRUG_INTERACTIONS (DRUG_INTRCTN_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;
*/
-- INDEX: INV.IDX_FIRST_DRUG_ID

-- DROP INDEX INV.IDX_FIRST_DRUG_ID;

CREATE INDEX INV.IDX_FIRST_DRUG_ID
   ON INV.INV_DRUG_INTERACTIONS (FIRST_DRUG_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.IDX_SECOND_DRUG_ID

-- DROP INDEX INV.IDX_SECOND_DRUG_ID;

CREATE INDEX INV.IDX_SECOND_DRUG_ID
   ON INV.INV_DRUG_INTERACTIONS (SECOND_DRUG_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE INV.INV_DRUG_INTERACTIONS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER INV.INV_DRUG_INTERACTIONS_TRG
   BEFORE INSERT
   ON INV.INV_DRUG_INTERACTIONS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.DRUG_INTRCTN_ID IS NULL)
DECLARE
   V_ID   INV.INV_DRUG_INTERACTIONS.DRUG_INTRCTN_ID%TYPE;
BEGIN
   SELECT   INV.INV_DRUG_INTERACTIONS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.DRUG_INTRCTN_ID := V_ID;
END INV_DRUG_INTERACTIONS_TRG;