/* Formatted on 10/6/2014 8:00:01 PM (QP5 v5.126.903.23003) */
-- TABLE: INV.INV_ITEM_TYPES_STORES_TEMPLATE

-- DROP TABLE INV.INV_ITEM_TYPES_STORES_TEMPLATE;

CREATE TABLE INV.INV_ITEM_TYPES_STORES_TEMPLATE (
   LINE_ID                 NUMBER NOT NULL,
   ITEM_TYPE_TEMPLATE_ID   NUMBER,
   SUBINV_ID               NUMBER,
   CREATED_BY              NUMBER,
   CREATION_DATE           VARCHAR2 (21 BYTE),
   LAST_UPDATE_BY          NUMBER,
   LAST_UPDATE_DATE        VARCHAR2 (21 BYTE),
   SHELVES                 CLOB,
   START_DATE              VARCHAR2 (21 BYTE),
   END_DATE                VARCHAR2 (21 BYTE),
   ORG_ID                  NUMBER,
   SHELVES_IDS             CLOB
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE INV.INV_ITEM_TYPES_STORES_TEMPLATE
ADD(  CONSTRAINT PK_ITM_TYPES_STORES_TMPLT PRIMARY KEY (LINE_ID ));

-- INDEX: INV.IDX_ITEM_TYPE_TEMPLATE_ID

-- DROP INDEX INV.IDX_ITEM_TYPE_TEMPLATE_ID;

CREATE INDEX INV.IDX_ITEM_TYPE_TEMPLATE_ID
   ON INV.INV_ITEM_TYPES_STORES_TEMPLATE (ITEM_TYPE_TEMPLATE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

   /*
-- INDEX: INV.IDX_LINE_ID4

-- DROP INDEX INV.IDX_LINE_ID4;

CREATE UNIQUE INDEX INV.IDX_LINE_ID4
   ON INV.INV_ITEM_TYPES_STORES_TEMPLATE (LINE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;
*/
-- INDEX: INV.IDX_SUBINV_ID3

-- DROP INDEX INV.IDX_SUBINV_ID3;

CREATE INDEX INV.IDX_SUBINV_ID3
   ON INV.INV_ITEM_TYPES_STORES_TEMPLATE (SUBINV_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE INV.INV_ITM_TYPES_STORES_TMPLT_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER INV.INV_ITM_TYPES_STORES_TMPLT_TRG
   BEFORE INSERT
   ON INV.INV_ITEM_TYPES_STORES_TEMPLATE
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.LINE_ID IS NULL)
DECLARE
   V_ID   INV.INV_ITEM_TYPES_STORES_TEMPLATE.LINE_ID%TYPE;
BEGIN
   SELECT   INV.INV_ITM_TYPES_STORES_TMPLT_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.LINE_ID := V_ID;
END INV_ITM_TYPES_STORES_TMPLT_TRG;