/* Formatted on 10/6/2014 8:12:24 PM (QP5 v5.126.903.23003) */
-- TABLE: INV.INV_ITM_LIST

-- DROP TABLE INV.INV_ITM_LIST;

CREATE TABLE INV.INV_ITM_LIST (
   ITEM_ID               NUMBER NOT NULL,
   ITEM_CODE             VARCHAR2 (200 BYTE),
   ITEM_DESC             VARCHAR2 (300 BYTE),
   CATEGORY_ID           NUMBER,
   ORG_ID                NUMBER,
   ENABLED_FLAG          VARCHAR2 (1 BYTE),
   SELLING_PRICE         NUMBER,
   COGS_ACCT_ID          NUMBER,
   INV_ASSET_ACCT_ID     NUMBER,
   CREATED_BY            NUMBER,
   CREATION_DATE         VARCHAR2 (50 BYTE),
   LAST_UPDATE_BY        NUMBER,
   LAST_UPDATE_DATE      VARCHAR2 (50 BYTE),
   TOTAL_QTY             NUMBER,
   RESERVATIONS          NUMBER,
   AVAILABLE_BALANCE     NUMBER,
   SALES_REV_ACCNT_ID    NUMBER,
   SALES_RET_ACCNT_ID    NUMBER,
   PURCH_RET_ACCNT_ID    NUMBER,
   EXPENSE_ACCNT_ID      NUMBER,
   TAX_CODE_ID           NUMBER,
   DSCNT_CODE_ID         NUMBER,
   EXTR_CHRG_ID          NUMBER,
   MIN_LEVEL             VARCHAR2 (100 BYTE),
   MAX_LEVEL             VARCHAR2 (100 BYTE),
   PLANNING_ENABLED      VARCHAR2 (1 BYTE),
   ITEM_TYPE             VARCHAR2 (50 BYTE),
   IMAGE                 CLOB,
   EXTRA_INFO            CLOB,
   OTHER_DESC            CLOB,
   BASE_UOM_ID           NUMBER DEFAULT -1 NOT NULL,
   TMPLT_ID              NUMBER DEFAULT -1 NOT NULL,
   GENERIC_NAME          VARCHAR2 (200),
   TRADE_NAME            VARCHAR2 (200),
   DRUG_USUAL_DSGE       CLOB,
   DRUG_MAX_DSGE         CLOB,
   CONTRAINDICATIONS     CLOB,
   FOOD_INTERACTIONS     CLOB,
   ORGNL_SELLING_PRICE   NUMBER DEFAULT 0 NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE INV.INV_ITM_LIST
ADD(  CONSTRAINT PK_ITM_LIST PRIMARY KEY (ITEM_ID ));

-- INDEX: INV.INV.IDX_BASE_UOM_ID

-- DROP INDEX INV.INV.IDX_BASE_UOM_ID;

CREATE INDEX INV.IDX_BASE_UOM_ID
   ON INV.INV_ITM_LIST (BASE_UOM_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.INV.IDX_CATEGORY_ID

-- DROP INDEX INV.INV.IDX_CATEGORY_ID;

CREATE INDEX INV.IDX_CATEGORY_ID
   ON INV.INV_ITM_LIST (CATEGORY_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.INV.IDX_ENABLED_FLAG

-- DROP INDEX INV.INV.IDX_ENABLED_FLAG;

CREATE INDEX INV.IDX_ENABLED_FLAG
   ON INV.INV_ITM_LIST (ENABLED_FLAG)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.INV.IDX_ITEM_CODE

-- DROP INDEX INV.INV.IDX_ITEM_CODE;

CREATE UNIQUE INDEX INV.IDX_ITEM_CODE
   ON INV.INV_ITM_LIST (ITEM_CODE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.INV.IDX_ITEM_DESC

-- DROP INDEX INV.INV.IDX_ITEM_DESC;

CREATE INDEX INV.IDX_ITEM_DESC
   ON INV.INV_ITM_LIST (ITEM_DESC)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

   /*
-- INDEX: INV.INV.IDX_ITEM_ID

-- DROP INDEX INV.INV.IDX_ITEM_ID;

CREATE UNIQUE INDEX INV.IDX_ITEM_ID
   ON INV.INV_ITM_LIST (ITEM_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;
*/
-- INDEX: INV.INV.IDX_ITEM_TYPE

-- DROP INDEX INV.INV.IDX_ITEM_TYPE;

CREATE INDEX INV.IDX_ITEM_TYPE
   ON INV.INV_ITM_LIST (ITEM_TYPE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.INV.IDX_ORG_ID5

-- DROP INDEX INV.INV.IDX_ORG_ID5;

CREATE INDEX INV.IDX_ORG_ID5
   ON INV.INV_ITM_LIST (ORG_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.INV.IDX_TMPLT_ID

-- DROP INDEX INV.INV.IDX_TMPLT_ID;

CREATE INDEX INV.IDX_TMPLT_ID
   ON INV.INV_ITM_LIST (TMPLT_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE INV.INV_ITM_LIST_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER INV.INV_ITM_LIST_TRG
   BEFORE INSERT
   ON INV.INV_ITM_LIST
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.ITEM_ID IS NULL)
DECLARE
   V_ID   INV.INV_ITM_LIST.ITEM_ID%TYPE;
BEGIN
   SELECT   INV.INV_ITM_LIST_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.ITEM_ID := V_ID;
END INV_ITM_LIST_TRG;