/* Formatted on 10/6/2014 8:13:50 PM (QP5 v5.126.903.23003) */
-- TABLE: INV.INV_ITM_TYPE_TEMPLATES

-- DROP TABLE INV.INV_ITM_TYPE_TEMPLATES;

CREATE TABLE INV.INV_ITM_TYPE_TEMPLATES (
   ITEM_TYPE_ID            NUMBER NOT NULL,
   ITEM_TYPE_NAME          VARCHAR2 (100 BYTE),
   ITEM_TYPE_DESC          VARCHAR2 (200 BYTE),
   COGS_ACCT_ID            NUMBER,
   INV_ASSET_ACCT_ID       NUMBER,
   CREATION_DATE           VARCHAR2 (50 BYTE),
   CREATED_BY              NUMBER,
   LAST_UPDATE_BY          NUMBER,
   LAST_UPDATE_DATE        VARCHAR2 (50 BYTE),
   CATEGORY_ID             NUMBER,
   IS_TMPLT_ENABLED_FLAG   VARCHAR2 (1 BYTE),
   SELLING_PRICE           NUMBER,
   SALES_REV_ACCNT_ID      NUMBER,
   SALES_RET_ACCNT_ID      NUMBER,
   PURCH_RET_ACCNT_ID      NUMBER,
   EXPENSE_ACCNT_ID        NUMBER,
   ORG_ID                  NUMBER,
   TAX_CODE_ID             NUMBER,
   DSCNT_CODE_ID           NUMBER,
   EXTR_CHRG_ID            NUMBER,
   MIN_LEVEL               VARCHAR2 (100 BYTE),
   MAX_LEVEL               VARCHAR2 (100 BYTE),
   PLANNING_ENABLED        VARCHAR2 (1 BYTE),
   ITEM_TYPE               VARCHAR2 (50 BYTE)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE INV.INV_ITM_TYPE_TEMPLATES
ADD(  CONSTRAINT PK_ITM_TYPE_TMPLTS PRIMARY KEY (ITEM_TYPE_ID ));

/*
-- INDEX: INV.INV.IDX_ITEM_TYPE_ID

-- DROP INDEX INV.INV.IDX_ITEM_TYPE_ID;

CREATE UNIQUE INDEX INV.IDX_ITEM_TYPE_ID
   ON INV.INV_ITM_TYPE_TEMPLATES (ITEM_TYPE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;
*/
-- INDEX: INV.INV.IDX_ITEM_TYPE_NAME

-- DROP INDEX INV.INV.IDX_ITEM_TYPE_NAME;

CREATE INDEX INV.IDX_ITEM_TYPE_NAME
   ON INV.INV_ITM_TYPE_TEMPLATES (ITEM_TYPE_NAME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.INV.IDX_ORG_ID7

-- DROP INDEX INV.INV.IDX_ORG_ID7;

CREATE INDEX INV.IDX_ORG_ID7
   ON INV.INV_ITM_TYPE_TEMPLATES (ORG_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE SEQUENCE INV.INV_ITM_TYPE_TEMPLATES_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER INV.INV_ITM_TYPE_TEMPLATES_TRG
   BEFORE INSERT
   ON INV.INV_ITM_TYPE_TEMPLATES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.ITEM_TYPE_ID IS NULL)
DECLARE
   V_ID   INV.INV_ITM_TYPE_TEMPLATES.ITEM_TYPE_ID%TYPE;
BEGIN
   SELECT   INV.INV_ITM_TYPE_TEMPLATES_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.ITEM_TYPE_ID := V_ID;
END INV_ITM_TYPE_TEMPLATES_TRG;