/* Formatted on 10/6/2014 8:19:28 PM (QP5 v5.126.903.23003) */
-- TABLE: INV.INV_SHELF

-- DROP TABLE INV.INV_SHELF;

CREATE TABLE INV.INV_SHELF (SHELF_ID           NUMBER,
                            STORE_ID           NUMBER,
                            CREATED_BY         NUMBER,
                            CREATION_DATE      VARCHAR2 (21 BYTE),
                            LAST_UPDATE_BY     NUMBER,
                            LAST_UPDATE_DATE   VARCHAR2 (21 BYTE),
                            ORG_ID             NUMBER,
                            LINE_ID            NUMBER NOT NULL)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE INV.INV_SHELF
ADD(  CONSTRAINT PK_SHELF PRIMARY KEY (LINE_ID ));

/*
-- INDEX: INV.INV.IDX_LINE_ID6

-- DROP INDEX INV.INV.IDX_LINE_ID6;

CREATE UNIQUE INDEX INV.IDX_LINE_ID6
   ON INV.INV_SHELF (LINE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;
*/

-- INDEX: INV.INV.IDX_ORG_ID8

-- DROP INDEX INV.INV.IDX_ORG_ID8;

CREATE INDEX INV.IDX_ORG_ID8
   ON INV.INV_SHELF (ORG_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.INV.IDX_SHELF_ID

-- DROP INDEX INV.INV.IDX_SHELF_ID;

CREATE INDEX INV.IDX_SHELF_ID
   ON INV.INV_SHELF (SHELF_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


-- INDEX: INV.INV.IDX_STORE_ID

-- DROP INDEX INV.INV.IDX_STORE_ID;

CREATE INDEX INV.IDX_STORE_ID
   ON INV.INV_SHELF (STORE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;



CREATE SEQUENCE INV.INV_SHELF_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER INV.INV_SHELF_TRG
   BEFORE INSERT
   ON INV.INV_SHELF
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.LINE_ID IS NULL)
DECLARE
   V_ID   INV.INV_SHELF.LINE_ID%TYPE;
BEGIN
   SELECT   INV.INV_SHELF_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.LINE_ID := V_ID;
END INV_SHELF_TRG;