/* Formatted on 10/6/2014 8:19:55 PM (QP5 v5.126.903.23003) */
-- TABLE: INV.INV_STOCK

-- DROP TABLE INV.INV_STOCK;

CREATE TABLE INV.INV_STOCK (STOCK_ID           NUMBER NOT NULL,
                            ITM_ID             NUMBER,
                            SUBINV_ID          NUMBER,                      --
                            CREATED_BY         NUMBER,
                            CREATION_DATE      VARCHAR2 (21 BYTE),
                            LAST_UPDATE_BY     NUMBER,
                            LAST_UPDATE_DATE   VARCHAR2 (21 BYTE),
                            SHELVES            CLOB,
                            START_DATE         VARCHAR2 (21 BYTE),
                            END_DATE           VARCHAR2 (21 BYTE),
                            ORG_ID             NUMBER,
                            SHELVES_IDS        CLOB)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE INV.INV_STOCK
ADD(  CONSTRAINT PK_STOCK PRIMARY KEY (STOCK_ID ));


-- INDEX: INV.INV.IDX_ITM_ID3

-- DROP INDEX INV.INV.IDX_ITM_ID3;

CREATE INDEX INV.IDX_ITM_ID3
   ON INV.INV_STOCK (ITM_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.INV.IDX_ORG_ID9

-- DROP INDEX INV.INV.IDX_ORG_ID9;

CREATE INDEX INV.IDX_ORG_ID9
   ON INV.INV_STOCK (ORG_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

   /*
-- INDEX: INV.INV.IDX_STOCK_ID2

-- DROP INDEX INV.INV.IDX_STOCK_ID2;

CREATE UNIQUE INDEX INV.IDX_STOCK_ID2
   ON INV.INV_STOCK (STOCK_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;
*/

-- INDEX: INV.INV.IDX_SUBINV_ID5

-- DROP INDEX INV.INV.IDX_SUBINV_ID5;

CREATE INDEX INV.IDX_SUBINV_ID5
   ON INV.INV_STOCK (SUBINV_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE INV.INV_STOCK_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER INV.INV_STOCK_TRG
   BEFORE INSERT
   ON INV.INV_STOCK
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.STOCK_ID IS NULL)
DECLARE
   V_ID   INV.INV_STOCK.STOCK_ID%TYPE;
BEGIN
   SELECT   INV.INV_STOCK_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.STOCK_ID := V_ID;
END INV_STOCK_TRG;