/* Formatted on 10/6/2014 8:21:24 PM (QP5 v5.126.903.23003) */
-- TABLE: INV.INV_STOCK_TRANSFER_DET

-- DROP TABLE INV.INV_STOCK_TRANSFER_DET;

CREATE TABLE INV.INV_STOCK_TRANSFER_DET (
   TRANSFER_QTY       NUMBER,
   SRC_STOCK_ID       NUMBER,
   REASON             CLOB,
   CREATION_DATE      VARCHAR2 (50 BYTE),
   CREATED_BY         NUMBER,
   LAST_UPDATE_DATE   VARCHAR2 (50 BYTE),
   LAST_UPDATE_BY     NUMBER,
   LINE_ID            NUMBER NOT NULL,
   TRANSFER_HDR_ID    NUMBER,
   REMARKS            CLOB,
   ITM_ID             NUMBER,
   DEST_SUBINV_ID     NUMBER,
   CNSGMNT_NOS        CLOB,
   TTL_AMOUNT         NUMBER DEFAULT 0 NOT NULL,
   SRC_STORE_ID       NUMBER,
   DEST_STOCK_ID      NUMBER,
   COST_PRICE         CLOB
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE INV.INV_STOCK_TRANSFER_DET
ADD(  CONSTRAINT PK_SUBINV_TRANSFE_DET PRIMARY KEY (LINE_ID ));

/*
-- INDEX: INV.INV.IDX_LINE_ID9

-- DROP INDEX INV.INV.IDX_LINE_ID9;

CREATE UNIQUE INDEX INV.IDX_LINE_ID9
   ON INV.INV_STOCK_TRANSFER_DET (LINE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;
*/

-- INDEX: INV.INV.IDX_TRANSFER_HDR_ID

-- DROP INDEX INV.INV.IDX_TRANSFER_HDR_ID;

CREATE INDEX INV.IDX_TRANSFER_HDR_ID
   ON INV.INV_STOCK_TRANSFER_DET (TRANSFER_HDR_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE INV.INV_STOCK_TRANSFER_DET_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER INV.INV_STOCK_TRANSFER_DET_TRG
   BEFORE INSERT
   ON INV.INV_STOCK_TRANSFER_DET
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.LINE_ID IS NULL)
DECLARE
   V_ID   INV.INV_STOCK_TRANSFER_DET.LINE_ID%TYPE;
BEGIN
   SELECT   INV.INV_STOCK_TRANSFER_DET_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.LINE_ID := V_ID;
END INV_STOCK_TRANSFER_DET_TRG;