/* Formatted on 10/6/2014 8:21:58 PM (QP5 v5.126.903.23003) */
-- TABLE: INV.INV_STOCK_TRANSFER_HDR

-- DROP TABLE INV.INV_STOCK_TRANSFER_HDR;

CREATE TABLE INV.INV_STOCK_TRANSFER_HDR (
   DESCRIPTION        CLOB,
   CREATED_BY         NUMBER,
   CREATION_DATE      VARCHAR2 (21 BYTE),
   LAST_UPDATE_BY     NUMBER,
   LAST_UPDATE_DATE   VARCHAR2 (21 BYTE),
   TRANSFER_DATE      VARCHAR2 (21 BYTE),
   SOURCE_SUBINV_ID   NUMBER,
   DEST_SUBINV_ID     NUMBER,
   TRANSFER_HDR_ID    NUMBER NOT NULL,
   ORG_ID             NUMBER,
   TOTAL_AMOUNT       NUMBER,
   STATUS             VARCHAR2 (20 BYTE)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE INV.INV_STOCK_TRANSFER_HDR
ADD(  CONSTRAINT PK_SUBINV_TRNSF_HDR PRIMARY KEY (TRANSFER_HDR_ID ));

/*
-- INDEX: INV.IDX_TRANSFER_HDR_ID1

-- DROP INDEX INV.IDX_TRANSFER_HDR_ID1;

CREATE UNIQUE INDEX INV.IDX_TRANSFER_HDR_ID1
   ON INV.INV_STOCK_TRANSFER_HDR (TRANSFER_HDR_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;
*/


CREATE SEQUENCE INV.INV_STOCK_TRANSFER_HDR_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER INV.INV_STOCK_TRANSFER_HDR_TRG
   BEFORE INSERT
   ON INV.INV_STOCK_TRANSFER_HDR
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.TRANSFER_HDR_ID IS NULL)
DECLARE
   V_ID   INV.INV_STOCK_TRANSFER_HDR.TRANSFER_HDR_ID%TYPE;
BEGIN
   SELECT   INV.INV_STOCK_TRANSFER_HDR_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.TRANSFER_HDR_ID := V_ID;
END INV_STOCK_TRANSFER_HDR_TRG;