/* Formatted on 10/6/2014 8:23:11 PM (QP5 v5.126.903.23003) */
-- TABLE: INV.INV_USER_SUBINVENTORIES

-- DROP TABLE INV.INV_USER_SUBINVENTORIES;

CREATE TABLE INV.INV_USER_SUBINVENTORIES (
   USER_ID            NUMBER,
   SUBINV_ID          NUMBER,
   START_DATE         VARCHAR2 (21 BYTE),
   END_DATE           VARCHAR2 (21 BYTE),
   CREATED_BY         NUMBER,
   CREATION_DATE      VARCHAR2 (21 BYTE),
   LAST_UPDATE_BY     NUMBER,
   LAST_UPDATE_DATE   VARCHAR2 (21 BYTE),
   ORG_ID             NUMBER,
   LINE_ID            NUMBER NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


--PRIMARY KEY
ALTER TABLE INV.INV_USER_SUBINVENTORIES ADD(
  CONSTRAINT PK_USER_SUBINV PRIMARY KEY (LINE_ID));

COMMENT ON TABLE INV.INV_USER_SUBINVENTORIES IS
'Storing users who can transact in what stores/warehouse';

/*
--UNIQUE INDEX ON PRIMARY KEY

CREATE UNIQUE INDEX INV.IDX_LINE_ID
   ON INV.INV_USER_SUBINVENTORIES (LINE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;
*/

--INDEX ON FOREIGN KEY

CREATE UNIQUE INDEX INV.IDX_SUBINV_ID_USR
   ON INV.INV_USER_SUBINVENTORIES (SUBINV_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

--INDEX ON FOREIGN KEY

CREATE UNIQUE INDEX INV.IDX_USER_ID_USR
   ON INV.INV_USER_SUBINVENTORIES (USER_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


--SEQUENCE

CREATE SEQUENCE INV.INV_USER_SUBINVENTORIES_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

--TRIGGER

CREATE OR REPLACE TRIGGER INV.INV_USER_SUBINVENTORIES_TRG
   BEFORE INSERT
   ON INV.INV_USER_SUBINVENTORIES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.LINE_ID IS NULL)
DECLARE
   V_ID   INV.INV_USER_SUBINVENTORIES.LINE_ID%TYPE;
BEGIN
   SELECT   INV.INV_USER_SUBINVENTORIES_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.LINE_ID := V_ID;
END INV_USER_SUBINVENTORIES_TRG;