/* Formatted on 10/6/2014 8:23:38 PM (QP5 v5.126.903.23003) */
-- TABLE: INV.ITM_UOMS

-- DROP TABLE INV.ITM_UOMS;

CREATE TABLE INV.ITM_UOMS (ITM_UOM_ID         NUMBER NOT NULL,
                           ITEM_ID            NUMBER,
                           UOM_ID             NUMBER,
                           IS_BASE_UOM        VARCHAR2 (1 BYTE),
                           CNVSN_FACTOR       NUMBER,
                           UOM_LEVEL          NUMBER,
                           CREATION_DATE      VARCHAR2 (21 BYTE),
                           CREATED_BY         NUMBER,
                           LAST_UPDATE_DATE   VARCHAR2 (21 BYTE),
                           LAST_UPDATE_BY     NUMBER,
                           PRICE_LESS_TAX     NUMBER DEFAULT 0 NOT NULL,
                           SELLING_PRICE      NUMBER DEFAULT 0 NOT NULL,
                           CONSTRAINT PK_ITM_UOM_ID PRIMARY KEY (ITM_UOM_ID))
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

-- ALTER TABLE INV.ITM_UOMS ADD (CONSTRAINT PK_ITM_UOM_ID PRIMARY KEY (ITM_UOM_ID));
-- INDEX: INV.IDX_IS_BASE_UOM

-- DROP INDEX INV.IDX_IS_BASE_UOM;

CREATE INDEX INV.IDX_IS_BASE_UOM
   ON INV.ITM_UOMS (IS_BASE_UOM)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.IDX_ITEM_ID2

-- DROP INDEX INV.IDX_ITEM_ID2;

CREATE INDEX INV.IDX_ITEM_ID2
   ON INV.ITM_UOMS (ITEM_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

   /*
-- INDEX: INV.IDX_ITM_UOM_ID

-- DROP INDEX INV.IDX_ITM_UOM_ID;

CREATE UNIQUE INDEX INV.IDX_ITM_UOM_ID
   ON INV.ITM_UOMS (ITM_UOM_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;
*/

-- INDEX: INV.IDX_UOM_ID2

-- DROP INDEX INV.IDX_UOM_ID2;

CREATE INDEX INV.IDX_UOM_ID2
   ON INV.ITM_UOMS (UOM_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: INV.IDX_UOM_LEVEL

-- DROP INDEX INV.IDX_UOM_LEVEL;

CREATE INDEX INV.IDX_UOM_LEVEL
   ON INV.ITM_UOMS (UOM_LEVEL)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE INV.ITM_UOMS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;


CREATE OR REPLACE TRIGGER INV.ITM_UOMS_TRG
   BEFORE INSERT
   ON INV.ITM_UOMS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.ITM_UOM_ID IS NULL)
DECLARE
   V_ID   INV.ITM_UOMS.ITM_UOM_ID%TYPE;
BEGIN
   SELECT   INV.ITM_UOMS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.ITM_UOM_ID := V_ID;
END ITM_UOMS_TRG;