/* Formatted on 12-19-2018 4:40:12 PM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION RPT.GETLOGMSG (P_MSGID NUMBER)
   RETURN CLOB
AS
   L_RESULT   CLOB := '';
BEGIN
   SELECT   '"' || REPLACE (LOG_MESSAGES, '''', '[]') || '"'
     INTO   L_RESULT
     FROM   RPT.RPT_RUN_MSGS A
    WHERE   A.MSG_ID = P_MSGID;


   RETURN COALESCE (L_RESULT, '');
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;