/* Formatted on 12-19-2018 4:33:43 PM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION RPT.GETRPTLOGMSGID (PROCSID     NUMBER,
                                               PROCSTYP    VARCHAR2)
   RETURN NUMBER
AS
   L_RESULT   NUMBER;
BEGIN
   SELECT   MSG_ID
     INTO   L_RESULT
     FROM   RPT.RPT_RUN_MSGS
    WHERE   PROCESS_TYP = PROCSTYP AND PROCESS_ID = PROCSID;

   RETURN COALESCE (L_RESULT, -1);
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN -1;
END;
/