/* Formatted on 12-19-2018 4:38:28 PM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION RPT.GET_RPT_NAME (P_RPTID NUMBER)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (300);
BEGIN
   SELECT   REPORT_NAME
     INTO   L_RESULT
     FROM   RPT.RPT_REPORTS
    WHERE   REPORT_ID = P_RPTID;

   RETURN COALESCE (L_RESULT, -1);
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN -1;
END;