/* Formatted on 12-19-2018 4:37:15 PM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION RPT.GET_RNNR_FILE_NAME (P_RNNRNM VARCHAR2)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (300);
BEGIN
   SELECT   EXECUTBL_FILE_NM
     INTO   L_RESULT
     FROM   RPT.RPT_PRCSS_RNNRS
    WHERE   UPPER (RNNR_NAME) = UPPER (P_RNNRNM);

   RETURN COALESCE (L_RESULT, -1);
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN -1;
END;