/* Formatted on 10/6/2014 9:06:23 PM (QP5 v5.126.903.23003) */
-- TABLE: TKP.TKP_AUDIT_TRAIL_TBL

-- DROP TABLE TKP.TKP_AUDIT_TRAIL_TBL;

CREATE TABLE TKP.TKP_AUDIT_TRAIL_TBL (USER_ID          NUMBER NOT NULL,
                                      ACTION_TYPE      VARCHAR2 (100 BYTE),
                                      ACTION_DETAILS   CLOB,
                                      ACTION_TIME      VARCHAR2 (21 BYTE),
                                      LOGIN_NUMBER     NUMBER NOT NULL,
                                      DFLT_ROW_ID      NUMBER NOT NULL)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE TKP.TKP_AUDIT_TRAIL_TBL
ADD(  CONSTRAINT PK_DFLT_ROW_ID PRIMARY KEY (DFLT_ROW_ID ));

/*
-- INDEX: TKP.TKP.IDX_ACTION_DETAILS

-- DROP INDEX TKP.TKP.IDX_ACTION_DETAILS;

CREATE INDEX TKP.IDX_ACTION_DETAILS
   ON TKP.TKP_AUDIT_TRAIL_TBL (ACTION_DETAILS)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;
*/

-- INDEX: TKP.TKP.IDX_ACTION_TIME

-- DROP INDEX TKP.TKP.IDX_ACTION_TIME;

CREATE INDEX TKP.IDX_ACTION_TIME
   ON TKP.TKP_AUDIT_TRAIL_TBL (ACTION_TIME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: TKP.TKP.IDX_ACTION_TYPE

-- DROP INDEX TKP.TKP.IDX_ACTION_TYPE;

CREATE INDEX TKP.IDX_ACTION_TYPE
   ON TKP.TKP_AUDIT_TRAIL_TBL (ACTION_TYPE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

   /*
-- INDEX: TKP.TKP.IDX_DFLT_ROW_ID

-- DROP INDEX TKP.TKP.IDX_DFLT_ROW_ID;

CREATE UNIQUE INDEX TKP.IDX_DFLT_ROW_ID
   ON TKP.TKP_AUDIT_TRAIL_TBL (DFLT_ROW_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;
*/

-- INDEX: TKP.TKP.IDX_LOGIN_NUMBER

-- DROP INDEX TKP.TKP.IDX_LOGIN_NUMBER;

CREATE INDEX TKP.IDX_LOGIN_NUMBER
   ON TKP.TKP_AUDIT_TRAIL_TBL (LOGIN_NUMBER)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: TKP.TKP.IDX_USER_ID

-- DROP INDEX TKP.TKP.IDX_USER_ID;

CREATE INDEX TKP.IDX_TKP_USER_ID
   ON TKP.TKP_AUDIT_TRAIL_TBL (USER_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE TKP.TKP_AUDIT_TRAIL_DFT_ROW_ID_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER TKP.TKP_AUDIT_TRAIL_ROW_ID_SEQ
   BEFORE INSERT
   ON TKP.TKP_AUDIT_TRAIL_TBL
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.DFLT_ROW_ID IS NULL)
DECLARE
   V_ID   TKP.TKP_AUDIT_TRAIL_TBL.DFLT_ROW_ID%TYPE;
BEGIN
   SELECT   TKP.TKP_AUDIT_TRAIL_DFT_ROW_ID_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.DFLT_ROW_ID := V_ID;
END TKP_AUDIT_TRAIL_ROW_ID_SEQ;