/* Formatted on 10/6/2014 9:06:42 PM (QP5 v5.126.903.23003) */
-- TABLE: TKP.TKP_PRSN_IN_OUT_RSN_TYPES

-- DROP TABLE TKP.TKP_PRSN_IN_OUT_RSN_TYPES;

CREATE TABLE TKP.TKP_PRSN_IN_OUT_RSN_TYPES (
   PRSN_IN_OUT_RSN_TYP_ID    NUMBER NOT NULL,
   PRSN_IN_OUT_RSN_NAME      VARCHAR2 (100 BYTE),
   PRSN_IN_OUT_REASON_DESC   VARCHAR2 (200 BYTE),
   CREATED_BY                NUMBER NOT NULL,
   CREATION_DATE             VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY            NUMBER NOT NULL,
   LAST_UPDATE_DATE          VARCHAR2 (21 BYTE) NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE TKP.TKP_PRSN_IN_OUT_RSN_TYPES
  ADD(  CONSTRAINT PK_PRSN_IN_OUT_RSN_TYP_ID PRIMARY KEY (PRSN_IN_OUT_RSN_TYP_ID ));

  /*
CREATE INDEX TKP.IDX_PRSN_IN_OUT_RSN_TYP_ID
   ON TKP.TKP_PRSN_IN_OUT_RSN_TYPES (PRSN_IN_OUT_RSN_TYP_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;
*/

CREATE SEQUENCE TKP.TKP_PRSN_IN_OUT_TYPES_ID_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER TKP.TKP_PRSN_IN_OUT_TYPES_ID_TRG
   BEFORE INSERT
   ON TKP.TKP_PRSN_IN_OUT_RSN_TYPES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.PRSN_IN_OUT_RSN_TYP_ID IS NULL)
DECLARE
   V_ID   TKP.TKP_PRSN_IN_OUT_RSN_TYPES.PRSN_IN_OUT_RSN_TYP_ID%TYPE;
BEGIN
   SELECT   TKP.TKP_PRSN_IN_OUT_TYPES_ID_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PRSN_IN_OUT_RSN_TYP_ID := V_ID;
END TKP_PRSN_IN_OUT_TYPES_ID_TRG;