/* Formatted on 10/6/2014 9:07:37 PM (QP5 v5.126.903.23003) */
-- TABLE: TKP.TKP_PRSN_INS_N_OUTS

-- DROP TABLE TKP.TKP_PRSN_INS_N_OUTS;

CREATE TABLE TKP.TKP_PRSN_INS_N_OUTS (
   REC_ID                   NUMBER NOT NULL,
   PERSON_ID                NUMBER,
   PRSN_IN_OUT_START_TIME   VARCHAR2 (21 BYTE),
   PRSN_IN_OUT_END_TIME     VARCHAR2 (21 BYTE),
   PRSN_IN_OUT_RSN_TYP_ID   NUMBER,
   FURTHER_DETAILS          VARCHAR2 (100 BYTE),
   SUPERVISOR_APPRVD        VARCHAR2 (1 BYTE),
   CREATED_BY               NUMBER,
   CREATION_DATE            VARCHAR2 (21 BYTE),
   LAST_UPDATE_BY           NUMBER NOT NULL,
   LAST_UPDATE_DATE         VARCHAR2 (21) NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE TKP.TKP_PRSN_INS_N_OUTS
  ADD(  CONSTRAINT PK_REC_ID PRIMARY KEY (REC_ID ));

  /*
CREATE INDEX TKP.IDX_REC_ID
   ON TKP.TKP_PRSN_INS_N_OUTS (REC_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;
*/

CREATE SEQUENCE TKP.TKP_PRSN_INS_N_OUTS_REC_ID_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER TKP.TKP_PRSN_INS_N_OUTS_REC_ID_TRG
   BEFORE INSERT
   ON TKP.TKP_PRSN_INS_N_OUTS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.REC_ID IS NULL)
DECLARE
   V_ID   TKP.TKP_PRSN_INS_N_OUTS.REC_ID%TYPE;
BEGIN
   SELECT   TKP.TKP_PRSN_INS_N_OUTS_REC_ID_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.REC_ID := V_ID;
END TKP_PRSN_INS_N_OUTS_REC_ID_TRG;