/* Formatted on 12-19-2018 11:14:46 AM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION WKF.GET_ACTIVE_INBX_MSGS (P_PERSON_ID NUMBER)
   RETURN INTEGER
AS
   BID   INTEGER := 0;
BEGIN
   SELECT   COUNT (1)
     INTO   BID
     FROM   WKF.WKF_ACTUAL_MSGS_ROUTNG A
    WHERE   A.TO_PRSN_ID = P_PERSON_ID AND A.IS_ACTION_DONE = '0';

   RETURN COALESCE (BID, 0);
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN 0;
END;
/