/* Formatted on 12-20-2018 9:56:46 AM (QP5 v5.126.903.23003) */
-- FUNCTION: ORG.GET_CRITERIA_NAME(BIGINT, VARCHAR2)

-- DROP FUNCTION ORG.GET_CRITERIA_NAME(BIGINT, VARCHAR2);

CREATE OR REPLACE FUNCTION ORG.GET_CRITERIA_NAME (CRTRIAID      NUMBER,
                                                  CRTRIATYPE    VARCHAR2)
   RETURN VARCHAR2
AS
   BID   VARCHAR2 (300) := '';
BEGIN
   IF CRTRIATYPE = 'Everyone'
   THEN
      SELECT   'Everyone' INTO BID FROM DUAL;
   ELSIF CRTRIATYPE = 'Divisions/Groups'
   THEN
      SELECT   DIV_CODE_NAME
        INTO   BID
        FROM   ORG.ORG_DIVS_GROUPS
       WHERE   DIV_ID = CRTRIAID;
   ELSIF CRTRIATYPE = 'Grade'
   THEN
      SELECT   GRADE_CODE_NAME
        INTO   BID
        FROM   ORG.ORG_GRADES
       WHERE   GRADE_ID = CRTRIAID;
   ELSIF CRTRIATYPE = 'Job'
   THEN
      SELECT   JOB_CODE_NAME
        INTO   BID
        FROM   ORG.ORG_JOBS
       WHERE   JOB_ID = CRTRIAID;
   ELSIF CRTRIATYPE = 'Position'
   THEN
      SELECT   POSITION_CODE_NAME
        INTO   BID
        FROM   ORG.ORG_POSITIONS
       WHERE   POSITION_ID = CRTRIAID;
   ELSIF CRTRIATYPE = 'Site/Location'
   THEN
      SELECT   REPLACE (LOCATION_CODE_NAME || '.' || SITE_DESC,
                        '.' || LOCATION_CODE_NAME,
                        '')
        INTO   BID
        FROM   ORG.ORG_SITES_LOCATIONS
       WHERE   LOCATION_ID = CRTRIAID;
   ELSIF CRTRIATYPE = 'Person Type'
   THEN
      SELECT   A.PSSBL_VALUE
        INTO   BID
        FROM   GST.GEN_STP_LOV_VALUES A, GST.GEN_STP_LOV_NAMES B
       WHERE       A.VALUE_LIST_ID = B.VALUE_LIST_ID
               AND B.VALUE_LIST_NAME = 'Person Types'
               AND A.PSSBL_VALUE_ID = CRTRIAID;
   ELSIF CRTRIATYPE = 'Single Person'
   THEN
      SELECT   PRS.GET_PRSN_NAME (CRTRIAID) INTO BID FROM DUAL;
   END IF;

   RETURN COALESCE (BID, '');
END;