/* Formatted on 12-20-2018 9:43:36 AM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION ORG.GET_ORG_NAME (P_ORGID NUMBER)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200 BYTE);
BEGIN
   SELECT   GST.GET_PSSBL_VAL (ORG_TYP_ID)
     INTO   L_RESULT
     FROM   ORG.ORG_DETAILS
    WHERE   ORG_ID = P_ORGID;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/