/* Formatted on 10/3/2014 3:24:36 PM (QP5 v5.126.903.23003) */
-- FUNCTION: APLAPPS.GET_ORGRETERNACCNTID(INTEGER)

-- DROP FUNCTION APLAPPS.GET_ORGRETERNACCNTID(INTEGER);

CREATE OR REPLACE FUNCTION APLAPPS.GET_ORGRETERNACCNTID (P_ORGIDNO NUMBER)
   RETURN NUMBER
AS
   L_RESULT   NUMERIC := 0.00;
BEGIN
   SELECT   ACCNT_ID
     INTO   L_RESULT
     FROM   ACCB.ACCB_CHART_OF_ACCNTS
    WHERE   IS_RETAINED_EARNINGS = '1' AND ORG_ID = P_ORGIDNO;
    
    RETURN L_RESULT;
END;