/* Formatted on 12-20-2018 9:21:49 AM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION ORG.GET_SITE_CODE_DESC (P_SITEID INTEGER)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200 BYTE);
BEGIN
   L_RESULT := '';

   SELECT   REPLACE (A.LOCATION_CODE_NAME || '.' || A.SITE_DESC,
                     '.' || A.LOCATION_CODE_NAME,
                     '')
               SITE_DESC
     INTO   L_RESULT
     FROM   ORG.ORG_SITES_LOCATIONS A
    WHERE   LOCATION_ID = P_SITEID;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/