/* Formatted on 12-20-2018 9:25:52 AM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION ORG.GET_SITE_DESC (P_SITEID INTEGER)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200 BYTE);
BEGIN
   L_RESULT := '';

   SELECT   SITE_DESC
     INTO   L_RESULT
     FROM   ORG.ORG_SITES_LOCATIONS
    WHERE   LOCATION_ID = P_SITEID;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/