/* Formatted on 12-20-2018 9:34:57 AM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION ORG.GET_DIV_ID (P_DIVNAME VARCHAR2)
   RETURN NUMBER
AS
   L_RESULT   NUMBER;
BEGIN
   L_RESULT := -1;

   SELECT   DIV_ID
     INTO   L_RESULT
     FROM   ORG.ORG_DIVS_GROUPS
    WHERE   LOWER (DIV_CODE_NAME) LIKE LOWER (P_DIVNAME);

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN -1;
END;
/