/* Formatted on 12-20-2018 8:59:23 AM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION PASN.GET_POS_ID (P_POSNAME VARCHAR2)
   RETURN INTEGER
AS
   L_RESULT   INTEGER;
BEGIN
   L_RESULT := -1;

   SELECT   POSITION_ID
     INTO   L_RESULT
     FROM   ORG.ORG_POSITIONS
    WHERE   UPPER (POSITION_CODE_NAME) = UPPER (P_POSNAME);

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN -1;
END;
/