/* Formatted on 12-20-2018 9:33:05 AM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION ORG.GET_SITE_NAME (P_SITEID INTEGER)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200 BYTE);
BEGIN
   SELECT   LOCATION_CODE_NAME
     INTO   L_RESULT
     FROM   ORG.ORG_SITES_LOCATIONS
    WHERE   LOCATION_ID = P_SITEID;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/