/* Formatted on 18/09/2014 08:36:56 (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION APLAPPS.GET_DIV_TYPE (P_DIVID NUMBER)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200 BYTE);
BEGIN
   L_RESULT := '';

   SELECT   APLAPPS.GET_PSSBL_VAL1(APLAPPS.GET_DIV_TYPE_ID (P_DIVID))
     INTO   L_RESULT
     FROM   DUAL;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/