/* Formatted on 18/09/2014 09:03:38 (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION APLAPPS.GET_ORG_NAME (P_ORGID NUMBER)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200 BYTE);
BEGIN
   SELECT   ORG_NAME
     INTO   L_RESULT
     FROM   ORG.ORG_DETAILS
    WHERE   ORG_ID = P_ORGID;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/