/* Formatted on 12-20-2018 9:36:40 AM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION ORG.GET_DIV_TYPE (P_DIVID NUMBER)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200 BYTE);
BEGIN
   L_RESULT := '';

   SELECT   GST.GET_PSSBL_VAL1 (ORG.GET_DIV_TYPE_ID (P_DIVID))
     INTO   L_RESULT
     FROM   DUAL;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/