/* Formatted on 12-20-2018 9:42:26 AM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION ORG.GET_ORG_ID (P_ORGNAME VARCHAR2)
   RETURN NUMBER
AS
   L_RESULT   NUMBER;
BEGIN
   L_RESULT := -1;

   SELECT   ORG_ID
     INTO   L_RESULT
     FROM   ORG.ORG_DETAILS
    WHERE   LOWER (ORG_NAME) LIKE LOWER (P_ORGNAME);

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN -1;
END;
/