/* Formatted on 18/09/2014 08:34:44 (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION APLAPPS.GET_DIV_TYPE_ID (P_DIVID NUMBER)
   RETURN NUMBER
AS
   L_RESULT   NUMBER;
BEGIN
   L_RESULT := -1;

   SELECT   DIV_TYP_ID
     INTO   L_RESULT
     FROM   ORG.ORG_DIVS_GROUPS
    WHERE   DIV_ID = P_DIVID;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN -1;
END;
/