/* Formatted on 12-20-2018 9:45:09 AM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION ORG.GET_POS_NAME (P_ORGID NUMBER)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200 BYTE);
BEGIN
   SELECT   POSITION_CODE_NAME
     INTO   L_RESULT
     FROM   ORG.ORG_POSITIONS
    WHERE   POSITION_ID = P_ORGID;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/