/* Formatted on 18/09/2014 08:57:44 (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION APLAPPS.GET_GRADE_NAME (P_GRDID NUMBER)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200 BYTE);
BEGIN
   SELECT   GRADE_CODE_NAME
     INTO   L_RESULT
     FROM   ORG.ORG_GRADES
    WHERE   GRADE_ID = P_GRDID;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/