/* Formatted on 12-20-2018 9:39:56 AM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION ORG.GET_GRADE_NAME (P_GRDID NUMBER)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200 BYTE);
BEGIN
   SELECT   GRADE_CODE_NAME
     INTO   L_RESULT
     FROM   ORG.ORG_GRADES
    WHERE   GRADE_ID = P_GRDID;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/