/* Formatted on 12-20-2018 9:41:23 AM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION ORG.GET_JOB_NAME (P_JOBID NUMBER)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200 BYTE);
BEGIN
   L_RESULT := '';

   SELECT   JOB_CODE_NAME
     INTO   L_RESULT
     FROM   ORG.ORG_JOBS
    WHERE   JOB_ID = P_JOBID;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/