/* Formatted on 18/09/2014 08:31:33 (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION APLAPPS.GET_DIV_NAME (P_DIVID NUMBER)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200 BYTE);
BEGIN
   L_RESULT := '';

   SELECT   DIV_CODE_NAME
     INTO   L_RESULT
     FROM   ORG.ORG_DIVS_GROUPS
    WHERE   DIV_ID = P_DIVID;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/