/* Formatted on 12-18-2018 9:24:24 AM (QP5 v5.126.903.23003) */
DROP TABLE WKF.WKF_APPRVR_GROUP_MEMBERS CASCADE CONSTRAINTS PURGE;

CREATE TABLE WKF.WKF_APPRVR_GROUP_MEMBERS (
   MEMBER_ID          NUMBER NOT NULL,
   APPRVR_GROUP_ID    INTEGER DEFAULT -1 NOT NULL,
   PERSON_ID          NUMBER,
   CREATED_BY         NUMBER NOT NULL,
   CREATION_DATE      VARCHAR2 (21),
   LAST_UPDATE_BY     NUMBER NOT NULL,
   LAST_UPDATE_DATE   VARCHAR2 (21) NOT NULL,
   IS_ENABLED         VARCHAR2 (1),
   CONSTRAINT PK_GM_MEMBER_ID PRIMARY KEY (MEMBER_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

DROP SEQUENCE WKF.WKF_APPRVR_GROUP_MEMBERS_SEQ;

CREATE SEQUENCE WKF.WKF_APPRVR_GROUP_MEMBERS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER WKF.WKF_APPRVR_GROUP_MEMBERS_TRG
   BEFORE INSERT
   ON WKF.WKF_APPRVR_GROUP_MEMBERS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.MEMBER_ID IS NULL)
DECLARE
   V_ID   WKF.WKF_APPRVR_GROUP_MEMBERS.MEMBER_ID%TYPE;
BEGIN
   SELECT   WKF.WKF_APPRVR_GROUP_MEMBERS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.MEMBER_ID := V_ID;
END WKF_APPRVR_GROUP_MEMBERS_TRG;