/* Formatted on 12-18-2018 9:54:10 AM (QP5 v5.126.903.23003) */
DROP TABLE WKF.WKF_AUDIT_TRAIL_TBL CASCADE CONSTRAINTS PURGE;

CREATE TABLE WKF.WKF_AUDIT_TRAIL_TBL (USER_ID          NUMBER NOT NULL,
                                      ACTION_TYPE      VARCHAR2 (30 BYTE),
                                      ACTION_DETAILS   CLOB,
                                      ACTION_TIME      VARCHAR2 (21 BYTE),
                                      LOGIN_NUMBER     NUMBER,
                                      DFLT_ROW_ID      NUMBER NOT NULL)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE WKF.WKF_AUDIT_TRAIL_TBL
ADD(  CONSTRAINT PK_DFLT_ROW_ID PRIMARY KEY (DFLT_ROW_ID ));

-- INDEX: WKF.WKF.IDX_ACTION_TIME

-- DROP INDEX WKF.WKF.IDX_ACTION_TIME;

CREATE INDEX WKF.IDX_ACTION_TIME
   ON WKF.WKF_AUDIT_TRAIL_TBL (ACTION_TIME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: WKF.WKF.IDX_ACTION_TYPE

-- DROP INDEX WKF.WKF.IDX_ACTION_TYPE;

CREATE INDEX WKF.IDX_ACTION_TYPE
   ON WKF.WKF_AUDIT_TRAIL_TBL (ACTION_TYPE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE INDEX WKF.IDX_LOGIN_NUMBER
   ON WKF.WKF_AUDIT_TRAIL_TBL (LOGIN_NUMBER)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: WKF.WKF.IDX_USER_ID

-- DROP INDEX WKF.WKF.IDX_USER_ID;

CREATE INDEX WKF.IDX_USER_ID
   ON WKF.WKF_AUDIT_TRAIL_TBL (USER_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP  SEQUENCE WKF.WKF_AUDIT_TRAIL_DFT_ROW_ID_SEQ;

CREATE SEQUENCE WKF.WKF_AUDIT_TRAIL_DFT_ROW_ID_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER WKF.WKF_AUDIT_TRAIL_DFT_ROW_ID_TRG
   BEFORE INSERT
   ON WKF.WKF_AUDIT_TRAIL_TBL
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.DFLT_ROW_ID IS NULL)
DECLARE
   V_ID   WKF.WKF_AUDIT_TRAIL_TBL.DFLT_ROW_ID%TYPE;
BEGIN
   SELECT   WKF.WKF_AUDIT_TRAIL_DFT_ROW_ID_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.DFLT_ROW_ID := V_ID;
END WKF_AUDIT_TRAIL_DFT_ROW_ID_TRG;