/* Formatted on 12-18-2018 9:11:17 AM (QP5 v5.126.903.23003) */
DROP TABLE WKF.WKF_ACTUAL_MSGS_HDR CASCADE CONSTRAINTS PURGE;

CREATE TABLE WKF.WKF_ACTUAL_MSGS_HDR (
   MSG_ID             NUMBER NOT NULL,
   MSG_HDR            VARCHAR2 (200 BYTE),
   MSG_BODY           CLOB,
   CREATED_BY         NUMBER NOT NULL,
   CREATION_DATE      VARCHAR2 (21 BYTE) NOT NULL,
   HERCHY_ID          NUMBER,
   MSG_TYP            VARCHAR2 (50 BYTE),                  -- INFORMATIONAL...
   APP_ID             NUMBER,
   MSG_STATUS         VARCHAR2 (1 BYTE),
   SRC_DOC_TYPE       VARCHAR2 (200 BYTE),
   SRC_DOC_ID         NUMBER,
   LAST_UPDATE_BY     NUMBER DEFAULT -1 NOT NULL,
   LAST_UPDATE_DATE   VARCHAR2 (21 BYTE),
   attchments         CLOB,
   attchments_desc    CLOB,
   CONSTRAINT PK_MSG_ID PRIMARY KEY (MSG_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;



COMMENT ON COLUMN WKF.WKF_ACTUAL_MSGS_HDR.MSG_TYP IS
'Informational
Approval Doc';


-- INDEX: WKF.WKF.IDX_APP_ID

-- DROP INDEX WKF.WKF.IDX_APP_ID;

CREATE INDEX WKF.IDX_APP_ID
   ON WKF.WKF_ACTUAL_MSGS_HDR (APP_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: WKF.WKF.IDX_CREATION_DATE

-- DROP INDEX WKF.WKF.IDX_CREATION_DATE;

CREATE INDEX WKF.IDX_CREATION_DATE
   ON WKF.WKF_ACTUAL_MSGS_HDR (CREATION_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: WKF.WKF.IDX_HERCHY_ID

-- DROP INDEX WKF.WKF.IDX_HERCHY_ID;

CREATE INDEX WKF.IDX_HERCHY_ID
   ON WKF.WKF_ACTUAL_MSGS_HDR (HERCHY_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: WKF.WKF.IDX_MSG_HDR

-- DROP INDEX WKF.WKF.IDX_MSG_HDR;

CREATE INDEX WKF.IDX_MSG_HDR
   ON WKF.WKF_ACTUAL_MSGS_HDR (MSG_HDR)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX WKF.IDX_MSG_TYP
   ON WKF.WKF_ACTUAL_MSGS_HDR (MSG_TYP)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE WKF.NTF_ACTUAL_MSGS_HDR_MSG_ID_SEQ;

CREATE SEQUENCE WKF.NTF_ACTUAL_MSGS_HDR_MSG_ID_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER WKF.NTF_ACTUAL_MSGS_HDR_MSG_ID_TRG
   BEFORE INSERT
   ON WKF.WKF_ACTUAL_MSGS_HDR
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.MSG_ID IS NULL)
DECLARE
   V_ID   WKF.WKF_ACTUAL_MSGS_HDR.MSG_ID%TYPE;
BEGIN
   SELECT   WKF.NTF_ACTUAL_MSGS_HDR_MSG_ID_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.MSG_ID := V_ID;
END NTF_ACTUAL_MSGS_HDR_MSG_ID_TRG;