/* Formatted on 12-18-2018 9:38:26 AM (QP5 v5.126.903.23003) */
DROP TABLE WKF.WKF_APPS CASCADE CONSTRAINTS PURGE;

CREATE TABLE WKF.WKF_APPS (APP_ID          NUMBER NOT NULL,
                           APP_NAME        VARCHAR2 (200 BYTE),
                           SOURCE_MODULE   VARCHAR2 (300 BYTE),
                           APP_DESC        VARCHAR2 (300 BYTE),
                           CREATED_BY      NUMBER NOT NULL,
                           CREATION_DATE   VARCHAR2 (21 BYTE) NOT NULL)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE WKF.WKF_APPS
 ADD(  CONSTRAINT PK_APP_ID PRIMARY KEY (APP_ID ));
DROP SEQUENCE WKF.WKF_WORKFLOW_APPS_APP_ID_SEQ;

CREATE SEQUENCE WKF.WKF_WORKFLOW_APPS_APP_ID_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER WKF.WKF_WORKFLOW_APPS_APP_ID_TRG
   BEFORE INSERT
   ON WKF.WKF_APPS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.APP_ID IS NULL)
DECLARE
   V_ID   WKF.WKF_APPS.APP_ID%TYPE;
BEGIN
   SELECT   WKF.WKF_WORKFLOW_APPS_APP_ID_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.APP_ID := V_ID;
END WKF_WORKFLOW_APPS_APP_ID_TRG;