/* Formatted on 12-18-2018 9:51:44 AM (QP5 v5.126.903.23003) */
DROP TABLE WKF.WKF_APPS_N_HRCHIES CASCADE CONSTRAINTS PURGE;

CREATE TABLE WKF.WKF_APPS_N_HRCHIES (
   APP_HRCHY_ID       NUMBER NOT NULL,
   APP_ID             NUMBER,
   HIERARCHY_ID       NUMBER,
   IS_ENABLED         VARCHAR2 (1 BYTE),
   CREATED_BY         NUMBER NOT NULL,
   CREATION_DATE      VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY     NUMBER NOT NULL,
   LAST_UPDATE_DATE   VARCHAR2 (21 BYTE) NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE WKF.WKF_APPS_N_HRCHIES
ADD(  CONSTRAINT PK_APP_HRCHY_ID PRIMARY KEY (APP_HRCHY_ID ));
DROP SEQUENCE WKF.WKF_APPS_N_HRCHIES_ID_SEQ;

CREATE SEQUENCE WKF.WKF_APPS_N_HRCHIES_ID_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER WKF.WKF_APPS_N_HRCHIES_ID_TRG
   BEFORE INSERT
   ON WKF.WKF_APPS_N_HRCHIES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.APP_HRCHY_ID IS NULL)
DECLARE
   V_ID   WKF.WKF_APPS_N_HRCHIES.APP_HRCHY_ID%TYPE;
BEGIN
   SELECT   WKF.WKF_APPS_N_HRCHIES_ID_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.APP_HRCHY_ID := V_ID;
END WKF_APPS_N_HRCHIES_ID_TRG;