/* Formatted on 12-18-2018 9:35:25 AM (QP5 v5.126.903.23003) */
DROP TABLE WKF.WKF_APPRVR_GROUPS CASCADE CONSTRAINTS PURGE;

CREATE TABLE WKF.WKF_APPRVR_GROUPS (
   APPRVR_GROUP_ID     NUMBER NOT NULL,
   GROUP_NAME          VARCHAR2 (200),
   GROUP_DESCRIPTION   VARCHAR2 (300),
   LINKED_FIRM_ID      NUMBER DEFAULT -1 NOT NULL,
   ORG_ID              INTEGER DEFAULT -1 NOT NULL,
   IS_ENABLED          VARCHAR2 (1),
   CREATED_BY          NUMBER NOT NULL,
   CREATION_DATE       VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY      NUMBER NOT NULL,
   LAST_UPDATE_DATE    VARCHAR2 (21) NOT NULL,
   CONSTRAINT PK_APPRVR_GRP_ID PRIMARY KEY (APPRVR_GROUP_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

DROP SEQUENCE WKF.WKF_APPRVR_GROUPS_SEQ;

CREATE SEQUENCE WKF.WKF_APPRVR_GROUPS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER WKF.WKF_APPRVR_GROUPS_TRG
   BEFORE INSERT
   ON WKF.WKF_APPRVR_GROUPS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.APPRVR_GROUP_ID IS NULL)
DECLARE
   V_ID   WKF.WKF_APPRVR_GROUPS.APPRVR_GROUP_ID%TYPE;
BEGIN
   SELECT   WKF.WKF_APPRVR_GROUPS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.APPRVR_GROUP_ID := V_ID;
END WKF_APPRVR_GROUPS_TRG;