/* Formatted on 12-18-2018 9:18:49 AM (QP5 v5.126.903.23003) */
DROP TABLE WKF.WKF_ACTUAL_MSGS_ROUTNG CASCADE CONSTRAINTS PURGE;

CREATE TABLE WKF.WKF_ACTUAL_MSGS_ROUTNG (
   member_id          NUMBER NOT NULL,
   apprvr_group_id    INTEGER DEFAULT -1 NOT NULL,
   person_id          NUMBER,
   created_by         NUMBER NOT NULL,
   creation_date      CHARACTER VARYING (21),
   last_update_by     NUMBER NOT NULL,
   last_update_date   CHARACTER VARYING (21) NOT NULL,
   is_enabled         CHARACTER VARYING (1),
   CONSTRAINT pk_member_id PRIMARY KEY (member_id)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE WKF.WKF_ACTUAL_MSGS_ROUTNG
ADD(  CONSTRAINT PK_ROUTING_ID PRIMARY KEY (ROUTING_ID ));


COMMENT ON COLUMN WKF.WKF_ACTUAL_MSGS_ROUTNG.MSG_STATUS IS
'Initiated
Approved
Rejected
Cancelled
Reviewed
Acknowledged';

COMMENT ON COLUMN WKF.WKF_ACTUAL_MSGS_ROUTNG.ACTION_TO_PERFORM IS
'Approve
Review
Reject
Cancel
Acknowledge
Initiate';


-- INDEX: WKF.WKF.IDX_DATE_ACTION_WS_PRFMD

-- DROP INDEX WKF.WKF.IDX_DATE_ACTION_WS_PRFMD;

CREATE INDEX WKF.IDX_DATE_ACTION_WS_PRFMD
   ON WKF.WKF_ACTUAL_MSGS_ROUTNG (DATE_ACTION_WS_PRFMD)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: WKF.WKF.IDX_DATE_SENT

-- DROP INDEX WKF.WKF.IDX_DATE_SENT;

CREATE INDEX WKF.IDX_DATE_SENT
   ON WKF.WKF_ACTUAL_MSGS_ROUTNG (DATE_SENT)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: WKF.WKF.IDX_FROM_PRSN_ID

-- DROP INDEX WKF.WKF.IDX_FROM_PRSN_ID;

CREATE INDEX WKF.IDX_FROM_PRSN_ID
   ON WKF.WKF_ACTUAL_MSGS_ROUTNG (FROM_PRSN_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: WKF.WKF.IDX_MSG_ID_R

-- DROP INDEX WKF.WKF.IDX_MSG_ID_R;

CREATE INDEX WKF.IDX_MSG_ID_R
   ON WKF.WKF_ACTUAL_MSGS_ROUTNG (MSG_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: WKF.WKF.IDX_MSG_STATUS

-- DROP INDEX WKF.WKF.IDX_MSG_STATUS;

CREATE INDEX WKF.IDX_MSG_STATUS
   ON WKF.WKF_ACTUAL_MSGS_ROUTNG (MSG_STATUS)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX WKF.IDX_STATUS_AFTR_ACTION
   ON WKF.WKF_ACTUAL_MSGS_ROUTNG (STATUS_AFTR_ACTION)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: WKF.WKF.IDX_TO_PRSN_ID

-- DROP INDEX WKF.WKF.IDX_TO_PRSN_ID;

CREATE INDEX WKF.IDX_TO_PRSN_ID
   ON WKF.WKF_ACTUAL_MSGS_ROUTNG (TO_PRSN_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: WKF.WKF.IDX_WHO_PRFMD_ACTION

-- DROP INDEX WKF.WKF.IDX_WHO_PRFMD_ACTION;

CREATE INDEX WKF.IDX_WHO_PRFMD_ACTION
   ON WKF.WKF_ACTUAL_MSGS_ROUTNG (WHO_PRFMD_ACTION)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE WKF.WKF_ACTUAL_MSGS_ROUTNG_ID_SEQ;

CREATE SEQUENCE WKF.WKF_ACTUAL_MSGS_ROUTNG_ID_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER WKF.WKF_ACTUAL_MSGS_ROUTNG_ID_TRG
   BEFORE INSERT
   ON WKF.WKF_ACTUAL_MSGS_ROUTNG
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.ROUTING_ID IS NULL)
DECLARE
   V_ID   WKF.WKF_ACTUAL_MSGS_ROUTNG.ROUTING_ID%TYPE;
BEGIN
   SELECT   WKF.WKF_ACTUAL_MSGS_ROUTNG_ID_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.ROUTING_ID := V_ID;
END WKF_ACTUAL_MSGS_ROUTNG_ID_TRG;