/* Formatted on 12-19-2018 12:06:53 PM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION SEC.GET_MODULE_ID (P_MDL_NAME VARCHAR2)
   RETURN INTEGER
AS
   L_RESULT   INTEGER := 0;
BEGIN
   SELECT   MODULE_ID
     INTO   L_RESULT
     FROM   SEC.SEC_MODULES
    WHERE   UPPER (MODULE_NAME) = UPPER (P_MDL_NAME);

   RETURN COALESCE (L_RESULT, -1);

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN 0;
END;
/