/* Formatted on 12-19-2018 12:15:27 PM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION SEC.GET_MODULE_NM (P_MDLID NUMBER)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200 BYTE);
BEGIN
   SELECT   MODULE_NAME
     INTO   L_RESULT
     FROM   SEC.SEC_MODULES
    WHERE   MODULE_ID = P_MDLID;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/