/* Formatted on 12-19-2018 12:07:27 PM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION SEC.GET_PRVLDG_ID (P_PRVLDG_NAME    VARCHAR2,
                                              P_MDL_NAME       VARCHAR2)
   RETURN INTEGER
AS
   L_RESULT   INTEGER := 0;
BEGIN
   SELECT   PRVLDG_ID
     INTO   L_RESULT
     FROM   SEC.SEC_PRVLDGS
    WHERE   (UPPER (PRVLDG_NAME) = UPPER (P_PRVLDG_NAME)
             AND MODULE_ID = SEC.GET_MODULE_ID (P_MDL_NAME));

   RETURN COALESCE (L_RESULT, -1);

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN 0;
END;
/