/* Formatted on 10/6/2014 7:31:17 PM (QP5 v5.126.903.23003) */
CREATE TABLE HOSP.APPNTMNT (APPNTMNT_ID          NUMBER NOT NULL,
                            VST_ID               NUMBER,
                            APPNTMNT_DATE        VARCHAR2 (21 BYTE),
                            APPNTMNT_STATUS      VARCHAR2 (11 BYTE) NOT NULL,
                            CMNTS                VARCHAR2 (500 BYTE),
                            CREATED_BY           VARCHAR2 (21 BYTE),
                            CREATION_DATE        VARCHAR2 (21 BYTE),
                            LAST_UPDATE_BY       VARCHAR2 (21 BYTE),
                            LAST_UPDATE_DATE     VARCHAR2 (21 BYTE),
                            PRVDR_TYPE           VARCHAR2 (1 BYTE),
                            SRVS_TYPE_ID         NUMBER,
                            SRVS_PRVDR_PRSN_ID   NUMBER NOT NULL,
                            PRVDR_GRP_ID         NUMBER NOT NULL)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX HOSP.IDX_APPNTMNT_ID
   ON HOSP.APPNTMNT (APPNTMNT_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE HOSP.APPNTMNT ADD (
  CONSTRAINT PK_APPNTMNT_ID
 PRIMARY KEY
 (APPNTMNT_ID));

CREATE SEQUENCE HOSP.APPNTMNT_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER HOSP.APPNTMNT_TRG
   BEFORE INSERT
   ON HOSP.APPNTMNT
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.APPNTMNT_ID IS NULL)
DECLARE
   V_ID   HOSP.APPNTMNT.APPNTMNT_ID%TYPE;
BEGIN
   SELECT   HOSP.APPNTMNT_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.APPNTMNT_ID := V_ID;
END APPNTMNT_TRG;