/* Formatted on 10/6/2014 7:31:38 PM (QP5 v5.126.903.23003) */
CREATE TABLE HOSP.APPNTMNT_DATA_ITEMS (APPDT_ITM_ID       NUMBER NOT NULL,
                                       APPNTMNT_ID        NUMBER,
                                       QTY                NUMBER (*, 2),
                                       CMNTS              VARCHAR2 (500 BYTE),
                                       CREATED_BY         NUMBER,
                                       CREATION_DATE      VARCHAR2 (21 BYTE),
                                       LAST_UPDATE_BY     VARCHAR2 (21 BYTE),
                                       LAST_UPDATE_DATE   VARCHAR2 (21 BYTE),
                                       ITEM_ID            NUMBER)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX HOSP.IDX_APPDT_ITM_ID
   ON HOSP.APPNTMNT_DATA_ITEMS (APPDT_ITM_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE HOSP.APPNTMNT_DATA_ITEMS ADD (
  CONSTRAINT PK_APPDT_ITM_ID
 PRIMARY KEY
 (APPDT_ITM_ID));

CREATE SEQUENCE HOSP.APPNTMNT_DATA_ITEMS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER HOSP.APPNTMNT_DATA_ITEMS_TRG
   BEFORE INSERT
   ON HOSP.APPNTMNT_DATA_ITEMS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.APPDT_ITM_ID IS NULL)
DECLARE
   V_ID   HOSP.APPNTMNT_DATA_ITEMS.APPDT_ITM_ID%TYPE;
BEGIN
   SELECT   HOSP.APPNTMNT_DATA_ITEMS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.APPDT_ITM_ID := V_ID;
END APPNTMNT_DATA_ITEMS_TRG;