/* Formatted on 10/6/2014 7:32:07 PM (QP5 v5.126.903.23003) */
CREATE TABLE HOSP.CNSLTN_DIAGN_TYPES (DIAG_ID            NUMBER NOT NULL,
                                      DIAG_TYPE          VARCHAR (50 BYTE), -- UNUSED - DELETE
                                      CMNTS              VARCHAR (500 BYTE),
                                      CREATED_BY         VARCHAR (21 BYTE),
                                      CREATION_DATE      VARCHAR (21 BYTE),
                                      LAST_UPDATE_BY     VARCHAR (21 BYTE),
                                      LAST_UPDATE_DATE   VARCHAR (21 BYTE),
                                      CNSLTN_ID          NUMBER,
                                      DISEASE_ID         NUMBER)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX HOSP.IDX_DIAG_ID
   ON HOSP.CNSLTN_DIAGN_TYPES (DIAG_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE HOSP.CNSLTN_DIAGN_TYPES ADD (
  CONSTRAINT PK_DIAG_ID
 PRIMARY KEY
 (DIAG_ID));

CREATE SEQUENCE HOSP.CNSLTN_DIAGN_TYPES_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER HOSP.CNSLTN_DIAGN_TYPES_TRG
   BEFORE INSERT
   ON HOSP.CNSLTN_DIAGN_TYPES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.DIAG_ID IS NULL)
DECLARE
   V_ID   HOSP.CNSLTN_DIAGN_TYPES.DIAG_ID%TYPE;
BEGIN
   SELECT   HOSP.CNSLTN_DIAGN_TYPES_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.DIAG_ID := V_ID;
END CNSLTN_DIAGN_TYPES_TRG;