/* Formatted on 10/6/2014 7:32:34 PM (QP5 v5.126.903.23003) */
CREATE TABLE HOSP.DISEASES (DISEASE_ID           NUMBER NOT NULL,
                            DISEASE_NAME         VARCHAR (200 BYTE),
                            DISEASE_DESC         VARCHAR (300 BYTE),
                            SYMTMS               VARCHAR (500 BYTE),
                            PSSBL_TRTMNT_MDCTN   VARCHAR (500 BYTE),
                            CREATED_BY           VARCHAR (21 BYTE),
                            CREATION_DATE        VARCHAR (21 BYTE),
                            LAST_UPDATE_BY       VARCHAR (21 BYTE),
                            LAST_UPDATE_DATE     VARCHAR (21 BYTE))
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX HOSP.IDX_DISEASE_ID
   ON HOSP.DISEASES (DISEASE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE HOSP.DISEASES ADD (
  CONSTRAINT PK_DISEASE_ID
 PRIMARY KEY
 (DISEASE_ID));

CREATE SEQUENCE HOSP.DISEASES_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER HOSP.DISEASES_TRG
   BEFORE INSERT
   ON HOSP.DISEASES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.DISEASE_ID IS NULL)
DECLARE
   V_ID   HOSP.DISEASES.DISEASE_ID%TYPE;
BEGIN
   SELECT   HOSP.DISEASES_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.DISEASE_ID := V_ID;
END DISEASES_TRG;