/* Formatted on 10/6/2014 7:32:46 PM (QP5 v5.126.903.23003) */
CREATE TABLE HOSP.INVSTGTN (INVSTGTN_ID        NUMBER NOT NULL,
                            CNSLTN_ID          NUMBER,
                            CREATED_BY         VARCHAR (21 BYTE),
                            CREATION_DATE      VARCHAR (21 BYTE),
                            LAST_UPDATE_BY     VARCHAR (21 BYTE),
                            LAST_UPDATE_DATE   VARCHAR (21 BYTE),
                            RCMDD_ITM_DESC     VARCHAR (200 BYTE),
                            ACTL_ITM_ID        NUMBER,
                            DOC_CMNTS          VARCHAR (500 BYTE),
                            LAB_CMNTS          VARCHAR (500 BYTE),
                            LAB_LOC            VARCHAR (200 BYTE),
                            LAB_RESULTS        VARCHAR (300 BYTE),
                            DEST_APPNTMNT_ID   NUMBER,
                            INVSTGTN_LIST_ID   NUMBER)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX HOSP.IDX_INVSTGTN_ID
   ON HOSP.INVSTGTN (INVSTGTN_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE HOSP.INVSTGTN ADD (
  CONSTRAINT PK_INVSTGTN_ID
 PRIMARY KEY
 (INVSTGTN_ID));

CREATE SEQUENCE HOSP.INVSTGTN_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER HOSP.INVSTGTN_TRG
   BEFORE INSERT
   ON HOSP.INVSTGTN
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.INVSTGTN_ID IS NULL)
DECLARE
   V_ID   HOSP.INVSTGTN.INVSTGTN_ID%TYPE;
BEGIN
   SELECT   HOSP.INVSTGTN_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.INVSTGTN_ID := V_ID;
END INVSTGTN_TRG;