/* Formatted on 10/6/2014 7:33:25 PM (QP5 v5.126.903.23003) */
CREATE TABLE HOSP.INVSTGTN_ITMS_SERVS (
   INVSTGTN_ITMSERVS_ID   NUMBER NOT NULL,
   INVSTGTN_LIST_ID       NUMBER,
   ITM_CODE               VARCHAR2 (200 BYTE),
   QUANTITY               NUMBER (*, 2),
   CMNTS                  VARCHAR2 (500 BYTE),
   CREATED_BY             VARCHAR2 (21 BYTE),
   CREATION_DATE          VARCHAR2 (21 BYTE),
   LAST_UPDATE_BY         VARCHAR2 (21 BYTE),
   LAST_UPDATE_DATE       VARCHAR2 (21 BYTE),
   ITM_ID                 NUMBER
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX HOSP.INVSTGTN_ITMSERVS_ID
   ON HOSP.INVSTGTN_ITMS_SERVS (INVSTGTN_ITMSERVS_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE HOSP.INVSTGTN_ITMS_SERVS ADD (
  CONSTRAINT PK_INVSTGTN_ITMSERVS_ID
 PRIMARY KEY
 (INVSTGTN_ITMSERVS_ID));

CREATE SEQUENCE HOSP.INVSTGTN_ITMS_SERVS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER HOSP.INVSTGTN_ITMS_SERVS_TRG
   BEFORE INSERT
   ON HOSP.INVSTGTN_ITMS_SERVS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.INVSTGTN_ITMSERVS_ID IS NULL)
DECLARE
   V_ID   HOSP.INVSTGTN_ITMS_SERVS.INVSTGTN_ITMSERVS_ID%TYPE;
BEGIN
   SELECT   HOSP.INVSTGTN_ITMS_SERVS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.INVSTGTN_ITMSERVS_ID := V_ID;
END INVSTGTN_ITMS_SERVS_TRG;