/* Formatted on 10/6/2014 7:34:22 PM (QP5 v5.126.903.23003) */
CREATE TABLE HOSP.MEDCL_CNSLTN (CNSLTN_ID          NUMBER NOT NULL,
                                APPNTMNT_ID        NUMBER,
                                SPCH_DICTN         VARCHAR2 (500 BYTE), -- SPEECH DICTATION
                                CMNTS              VARCHAR2 (500 BYTE),
                                CREATED_BY         VARCHAR2 (21 BYTE),
                                CREATION_DATE      VARCHAR2 (21 BYTE),
                                LAST_UPDATE_BY     VARCHAR2 (21 BYTE),
                                LAST_UPDATE_DATE   VARCHAR2 (21 BYTE))
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX HOSP.IDX_CNSLTN_ID
   ON HOSP.MEDCL_CNSLTN (CNSLTN_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE HOSP.MEDCL_CNSLTN ADD (
  CONSTRAINT PK_CNSLTN_ID
 PRIMARY KEY
 (CNSLTN_ID));

CREATE SEQUENCE HOSP.MEDCL_CNSLTN_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER HOSP.MEDCL_CNSLTN_TRG
   BEFORE INSERT
   ON HOSP.MEDCL_CNSLTN
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.CNSLTN_ID IS NULL)
DECLARE
   V_ID   HOSP.MEDCL_CNSLTN.CNSLTN_ID%TYPE;
BEGIN
   SELECT   HOSP.MEDCL_CNSLTN_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.CNSLTN_ID := V_ID;
END MEDCL_CNSLTN_TRG;