/* Formatted on 10/6/2014 7:35:08 PM (QP5 v5.126.903.23003) */
CREATE TABLE HOSP.PRVDR_GRPS (PRVDR_GRP_ID       NUMBER,
                              PRVDR_GRP_NAME     VARCHAR2 (100 BYTE),
                              PRVDR_GRP_DESC     VARCHAR2 (300 BYTE),
                              CREATED_BY         VARCHAR2 (21 BYTE),
                              CREATION_DATE      VARCHAR2 (21 BYTE),
                              LAST_UPDATE_BY     VARCHAR2 (21 BYTE),
                              LAST_UPDATE_DATE   VARCHAR2 (21 BYTE),
                              ENABLED_FLAG       VARCHAR2 (1 BYTE))
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX HOSP.IDX_PRVDR_GRP_ID
   ON HOSP.PRVDR_GRPS (PRVDR_GRP_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE HOSP.PRVDR_GRPS ADD (
  CONSTRAINT PK_PRVDR_GRP_ID
 PRIMARY KEY
 (PRVDR_GRP_ID));

CREATE SEQUENCE HOSP.PRVDR_GRPS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER HOSP.PRVDR_GRPS_TRG
   BEFORE INSERT
   ON HOSP.PRVDR_GRPS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.PRVDR_GRP_ID IS NULL)
DECLARE
   V_ID   HOSP.PRVDR_GRPS.PRVDR_GRP_ID%TYPE;
BEGIN
   SELECT   HOSP.PRVDR_GRPS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PRVDR_GRP_ID := V_ID;
END PRVDR_GRPS_TRG;