/* Formatted on 10/6/2014 7:37:12 PM (QP5 v5.126.903.23003) */
CREATE TABLE HOSP.VISIT (VST_ID             NUMBER,
                         PRSN_ID            NUMBER,
                         VST_DATE           VARCHAR2 (21 BYTE),
                         CMNTS              VARCHAR2 (500 BYTE),   -- COMMENTS
                         CREATED_BY         VARCHAR2 (21 BYTE),
                         CREATION_DATE      VARCHAR2 (21 BYTE),
                         LAST_UPDATE_BY     VARCHAR2 (21 BYTE),
                         LAST_UPDATE_DATE   VARCHAR2 (21 BYTE),
                         VST_STATUS         VARCHAR2 (21 BYTE))
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX HOSP.IDX_VST_ID
   ON HOSP.VISIT (VST_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE HOSP.VISIT ADD (
  CONSTRAINT PK_VST_ID
 PRIMARY KEY
 (VST_ID));

CREATE SEQUENCE HOSP.VISIT_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER HOSP.VISIT_TRG
   BEFORE INSERT
   ON HOSP.VISIT
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.VST_ID IS NULL)
DECLARE
   V_ID   HOSP.VISIT.VST_ID%TYPE;
BEGIN
   SELECT   HOSP.VISIT_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.VST_ID := V_ID;
END VISIT_TRG;