/* Formatted on 12-15-2018 12:09:19 PM (QP5 v5.126.903.23003) */
DROP TABLE RPT.RPT_REPORTS_ALLWD_ROLES  CASCADE CONSTRAINTS PURGE;

CREATE TABLE RPT.RPT_REPORTS_ALLWD_ROLES (
   RPT_ROLES_ID    NUMBER NOT NULL,
   REPORT_ID       NUMBER,
   USER_ROLE_ID    NUMBER,
   CREATED_BY      NUMBER NOT NULL,
   CREATION_DATE   VARCHAR2 (21 BYTE) NOT NULL,
   CONSTRAINT PK_RPT_ROLES_ID PRIMARY KEY (RPT_ROLES_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX RPT.IDX_ROLE_REPORT_ID
   ON RPT.RPT_REPORTS_ALLWD_ROLES (REPORT_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX RPT.IDX_USER_ROLE_ID
   ON RPT.RPT_REPORTS_ALLWD_ROLES (USER_ROLE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE RPT.RPT_REPORTS_ALLWD_ROLES_ID_SEQ;

CREATE SEQUENCE RPT.RPT_REPORTS_ALLWD_ROLES_ID_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER RPT.RPT_REPORTS_ALLWD_ROLES_ID_TRG
   BEFORE INSERT
   ON RPT.RPT_REPORTS_ALLWD_ROLES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.RPT_ROLES_ID IS NULL)
DECLARE
   V_ID   RPT.RPT_REPORTS_ALLWD_ROLES.RPT_ROLES_ID%TYPE;
BEGIN
   SELECT   RPT.RPT_REPORTS_ALLWD_ROLES_ID_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.RPT_ROLES_ID := V_ID;
END RPT_REPORTS_ALLWD_ROLES_ID_TRG;