/* Formatted on 12-15-2018 12:09:35 PM (QP5 v5.126.903.23003) */
DROP TABLE RPT.RPT_REPORTS  CASCADE CONSTRAINTS PURGE;

CREATE TABLE RPT.RPT_REPORTS (
   REPORT_ID           NUMBER NOT NULL,
   REPORT_NAME         VARCHAR2 (200 BYTE),
   REPORT_DESC         VARCHAR2 (300 BYTE),
   RPT_SQL_QUERY       CLOB,
   OWNER_MODULE        VARCHAR2 (200 BYTE),
   CREATED_BY          NUMBER NOT NULL,
   CREATION_DATE       VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY      NUMBER NOT NULL,
   LAST_UPDATE_DATE    VARCHAR2 (21 BYTE) NOT NULL,
   RPT_OR_SYS_PRCS     VARCHAR2 (100 BYTE),
   IS_ENABLED          VARCHAR2 (1 BYTE),
   COLS_TO_GROUP       CLOB,
   COLS_TO_COUNT       CLOB,
   COLS_TO_SUM         CLOB,
   COLS_TO_AVERAGE     CLOB,
   COLS_TO_NO_FRMT     CLOB,
   OUTPUT_TYPE         VARCHAR2 (100 BYTE) DEFAULT 'None' NOT NULL,
   PORTRAIT_LNDSCP     VARCHAR2 (50 BYTE) DEFAULT 'Portrait' NOT NULL,
   RPT_LAYOUT          VARCHAR2 (50 BYTE) DEFAULT 'None' NOT NULL,
   IMGS_COL_NOS        CLOB,
   CSV_DELIMITER       VARCHAR2 (20 BYTE),
   PROCESS_RUNNER      VARCHAR2 (200 BYTE)
         DEFAULT 'Standard Process Runner' NOT NULL,
   IS_SEEDED_RPT       VARCHAR2 (1 BYTE) DEFAULT 0,
   JRXML_FILE_NAME     VARCHAR2 (300),
   PRE_RPT_SQL_QUERY   CLOB,
   PST_RPT_SQL_QUERY   CLOB,
   CONSTRAINT PK_RPT_ID PRIMARY KEY (REPORT_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX RPT.IDX_REPORT_DESC
   ON RPT.RPT_REPORTS (REPORT_DESC)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE UNIQUE INDEX RPT.IDX_REPORT_NAME
   ON RPT.RPT_REPORTS (REPORT_NAME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE RPT.RPT_REPORTS_REPORT_ID_SEQ;

CREATE SEQUENCE RPT.RPT_REPORTS_REPORT_ID_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER RPT.RPT_REPORTS_REPORT_ID_TRG
   BEFORE INSERT
   ON RPT.RPT_REPORTS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.REPORT_ID IS NULL)
DECLARE
   V_ID   RPT.RPT_REPORTS.REPORT_ID%TYPE;
BEGIN
   SELECT   RPT.RPT_REPORTS_REPORT_ID_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.REPORT_ID := V_ID;
END RPT_REPORTS_REPORT_ID_TRG;