/* Formatted on 12-15-2018 12:20:53 PM (QP5 v5.126.903.23003) */
DROP TABLE RPT.RPT_SET_PRGRM_UNITS  CASCADE CONSTRAINTS PURGE;

CREATE TABLE RPT.RPT_SET_PRGRM_UNITS (
   SET_UNIT_ID       NUMBER NOT NULL,
   REPORT_SET_ID     NUMBER,
   PROGRAM_UNIT_ID   NUMBER,
   CREATED_BY        NUMBER NOT NULL,
   CREATION_DATE     VARCHAR2 (21 BYTE),
   CONSTRAINT PK_SET_UNIT_ID PRIMARY KEY (SET_UNIT_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX RPT.IDX_PROGRAM_UNIT_ID
   ON RPT.RPT_SET_PRGRM_UNITS (PROGRAM_UNIT_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE INDEX RPT.IDX_REPORT_SET_ID
   ON RPT.RPT_SET_PRGRM_UNITS (REPORT_SET_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE RPT.RPT_SET_PRGRM_UNITS_ID_SEQ;

CREATE SEQUENCE RPT.RPT_SET_PRGRM_UNITS_ID_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER RPT.RPT_SET_PRGRM_UNITS_ID_TRG
   BEFORE INSERT
   ON RPT.RPT_SET_PRGRM_UNITS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.SET_UNIT_ID IS NULL)
DECLARE
   V_ID   RPT.RPT_SET_PRGRM_UNITS.SET_UNIT_ID%TYPE;
BEGIN
   SELECT   RPT.RPT_SET_PRGRM_UNITS_ID_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.SET_UNIT_ID := V_ID;
END RPT_SET_PRGRM_UNITS_ID_TRG;