/* Formatted on 12-15-2018 10:57:13 AM (QP5 v5.126.903.23003) */
DROP TABLE RPT.RPT_PRCSS_RNNRS  CASCADE CONSTRAINTS PURGE;

CREATE TABLE RPT.RPT_PRCSS_RNNRS (
   PRCSS_RNNR_ID          NUMBER NOT NULL,
   RNNR_NAME              VARCHAR2 (100),
   RNNR_DESC              VARCHAR2 (300),
   RNNR_LST_ACTV_DTETME   VARCHAR2 (21),
   CREATED_BY             NUMBER NOT NULL,
   CREATION_DATE          VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY         NUMBER NOT NULL,
   LAST_UPDATE_DATE       VARCHAR2 (21) NOT NULL,
   RNNR_STATUS            CLOB,
   EXECUTBL_FILE_NM       VARCHAR2 (300),
   CRNT_RNNG_PRIORITY     VARCHAR2 (15),
   SHLD_RNNR_STOP         VARCHAR2 (1) DEFAULT 0 NOT NULL,
   CONSTRAINT PK_PRCSS_RNNR_ID PRIMARY KEY (PRCSS_RNNR_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX IDX_RNNR_NAME
   ON RPT.RPT_PRCSS_RNNRS (RNNR_NAME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE RPT.RPT_PRCSS_RNNRS_PRCSS_RNNR_ID_SEQ;

CREATE SEQUENCE RPT.RPT_PRCSS_RNNRS_PRCSS_RNNR_ID_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER RPT.RPT_PRCSS_RNNRS_PRCSS_RNNR_ID_TRG
   BEFORE INSERT
   ON RPT.RPT_PRCSS_RNNRS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.PRCSS_RNNR_ID IS NULL)
DECLARE
   V_ID   RPT.RPT_PRCSS_RNNRS.PRCSS_RNNR_ID%TYPE;
BEGIN
   SELECT   RPT.RPT_PRCSS_RNNRS_PRCSS_RNNR_ID_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PRCSS_RNNR_ID := V_ID;
END RPT_PRCSS_RNNRS_PRCSS_RNNR_ID_TRG;