/* Formatted on 12-14-2018 7:35:56 PM (QP5 v5.126.903.23003) */
DROP TABLE RPT.RPT_RUN_MSGS  CASCADE CONSTRAINTS PURGE;

CREATE TABLE RPT.RPT_RUN_MSGS (
   MSG_ID             NUMBER NOT NULL,
   LOG_MESSAGES       CLOB,
   PROCESS_TYP        VARCHAR2 (100 BYTE),
   PROCESS_ID         NUMBER,
   CREATED_BY         NUMBER NOT NULL,
   CREATION_DATE      VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY     NUMBER NOT NULL,
   LAST_UPDATE_DATE   VARCHAR2 (21 BYTE) NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX RPT.IDX_MSG_ID
   ON RPT.RPT_RUN_MSGS (MSG_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX RPT.IDX_PROCESS_ID
   ON RPT.RPT_RUN_MSGS (PROCESS_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE RPT.RPT_RUN_MSGS_MSG_ID_SEQ;
CREATE SEQUENCE RPT.RPT_RUN_MSGS_MSG_ID_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER RPT.RPT_RUN_MSGS_MSG_ID_TRG
   BEFORE INSERT
   ON RPT.RPT_RUN_MSGS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.MSG_ID IS NULL)
DECLARE
   V_ID   RPT.RPT_RUN_MSGS.MSG_ID%TYPE;
BEGIN
   SELECT   RPT.RPT_RUN_MSGS_MSG_ID_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.MSG_ID := V_ID;
END RPT_RUN_MSGS_MSG_ID_TRG;