/* Formatted on 9/13/2014 9:55:50 PM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION GST.GET_PSSBL_VAL (P_PSSBL_VAL_ID NUMBER)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200 BYTE);
BEGIN
   L_RESULT := '';

   SELECT   PSSBL_VALUE
     INTO   L_RESULT
     FROM   GST.GEN_STP_LOV_VALUES
    WHERE   PSSBL_VALUE_ID = P_PSSBL_VAL_ID;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/