/* Formatted on 9/13/2014 10:02:54 PM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION GST.GET_PSSBL_VAL2 (P_PSSBL_VAL_DESC    VARCHAR2,
                                               P_VALLSTID          NUMBER)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200 BYTE);
BEGIN
   L_RESULT := '';

   SELECT   PSSBL_VALUE
     INTO   L_RESULT
     FROM   GST.GEN_STP_LOV_VALUES
    WHERE   LOWER (PSSBL_VALUE_DESC) LIKE LOWER (P_PSSBL_VAL_DESC)
            AND VALUE_LIST_ID = P_VALLSTID;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/