/* Formatted on 9/13/2014 9:41:05 PM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION GST.GET_LOV_NAME (P_LOVID NUMBER)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200 BYTE);
BEGIN
   L_RESULT := '';

   SELECT   VALUE_LIST_NAME
     INTO   L_RESULT
     FROM   GST.GEN_STP_LOV_NAMES
    WHERE   VALUE_LIST_ID = P_LOVID;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/