/* Formatted on 9/13/2014 9:44:58 PM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION GST.GET_LOV_ID (P_LOVNAME VARCHAR2)
   RETURN NUMBER
AS
   L_RESULT   NUMBER;
BEGIN
   L_RESULT := -1;

   SELECT   VALUE_LIST_ID
     INTO   L_RESULT
     FROM   GST.GEN_STP_LOV_NAMES
    WHERE   LOWER (VALUE_LIST_NAME) LIKE LOWER (P_LOVNAME);

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN -1;
END;
/