/* Formatted on 10/6/2014 9:00:28 PM (QP5 v5.126.903.23003) */
-- TABLE: SCM.SCM_SALES_INVC_HDR

-- DROP TABLE SCM.SCM_SALES_INVC_HDR;

CREATE TABLE SCM.SCM_SALES_INVC_HDR (
   INVC_HDR_ID            NUMBER NOT NULL,
   INVC_DATE              VARCHAR2 (21 BYTE),
   CREATED_BY             NUMBER,
   CREATION_DATE          VARCHAR2 (50),
   LAST_UPDATE_BY         NUMBER,
   LAST_UPDATE_DATE       VARCHAR2 (50 BYTE),
   INVC_NUMBER            VARCHAR2 (100 BYTE),
   INVC_TYPE              VARCHAR2 (50 BYTE),
   COMMENTS_DESC          CLOB,
   SRC_DOC_HDR_ID         NUMBER,
   CUSTOMER_ID            NUMBER,
   CUSTOMER_SITE_ID       NUMBER,
   APPROVAL_STATUS        VARCHAR2 (100 BYTE),
   NEXT_APROVAL_ACTION    VARCHAR2 (100 BYTE),
   ORG_ID                 NUMBER,
   RECEIVABLES_ACCNT_ID   NUMBER NOT NULL,
   PAYMENT_TERMS          CLOB,
   SRC_DOC_TYPE           VARCHAR2 (200 BYTE) DEFAULT 'Inventory' NOT NULL,
   PYMNY_METHOD_ID        NUMBER DEFAULT -1 NOT NULL,
   INVC_CURR_ID           NUMBER DEFAULT -1 NOT NULL,
   EXCHNG_RATE            NUMBER DEFAULT 1 NOT NULL,
   IS_ACCNTNG_CREATED     VARCHAR2 (1 BYTE) DEFAULT '1' NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE SCM.SCM_SALES_INVC_HDR
ADD(  CONSTRAINT PK_INVC_HDR_ID PRIMARY KEY (INVC_HDR_ID ));

-- INDEX: SCM.SCM.IDX_CUSTOMER_ID

-- DROP INDEX SCM.SCM.IDX_CUSTOMER_ID;

CREATE INDEX SCM.IDX_CUSTOMER_ID
   ON SCM.SCM_SALES_INVC_HDR (CUSTOMER_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: SCM.SCM.IDX_CUSTOMER_SITE_ID

-- DROP INDEX SCM.SCM.IDX_CUSTOMER_SITE_ID;

CREATE INDEX SCM.IDX_CUSTOMER_SITE_ID
   ON SCM.SCM_SALES_INVC_HDR (CUSTOMER_SITE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: SCM.SCM.IDX_INVC_DATE

-- DROP INDEX SCM.SCM.IDX_INVC_DATE;

CREATE INDEX SCM.IDX_INVC_DATE
   ON SCM.SCM_SALES_INVC_HDR (INVC_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

   /*
-- INDEX: SCM.SCM.IDX_INVC_HDR_ID

-- DROP INDEX SCM.SCM.IDX_INVC_HDR_ID;

CREATE UNIQUE INDEX SCM.IDX_INVC_HDR_ID
   ON SCM.SCM_SALES_INVC_HDR (INVC_HDR_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;
*/

-- INDEX: SCM.SCM.IDX_INVC_NUMBER

-- DROP INDEX SCM.SCM.IDX_INVC_NUMBER;

CREATE INDEX SCM.IDX_INVC_NUMBER
   ON SCM.SCM_SALES_INVC_HDR (INVC_NUMBER)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: SCM.SCM.IDX_INVC_TYPE

-- DROP INDEX SCM.SCM.IDX_INVC_TYPE;

CREATE INDEX SCM.IDX_INVC_TYPE
   ON SCM.SCM_SALES_INVC_HDR (INVC_TYPE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: SCM.SCM.IDX_IS_ACCNTNG_CREATED

-- DROP INDEX SCM.SCM.IDX_IS_ACCNTNG_CREATED;

CREATE INDEX SCM.IDX_IS_ACCNTNG_CREATED
   ON SCM.SCM_SALES_INVC_HDR (IS_ACCNTNG_CREATED)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: SCM.SCM.IDX_S_APPROVAL_STATUS

-- DROP INDEX SCM.SCM.IDX_S_APPROVAL_STATUS;

CREATE INDEX SCM.IDX_S_APPROVAL_STATUS
   ON SCM.SCM_SALES_INVC_HDR (APPROVAL_STATUS)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: SCM.SCM.IDX_S_CREATED_BY

-- DROP INDEX SCM.SCM.IDX_S_CREATED_BY;

CREATE INDEX SCM.IDX_S_CREATED_BY
   ON SCM.SCM_SALES_INVC_HDR (CREATED_BY)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: SCM.SCM.IDX_S_LAST_UPDATE_BY

-- DROP INDEX SCM.SCM.IDX_S_LAST_UPDATE_BY;

CREATE INDEX SCM.IDX_S_LAST_UPDATE_BY
   ON SCM.SCM_SALES_INVC_HDR (LAST_UPDATE_BY)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: SCM.SCM.IDX_S_SRC_DOC_HDR_ID

-- DROP INDEX SCM.SCM.IDX_S_SRC_DOC_HDR_ID;

CREATE INDEX SCM.IDX_S_SRC_DOC_HDR_ID
   ON SCM.SCM_SALES_INVC_HDR (SRC_DOC_HDR_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE SEQUENCE SCM.SCM_ITM_SALES_ORDRS_HDR_ID_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER SCM.SCM_ITM_SALES_ORDRS_HDR_ID_TRG
   BEFORE INSERT
   ON SCM.SCM_SALES_INVC_HDR
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.INVC_HDR_ID IS NULL)
DECLARE
   V_ID   SCM.SCM_SALES_INVC_HDR.INVC_HDR_ID%TYPE;
BEGIN
   SELECT   SCM.SCM_ITM_SALES_ORDRS_HDR_ID_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.INVC_HDR_ID := V_ID;
END SCM_ITM_SALES_ORDRS_HDR_ID_TRG;