/* Formatted on 10/6/2014 8:52:05 PM (QP5 v5.126.903.23003) */
-- TABLE: SCM.SCM_PAYMENTS

-- DROP TABLE SCM.SCM_PAYMENTS;

CREATE TABLE SCM.SCM_PAYMENTS (
   PYMNT_ID           NUMBER NOT NULL,
   PYMNT_TYPE         VARCHAR2 (10 BYTE) NOT NULL,
   AMOUNT_PAID        NUMBER,
   CUSTMRS_BALANCE    NUMBER,
   PYMNT_REMARK       VARCHAR2 (300 BYTE),
   SRC_DOC_TYP        VARCHAR2 (100 BYTE),
   SRC_DOC_ID         NUMBER NOT NULL,
   CREATED_BY         NUMBER,
   CREATION_DATE      VARCHAR2 (21 BYTE),
   LAST_UPDATE_BY     NUMBER,
   LAST_UPDATE_DATE   VARCHAR2 (21 BYTE),
   DATE_RCVD          VARCHAR2 (21 BYTE) NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE SCM.SCM_PAYMENTS
ADD(  CONSTRAINT PK_PYMNT_ID PRIMARY KEY (PYMNT_ID ));

-- INDEX: SCM.SCM.IDX_DATE_RCVD

-- DROP INDEX SCM.SCM.IDX_DATE_RCVD;

CREATE INDEX SCM.IDX_DATE_RCVD
   ON SCM.SCM_PAYMENTS (DATE_RCVD)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: SCM.SCM.IDX_PY_CREATED_BY

-- DROP INDEX SCM.SCM.IDX_PY_CREATED_BY;

CREATE INDEX SCM.IDX_PY_CREATED_BY
   ON SCM.SCM_PAYMENTS (CREATED_BY)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: SCM.SCM.IDX_PY_LAST_UPDATE_BY

-- DROP INDEX SCM.SCM.IDX_PY_LAST_UPDATE_BY;

CREATE INDEX SCM.IDX_PY_LAST_UPDATE_BY
   ON SCM.SCM_PAYMENTS (LAST_UPDATE_BY)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: SCM.SCM.IDX_PY_SRC_DOC_ID

-- DROP INDEX SCM.SCM.IDX_PY_SRC_DOC_ID;

CREATE INDEX SCM.IDX_PY_SRC_DOC_ID
   ON SCM.SCM_PAYMENTS (SRC_DOC_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: SCM.SCM.IDX_PY_SRC_DOC_TYP

-- DROP INDEX SCM.SCM.IDX_PY_SRC_DOC_TYP;

CREATE INDEX SCM.IDX_PY_SRC_DOC_TYP
   ON SCM.SCM_PAYMENTS (SRC_DOC_TYP)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

   /*
-- INDEX: SCM.SCM.IDX_PYMNT_ID

-- DROP INDEX SCM.SCM.IDX_PYMNT_ID;

CREATE UNIQUE INDEX SCM.IDX_PYMNT_ID
   ON SCM.SCM_PAYMENTS (PYMNT_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;
*/

-- INDEX: SCM.SCM.IDX_PYMNT_REMARK

-- DROP INDEX SCM.SCM.IDX_PYMNT_REMARK;

CREATE INDEX SCM.IDX_PYMNT_REMARK
   ON SCM.SCM_PAYMENTS (PYMNT_REMARK)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: SCM.SCM.IDX_PYMNT_TYPE

-- DROP INDEX SCM.SCM.IDX_PYMNT_TYPE;

CREATE INDEX SCM.IDX_PYMNT_TYPE
   ON SCM.SCM_PAYMENTS (PYMNT_TYPE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE SEQUENCE SCM.SCM_PAYMENTS_PYMNT_ID_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER SCM.SCM_PAYMENTS_PYMNT_ID_TRG
   BEFORE INSERT
   ON SCM.SCM_PAYMENTS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.PYMNT_ID IS NULL)
DECLARE
   V_ID   SCM.SCM_PAYMENTS.PYMNT_ID%TYPE;
BEGIN
   SELECT   SCM.SCM_PAYMENTS_PYMNT_ID_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PYMNT_ID := V_ID;
END SCM_PAYMENTS_PYMNT_ID_TRG;