/* Formatted on 12-15-2018 12:24:52 PM (QP5 v5.126.903.23003) */
DROP TABLE SCM.SCM_ALL_OTHER_INFO_TABLE  CASCADE CONSTRAINTS PURGE;

CREATE TABLE SCM.SCM_ALL_OTHER_INFO_TABLE (
   DFLT_ROW_ID               NUMBER NOT NULL,
   TBL_OTHR_INF_COMBNTN_ID   NUMBER NOT NULL,
   ROW_PK_ID_VAL             NUMBER NOT NULL,
   OTHER_INFO_VALUE          CLOB,
   CREATED_BY                NUMBER NOT NULL,
   CREATION_DATE             VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY            NUMBER NOT NULL,
   LAST_UPDATE_DATE          VARCHAR2 (21 BYTE) NOT NULL,
   other_info_label          CLOB,
   other_info_category       VARCHAR2(200),
   CONSTRAINT pk_dflt_row_id_oi PRIMARY KEY (dflt_row_id)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX SCM.IDX_ROW_PK_ID_VAL
   ON SCM.SCM_ALL_OTHER_INFO_TABLE (ROW_PK_ID_VAL)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SCM.IDX_TBL_OTHR_INF_COMBNTN_ID
   ON SCM.SCM_ALL_OTHER_INFO_TABLE (TBL_OTHR_INF_COMBNTN_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SCM.SCM_ALL_OTHER_INFO_ROW_ID_SEQ;

CREATE SEQUENCE SCM.SCM_ALL_OTHER_INFO_ROW_ID_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER SCM.SCM_ALL_OTHER_INFO_ROW_ID_TRG
   BEFORE INSERT
   ON SCM.SCM_ALL_OTHER_INFO_TABLE
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.DFLT_ROW_ID IS NULL)
DECLARE
   V_ID   SCM.SCM_ALL_OTHER_INFO_TABLE.DFLT_ROW_ID%TYPE;
BEGIN
   SELECT   SCM.SCM_ALL_OTHER_INFO_ROW_ID_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.DFLT_ROW_ID := V_ID;
END SCM_ALL_OTHER_INFO_ROW_ID_TRG;