/* Formatted on 10/6/2014 8:50:44 PM (QP5 v5.126.903.23003) */
-- TABLE: SCM.SCM_DOC_AMNT_SMMRYS

-- DROP TABLE SCM.SCM_DOC_AMNT_SMMRYS;

CREATE TABLE SCM.SCM_DOC_AMNT_SMMRYS (
   SMMRY_ID           NUMBER NOT NULL,
   SMMRY_TYPE         VARCHAR2 (100 BYTE) NOT NULL,      -- 1INITIAL AMOUNT...
   SMMRY_NAME         VARCHAR2 (200 BYTE),
   SMMRY_AMNT         NUMBER,
   CODE_ID_BEHIND     NUMBER,
   SRC_DOC_TYPE       VARCHAR2 (100 BYTE),
   SRC_DOC_HDR_ID     NUMBER,
   CREATED_BY         NUMBER,
   CREATION_DATE      VARCHAR2 (21 BYTE),
   LAST_UPDATE_BY     NUMBER,
   LAST_UPDATE_DATE   VARCHAR2 (21 BYTE),
   AUTO_CALC          VARCHAR2 (1 BYTE) DEFAULT '1' NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE SCM.SCM_DOC_AMNT_SMMRYS
ADD(  CONSTRAINT PK_SMMRY_ID PRIMARY KEY (SMMRY_ID ));


COMMENT ON COLUMN SCM.SCM_DOC_AMNT_SMMRYS.SMMRY_TYPE IS
'1Initial Amount
2Tax
3Discount
4Extra Charge
5Grand Total';


-- INDEX: SCM.SCM.IDX_CODE_ID_BEHIND

-- DROP INDEX SCM.SCM.IDX_CODE_ID_BEHIND;

CREATE INDEX SCM.IDX_CODE_ID_BEHIND
   ON SCM.SCM_DOC_AMNT_SMMRYS (CODE_ID_BEHIND)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

   /*
-- INDEX: SCM.SCM.IDX_SMMRY_ID

-- DROP INDEX SCM.SCM.IDX_SMMRY_ID;

CREATE UNIQUE INDEX SCM.IDX_SMMRY_ID
   ON SCM.SCM_DOC_AMNT_SMMRYS (SMMRY_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;
*/

-- INDEX: SCM.SCM.IDX_SMMRY_NAME

-- DROP INDEX SCM.SCM.IDX_SMMRY_NAME;

CREATE INDEX SCM.IDX_SMMRY_NAME
   ON SCM.SCM_DOC_AMNT_SMMRYS (SMMRY_NAME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: SCM.SCM.IDX_SMMRY_TYPE

-- DROP INDEX SCM.SCM.IDX_SMMRY_TYPE;

CREATE INDEX SCM.IDX_SMMRY_TYPE
   ON SCM.SCM_DOC_AMNT_SMMRYS (SMMRY_TYPE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: SCM.SCM.IDX_SMRY_SRC_DOC_HDR_ID

-- DROP INDEX SCM.SCM.IDX_SMRY_SRC_DOC_HDR_ID;

CREATE INDEX SCM.IDX_SMRY_SRC_DOC_HDR_ID
   ON SCM.SCM_DOC_AMNT_SMMRYS (SRC_DOC_HDR_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: SCM.SCM.IDX_SMRY_SRC_DOC_TYPE

-- DROP INDEX SCM.SCM.IDX_SMRY_SRC_DOC_TYPE;

CREATE INDEX SCM.IDX_SMRY_SRC_DOC_TYPE
   ON SCM.SCM_DOC_AMNT_SMMRYS (SRC_DOC_TYPE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE SEQUENCE SCM.SCM_DOC_AMOUNT_SMMRYS_ID_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER SCM.SCM_DOC_AMOUNT_SMMRYS_ID_TRG
   BEFORE INSERT
   ON SCM.SCM_DOC_AMNT_SMMRYS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.SMMRY_ID IS NULL)
DECLARE
   V_ID   SCM.SCM_DOC_AMNT_SMMRYS.SMMRY_ID%TYPE;
BEGIN
   SELECT   SCM.SCM_DOC_AMOUNT_SMMRYS_ID_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.SMMRY_ID := V_ID;
END SCM_DOC_AMOUNT_SMMRYS_ID_TRG;