/* Formatted on 10/6/2014 9:01:44 PM (QP5 v5.126.903.23003) */
-- TABLE: SCM.SCM_TAX_CODES

-- DROP TABLE SCM.SCM_TAX_CODES;

CREATE TABLE SCM.SCM_TAX_CODES (
   CODE_ID                   NUMBER NOT NULL,
   CODE_NAME                 VARCHAR2 (50 BYTE),
   CODE_DESC                 VARCHAR2 (200 BYTE),
   CREATED_BY                NUMBER,
   CREATION_DATE             VARCHAR2 (50 BYTE),
   LAST_UPDATE_BY            NUMBER,
   LAST_UPDATE_DATE          VARCHAR2 (50 BYTE),
   ITM_TYPE                  VARCHAR2 (20 BYTE),
   IS_ENABLED                VARCHAR2 (1 BYTE),
   TAXES_PAYABLES_ACCNT_ID   NUMBER,
   DSCOUNT_EXPNS_ACCNT_ID    NUMBER,
   CHRGE_REVNU_ACCNT_ID      NUMBER,
   ORG_ID                    NUMBER,
   SQL_FORMULAR              CLOB,
   IS_RECOVRBL_TAX           VARCHAR2 (1 BYTE) DEFAULT 0 NOT NULL,
   TAX_EXPENSE_ACCNT_ID      NUMBER DEFAULT -1 NOT NULL,
   PRCHS_DSCNT_ACCNT_ID      NUMBER DEFAULT -1 NOT NULL,
   CHRGE_EXPNS_ACCNT_ID      NUMBER DEFAULT -1 NOT NULL,
   IS_WITHLDNG_TAX           VARCHAR2 (1 BYTE) DEFAULT '0' NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE SCM.SCM_TAX_CODES
ADD(  CONSTRAINT PK_CODE_ID PRIMARY KEY (CODE_ID ));

-- INDEX: SCM.SCM.IDX_CODE_DESC

-- DROP INDEX SCM.SCM.IDX_CODE_DESC;

CREATE INDEX SCM.IDX_CODE_DESC
   ON SCM.SCM_TAX_CODES (CODE_DESC)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

   /*
-- INDEX: SCM.SCM.IDX_CODE_ID

-- DROP INDEX SCM.SCM.IDX_CODE_ID;

CREATE UNIQUE INDEX SCM.IDX_CODE_ID
   ON SCM.SCM_TAX_CODES (CODE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;
*/

-- INDEX: SCM.SCM.IDX_CODE_NAME

-- DROP INDEX SCM.SCM.IDX_CODE_NAME;

CREATE INDEX SCM.IDX_CODE_NAME
   ON SCM.SCM_TAX_CODES (CODE_NAME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE SEQUENCE SCM.SCM_ITM_TAX_CODES_CODE_ID_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER SCM.SCM_ITM_TAX_CODES_CODE_ID_TRG
   BEFORE INSERT
   ON SCM.SCM_TAX_CODES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.CODE_ID IS NULL)
DECLARE
   V_ID   SCM.SCM_TAX_CODES.CODE_ID%TYPE;
BEGIN
   SELECT   SCM.SCM_ITM_TAX_CODES_CODE_ID_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.CODE_ID := V_ID;
END SCM_ITM_TAX_CODES_CODE_ID_TRG;