/* Formatted on 10/6/2014 8:52:58 PM (QP5 v5.126.903.23003) */
-- TABLE: SCM.SCM_PRCHS_DOCS_DET

-- DROP TABLE SCM.SCM_PRCHS_DOCS_DET;

CREATE TABLE SCM.SCM_PRCHS_DOCS_DET (
   PRCHS_DOC_LINE_ID   NUMBER NOT NULL,
   PRCHS_DOC_HDR_ID    NUMBER,
   ITM_ID              NUMBER,
   QUANTITY            NUMBER,
   UNIT_PRICE          NUMBER,
   CREATED_BY          NUMBER,
   CREATION_DATE       VARCHAR2 (21 BYTE),
   LAST_UPDATE_BY      NUMBER,
   LAST_UPDATE_DATE    VARCHAR2 (21 BYTE),
   STORE_ID            NUMBER,
   CRNCY_ID            NUMBER,
   QTY_RCVD            NUMBER DEFAULT 0 NOT NULL,
   RQSTD_QTY_ORDRD     NUMBER DEFAULT 0 NOT NULL,
   SRC_LINE_ID         NUMBER DEFAULT -1 NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE SCM.SCM_PRCHS_DOCS_DET
ADD(  CONSTRAINT PK_PRCHS_DOC_LINE_ID PRIMARY KEY (PRCHS_DOC_LINE_ID ));

-- INDEX: SCM.SCM.IDX_D_PRCHS_DOC_HDR_ID

-- DROP INDEX SCM.SCM.IDX_D_PRCHS_DOC_HDR_ID;

CREATE INDEX SCM.IDX_D_PRCHS_DOC_HDR_ID
   ON SCM.SCM_PRCHS_DOCS_DET (PRCHS_DOC_HDR_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: SCM.SCM.IDX_PRCH_ITM_ID

-- DROP INDEX SCM.SCM.IDX_PRCH_ITM_ID;

CREATE INDEX SCM.IDX_PRCH_ITM_ID
   ON SCM.SCM_PRCHS_DOCS_DET (ITM_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: SCM.SCM.IDX_PRCH_STORE_ID

-- DROP INDEX SCM.SCM.IDX_PRCH_STORE_ID;

CREATE INDEX SCM.IDX_PRCH_STORE_ID
   ON SCM.SCM_PRCHS_DOCS_DET (STORE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

   /*
-- INDEX: SCM.SCM.IDX_PRCHS_DOC_LINE_ID

-- DROP INDEX SCM.SCM.IDX_PRCHS_DOC_LINE_ID;

CREATE UNIQUE INDEX SCM.IDX_PRCHS_DOC_LINE_ID
   ON SCM.SCM_PRCHS_DOCS_DET (PRCHS_DOC_LINE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;
*/

-- INDEX: SCM.SCM.IDX_SRC_LINE_ID

-- DROP INDEX SCM.SCM.IDX_SRC_LINE_ID;

CREATE INDEX SCM.IDX_SRC_LINE_ID
   ON SCM.SCM_PRCHS_DOCS_DET (SRC_LINE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE SCM.SCM_ITM_P_ORDS_DET_LINE_ID_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER SCM.SCM_ITM_P_ORDS_DET_LINE_ID_TRG
   BEFORE INSERT
   ON SCM.SCM_PRCHS_DOCS_DET
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.PRCHS_DOC_LINE_ID IS NULL)
DECLARE
   V_ID   SCM.SCM_PRCHS_DOCS_DET.PRCHS_DOC_LINE_ID%TYPE;
BEGIN
   SELECT   SCM.SCM_ITM_P_ORDS_DET_LINE_ID_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PRCHS_DOC_LINE_ID := V_ID;
END SCM_ITM_P_ORDS_DET_LINE_ID_TRG;