/* Formatted on 12-18-2018 5:16:22 PM (QP5 v5.126.903.23003) */
DROP TABLE EPAY.EPAY_PSB3_TRNS CASCADE CONSTRAINTS PURGE;

CREATE TABLE EPAY.EPAY_PSB3_TRNS (
   TRANSACTIONS_ID     NUMBER NOT NULL,
   INDICATOR_ID        NUMBER,
   PSB_HDR_ID          NUMBER,
   GAR_VOLUME          INTEGER,
   GAR_VALUE           NUMBER,
   ER_VOLUME           INTEGER,
   ER_VALUE            NUMBER,
   CR_VOLUME           INTEGER,
   CR_VALUE            NUMBER,
   WR_VOLUME           INTEGER,
   WR_VALUE            NUMBER,
   VR_VOLUME           INTEGER,
   VR_VALUE            NUMBER,
   AR_VOLUME           INTEGER,
   AR_VALUE            NUMBER,
   BAR_VOLUME          INTEGER,
   BAR_VALUE           NUMBER,
   NR_VOLUME           INTEGER,
   NR_VALUE            NUMBER,
   UER_VOLUME          INTEGER,
   UER_VALUE           NUMBER,
   UWR_VOLUME          INTEGER,
   UWR_VALUE           NUMBER,
   CREATED_BY          NUMBER,
   CREATION_DATE       VARCHAR2 (21),
   LAST_UPDATE_BY      NUMBER,
   LAST_UPDATE_DATE    VARCHAR2 (21),
   INDICATOR_DETAILS   CLOB,
   CONSTRAINT PK_EMONEY_TRNS_INDICATOR_ID PRIMARY KEY (TRANSACTIONS_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

DROP SEQUENCE EPAY.EPAY_PSB3_TRNS_SEQ;

CREATE SEQUENCE EPAY.EPAY_PSB3_TRNS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER EPAY.EPAY_PSB3_TRNS_TRG
   BEFORE INSERT
   ON EPAY.EPAY_PSB3_TRNS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.TRANSACTIONS_ID IS NULL)
DECLARE
   V_ID   EPAY.EPAY_PSB3_TRNS.TRANSACTIONS_ID%TYPE;
BEGIN
   SELECT   EPAY.EPAY_PSB3_TRNS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.TRANSACTIONS_ID := V_ID;
END EPAY_PSB3_TRNS_TRG;