/* Formatted on 12-19-2018 8:44:05 AM (QP5 v5.126.903.23003) */
DROP TABLE EPAY.EPAY_PSB6_TRNS CASCADE CONSTRAINTS PURGE;

CREATE TABLE EPAY.EPAY_PSB6_TRNS (
   INTERRUPTION_ID              NUMBER NOT NULL,
   INTERRUPTION_NATURE_ID       INTEGER,     -- NATURE OF SERVICE INTERRUPTION
   PSB_HDR_ID                   INTEGER,
   START_DATE                   VARCHAR2 (21),
   START_TIME                   VARCHAR2 (10),
   END_DATE                     VARCHAR2 (21),
   END_TIME                     VARCHAR2 (10),
   CORRECTIVE_ACTION_TAKEN_ID   NUMBER,
   CREATED_BY                   NUMBER,
   CREATION_DATE                VARCHAR2 (21),
   LAST_UPDATE_BY               NUMBER,
   LAST_UPDATE_DATE             VARCHAR2 (21),
   CONSTRAINT PK_PSB6_INTERRUPTION_ID PRIMARY KEY (INTERRUPTION_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN EPAY.EPAY_PSB6_TRNS.INTERRUPTION_NATURE_ID IS
'Nature of Service Interruption';

DROP SEQUENCE EPAY.EPAY_PSB6_TRNS_SEQ;

CREATE SEQUENCE EPAY.EPAY_PSB6_TRNS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER EPAY.EPAY_PSB6_TRNS_TRG
   BEFORE INSERT
   ON EPAY.EPAY_PSB6_TRNS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.INTERRUPTION_ID IS NULL)
DECLARE
   V_ID   EPAY.EPAY_PSB6_TRNS.INTERRUPTION_ID%TYPE;
BEGIN
   SELECT   EPAY.EPAY_PSB6_TRNS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.INTERRUPTION_ID := V_ID;
END EPAY_PSB6_TRNS_TRG;