/* Formatted on 12-19-2018 8:43:26 AM (QP5 v5.126.903.23003) */
DROP TABLE EPAY.EPAY_PSB5_TRNS CASCADE CONSTRAINTS PURGE;

CREATE TABLE EPAY.EPAY_PSB5_TRNS (
   COMPLAINT_ID                NUMBER NOT NULL,
   COMPLAINT_TYPE_ID           NUMBER,
   FEMALE_COMPLAINANTS_NO      INTEGER,
   COMPLAINTS_RCVD_RPTMNT      INTEGER,   -- COMPAINT RECEIVED REPORTING MONTH
   COMPLAINTS_RSLVD_RPTMNT     INTEGER, -- COMPLAINTS RESOLVED REPORTING MONTH
   UNRESOLVED_COMPLAINTS_EOM   INTEGER,  -- UNRESOLVED COMPLAINTS END OF MONTH
   PSB_HDR_ID                  NUMBER,
   CREATED_BY                  NUMBER,
   CREATION_DATE               VARCHAR2 (21),
   LAST_UPDATE_BY              NUMBER,
   LAST_UPDATE_DATE            VARCHAR2 (21),
   CONSTRAINT PK_CMPLNT_ID PRIMARY KEY (COMPLAINT_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN EPAY.EPAY_PSB5_TRNS.COMPLAINTS_RCVD_RPTMNT IS
'compaint received reporting month';

COMMENT ON COLUMN EPAY.EPAY_PSB5_TRNS.COMPLAINTS_RSLVD_RPTMNT IS
'complaints resolved reporting month';

COMMENT ON COLUMN EPAY.EPAY_PSB5_TRNS.UNRESOLVED_COMPLAINTS_EOM IS
'unresolved complaints end of month';

DROP SEQUENCE EPAY.EPAY_PSB5_TRNS_SEQ;

CREATE SEQUENCE EPAY.EPAY_PSB5_TRNS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER EPAY.EPAY_PSB5_TRNS_TRG
   BEFORE INSERT
   ON EPAY.EPAY_PSB5_TRNS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.COMPLAINT_ID IS NULL)
DECLARE
   V_ID   EPAY.EPAY_PSB5_TRNS.COMPLAINT_ID%TYPE;
BEGIN
   SELECT   EPAY.EPAY_PSB5_TRNS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.COMPLAINT_ID := V_ID;
END EPAY_PSB5_TRNS_TRG;