/* Formatted on 10/6/2014 8:53:38 PM (QP5 v5.126.903.23003) */
-- TABLE: SCM.SCM_PRCHS_DOCS_HDR

-- DROP TABLE SCM.SCM_PRCHS_DOCS_HDR;

CREATE TABLE SCM.SCM_PRCHS_DOCS_HDR (
   PRCHS_DOC_DATE        VARCHAR2 (12 BYTE),
   NEED_BY_DATE          VARCHAR2 (12 BYTE),
   SUPPLIER_ID           NUMBER,
   SUPPLIER_SITE_ID      NUMBER,
   COMMENTS_DESC         CLOB,
   APPROVAL_STATUS       VARCHAR2 (25 BYTE),
   CREATED_BY            NUMBER,
   CREATION_DATE         VARCHAR2 (21 BYTE),
   LAST_UPDATE_BY        NUMBER,
   LAST_UPDATE_DATE      VARCHAR2 (21 BYTE),
   NEXT_APROVAL_ACTION   VARCHAR2 (100 BYTE),
   PURCHASE_DOC_NUM      VARCHAR2 (100 BYTE) NOT NULL,
   PURCHASE_DOC_TYPE     VARCHAR2 (50 BYTE),
   REQUISITION_ID        NUMBER,
   ORG_ID                NUMBER,
   PRCHS_DOC_HDR_ID      NUMBER NOT NULL,
   PO_REC_STATUS         VARCHAR2 (20 BYTE)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE SCM.SCM_PRCHS_DOCS_HDR
ADD(  CONSTRAINT PK_PRCHS_DOC_HDR_ID PRIMARY KEY (PRCHS_DOC_HDR_ID ));

-- INDEX: SCM.SCM.IDX_NEED_BY_DATE

-- DROP INDEX SCM.SCM.IDX_NEED_BY_DATE;

CREATE INDEX SCM.IDX_NEED_BY_DATE
   ON SCM.SCM_PRCHS_DOCS_HDR (NEED_BY_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: SCM.SCM.IDX_P_APPROVAL_STATUS

-- DROP INDEX SCM.SCM.IDX_P_APPROVAL_STATUS;

CREATE INDEX SCM.IDX_P_APPROVAL_STATUS
   ON SCM.SCM_PRCHS_DOCS_HDR (APPROVAL_STATUS)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: SCM.SCM.IDX_P_SUPPLIER_SITE_ID

-- DROP INDEX SCM.SCM.IDX_P_SUPPLIER_SITE_ID;

CREATE INDEX SCM.IDX_P_SUPPLIER_SITE_ID
   ON SCM.SCM_PRCHS_DOCS_HDR (SUPPLIER_SITE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: SCM.SCM.IDX_PRCH_CREATED_BY

-- DROP INDEX SCM.SCM.IDX_PRCH_CREATED_BY;

CREATE INDEX SCM.IDX_PRCH_CREATED_BY
   ON SCM.SCM_PRCHS_DOCS_HDR (CREATED_BY)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: SCM.SCM.IDX_PRCH_LAST_UPDATE_BY

-- DROP INDEX SCM.SCM.IDX_PRCH_LAST_UPDATE_BY;

CREATE INDEX SCM.IDX_PRCH_LAST_UPDATE_BY
   ON SCM.SCM_PRCHS_DOCS_HDR (LAST_UPDATE_BY)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: SCM.SCM.IDX_PRCH_SUPPLIER_ID

-- DROP INDEX SCM.SCM.IDX_PRCH_SUPPLIER_ID;

CREATE INDEX SCM.IDX_PRCH_SUPPLIER_ID
   ON SCM.SCM_PRCHS_DOCS_HDR (SUPPLIER_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: SCM.SCM.IDX_PRCHS_DOC_DATE

-- DROP INDEX SCM.SCM.IDX_PRCHS_DOC_DATE;

CREATE INDEX SCM.IDX_PRCHS_DOC_DATE
   ON SCM.SCM_PRCHS_DOCS_HDR (PRCHS_DOC_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

/*
-- INDEX: SCM.SCM.IDX_PRCHS_DOC_HDR_ID

-- DROP INDEX SCM.SCM.IDX_PRCHS_DOC_HDR_ID;

CREATE UNIQUE INDEX SCM.IDX_PRCHS_DOC_HDR_ID
   ON SCM.SCM_PRCHS_DOCS_HDR (PRCHS_DOC_HDR_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;
*/
-- INDEX: SCM.SCM.IDX_PURCHASE_DOC_NUM

-- DROP INDEX SCM.SCM.IDX_PURCHASE_DOC_NUM;

CREATE INDEX SCM.IDX_PURCHASE_DOC_NUM
   ON SCM.SCM_PRCHS_DOCS_HDR (PURCHASE_DOC_NUM)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: SCM.SCM.IDX_PURCHASE_DOC_TYPE

-- DROP INDEX SCM.SCM.IDX_PURCHASE_DOC_TYPE;

CREATE INDEX SCM.IDX_PURCHASE_DOC_TYPE
   ON SCM.SCM_PRCHS_DOCS_HDR (PURCHASE_DOC_TYPE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

-- INDEX: SCM.SCM.IDX_REQUISITION_ID

-- DROP INDEX SCM.SCM.IDX_REQUISITION_ID;

CREATE INDEX SCM.IDX_REQUISITION_ID
   ON SCM.SCM_PRCHS_DOCS_HDR (REQUISITION_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE SEQUENCE SCM.SCM_PRCHS_DOCS_HDR_ID_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER SCM.SCM_PRCHS_DOCS_HDR_ID_TRG
   BEFORE INSERT
   ON SCM.SCM_PRCHS_DOCS_HDR
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.PRCHS_DOC_HDR_ID IS NULL)
DECLARE
   V_ID   SCM.SCM_PRCHS_DOCS_HDR.PRCHS_DOC_HDR_ID%TYPE;
BEGIN
   SELECT   SCM.SCM_PRCHS_DOCS_HDR_ID_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PRCHS_DOC_HDR_ID := V_ID;
END SCM_PRCHS_DOCS_HDR_ID_TRG;