/* Formatted on 12-18-2018 10:48:36 AM (QP5 v5.126.903.23003) */
DROP TABLE EPAY.EPAY_PERIODS CASCADE CONSTRAINTS PURGE;

CREATE TABLE EPAY.EPAY_PERIODS (
   PERIOD_ID          NUMBER NOT NULL,
   PERIOD             VARCHAR2 (8),
   PERIOD_DESC        VARCHAR2 (50),
   DUE_DATE           VARCHAR2 (21),
   STATUS             VARCHAR2 (6),
   CREATED_BY         NUMBER,
   CREATION_DATE      VARCHAR2 (21),
   LAST_UPDATE_BY     NUMBER,
   LAST_UPDATE_DATE   VARCHAR2 (21),
   CONSTRAINT PK_PERIOD_ID PRIMARY KEY (PERIOD_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

DROP SEQUENCE EPAY.EPAY_PERIODS_SEQ;

CREATE SEQUENCE EPAY.EPAY_PERIODS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER EPAY.EPAY_PERIODS_TRG
   BEFORE INSERT
   ON EPAY.EPAY_PERIODS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.PERIOD_ID IS NULL)
DECLARE
   V_ID   EPAY.EPAY_PERIODS.PERIOD_ID%TYPE;
BEGIN
   SELECT   EPAY.EPAY_PERIODS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PERIOD_ID := V_ID;
END EPAY_PERIODS_TRG;