/* Formatted on 12-18-2018 9:35:58 PM (QP5 v5.126.903.23003) */
DROP TABLE EPAY.VALIDATION_DETAILS CASCADE CONSTRAINTS PURGE;

CREATE TABLE EPAY.VALIDATION_DETAILS (
   VLDTN_DET_ID       NUMBER NOT NULL,
   VLDTN_HDR_ID       NUMBER,
   CATEGORY_X_ID      NUMBER,
   ACTION_X           VARCHAR2 (50),
   VLDTN_OPERATOR     VARCHAR2 (2),
   CATEGORY_Y_ID      NUMBER,
   ACTION_Y           VARCHAR2 (50),
   ERROR_MSG          CLOB,
   CREATED_BY         NUMBER,
   CREATION_DATE      VARCHAR2 (21),
   LAST_UPDATE_BY     NUMBER,
   LAST_UPDATE_DATE   VARCHAR2 (21),
   LINE_STATUS        VARCHAR2 (10),
   PSB_X_ID           NUMBER,
   PSB_Y_ID           NUMBER,
   CONSTRAINT PK_VLDTN_DET_ID PRIMARY KEY (VLDTN_DET_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

DROP SEQUENCE EPAY.VALIDATION_DETAILS_SEQ;

CREATE SEQUENCE EPAY.VALIDATION_DETAILS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER EPAY.VALIDATION_DETAILS_TRG
   BEFORE INSERT
   ON EPAY.VALIDATION_DETAILS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.VLDTN_DET_ID IS NULL)
DECLARE
   V_ID   EPAY.VALIDATION_DETAILS.VLDTN_DET_ID%TYPE;
BEGIN
   SELECT   EPAY.VALIDATION_DETAILS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.VLDTN_DET_ID := V_ID;
END VALIDATION_DETAILS_TRG;