/* Formatted on 12-18-2018 1:17:26 PM (QP5 v5.126.903.23003) */
DROP TABLE EPAY.EPAY_PSB10_INTERNET_TRNS_FEES CASCADE CONSTRAINTS PURGE;

CREATE TABLE EPAY.EPAY_PSB10_INTERNET_TRNS_FEES (
   INTERNET_FEE_ID    NUMBER NOT NULL,
   PSB_HDR_ID         NUMBER,
   PRODUCT_ID         NUMBER,
   FEE_TO_CUSTOMER    NUMBER,
   CREATED_BY         NUMBER,
   CREATION_DATE      VARCHAR2 (21),
   LAST_UPDATE_BY     NUMBER,
   LAST_UPDATE_DATE   VARCHAR2 (21),
   PRODUCT_NAME       VARCHAR2 (50),
   CONSTRAINT PK_INTERNET_FEE_ID PRIMARY KEY (INTERNET_FEE_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

DROP SEQUENCE EPAY.EPAY_PSB10_INTERNET_TRNS_FEES_SEQ;

CREATE SEQUENCE EPAY.EPAY_PSB10_INTERNET_TRNS_FEES_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER EPAY.EPAY_PSB10_INTERNET_TRNS_FEES_TRG
   BEFORE INSERT
   ON EPAY.EPAY_PSB10_INTERNET_TRNS_FEES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.INTERNET_FEE_ID IS NULL)
DECLARE
   V_ID   EPAY.EPAY_PSB10_INTERNET_TRNS_FEES.INTERNET_FEE_ID%TYPE;
BEGIN
   SELECT   EPAY.EPAY_PSB10_INTERNET_TRNS_FEES_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.INTERNET_FEE_ID := V_ID;
END EPAY_PSB10_INTERNET_TRNS_FEES_TRG;