/* Formatted on 12-18-2018 3:37:48 PM (QP5 v5.126.903.23003) */
DROP TABLE EPAY.EPAY_PSB1_PREPAID_CARD_TYPES CASCADE CONSTRAINTS PURGE;

CREATE TABLE EPAY.EPAY_PSB1_PREPAID_CARD_TYPES (
   CARDTYPE_ID        NUMBER NOT NULL,
   PSB_HDR_ID         NUMBER,
   CREATED_BY         NUMBER,
   CREATION_DATE      VARCHAR (21),
   LAST_UPDATE_BY     NUMBER,
   LAST_UPDATE_DATE   VARCHAR(21),
   INDICATOR_ID       NUMBER,
   SINGLE_CURRENCY    VARCHAR (1),
   MULTI_CURRENCY     VARCHAR (1),
   CONSTRAINT PK_CARDTYPE_ID PRIMARY KEY (CARDTYPE_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

DROP SEQUENCE EPAY.EPAY_PSB1_PREPAID_CARD_TYPES_SEQ;

CREATE SEQUENCE EPAY.EPAY_PSB1_PREPAID_CARD_TYPES_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER EPAY.EPAY_PSB1_PREPAID_CARD_TYPES_TRG
   BEFORE INSERT
   ON EPAY.EPAY_PSB1_PREPAID_CARD_TYPES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.CARDTYPE_ID IS NULL)
DECLARE
   V_ID   EPAY.EPAY_PSB1_PREPAID_CARD_TYPES.CARDTYPE_ID%TYPE;
BEGIN
   SELECT   EPAY.EPAY_PSB1_PREPAID_CARD_TYPES_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.CARDTYPE_ID := V_ID;
END EPAY_PSB1_PREPAID_CARD_TYPES_TRG;