/* Formatted on 12-19-2018 8:28:47 AM (QP5 v5.126.903.23003) */
DROP TABLE EPAY.EPAY_PSB1_MONEY_TRANSFER_COMPANIES CASCADE CONSTRAINTS PURGE;

CREATE TABLE EPAY.EPAY_PSB1_MONEY_TRANSFER_COMPANIES (
   CMPNY_ROW_ID       NUMBER NOT NULL,
   PSB_HDR_ID         NUMBER,
   CMPNY_ID           NUMBER,                       -- MONEY TRANSFER COMPANIE
   CATEGORY_ID        NUMBER,
   CREATED_BY         NUMBER,
   CREATION_DATE      VARCHAR2 (21),
   LAST_UPDATE_BY     NUMBER,
   LAST_UPDATE_DATE   VARCHAR2 (21),
   VOLUME             NUMBER,
   CONSTRAINT PK_CMPNY_ROW_ID PRIMARY KEY (CMPNY_ROW_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN EPAY.EPAY_PSB1_MONEY_TRANSFER_COMPANIES.CMPNY_ID IS
'Money Transfer Companie';

DROP SEQUENCE EPAY.EPAY_PSB1_MONEY_TRANSFER_COMPANIES_SEQ;

CREATE SEQUENCE EPAY.EPAY_PSB1_MONEY_TRANSFER_COMPANIES_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER EPAY.EPAY_PSB1_MONEY_TRANSFER_COMPANIES_TRG
   BEFORE INSERT
   ON EPAY.EPAY_PSB1_MONEY_TRANSFER_COMPANIES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.CMPNY_ROW_ID IS NULL)
DECLARE
   V_ID   EPAY.EPAY_PSB1_MONEY_TRANSFER_COMPANIES.CMPNY_ROW_ID%TYPE;
BEGIN
   SELECT   EPAY.EPAY_PSB1_MONEY_TRANSFER_COMPANIES_SEQ.NEXTVAL
     INTO   V_ID
     FROM   DUAL;

   :NEW.CMPNY_ROW_ID := V_ID;
END EPAY_PSB1_MONEY_TRANSFER_COMPANIES_TRG;