/* Formatted on 12-18-2018 9:45:31 PM (QP5 v5.126.903.23003) */
DROP TABLE EPAY.EPAY_CATEGORIES CASCADE CONSTRAINTS PURGE;

CREATE TABLE EPAY.EPAY_CATEGORIES (
   CATEGORY_ID        NUMBER NOT NULL,
   CATEGORY           CLOB,
   CREATED_BY         NUMBER,
   CREATION_DATE      VARCHAR2 (21),
   LAST_UPDATE_BY     NUMBER,
   LAST_UPDATE_DATE   VARCHAR2 (21),
   PSB_TYPE_ID        INTEGER,
   SECTION_ID         INTEGER,                         -- VOLUME ONLY  -- 1...
   CATEGORY_DESC      VARCHAR2 (500),
   CONSTRAINT PK_CATEGORY_ID PRIMARY KEY (CATEGORY_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

set define off;

COMMENT ON COLUMN EPAY.EPAY_CATEGORIES.SECTION_ID IS
'Volume Only  -- 1
Value Only -- 2
Volume & Value -- 3';

DROP SEQUENCE EPAY.EPAY_CATEGORIES_SEQ;

CREATE SEQUENCE EPAY.EPAY_CATEGORIES_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER EPAY.EPAY_CATEGORIES_TRG
   BEFORE INSERT
   ON EPAY.EPAY_CATEGORIES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.CATEGORY_ID IS NULL)
DECLARE
   V_ID   EPAY.EPAY_CATEGORIES.CATEGORY_ID%TYPE;
BEGIN
   SELECT   EPAY.EPAY_CATEGORIES_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.CATEGORY_ID := V_ID;
END EPAY_CATEGORIES_TRG;