/* Formatted on 12-18-2018 9:45:25 PM (QP5 v5.126.903.23003) */
DROP TABLE EPAY.EPAY_INDICATOR CASCADE CONSTRAINTS PURGE;

CREATE TABLE EPAY.EPAY_INDICATOR (
   INDICATOR_ID       NUMBER NOT NULL,
   NAME               VARCHAR2 (100),
   DESCRIPTION        CLOB,
   CREATED_BY         NUMBER,
   CREATION_DATE      VARCHAR2 (21),
   LAST_UPDATE_BY     NUMBER,
   LAST_UPDATE_DATE   VARCHAR2 (21),
   CATEGORY_ID        NUMBER,
   VOL_RQRD           VARCHAR2 (1),
   VAL_RQRD           VARCHAR2 (1),
   ALLOW_DATA         INTEGER,                   -- 1 = ONLY VOLUME ALLOWED...
   CONSTRAINT PK_IND_ID PRIMARY KEY (INDICATOR_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE epay.epay_indicator IS 'Category Indicators';

COMMENT ON COLUMN epay.epay_indicator.allow_data IS
'
1 = only Volume allowed
2 = only Value allowed
3 = Both allowed';

DROP SEQUENCE EPAY.EPAY_INDICATOR_SEQ;

CREATE SEQUENCE EPAY.EPAY_INDICATOR_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER EPAY.EPAY_INDICATOR_TRG
   BEFORE INSERT
   ON EPAY.EPAY_INDICATOR
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.INDICATOR_ID IS NULL)
DECLARE
   V_ID   EPAY.EPAY_INDICATOR.INDICATOR_ID%TYPE;
BEGIN
   SELECT   EPAY.EPAY_INDICATOR_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.INDICATOR_ID := V_ID;
END EPAY_INDICATOR_TRG;