/* Formatted on 12-19-2018 8:32:09 AM (QP5 v5.126.903.23003) */
DROP TABLE EPAY.EPAY_PSB4_FRAUD_PRS_INST CASCADE CONSTRAINTS PURGE;

CREATE TABLE EPAY.EPAY_PSB4_FRAUD_PRS_INST (
   PRS_INST_ID            NUMBER NOT NULL,
   PRS_INST_TYPE_ID       NUMBER,
   PRS_INST_NAME          CLOB,
   PERSONAL_ID_TYPE_ID    NUMBER,
   PERSONAL_ID_NUMBER     VARCHAR2 (100),
   APPRHNSN_CHRG_STATUS   VARCHAR2 (15),
   CREATED_BY             NUMBER,
   CREATION_DATE          VARCHAR2 (21),
   LAST_UPDATE_BY         NUMBER,
   LAST_UPDATE_DATE       VARCHAR2 (21),
   INCIDENT_ID            NUMBER, -- FOREIGN KEY TO PSB4 INCIDENT_ID PRIMARY KEY
   OTHER_ID_TYPE          VARCHAR2 (50),
   CONSTRAINT PK_PRS_INST_ID PRIMARY KEY (PRS_INST_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN EPAY.EPAY_PSB4_FRAUD_PRS_INST.INCIDENT_ID IS
'foreign key to PSB4 incident_id primary key';

DROP SEQUENCE EPAY.EPAY_PSB4_FRAUD_PRS_INST_SEQ;

CREATE SEQUENCE EPAY.EPAY_PSB4_FRAUD_PRS_INST_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER EPAY.EPAY_PSB4_FRAUD_PRS_INST_TRG
   BEFORE INSERT
   ON EPAY.EPAY_PSB4_FRAUD_PRS_INST
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.PRS_INST_ID IS NULL)
DECLARE
   V_ID   EPAY.EPAY_PSB4_FRAUD_PRS_INST.PRS_INST_ID%TYPE;
BEGIN
   SELECT   EPAY.EPAY_PSB4_FRAUD_PRS_INST_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PRS_INST_ID := V_ID;
END EPAY_PSB4_FRAUD_PRS_INST_TRG;