/* Formatted on 12-18-2018 6:07:26 PM (QP5 v5.126.903.23003) */
DROP TABLE EPAY.EPAY_PSB8_MINTIER_TRNS CASCADE CONSTRAINTS PURGE;

CREATE TABLE EPAY.EPAY_PSB8_MINTIER_TRNS (
   MINTIER_ID            NUMERIC NOT NULL,
   CUSTOMER_NAME         CLOB,
   MOBILE_NUMBER         VARCHAR2 (50),
   OUTSTANDING_BALANCE   NUMERIC,
   PSB_HDR_ID            NUMERIC,
   CREATED_BY            NUMERIC,
   CREATION_DATE         VARCHAR2 (21),
   LAST_UPDATE_BY        NUMERIC,
   LAST_UPDATE_DATE      VARCHAR2 (21),
   CONSTRAINT PK_ROW_ID_MINTIER PRIMARY KEY (MINTIER_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

DROP SEQUENCE EPAY.EPAY_PSB8_MINTIER_TRNS_SEQ;

CREATE SEQUENCE EPAY.EPAY_PSB8_MINTIER_TRNS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER EPAY.EPAY_PSB8_MINTIER_TRNS_TRG
   BEFORE INSERT
   ON EPAY.EPAY_PSB8_MINTIER_TRNS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.MINTIER_ID IS NULL)
DECLARE
   V_ID   EPAY.EPAY_PSB8_MINTIER_TRNS.MINTIER_ID%TYPE;
BEGIN
   SELECT   EPAY.EPAY_PSB8_MINTIER_TRNS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.MINTIER_ID := V_ID;
END EPAY_PSB8_MINTIER_TRNS_TRG;