/* Formatted on 12-19-2018 8:29:56 AM (QP5 v5.126.903.23003) */
DROP TABLE EPAY.EPAY_PSB1_TRNS CASCADE CONSTRAINTS PURGE;

CREATE TABLE EPAY.EPAY_PSB1_TRNS (
   TRANSACTIONS_ID    NUMBER NOT NULL,
   CATIND_ID          NUMBER,
   PSB_HDR_ID         NUMBER,
   VALUE              NUMBER,
   VOLUME             NUMBER,
   CREATED_BY         NUMBER,
   CREATION_DATE      VARCHAR2 (21),
   LAST_UPDATE_BY     NUMBER,
   LAST_UPDATE_DATE   VARCHAR2 (21),
   CONSTRAINT PK_TRANSACTIONS_ID PRIMARY KEY (TRANSACTIONS_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN EPAY.EPAY_PSB1_TRNS.CATIND_ID IS 'OLD: indicator_id';

DROP SEQUENCE EPAY.EPAY_PSB1_TRNS_SEQ;

CREATE SEQUENCE EPAY.EPAY_PSB1_TRNS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER EPAY.EPAY_PSB1_TRNS_TRG
   BEFORE INSERT
   ON EPAY.EPAY_PSB1_TRNS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.TRANSACTIONS_ID IS NULL)
DECLARE
   V_ID   EPAY.EPAY_PSB1_TRNS.TRANSACTIONS_ID%TYPE;
BEGIN
   SELECT   EPAY.EPAY_PSB1_TRNS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.TRANSACTIONS_ID := V_ID;
END EPAY_PSB1_TRNS_TRG;