/* Formatted on 12-18-2018 9:46:03 PM (QP5 v5.126.903.23003) */
DROP TABLE EPAY.EPAY_PSB10_CARD_FEES_DET CASCADE CONSTRAINTS PURGE;

CREATE TABLE EPAY.EPAY_PSB10_CARD_FEES_DET (
   CARD_FEE_DET_ID          NUMBER NOT NULL,
   CARD_FEE_HDR_ID          NUMBER,
   AMOUNT_LOW               NUMBER,                  -- TRANSACTION AMOUNT LOW
   AMOUNT_HIGH              NUMBER,
   FEE_CHARGED_FLAT_RATE    NUMBER,
   REMARKS                  CLOB,
   CREATED_BY               NUMBER,
   CREATION_DATE            VARCHAR2 (21),
   LAST_UPDATE_BY           NUMBER,
   LAST_UPDATE_DATE         VARCHAR2 (21),
   AMOUNT_TYPE              VARCHAR2 (5),
   CURRENCY_CODE            VARCHAR2 (5),
   FEE_CHARGED_PERCENTAGE   NUMBER,
   CONSTRAINT PK_CARD_FEE_DET_ID PRIMARY KEY (CARD_FEE_DET_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN epay.epay_psb10_card_fees_det.amount_low IS
'Transaction Amount low';

DROP SEQUENCE EPAY.EPAY_PSB10_CARD_FEES_DET_SEQ;

CREATE SEQUENCE EPAY.EPAY_PSB10_CARD_FEES_DET_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER EPAY.EPAY_PSB10_CARD_FEES_DET_TRG
   BEFORE INSERT
   ON EPAY.EPAY_PSB10_CARD_FEES_DET
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.CARD_FEE_DET_ID IS NULL)
DECLARE
   V_ID   EPAY.EPAY_PSB10_CARD_FEES_DET.CARD_FEE_DET_ID%TYPE;
BEGIN
   SELECT   EPAY.EPAY_PSB10_CARD_FEES_DET_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.CARD_FEE_DET_ID := V_ID;
END EPAY_PSB10_CARD_FEES_DET_TRG;