/* Formatted on 10/6/2014 7:22:23 PM (QP5 v5.126.903.23003) */
--DROP TABLE ATTN.ATTN_ALL_OTHER_INFO_TABLE;

CREATE TABLE ATTN.ATTN_ALL_OTHER_INFO_TABLE (
   DFLT_ROW_ID               NUMBER NOT NULL,
   TBL_OTHR_INF_COMBNTN_ID   NUMBER NOT NULL,
   ROW_PK_ID_VAL             NUMBER NOT NULL,
   OTHER_INFO_VALUE          VARCHAR2 (500 BYTE),
   CREATED_BY                VARCHAR2 (21 BYTE) NOT NULL,
   CREATION_DATE             VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY            VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_DATE          VARCHAR2 (21 BYTE) NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX ATTN.IDX_DEFLT_ROW_ID
   ON ATTN.ATTN_ALL_OTHER_INFO_TABLE (DFLT_ROW_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

   ALTER TABLE ATTN.ATTN_ALL_OTHER_INFO_TABLE ADD (
  CONSTRAINT PK_DFLT_ROW_ID
 PRIMARY KEY
 (DFLT_ROW_ID));

CREATE INDEX ATTN.IDX_OTHER_INFO_VALUE
   ON ATTN.ATTN_ALL_OTHER_INFO_TABLE (OTHER_INFO_VALUE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ATTN.IDX_ROW_PK_ID_VAL
   ON ATTN.ATTN_ALL_OTHER_INFO_TABLE (ROW_PK_ID_VAL)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ATTN.IDX_TBL_OTHR_INF_COMBNTN_ID
   ON ATTN.ATTN_ALL_OTHER_INFO_TABLE (TBL_OTHR_INF_COMBNTN_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE ATTN.ATTN_ALL_OTHER_INFO_TABLE_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ATTN.ATTN_ALL_OTHER_INFO_TABLE_TRG
   BEFORE INSERT
   ON ATTN.ATTN_ALL_OTHER_INFO_TABLE
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.DFLT_ROW_ID IS NULL)
DECLARE
   V_ID   ATTN.ATTN_ALL_OTHER_INFO_TABLE.DFLT_ROW_ID%TYPE;
BEGIN
   SELECT   ATTN.ATTN_ALL_OTHER_INFO_TABLE_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.DFLT_ROW_ID := V_ID;
END ATTN_ALL_OTHER_INFO_TABLE_TRG;