/* Formatted on 10/6/2014 7:22:41 PM (QP5 v5.126.903.23003) */
CREATE TABLE ATTN.ATTN_ATTENDANCE_EVENTS (
   EVENT_ID               NUMBER NOT NULL,
   EVENT_NAME             VARCHAR2 (300 BYTE),
   EVENT_DESC             VARCHAR2 (300 BYTE),
   EVENT_TYP              VARCHAR2 (2 BYTE), -- E.G R-RECURRING, NR-NON-RECURRING
   HOST_PRSN_ID           NUMBER,
   ALLWD_GRP_TYP          VARCHAR2 (50 BYTE),
   ALLWD_GRP_ID           NUMBER,
   TTL_TMTBL_SESSN_MINS   NUMBER,
   HGHST_CNTNUOUS_MINS    NUMBER,
   SLOT_PRIORITY          NUMBER,
   CREATED_BY             VARCHAR2 (21 BYTE) NOT NULL,
   CREATION_DATE          VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY         VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_DATE       VARCHAR2 (21 BYTE) NOT NULL,
   EVENT_CLASSIFICATION   VARCHAR2 (21 BYTE),
   ORG_ID                 NUMBER,
   PREFFRD_VENUE_ID       NUMBER,
   IS_ENABLED             VARCHAR2 (1 BYTE),
   ALLWD_GROUP_NM         VARCHAR2 (300 BYTE) NOT NULL,
   ATTND_METRIC_LOV_NM    VARCHAR2 (200 BYTE) NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX ATTN.IDX_EVENT_ID
   ON ATTN.ATTN_ATTENDANCE_EVENTS (EVENT_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

   ALTER TABLE ATTN.ATTN_ATTENDANCE_EVENTS ADD (
  CONSTRAINT PK_EVENT_ID
 PRIMARY KEY
 (EVENT_ID));

CREATE SEQUENCE ATTN.ATTN_ATTENDANCE_EVENTS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ATTN.ATTN_ATTENDANCE_EVENTS_TRG
   BEFORE INSERT
   ON ATTN.ATTN_ATTENDANCE_EVENTS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.EVENT_ID IS NULL)
DECLARE
   V_ID   ATTN.ATTN_ATTENDANCE_EVENTS.EVENT_ID%TYPE;
BEGIN
   SELECT   ATTN.ATTN_ATTENDANCE_EVENTS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.EVENT_ID := V_ID;
END ATTN_ATTENDANCE_EVENTS_TRG;