/* Formatted on 10/6/2014 7:24:30 PM (QP5 v5.126.903.23003) */
CREATE TABLE ATTN.ATTN_ATTENDANCE_RECS_CNTR (
   CNTR_ID             NUMBER NOT NULL,
   RECS_HDR_ID         NUMBER,
   METRIC_NAME_DESC    VARCHAR2 (200 BYTE),
   CNTR_RESULT         NUMBER NOT NULL,
   RSLT_COMMENT        VARCHAR2 (500 BYTE),
   CREATED_BY          VARCHAR2 (21 BYTE) NOT NULL,
   CREATION_DATE       VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY      VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_DATE    VARCHAR2 (21 BYTE) NOT NULL,
   LNKD_PSSBL_VAL_ID   NUMBER NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX ATTN.IDX_CNTR_ID
   ON ATTN.ATTN_ATTENDANCE_RECS_CNTR (CNTR_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

   ALTER TABLE ATTN.ATTN_ATTENDANCE_RECS_CNTR ADD (
  CONSTRAINT PK_CNTR_ID
 PRIMARY KEY
 (CNTR_ID));

CREATE SEQUENCE ATTN.ATTN_ATTENDANCE_RECDS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ATTN.ATTN_ATTENDANCE_RECDS_TRG
   BEFORE INSERT
   ON ATTN.ATTN_ATTENDANCE_RECS_CNTR
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.CNTR_ID IS NULL)
DECLARE
   V_ID   ATTN.ATTN_ATTENDANCE_RECS_CNTR.CNTR_ID%TYPE;
BEGIN
   SELECT   ATTN.ATTN_ATTENDANCE_RECDS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.CNTR_ID := V_ID;
END ATTN_ATTENDANCE_RECDS_TRG;