/* Formatted on 10/6/2014 7:24:43 PM (QP5 v5.126.903.23003) */
CREATE TABLE ATTN.ATTN_ATTENDANCE_RECS_HDR (
   RECS_HDR_ID         NUMBER NOT NULL,
   RECS_HDR_NAME       VARCHAR2 (200 BYTE),
   RECS_HDR_DESC       VARCHAR2 (300 BYTE),
   TIME_TABLE_ID       NUMBER,
   TIME_TABLE_DET_ID   NUMBER,
   CREATED_BY          VARCHAR2 (21 BYTE) NOT NULL,
   CREATION_DATE       VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY      VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_DATE    VARCHAR2 (21 BYTE) NOT NULL,
   ORG_ID              NUMBER,
   EVENT_DATE          VARCHAR2 (21 BYTE),
   END_DATE            VARCHAR2 (21 BYTE) NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX ATTN.IDX_RECS_HDR_ID
   ON ATTN.ATTN_ATTENDANCE_RECS_HDR (RECS_HDR_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

   ALTER TABLE ATTN.ATTN_ATTENDANCE_RECS_HDR ADD (
  CONSTRAINT PK_RECS_HDR_ID
 PRIMARY KEY
 (RECS_HDR_ID));

CREATE SEQUENCE ATTN.ATTN_ATTENDANCE_RECS_HDR_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ATTN.ATTN_ATTENDANCE_RECS_HDR_TRG
   BEFORE INSERT
   ON ATTN.ATTN_ATTENDANCE_RECS_HDR
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.RECS_HDR_ID IS NULL)
DECLARE
   V_ID   ATTN.ATTN_ATTENDANCE_RECS_HDR.RECS_HDR_ID%TYPE;
BEGIN
   SELECT   ATTN.ATTN_ATTENDANCE_RECS_HDR_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.RECS_HDR_ID := V_ID;
END ATTN_ATTENDANCE_RECS_HDR_TRG;