/* Formatted on 10/6/2014 7:25:31 PM (QP5 v5.126.903.23003) */
CREATE TABLE ATTN.ATTN_EVENT_VENUES (
   VENUE_ID               NUMBER NOT NULL,
   VENUE_NAME             VARCHAR2 (300 BYTE),
   VENUE_DESC             VARCHAR2 (300 BYTE),
   MAX_NO_PERSONS         NUMBER,
   VENUE_CLASSIFICATION   VARCHAR2 (100 BYTE),
   CREATED_BY             VARCHAR2 (21 BYTE) NOT NULL,
   CREATION_DATE          VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY         VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_DATE       VARCHAR2 (21 BYTE) NOT NULL,
   ORG_ID                 NUMBER,
   IS_ENABLED             VARCHAR2 (1 BYTE)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX ATTN.IDX_VENUE_ID
   ON ATTN.ATTN_EVENT_VENUES (VENUE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

   ALTER TABLE ATTN.ATTN_EVENT_VENUES ADD (
  CONSTRAINT PK_VENUE_ID
 PRIMARY KEY
 (VENUE_ID));

CREATE SEQUENCE ATTN.ATTN_EVENT_VENUES_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ATTN.ATTN_EVENT_VENUES_TRG
   BEFORE INSERT
   ON ATTN.ATTN_EVENT_VENUES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.VENUE_ID IS NULL)
DECLARE
   V_ID   ATTN.ATTN_EVENT_VENUES.VENUE_ID%TYPE;
BEGIN
   SELECT   ATTN.ATTN_EVENT_VENUES_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.VENUE_ID := V_ID;
END ATTN_EVENT_VENUES_TRG;