/* Formatted on 10/6/2014 7:26:25 PM (QP5 v5.126.903.23003) */
CREATE TABLE ATTN.ATTN_TIME_TABLE_HDRS (
   TIME_TABLE_ID             NUMBER NOT NULL,
   TIME_TABLE_NAME           VARCHAR2 (200 BYTE),
   TIME_TABLE_DESC           VARCHAR2 (300 BYTE),
   SMLLST_SLOT_DURATN_MINS   NUMBER,
   MAJ_TME_DIV_TYP           VARCHAR2 (50 BYTE),
   MAJ_TME_DIV_START_VAL     VARCHAR2 (100 BYTE),
   MAJ_TME_DIV_END_VAL       VARCHAR2 (100 BYTE),
   MIN_TME_DIV_TYP           VARCHAR2 (50 BYTE),
   MIN_TME_DIV_START_VAL     VARCHAR2 (100 BYTE),
   MIN_TME_DIV_END_VAL       VARCHAR2 (100 BYTE),
   CREATED_BY                VARCHAR2 (21 BYTE) NOT NULL,
   CREATION_DATE             VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY            VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_DATE          VARCHAR2 (21 BYTE) NOT NULL,
   EVENTS_CLASSIFCTION_USD   VARCHAR2 (200 BYTE),
   ORG_ID                    NUMBER,
   IS_ENABLED                VARCHAR2 (1 BYTE)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX ATTN.IDX_TIME_TABLE_ID
   ON ATTN.ATTN_TIME_TABLE_HDRS (TIME_TABLE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

   ALTER TABLE ATTN.ATTN_TIME_TABLE_HDRS ADD (
  CONSTRAINT PK_TIME_TABLE_ID
 PRIMARY KEY
 (TIME_TABLE_ID));

CREATE SEQUENCE ATTN.ATTN_TIME_TABLE_HDRS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ATTN.ATTN_TIME_TABLE_HDRS_TRG
   BEFORE INSERT
   ON ATTN.ATTN_TIME_TABLE_HDRS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.TIME_TABLE_ID IS NULL)
DECLARE
   V_ID   ATTN.ATTN_TIME_TABLE_HDRS.TIME_TABLE_ID%TYPE;
BEGIN
   SELECT   ATTN.ATTN_TIME_TABLE_HDRS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.TIME_TABLE_ID := V_ID;
END ATTN_TIME_TABLE_HDRS_TRG;