/* Formatted on 12-17-2018 8:39:18 AM (QP5 v5.126.903.23003) */
DROP TABLE SEC.SEC_APPLD_PATCHES  CASCADE CONSTRAINTS PURGE;

CREATE TABLE SEC.SEC_APPLD_PATCHES (
   PATCH_ID            NUMBER NOT NULL,
   PATCH_DESCRIPTION   VARCHAR2 (4000 BYTE),
   PATCH_DATE          VARCHAR2 (21 BYTE),
   PATCH_VERSION_NM    VARCHAR2 (100 BYTE),
   CONSTRAINT PK_PATCH_ID PRIMARY KEY (PATCH_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

DROP SEQUENCE SEC.SEC_APPLD_PATCHES_SEQ;

CREATE SEQUENCE SEC.SEC_APPLD_PATCHES_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;


CREATE INDEX SEC.IDX_PATCH_DATE
   ON SEC.SEC_APPLD_PATCHES (PATCH_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE OR REPLACE TRIGGER SEC.SEC_APPLD_PATCHES_TRG
   BEFORE INSERT
   ON SEC.SEC_APPLD_PATCHES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.PATCH_ID IS NULL)
DECLARE
   V_ID   SEC.SEC_APPLD_PATCHES.PATCH_ID%TYPE;
BEGIN
   SELECT   SEC.SEC_APPLD_PATCHES_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PATCH_ID := V_ID;
END SEC_APPLD_PATCHES_TRG;