/* Formatted on 12-17-2018 8:03:21 AM (QP5 v5.126.903.23003) */
DROP TABLE SEC.SEC_ALLWD_OTHER_INFOS  CASCADE CONSTRAINTS PURGE;

CREATE TABLE SEC.SEC_ALLWD_OTHER_INFOS (
   COMB_INFO_ID       NUMBER NOT NULL,
   TABLE_ID           NUMBER NOT NULL,
   OTHER_INFO_ID      NUMBER NOT NULL,
   IS_ENABLED         VARCHAR2 (1 BYTE),
   CREATED_BY         NUMBER NOT NULL,
   CREATION_DATE      VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY     NUMBER NOT NULL,
   LAST_UPDATE_DATE   VARCHAR2 (21 BYTE) NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX SEC.IDX_COMB_INFO_ID
   ON SEC.SEC_ALLWD_OTHER_INFOS (COMB_INFO_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SEC.SEC_ALLWD_OTHER_INFOS_SEQ;

CREATE SEQUENCE SEC.SEC_ALLWD_OTHER_INFOS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

ALTER TABLE SEC.SEC_ALLWD_OTHER_INFOS ADD (
CONSTRAINT PK_COMB_INFO_ID
PRIMARY KEY
(COMB_INFO_ID));


CREATE INDEX SEC.IDX_TABLE_ID_ALLWD
   ON SEC.SEC_ALLWD_OTHER_INFOS (TABLE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SEC.IDX_OTHER_INFO_ID_ALLWD
   ON SEC.SEC_ALLWD_OTHER_INFOS (OTHER_INFO_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;



CREATE OR REPLACE TRIGGER SEC.SEC_ALLWD_OTHER_INFOS_TRG
   BEFORE INSERT
   ON SEC.SEC_ALLWD_OTHER_INFOS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.COMB_INFO_ID IS NULL)
DECLARE
   V_ID   SEC.SEC_ALLWD_OTHER_INFOS.COMB_INFO_ID%TYPE;
BEGIN
   SELECT   SEC.SEC_ALLWD_OTHER_INFOS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.COMB_INFO_ID := V_ID;
END SEC_ALLWD_OTHER_INFOS_TRG;