/* Formatted on 12-17-2018 10:09:25 AM (QP5 v5.126.903.23003) */
DROP TABLE SEC.SEC_SECURITY_POLICIES  CASCADE CONSTRAINTS PURGE;

CREATE TABLE SEC.SEC_SECURITY_POLICIES (
   POLICY_ID                  NUMBER NOT NULL,
   POLICY_NAME                VARCHAR2 (100),
   MAX_FAILED_LGN_ATTMPTS     NUMBER,
   PSWD_EXPIRY_DAYS           NUMBER,
   AUTO_UNLOCKING_TIME_MINS   NUMBER,
   PSWD_REQUIRE_CAPS          VARCHAR2 (1 BYTE),
   PSWD_REQUIRE_SMALL         VARCHAR2 (1 BYTE),
   PSWD_REQUIRE_DGT           VARCHAR2 (1 BYTE),
   PSWD_REQUIRE_WILD          VARCHAR2 (1 BYTE),
   PSWD_REQRMNT_COMBNTNS      VARCHAR2 (5 BYTE),   -- POSSIBILITIES INCLUDE...
   IS_DEFAULT                 VARCHAR2 (1 BYTE),
   CREATED_BY                 NUMBER NOT NULL,
   CREATION_DATE              VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY             NUMBER NOT NULL,
   LAST_UPDATE_DATE           VARCHAR2 (21) NOT NULL,
   OLD_PSWD_CNT_TO_DISALLOW   NUMBER,
   PSWD_MIN_LENGTH            NUMBER,
   PSWD_MAX_LENGTH            NUMBER,
   MAX_NO_RECS_TO_DSPLY       NUMBER,
   ALLOW_REPEATING_CHARS      VARCHAR2 (1 BYTE),
   ALLOW_USRNAME_IN_PSWDS     VARCHAR2 (1 BYTE),
   SESSION_TIMEOUT            NUMBER NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX SEC.IDX_POLICY_ID
   ON SEC.SEC_SECURITY_POLICIES (POLICY_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SEC.SEC_SECURITY_POLICIES_SEQ;

CREATE SEQUENCE SEC.SEC_SECURITY_POLICIES_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

ALTER TABLE SEC.SEC_SECURITY_POLICIES ADD (
CONSTRAINT PK_POLICY_ID
PRIMARY KEY
(POLICY_ID));


CREATE UNIQUE INDEX SEC.IDX_POLICY_NAME
   ON SEC.SEC_SECURITY_POLICIES (POLICY_NAME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE OR REPLACE TRIGGER SEC.SEC_SECURITY_POLICIES_TRG
   BEFORE INSERT
   ON SEC.SEC_SECURITY_POLICIES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.POLICY_ID IS NULL)
DECLARE
   V_ID   SEC.SEC_SECURITY_POLICIES.POLICY_ID%TYPE;
BEGIN
   SELECT   SEC.SEC_SECURITY_POLICIES_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.POLICY_ID := V_ID;
END SEC_SECURITY_POLICIES_TRG;