/* Formatted on 12-17-2018 10:43:52 AM (QP5 v5.126.903.23003) */
--DROP TABLE SEC.SEC_USERS_N_ROLES;
DROP TABLE SEC.SEC_USERS_N_ROLES  CASCADE CONSTRAINTS PURGE;

CREATE TABLE SEC.SEC_USERS_N_ROLES (USER_ID            NUMBER NOT NULL,
                                    ROLE_ID            NUMBER,
                                    VALID_START_DATE   VARCHAR2 (21 BYTE),
                                    VALID_END_DATE     VARCHAR2 (21 BYTE),
                                    CREATED_BY         NUMBER,
                                    CREATION_DATE      VARCHAR2 (21 BYTE),
                                    LAST_UPDATE_BY     NUMBER,
                                    LAST_UPDATE_DATE   VARCHAR2 (21 BYTE),
                                    DFLT_ROW_ID        NUMBER NOT NULL)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SEC.IDX_DFLT_ROW_ID
   ON SEC.SEC_USERS_N_ROLES (DFLT_ROW_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SEC.SEC_USERS_N_ROLES_SEQ;

CREATE SEQUENCE SEC.SEC_USERS_N_ROLES_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

ALTER TABLE SEC.SEC_USERS_N_ROLES ADD (
CONSTRAINT PK_DFLT_ROW_ID_UR
PRIMARY KEY (DFLT_ROW_ID));


CREATE INDEX SEC.IDX_UR_VALID_END_DATE
   ON SEC.SEC_USERS_N_ROLES (VALID_END_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SEC.IDX_UR_VALID_START_DATE
   ON SEC.SEC_USERS_N_ROLES (VALID_START_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE OR REPLACE TRIGGER SEC.SEC_USERS_N_ROLES_TRG
   BEFORE INSERT
   ON SEC.SEC_USERS_N_ROLES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.DFLT_ROW_ID IS NULL)
DECLARE
   V_ID   SEC.SEC_USERS_N_ROLES.DFLT_ROW_ID%TYPE;
BEGIN
   SELECT   SEC.SEC_USERS_N_ROLES_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.DFLT_ROW_ID := V_ID;
END SEC_USERS_N_ROLES_TRG;