/* Formatted on 12-17-2018 9:25:03 AM (QP5 v5.126.903.23003) */
DROP TABLE SEC.SEC_AUDIT_TRAIL_TBLS_TO_ENBL  CASCADE CONSTRAINTS PURGE;

CREATE TABLE SEC.SEC_AUDIT_TRAIL_TBLS_TO_ENBL (
   POLICY_ID              NUMBER,
   MODULE_ID              NUMBER,
   ACTION_TYPS_TO_TRACK   VARCHAR2 (100 BYTE),                  -- EXAMPLES...
   ENABLE_TRACKING        VARCHAR2 (1 BYTE),
   CREATED_BY             NUMBER,
   CREATION_DATE          VARCHAR2 (21 BYTE),
   LAST_UPDATE_BY         NUMBER,
   LAST_UPDATE_DATE       VARCHAR2 (21 BYTE),
   DFLT_ROW_ID            NUMBER NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

--DROP INDEX SEC.IDX_DFLT_ROW_ID_AT;

CREATE UNIQUE INDEX SEC.IDX_DFLT_ROW_ID_AT
   ON SEC.SEC_AUDIT_TRAIL_TBLS_TO_ENBL (DFLT_ROW_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SEC.SEC_ADT_TRL_TBLS_TOENBL_SEQ;

CREATE SEQUENCE SEC.SEC_ADT_TRL_TBLS_TOENBL_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

ALTER TABLE SEC.SEC_AUDIT_TRAIL_TBLS_TO_ENBL ADD (
CONSTRAINT PK_DFLT_ROW_ID_AT
PRIMARY KEY
(DFLT_ROW_ID));


CREATE INDEX SEC.IDX_MODULE_ID_ADT
   ON SEC.SEC_AUDIT_TRAIL_TBLS_TO_ENBL (MODULE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SEC.IDX_POLICY_ID_ADT
   ON SEC.SEC_AUDIT_TRAIL_TBLS_TO_ENBL (POLICY_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

--DROP TRIGGER SEC.SEC_ADT_TRL_TBLS_TO_ENBL_TRG;

CREATE OR REPLACE TRIGGER SEC.SEC_ADT_TRL_TBLS_TOENBL_TRG
   BEFORE INSERT
   ON SEC.SEC_AUDIT_TRAIL_TBLS_TO_ENBL
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.DFLT_ROW_ID IS NULL)
DECLARE
   V_ID   SEC.SEC_AUDIT_TRAIL_TBLS_TO_ENBL.DFLT_ROW_ID%TYPE;
BEGIN
   SELECT   SEC.SEC_ADT_TRL_TBLS_TOENBL_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.DFLT_ROW_ID := V_ID;
END SEC_ADT_TRL_TBLS_TOENBL_TRG;