/* Formatted on 12-17-2018 10:07:25 AM (QP5 v5.126.903.23003) */
DROP TABLE SEC.SEC_ROLES_N_PRVLDGS  CASCADE CONSTRAINTS PURGE;

CREATE TABLE SEC.SEC_ROLES_N_PRVLDGS (
   ROLE_ID            NUMBER,
   PRVLDG_ID          NUMBER,
   VALID_START_DATE   VARCHAR2 (21 BYTE),
   VALID_END_DATE     VARCHAR2 (21 BYTE),
   CREATED_BY         NUMBER NOT NULL,
   CREATION_DATE      VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY     NUMBER NOT NULL,
   LAST_UPDATE_DATE   VARCHAR2 (21 BYTE) NOT NULL,
   DFLT_ROW_ID        NUMBER NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX SEC.IDX_DFLT_ROW_ID_RP
   ON SEC.SEC_ROLES_N_PRVLDGS (DFLT_ROW_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SEC.SEC_ROLES_N_PRVLDGS_SEQ;

CREATE SEQUENCE SEC.SEC_ROLES_N_PRVLDGS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

ALTER TABLE SEC.SEC_ROLES_N_PRVLDGS ADD (
CONSTRAINT PK_DFLT_ROW_ID_RP
PRIMARY KEY
(DFLT_ROW_ID));


CREATE INDEX SEC.IDX_PRVLDG_ID_RP
   ON SEC.SEC_ROLES_N_PRVLDGS (PRVLDG_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SEC.IDX_ROLE_ID_RP
   ON SEC.SEC_ROLES_N_PRVLDGS (ROLE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE INDEX SEC.IDX_RP_VALID_END_DATE
   ON SEC.SEC_ROLES_N_PRVLDGS (VALID_END_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SEC.IDX_RP_VALID_START_DATE
   ON SEC.SEC_ROLES_N_PRVLDGS (VALID_START_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE OR REPLACE TRIGGER SEC.SEC_ROLES_N_PRVLDGS_TRG
   BEFORE INSERT
   ON SEC.SEC_ROLES_N_PRVLDGS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.DFLT_ROW_ID IS NULL)
DECLARE
   V_ID   SEC.SEC_ROLES_N_PRVLDGS.DFLT_ROW_ID%TYPE;
BEGIN
   SELECT   SEC.SEC_ROLES_N_PRVLDGS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.DFLT_ROW_ID := V_ID;
END SEC_ROLES_N_PRVLDGS_TRG;