/* Formatted on 12-17-2018 10:15:52 AM (QP5 v5.126.903.23003) */
DROP TABLE SEC.SEC_TRACK_USER_LOGINS  CASCADE CONSTRAINTS PURGE;

CREATE TABLE SEC.SEC_TRACK_USER_LOGINS (
   USER_ID                  NUMBER NOT NULL,
   LOGIN_TIME               VARCHAR2 (21 BYTE) NOT NULL,
   LOGOUT_TIME              VARCHAR2 (21 BYTE),
   HOST_MACH_DETAILS        VARCHAR2 (500 BYTE),
   LOGIN_NUMBER             NUMBER NOT NULL,
   WAS_LGN_ATMPT_SUCCSFUL   VARCHAR2 (1 BYTE) NOT NULL,
   APP_VRSN                 VARCHAR2 (6) NOT NULL,
   WEB_SESSION_ID           VARCHAR2 (300),
   LAST_ACTIVE_TIME         VARCHAR2 (21),
   LGN_REMARKS              VARCHAR2 (300)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX SEC.INDX_LGN_NUM
   ON SEC.SEC_TRACK_USER_LOGINS (LOGIN_NUMBER)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SEC.SEC_TRACK_USER_LOGINS_SEQ;

CREATE SEQUENCE SEC.SEC_TRACK_USER_LOGINS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

ALTER TABLE SEC.SEC_TRACK_USER_LOGINS ADD (
CONSTRAINT PK_LOGIN_NUMBER
PRIMARY KEY
(LOGIN_NUMBER));


CREATE INDEX SEC.IDX_HOST_MACH_DETAILS
   ON SEC.SEC_TRACK_USER_LOGINS (HOST_MACH_DETAILS)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SEC.IDX_LOGIN_TIME
   ON SEC.SEC_TRACK_USER_LOGINS (LOGIN_TIME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE INDEX SEC.IDX_LOGOUT_TIME
   ON SEC.SEC_TRACK_USER_LOGINS (LOGOUT_TIME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SEC.IDX_USER_ID_TUL
   ON SEC.SEC_TRACK_USER_LOGINS (USER_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE OR REPLACE TRIGGER SEC.SEC_TRACK_USER_LOGINS_TRG
   BEFORE INSERT
   ON SEC.SEC_TRACK_USER_LOGINS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.LOGIN_NUMBER IS NULL)
DECLARE
   V_ID   SEC.SEC_TRACK_USER_LOGINS.LOGIN_NUMBER%TYPE;
BEGIN
   SELECT   SEC.SEC_TRACK_USER_LOGINS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.LOGIN_NUMBER := V_ID;
END SEC_TRACK_USER_LOGINS_TRG;