/* Formatted on 12-17-2018 9:40:15 AM (QP5 v5.126.903.23003) */
DROP TABLE SEC.SEC_PRVLDGS  CASCADE CONSTRAINTS PURGE;

CREATE TABLE SEC.SEC_PRVLDGS (PRVLDG_ID     NUMBER NOT NULL,
                              PRVLDG_NAME   VARCHAR2 (100 BYTE),
                              MODULE_ID     NUMBER)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX SEC.IDX_PRVLDG_ID
   ON SEC.SEC_PRVLDGS (PRVLDG_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SEC.SEC_PRVLDGS_SEQ;

CREATE SEQUENCE SEC.SEC_PRVLDGS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

ALTER TABLE SEC.SEC_PRVLDGS ADD (
CONSTRAINT PK_PRVLDG_ID
PRIMARY KEY
(PRVLDG_ID));


CREATE INDEX SEC.IDX_MODULE_ID_SP
   ON SEC.SEC_PRVLDGS (MODULE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SEC.IDX_PRVLDG_NAME
   ON SEC.SEC_PRVLDGS (PRVLDG_NAME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE OR REPLACE TRIGGER SEC.SEC_PRVLDGS_TRG
   BEFORE INSERT
   ON SEC.SEC_PRVLDGS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.PRVLDG_ID IS NULL)
DECLARE
   V_ID   SEC.SEC_PRVLDGS.PRVLDG_ID%TYPE;
BEGIN
   SELECT   SEC.SEC_PRVLDGS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PRVLDG_ID := V_ID;
END SEC_PRVLDGS_TRG;