/* Formatted on 10/5/2014 6:37:26 PM (QP5 v5.126.903.23003) */
-- TABLE: PAY.PAY_AUDIT_TRAIL_TBL

--DROP TABLE PAY.PAY_AUDIT_TRAIL_TBL;

CREATE TABLE PAY.PAY_AUDIT_TRAIL_TBL (
   USER_ID          NUMBER NOT NULL,
   ACTION_TYPE      VARCHAR2 (30),
   ACTION_DETAILS   CLOB,
   ACTION_TIME      VARCHAR2 (21),
   LOGIN_NUMBER     NUMBER,
   DFLT_ROW_ID      NUMBER NOT NULL,
   CONSTRAINT PK_DFLT_ROW_ID PRIMARY KEY (DFLT_ROW_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX PAY.IDX_ACTION_TIME
   ON PAY.PAY_AUDIT_TRAIL_TBL (ACTION_TIME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PAY.IDX_ACTION_TYPE
   ON PAY.PAY_AUDIT_TRAIL_TBL (ACTION_TYPE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PAY.IDX_LOGIN_NUMBER
   ON PAY.PAY_AUDIT_TRAIL_TBL (LOGIN_NUMBER)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PAY.IDX_USER_ID
   ON PAY.PAY_AUDIT_TRAIL_TBL (USER_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE PAY.PAY_AUDIT_TRAIL_TBL_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER PAY.PAY_AUDIT_TRAIL_TBL_TRG
   BEFORE INSERT
   ON PAY.PAY_AUDIT_TRAIL_TBL
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.DFLT_ROW_ID IS NULL)
DECLARE
   V_ID   PAY.PAY_AUDIT_TRAIL_TBL.DFLT_ROW_ID%TYPE;
BEGIN
   SELECT   PAY.PAY_AUDIT_TRAIL_TBL_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.DFLT_ROW_ID := V_ID;
END PAY_AUDIT_TRAIL_TBL_TRG;