/* Formatted on 10/6/2014 8:29:04 PM (QP5 v5.126.903.23003) */
-- TABLE: PAY.PAY_BALSITM_BALS

-- DROP TABLE PAY.PAY_BALSITM_BALS;

CREATE TABLE PAY.PAY_BALSITM_BALS (
   BALS_ID            NUMBER NOT NULL,
   BALS_ITM_ID        NUMBER,
   BALS_AMOUNT        NUMBER,
   PERSON_ID          NUMBER,
   BALS_DATE          VARCHAR2 (12),
   CREATED_BY         NUMBER NOT NULL,
   CREATION_DATE      VARCHAR2 (21),
   LAST_UPDATE_BY     NUMBER NOT NULL,
   LAST_UPDATE_DATE   VARCHAR2 (21) NOT NULL,
   SOURCE_TRNS_IDS    CLOB DEFAULT ',' NOT NULL,
   CONSTRAINT PK_BALS_ID PRIMARY KEY (BALS_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX PAY.IDX_BAL_PERSON_ID
   ON PAY.PAY_BALSITM_BALS (PERSON_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PAY.IDX_BALS_DATE
   ON PAY.PAY_BALSITM_BALS (BALS_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PAY.IDX_BALS_ITM_ID
   ON PAY.PAY_BALSITM_BALS (BALS_ITM_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE PAY.PAY_BALSITM_BALS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER PAY.PAY_BALSITM_BALS_TRG
   BEFORE INSERT
   ON PAY.PAY_BALSITM_BALS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.BALS_ID IS NULL)
DECLARE
   V_ID   PAY.PAY_BALSITM_BALS.BALS_ID%TYPE;
BEGIN
   SELECT   PAY.PAY_BALSITM_BALS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.BALS_ID := V_ID;
END PAY_BALSITM_BALS_TRG;