/* Formatted on 10/5/2014 6:46:37 PM (QP5 v5.126.903.23003) */
-- TABLE: PAY.PAY_GL_INTERFACE

-- DROP TABLE PAY.PAY_GL_INTERFACE;

CREATE TABLE PAY.PAY_GL_INTERFACE (
   INTERFACE_ID       NUMBER NOT NULL,
   ACCNT_ID           NUMBER,
   TRANSACTION_DESC   VARCHAR2 (500) NOT NULL,
   DBT_AMOUNT         NUMBER DEFAULT 0.00 NOT NULL,
   TRNSCTN_DATE       VARCHAR2 (21),
   FUNC_CUR_ID        NUMBER,
   CREATED_BY         NUMBER NOT NULL,
   CREATION_DATE      VARCHAR2 (21),
   CRDT_AMOUNT        NUMBER DEFAULT 0.00 NOT NULL,
   LAST_UPDATE_BY     NUMBER NOT NULL,
   LAST_UPDATE_DATE   VARCHAR2 (21) NOT NULL,
   NET_AMOUNT         NUMBER DEFAULT 0.00 NOT NULL,
   SOURCE_TRNS_ID     NUMBER DEFAULT (-1) NOT NULL,
   GL_BATCH_ID        NUMBER DEFAULT (-1) NOT NULL,
   TRNS_SOURCE        VARCHAR2 (3) DEFAULT 'SYS' NOT NULL,
   CONSTRAINT PK_INTFC_ID PRIMARY KEY (INTERFACE_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX PAY.IDX_INFC_GL_BATCH_ID
   ON PAY.PAY_GL_INTERFACE (GL_BATCH_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PAY.IDX_INTFC_ACCNT_ID
   ON PAY.PAY_GL_INTERFACE (ACCNT_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PAY.IDX_TRNSCTN_DATE
   ON PAY.PAY_GL_INTERFACE (TRNSCTN_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE PAY.PAY_GL_INTERFACE_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER PAY.PAY_GL_INTERFACE_TRG
   BEFORE INSERT
   ON PAY.PAY_GL_INTERFACE
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.INTERFACE_ID IS NULL)
DECLARE
   V_ID   PAY.PAY_GL_INTERFACE.INTERFACE_ID%TYPE;
BEGIN
   SELECT   PAY.PAY_GL_INTERFACE_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.INTERFACE_ID := V_ID;
END PAY_GL_INTERFACE_TRG;