/* Formatted on 10/5/2014 7:26:32 PM (QP5 v5.126.903.23003) */
-- TABLE: PAY.PAY_GLOBAL_VALUES_HDR

-- DROP TABLE PAY.PAY_GLOBAL_VALUES_HDR;

CREATE TABLE PAY.PAY_GLOBAL_VALUES_HDR (
   GLOBAL_VAL_ID        NUMBER NOT NULL,
   GLOBAL_VALUE_NAME    VARCHAR2 (100),
   GLOBAL_VALUE_DESC    VARCHAR2 (300),
   IS_ENABLED           VARCHAR2 (1),
   DFLT_CRITERIA_TYPE   VARCHAR2 (100),
   CREATED_BY           NUMBER NOT NULL,
   CREATION_DATE        VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY       NUMBER NOT NULL,
   LAST_UPDATE_DATE     VARCHAR2 (21) NOT NULL,
   CONSTRAINT PK_GLOBAL_VAL_ID PRIMARY KEY (GLOBAL_VAL_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX PAY.IDX_GLOBAL_VALUE_NAME
   ON PAY.PAY_GLOBAL_VALUES_HDR (GLOBAL_VALUE_NAME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE PAY.PAY_GLOBAL_VALUES_HDR_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER PAY.PAY_GLOBAL_VALUES_HDR_TRG
   BEFORE INSERT
   ON PAY.PAY_GLOBAL_VALUES_HDR
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.GLOBAL_VAL_ID IS NULL)
DECLARE
   V_ID   PAY.PAY_GLOBAL_VALUES_HDR.GLOBAL_VAL_ID%TYPE;
BEGIN
   SELECT   PAY.PAY_GLOBAL_VALUES_HDR_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.GLOBAL_VAL_ID := V_ID;
END PAY_GLOBAL_VALUES_HDR_TRG;