/* Formatted on 10/5/2014 8:09:58 PM (QP5 v5.126.903.23003) */
-- TABLE: PAY.PAY_ITM_TRNSCTNS

-- DROP TABLE PAY.PAY_ITM_TRNSCTNS;

CREATE TABLE PAY.PAY_ITM_TRNSCTNS (
   PAY_TRNS_ID          NUMBER NOT NULL,
   PERSON_ID            NUMBER,
   ITEM_ID              NUMBER,
   AMOUNT_PAID          NUMBER,
   PAYMNT_DATE          VARCHAR2 (21),
   PAYMNT_SOURCE        VARCHAR2 (50),
   PAY_TRNS_TYPE        VARCHAR2 (50),
   CREATED_BY           NUMBER NOT NULL,
   CREATION_DATE        VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY       NUMBER NOT NULL,
   LAST_UPDATE_DATE     VARCHAR2 (21) NOT NULL,
   MASS_PAY_ID          NUMBER,
   PYMNT_DESC           VARCHAR2 (500),
   CRNCY_ID             NUMBER DEFAULT (-1) NOT NULL,
   PYMNT_VLDTY_STATUS   VARCHAR2 (10) DEFAULT 'VALID' NOT NULL,
   SRC_PY_TRNS_ID       NUMBER DEFAULT (-1) NOT NULL,
   GL_DATE              VARCHAR2 (21) DEFAULT '' NOT NULL,
   CONSTRAINT PK_PAY_TRNS_ID PRIMARY KEY (PAY_TRNS_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX PAY.IDX_MASS_PAY_ID
   ON PAY.PAY_ITM_TRNSCTNS (MASS_PAY_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PAY.IDX_PAY_TRNS_TYPE
   ON PAY.PAY_ITM_TRNSCTNS (PAY_TRNS_TYPE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PAY.IDX_PAYMNT_DATE
   ON PAY.PAY_ITM_TRNSCTNS (PAYMNT_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PAY.IDX_PAYMNT_SOURCE
   ON PAY.PAY_ITM_TRNSCTNS (PAYMNT_SOURCE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PAY.IDX_PYMNT_DESC
   ON PAY.PAY_ITM_TRNSCTNS (PYMNT_DESC)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PAY.IDX_SRC_PY_TRNS_ID
   ON PAY.PAY_ITM_TRNSCTNS (SRC_PY_TRNS_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PAY.IDX_TRNS_ITEM_ID
   ON PAY.PAY_ITM_TRNSCTNS (ITEM_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PAY.IDX_TRNS_PERSON_ID
   ON PAY.PAY_ITM_TRNSCTNS (PERSON_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE PAY.PAY_ITM_TRNSCTNS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER PAY.PAY_ITM_TRNSCTNS_TRG
   BEFORE INSERT
   ON PAY.PAY_ITM_TRNSCTNS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.PAY_TRNS_ID IS NULL)
DECLARE
   V_ID   PAY.PAY_ITM_TRNSCTNS.PAY_TRNS_ID%TYPE;
BEGIN
   SELECT   PAY.PAY_ITM_TRNSCTNS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PAY_TRNS_ID := V_ID;
END PAY_ITM_TRNSCTNS_TRG;