/* Formatted on 10/5/2014 8:49:03 PM (QP5 v5.126.903.23003) */
-- TABLE: PAY.PAY_MASS_PAY_RUN_HDR
-- DROP TABLE PAY.PAY_MASS_PAY_RUN_HDR;

CREATE TABLE PAY.PAY_MASS_PAY_RUN_HDR (
   MASS_PAY_ID          NUMBER NOT NULL,
   MASS_PAY_NAME        VARCHAR2 (200),
   MASS_PAY_DESC        VARCHAR2 (300),
   CREATED_BY           NUMBER NOT NULL,
   CREATION_DATE        VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY       NUMBER NOT NULL,
   LAST_UPDATE_DATE     VARCHAR2 (21) NOT NULL,
   RUN_STATUS           VARCHAR2 (1) DEFAULT '0' NOT NULL,
   MASS_PAY_TRNS_DATE   VARCHAR2 (21) NOT NULL,
   PRS_ST_ID            NUMBER,
   ITM_ST_ID            NUMBER,
   ORG_ID               NUMBER,
   SENT_TO_GL           VARCHAR2 (1) DEFAULT '0' NOT NULL,
   GL_DATE              VARCHAR2 (21) DEFAULT '' NOT NULL,
   CONSTRAINT PK_MASS_RUN_ID PRIMARY KEY (MASS_PAY_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX PAY.IDX_MASS_PAY_DESC
   ON PAY.PAY_MASS_PAY_RUN_HDR (MASS_PAY_DESC)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PAY.IDX_MASS_PAY_NAME
   ON PAY.PAY_MASS_PAY_RUN_HDR (MASS_PAY_NAME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX PAY.IDX_MASS_PAY_TRNS_DATE
   ON PAY.PAY_MASS_PAY_RUN_HDR (MASS_PAY_TRNS_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE PAY.PAY_MASS_PAY_RUN_HDR_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER PAY.PAY_MASS_PAY_RUN_HDR_TRG
   BEFORE INSERT
   ON PAY.PAY_MASS_PAY_RUN_HDR
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.MASS_PAY_ID IS NULL)
DECLARE
   V_ID   PAY.PAY_MASS_PAY_RUN_HDR.MASS_PAY_ID%TYPE;
BEGIN
   SELECT   PAY.PAY_MASS_PAY_RUN_HDR_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.MASS_PAY_ID := V_ID;
END PAY_MASS_PAY_RUN_HDR_TRG;