/* Formatted on 10/5/2014 8:58:38 PM (QP5 v5.126.903.23003) */
-- TABLE: PAY.PAY_MASS_PAY_RUN_MSGS

-- DROP TABLE PAY.PAY_MASS_PAY_RUN_MSGS;

CREATE TABLE PAY.PAY_MASS_PAY_RUN_MSGS (
   MSG_ID             NUMBER NOT NULL,
   LOG_MESSAGES       CLOB,
   PROCESS_TYP        VARCHAR2 (100),
   PROCESS_ID         NUMBER,
   CREATED_BY         NUMBER NOT NULL,
   CREATION_DATE      VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY     NUMBER NOT NULL,
   LAST_UPDATE_DATE   VARCHAR2 (21) NOT NULL,
   CONSTRAINT PK_MSG_ID PRIMARY KEY (MSG_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX PAY.IDX_PROCESS_ID
   ON PAY.PAY_MASS_PAY_RUN_MSGS (PROCESS_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE PAY.PAY_MASS_PAY_RUN_MSGS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER PAY.PAY_MASS_PAY_RUN_MSGS_TRG
   BEFORE INSERT
   ON PAY.PAY_MASS_PAY_RUN_MSGS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.MSG_ID IS NULL)
DECLARE
   V_ID   PAY.PAY_MASS_PAY_RUN_MSGS.MSG_ID%TYPE;
BEGIN
   SELECT   PAY.PAY_MASS_PAY_RUN_MSGS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.MSG_ID := V_ID;
END PAY_MASS_PAY_RUN_MSGS_TRG;