/* Formatted on 12-18-2018 9:05:03 AM (QP5 v5.126.903.23003) */
DROP TABLE SELF.SELF_SURVEY_PERSONS CASCADE CONSTRAINTS PURGE;

CREATE TABLE SELF.SELF_SURVEY_PERSONS (
   SRVY_PRSN_ID       NUMBER NOT NULL,
   SRVY_ID            NUMBER,
   PRSN_SET_HRDR_ID   NUMBER,
   SRVY_START_DATE    VARCHAR2 (21),
   SRVY_END_DATE      VARCHAR2 (21),
   CREATED_BY         NUMBER,
   CREATION_DATE      VARCHAR2 (21),
   LAST_UPDATE_BY     NUMBER,
   LAST_UPDATE_DATE   VARCHAR2 (21),
   PRSN_TYPE          VARCHAR2 (15),                         -- PERSON SET,...
   PERSON_ID          NUMBER,
   CONSTRAINT PK_PRSNSET_SRVY_ID PRIMARY KEY (SRVY_PRSN_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX SELF.IDX_SP_PRSN_SET_HRDR_ID
   ON SELF.SELF_SURVEY_PERSONS (PRSN_SET_HRDR_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SELF.IDX_SP_SRVY_ID
   ON SELF.SELF_SURVEY_PERSONS (SRVY_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SELF.SELF_SURVEY_PERSONS_SEQ;

CREATE SEQUENCE SELF.SELF_SURVEY_PERSONS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER SELF.SELF_SURVEY_PERSONS_TRG
   BEFORE INSERT
   ON SELF.SELF_SURVEY_PERSONS
   FOR EACH ROW
   WHEN (NEW.SRVY_PRSN_ID IS NULL)
DECLARE
   V_ID   SELF.SELF_SURVEY_PERSONS.SRVY_PRSN_ID%TYPE;
BEGIN
   SELECT   SELF.SELF_SURVEY_PERSONS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.SRVY_PRSN_ID := V_ID;
END SELF_SURVEY_PERSONS_TRG;