/* Formatted on 12-17-2018 3:56:17 PM (QP5 v5.126.903.23003) */
DROP TABLE SELF.SELF_PRSN_EXTRA_DATA_COLS CASCADE CONSTRAINTS PURGE;

CREATE TABLE SELF.SELF_PRSN_EXTRA_DATA_COLS (
   EXTRA_DATA_COLS_ID     NUMBER NOT NULL,
   COLUMN_NO              INTEGER,
   COLUMN_LABEL           VARCHAR2 (300),
   ATTCHD_LOV_NAME        VARCHAR2 (300),
   COLUMN_DATA_TYPE       VARCHAR2 (100),                           -- E.G....
   COLUMN_DATA_CATEGORY   VARCHAR2 (300),
   DATA_LENGTH            INTEGER,
   DATA_DSPLY_TYPE        VARCHAR2 (1),                         -- E.G. T OR D
   ORG_ID                 INTEGER NOT NULL,
   NO_COLS_TBLR_DSPLY     INTEGER,
   COL_ORDER              INTEGER DEFAULT 1 NOT NULL,
   CSV_TBLR_COL_NMS       CLOB,
   CREATED_BY             NUMBER DEFAULT -1 NOT NULL,
   CREATION_DATE          VARCHAR2 (21)
         DEFAULT '2013-01-01 00:00:00' NOT NULL,
   LAST_UPDATE_BY         NUMBER DEFAULT -1 NOT NULL,
   LAST_UPDATE_DATE       VARCHAR2 (21)
         DEFAULT '2013-01-01 00:00:00' NOT NULL,
   IS_REQUIRED            VARCHAR2 (1) DEFAULT '0' NOT NULL,
   CONSTRAINT PK_EXTR_DTA_COL_ID PRIMARY KEY (EXTRA_DATA_COLS_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX SELF.IDX_EXC_COLUMN_NO
   ON SELF.SELF_PRSN_EXTRA_DATA_COLS (COLUMN_NO)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SELF.IDX_EXC_COLUMN_CATEGORY
   ON SELF.SELF_PRSN_EXTRA_DATA_COLS (COLUMN_DATA_CATEGORY)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SELF.SELF_PRSN_EXTRA_DATA_COLS_SEQ;

CREATE SEQUENCE SELF.SELF_PRSN_EXTRA_DATA_COLS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER SELF.SELF_PRSN_EXTRA_DATA_COLS_TRG
   BEFORE INSERT
   ON SELF.SELF_PRSN_EXTRA_DATA_COLS
   FOR EACH ROW
   WHEN (NEW.EXTRA_DATA_COLS_ID IS NULL)
DECLARE
   V_ID   SELF.SELF_PRSN_EXTRA_DATA_COLS.EXTRA_DATA_COLS_ID%TYPE;
BEGIN
   SELECT   SELF.SELF_PRSN_EXTRA_DATA_COLS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.EXTRA_DATA_COLS_ID := V_ID;
END SELF_PRSN_EXTRA_DATA_COLS_TRG;