/* Formatted on 12-17-2018 11:37:55 AM (QP5 v5.126.903.23003) */
DROP TABLE SELF.SELF_PERSON_QUESTION_ANSWERS CASCADE CONSTRAINTS PURGE;

CREATE TABLE SELF.SELF_PERSON_QUESTION_ANSWERS (
   PRSN_ANSR_ID       NUMBER NOT NULL,
   QSTN_ID            NUMBER,
   PRSN_ID            NUMBER,
   PSBL_ANSR_ID       NUMBER,
   ANSR_DESC          CLOB,
   CREATED_BY         NUMBER,
   CREATION_DATE      VARCHAR2 (21),
   LAST_UPDATE_BY     NUMBER,
   LAST_UPDATE_DATE   VARCHAR2 (21),
   SRVY_ID            NUMBER DEFAULT -1 NOT NULL,
   IS_SUBMITTED       VARCHAR2 (1) DEFAULT 0 NOT NULL,
   CONSTRAINT PK_PRSN_ANSR_ID PRIMARY KEY (PRSN_ANSR_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX SELF.IDX_PQA_QSTN_ID
   ON SELF.SELF_PERSON_QUESTION_ANSWERS (QSTN_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SELF.IDX_PQA_PRSN_ID
   ON SELF.SELF_PERSON_QUESTION_ANSWERS (PRSN_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SELF.IDX_PQA_PSBL_ANSR_ID
   ON SELF.SELF_PERSON_QUESTION_ANSWERS (PSBL_ANSR_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SELF.IDX_PQA_SRVY_ID
   ON SELF.SELF_PERSON_QUESTION_ANSWERS (SRVY_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE INDEX SELF.IDX_PQA_IS_SUBMITTED
   ON SELF.SELF_PERSON_QUESTION_ANSWERS (IS_SUBMITTED)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SELF.SELF_PERSON_QUESTION_ANSWERS_SEQ;

CREATE SEQUENCE SELF.SELF_PERSON_QUESTION_ANSWERS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER SELF.SELF_PERSON_QUESTION_ANSWERS_TRG
   BEFORE INSERT
   ON SELF.SELF_PERSON_QUESTION_ANSWERS
   FOR EACH ROW
   WHEN (NEW.PRSN_ANSR_ID IS NULL)
DECLARE
   V_ID   SELF.SELF_PERSON_QUESTION_ANSWERS.PRSN_ANSR_ID%TYPE;
BEGIN
   SELECT   SELF.SELF_PERSON_QUESTION_ANSWERS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PRSN_ANSR_ID := V_ID;
END SELF_PERSON_QUESTION_ANSWERS_TRG;