/* Formatted on 12-17-2018 3:43:56 PM (QP5 v5.126.903.23003) */
DROP TABLE SELF.SELF_PRSN_EVENT_RGSTRTNS CASCADE CONSTRAINTS PURGE;

CREATE TABLE SELF.SELF_PRSN_EVENT_RGSTRTNS (
   EVENT_REQ_ID         NUMBER NOT NULL,
   ATTENDEE_PERSON_ID   NUMBER NOT NULL,
   REGISTER_HDR_ID      NUMBER DEFAULT -1 NOT NULL,
   WKF_MSG_ID           NUMBER DEFAULT -1 NOT NULL,
   ATTENDEE_CSTMER_ID   NUMBER NOT NULL,
   SPONSOR_FIRM_ID      NUMBER NOT NULL,
   AMOUNT_PAID          NUMERIC DEFAULT 0 NOT NULL,
   CREATED_BY           NUMBER DEFAULT -1 NOT NULL,
   CREATION_DATE        VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY       NUMBER DEFAULT -1 NOT NULL,
   LAST_UPDATE_DATE     VARCHAR2 (21) NOT NULL,
   ATTACHMENTS          CLOB,
   STATUS               VARCHAR2 (20),
   CONSTRAINT PK_EVENT_REQ_ID PRIMARY KEY (EVENT_REQ_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX SELF.IDX_PV_PERSON_ID
   ON SELF.SELF_PRSN_EVENT_RGSTRTNS (ATTENDEE_PERSON_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SELF.IDX_PV_REGISTER_HDR_ID
   ON SELF.SELF_PRSN_EVENT_RGSTRTNS (REGISTER_HDR_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SELF.SELF_PRSN_EVENT_RGSTRTNS_SEQ;

CREATE SEQUENCE SELF.SELF_PRSN_EVENT_RGSTRTNS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER SELF.SELF_PRSN_EVENT_RGSTRTNS_TRG
   BEFORE INSERT
   ON SELF.SELF_PRSN_EVENT_RGSTRTNS
   FOR EACH ROW
   WHEN (NEW.EVENT_REQ_ID IS NULL)
DECLARE
   V_ID   SELF.SELF_PRSN_EVENT_RGSTRTNS.EVENT_REQ_ID%TYPE;
BEGIN
   SELECT   SELF.SELF_PRSN_EVENT_RGSTRTNS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.EVENT_REQ_ID := V_ID;
END SELF_PRSN_EVENT_RGSTRTNS_TRG;