/* Formatted on 12-17-2018 4:38:43 PM (QP5 v5.126.903.23003) */
DROP TABLE SELF.SELF_PRSN_NAMES_NOS CASCADE CONSTRAINTS PURGE;

CREATE TABLE SELF.SELF_PRSN_NAMES_NOS (
   PERSON_ID           NUMBER NOT NULL,
   CREATED_BY          NUMBER NOT NULL,
   CREATION_DATE       VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY      NUMBER NOT NULL,
   LAST_UPDATE_DATE    VARCHAR2 (21) NOT NULL,
   FIRST_NAME          VARCHAR2 (100),
   SUR_NAME            VARCHAR2 (100),
   OTHER_NAMES         VARCHAR2 (100),
   TITLE               VARCHAR2 (100),
   LOCAL_ID_NO         VARCHAR2 (100) DEFAULT 0 NOT NULL,
   ORG_ID              INTEGER DEFAULT -1 NOT NULL,
   GENDER              VARCHAR2 (20),
   MARITAL_STATUS      VARCHAR2 (30),
   DATE_OF_BIRTH       VARCHAR2 (12),
   PLACE_OF_BIRTH      VARCHAR2 (300),
   RELIGION            VARCHAR2 (300),
   RES_ADDRESS         VARCHAR2 (200),
   PSTL_ADDRS          VARCHAR2 (200),
   EMAIL               VARCHAR2 (100),
   CNTCT_NO_TEL        VARCHAR2 (100),
   CNTCT_NO_MOBL       VARCHAR2 (100),
   CNTCT_NO_FAX        VARCHAR2 (100),
   IMG_LOCATION        VARCHAR2 (500) NOT NULL,
   HOMETOWN            VARCHAR2 (300),
   NATIONALITY         VARCHAR2 (300),
   LNKD_FIRM_ORG_ID    NUMBER DEFAULT -1 NOT NULL,
   LNKD_FIRM_SITE_ID   NUMBER DEFAULT -1 NOT NULL,
   NEW_COMPANY         VARCHAR2 (300),
   NEW_COMPANY_LOC     VARCHAR2 (300),
   CONSTRAINT PK_PERSON_ID PRIMARY KEY (PERSON_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX SELF.IDX_PN_LOCAL_ID_NO
   ON SELF.SELF_PRSN_NAMES_NOS (LOCAL_ID_NO)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SELF.IDX_PN_first_name
   ON SELF.SELF_PRSN_NAMES_NOS (first_name)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SELF.SELF_PRSN_NAMES_NOS_SEQ;

CREATE SEQUENCE SELF.SELF_PRSN_NAMES_NOS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER SELF.SELF_PRSN_NAMES_NOS_TRG
   BEFORE INSERT
   ON SELF.SELF_PRSN_NAMES_NOS
   FOR EACH ROW
   WHEN (NEW.PERSON_ID IS NULL)
DECLARE
   V_ID   SELF.SELF_PRSN_NAMES_NOS.PERSON_ID%TYPE;
BEGIN
   SELECT   SELF.SELF_PRSN_NAMES_NOS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PERSON_ID := V_ID;
END SELF_PRSN_NAMES_NOS_TRG;