/* Formatted on 12-17-2018 5:33:11 PM (QP5 v5.126.903.23003) */
DROP TABLE SELF.SELF_SRVY_QUSTNS CASCADE CONSTRAINTS PURGE;

CREATE TABLE SELF.SELF_SRVY_QUSTNS (
   SRVY_QSTN_ID            NUMBER NOT NULL,
   SRVY_ID                 NUMBER,
   QSTN_ID                 NUMBER,
   QSTN_ORDER              INTEGER,
   CREATED_BY              NUMBER,
   CREATION_DATE           VARCHAR2 (21),
   LAST_UPDATE_BY          NUMBER,
   LAST_UPDATE_DATE        VARCHAR2 (21),
   QSTN_DSPLY_CONDTN_SQL   CLOB,
   QSTN_ANS_VALDTN_SQL     CLOB,
   INVALID_ANS_SET_MSG     CLOB,
   CONSTRAINT PK_SRVY_QSTN_ID PRIMARY KEY (SRVY_QSTN_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX SELF.IDX_SQ_QSTN_ID
   ON SELF.SELF_SRVY_QUSTNS (QSTN_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SELF.IDX_SQ_SRVY_ID
   ON SELF.SELF_SRVY_QUSTNS (QSTN_ORDER)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SELF.SELF_SRVY_QUSTNS_SEQ;

CREATE SEQUENCE SELF.SELF_SRVY_QUSTNS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER SELF.SELF_SRVY_QUSTNS_TRG
   BEFORE INSERT
   ON SELF.SELF_SRVY_QUSTNS
   FOR EACH ROW
   WHEN (NEW.SRVY_QSTN_ID IS NULL)
DECLARE
   V_ID   SELF.SELF_SRVY_QUSTNS.SRVY_QSTN_ID%TYPE;
BEGIN
   SELECT   SELF.SELF_SRVY_QUSTNS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.SRVY_QSTN_ID := V_ID;
END SELF_SRVY_QUSTNS_TRG;