/* Formatted on 12-17-2018 5:16:51 PM (QP5 v5.126.903.23003) */
DROP TABLE SELF.SELF_QUESTION_POSSIBLE_ANSWERS CASCADE CONSTRAINTS PURGE;

CREATE TABLE SELF.SELF_QUESTION_POSSIBLE_ANSWERS (
   PSBL_ANSR_ID           NUMBER NOT NULL,
   QSTN_ID                NUMBER,
   PSBL_ANSR_DESC         CLOB,
   PSBL_ANSR_ORDER_NO     INTEGER,
   CORRECT_ANSR           VARCHAR2 (1),
   CREATED_BY             NUMBER,
   CREATION_DATE          VARCHAR2 (21),
   LAST_UPDATE_BY         NUMBER,
   LAST_UPDATE_DATE       VARCHAR2 (21),
   ANSWER_IMG_LOC         VARCHAR2 (300),
   ANSWER_HINT_LINK_TXT   VARCHAR2 (300),
   ANSWER_HINT            CLOB,
   IS_ENABLED             VARCHAR2 (1) DEFAULT 1 NOT NULL,
   CONSTRAINT PK_PSBL_ANSR_ID PRIMARY KEY (PSBL_ANSR_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX SELF.IDX_ANS_QSTN_ID
   ON SELF.SELF_QUESTION_POSSIBLE_ANSWERS (QSTN_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SELF.IDX_ANS_PSBL_ANSR_ORDER_NO
   ON SELF.SELF_QUESTION_POSSIBLE_ANSWERS (PSBL_ANSR_ORDER_NO)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SELF.SELF_QUESTION_POSSIBLE_ANSWERS_SEQ;

CREATE SEQUENCE SELF.SELF_QUESTION_POSSIBLE_ANSWERS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER SELF.SELF_QUESTION_POSSIBLE_ANSWERS_TRG
   BEFORE INSERT
   ON SELF.SELF_QUESTION_POSSIBLE_ANSWERS
   FOR EACH ROW
   WHEN (NEW.PSBL_ANSR_ID IS NULL)
DECLARE
   V_ID   SELF.SELF_QUESTION_POSSIBLE_ANSWERS.PSBL_ANSR_ID%TYPE;
BEGIN
   SELECT   SELF.SELF_QUESTION_POSSIBLE_ANSWERS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PSBL_ANSR_ID := V_ID;
END SELF_QUESTION_POSSIBLE_ANSWERS_TRG;