/* Formatted on 12-17-2018 1:42:29 PM (QP5 v5.126.903.23003) */
DROP TABLE SELF.SELF_PRSN_DOC_ATTCHMNTS CASCADE CONSTRAINTS PURGE;

CREATE TABLE SELF.SELF_PRSN_DOC_ATTCHMNTS (
   ATTCHMNT_ID        NUMBER NOT NULL,
   PERSON_ID          NUMBER NOT NULL,
   ATTCHMNT_DESC      VARCHAR2 (500) NOT NULL,
   FILE_NAME          VARCHAR2 (300) NOT NULL,
   CREATED_BY         NUMBER NOT NULL,
   CREATION_DATE      VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY     NUMBER NOT NULL,
   LAST_UPDATE_DATE   VARCHAR2 (21) NOT NULL,
   CONSTRAINT PK_ATTCHMNT_ID PRIMARY KEY (ATTCHMNT_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX SELF.IDX_PD_ATTCHMNT_DESC
   ON SELF.SELF_PRSN_DOC_ATTCHMNTS (ATTCHMNT_DESC)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SELF.IDX_PD_PERSON_ID
   ON SELF.SELF_PRSN_DOC_ATTCHMNTS (PERSON_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SELF.SELF_PRSN_DOC_ATTCHMNTS_SEQ;

CREATE SEQUENCE SELF.SELF_PRSN_DOC_ATTCHMNTS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER SELF.SELF_PRSN_DOC_ATTCHMNTS_TRG
   BEFORE INSERT
   ON SELF.SELF_PRSN_DOC_ATTCHMNTS
   FOR EACH ROW
   WHEN (NEW.ATTCHMNT_ID IS NULL)
DECLARE
   V_ID   SELF.SELF_PRSN_DOC_ATTCHMNTS.ATTCHMNT_ID%TYPE;
BEGIN
   SELECT   SELF.SELF_PRSN_DOC_ATTCHMNTS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.ATTCHMNT_ID := V_ID;
END SELF_PRSN_DOC_ATTCHMNTS_TRG;