/* Formatted on 12-17-2018 11:49:06 AM (QP5 v5.126.903.23003) */
DROP TABLE SELF.SELF_PRSN_ABSENCE_REQS CASCADE CONSTRAINTS PURGE;

CREATE TABLE SELF.SELF_PRSN_ABSENCE_REQS (
   ABSENCE_REQ_ID       NUMBER NOT NULL,
   PERSON_ID            NUMBER NOT NULL,
   ABSENCE_PAY_ITM_ID   NUMBER DEFAULT -1 NOT NULL,
   ABSENCE_START_DATE   VARCHAR2 (21) NOT NULL,
   NO_DAYS_REQUESTED    NUMBER DEFAULT 0 NOT NULL,
   WKF_MSG_ID           NUMBER DEFAULT -1 NOT NULL,
   CREATED_BY           NUMBER DEFAULT -1 NOT NULL,
   CREATION_DATE        VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY       NUMBER DEFAULT -1 NOT NULL,
   LAST_UPDATE_DATE     VARCHAR2 (21) NOT NULL,
   ATTACHMENTS          CLOB,
   STATUS               VARCHAR2 (20),
   CONSTRAINT PK_ABSENCE_REQ_ID PRIMARY KEY (ABSENCE_REQ_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX SELF.IDX_AB_PERSON_ID
   ON SELF.SELF_PRSN_ABSENCE_REQS (PERSON_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SELF.IDX_AB_ABSENCE_START_DATE
   ON SELF.SELF_PRSN_ABSENCE_REQS (ABSENCE_START_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SELF.IDX_AB_STATUS
   ON SELF.SELF_PRSN_ABSENCE_REQS (STATUS)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SELF.IDX_AB_WKF_MSG_ID
   ON SELF.SELF_PRSN_ABSENCE_REQS (WKF_MSG_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SELF.SELF_PRSN_ABSENCE_REQS_SEQ;

CREATE SEQUENCE SELF.SELF_PRSN_ABSENCE_REQS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER SELF.SELF_PRSN_ABSENCE_REQS_TRG
   BEFORE INSERT
   ON SELF.SELF_PRSN_ABSENCE_REQS
   FOR EACH ROW
   WHEN (NEW.ABSENCE_REQ_ID IS NULL)
DECLARE
   V_ID   SELF.SELF_PRSN_ABSENCE_REQS.ABSENCE_REQ_ID%TYPE;
BEGIN
   SELECT   SELF.SELF_PRSN_ABSENCE_REQS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.ABSENCE_REQ_ID := V_ID;
END SELF_PRSN_ABSENCE_REQS_TRG;