/* Formatted on 12-17-2018 11:28:32 AM (QP5 v5.126.903.23003) */
DROP TABLE SELF.SELF_ARTICLES_HITS  CASCADE CONSTRAINTS PURGE;

CREATE TABLE SELF.SELF_ARTICLES_HITS (
   ARTICLE_HIT_ID   NUMBER NOT NULL,
   ARTICLE_ID       NUMBER DEFAULT -1 NOT NULL,
   CREATED_BY       NUMBER DEFAULT -1 NOT NULL,
   CREATION_DATE    VARCHAR2 (21) NOT NULL,
   LOGIN_NUMBER     NUMBER DEFAULT -1 NOT NULL,
   CONSTRAINT PK_ARTICLE_HIT_ID PRIMARY KEY (ARTICLE_HIT_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX SELF.IDX_AH_ARTICLE_ID
   ON SELF.SELF_ARTICLES_HITS (ARTICLE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SELF.SELF_ARTICLES_HITS_SEQ;

CREATE SEQUENCE SELF.SELF_ARTICLES_HITS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER SELF.SELF_ARTICLES_HITS_TRG
   BEFORE INSERT
   ON SELF.SELF_ARTICLES_HITS
   FOR EACH ROW
   WHEN (NEW.ARTICLE_HIT_ID IS NULL)
DECLARE
   V_ID   SELF.SELF_ARTICLES_HITS.ARTICLE_HIT_ID%TYPE;
BEGIN
   SELECT   SELF.SELF_ARTICLES_HITS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.ARTICLE_HIT_ID := V_ID;
END SELF_ARTICLES_HITS_TRG;