/* Formatted on 12-17-2018 1:36:55 PM (QP5 v5.126.903.23003) */
DROP TABLE SELF.SELF_PRSN_CHNG_RQST CASCADE CONSTRAINTS PURGE;

CREATE TABLE SELF.SELF_PRSN_CHNG_RQST (
   RQST_ID              NUMBER NOT NULL,
   RQST_DATE            VARCHAR2 (21),
   PERSON_ID            NUMBER,
   RQST_STATUS          VARCHAR2 (21),
   APPRVR_PERSON_ID     NUMBER,
   APPRVR_DATE          VARCHAR2 (21),
   CREATED_BY           NUMBER,
   CREATION_DATE        VARCHAR2 (21),
   LAST_UPDATE_BY       NUMBER,
   LAST_UPDATE_DATE     VARCHAR2 (21),
   HS_BEEN_DOWNLOADED   VARCHAR2 (1) DEFAULT '0' NOT NULL,
   CONSTRAINT PK_RQST_ID PRIMARY KEY (RQST_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX SELF.IDX_CR_RQST_DATE
   ON SELF.SELF_PRSN_CHNG_RQST (RQST_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SELF.IDX_CR_PERSON_ID
   ON SELF.SELF_PRSN_CHNG_RQST (PERSON_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SELF.SELF_PRSN_CHNG_RQST_SEQ;

CREATE SEQUENCE SELF.SELF_PRSN_CHNG_RQST_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER SELF.SELF_PRSN_CHNG_RQST_TRG
   BEFORE INSERT
   ON SELF.SELF_PRSN_CHNG_RQST
   FOR EACH ROW
   WHEN (NEW.RQST_ID IS NULL)
DECLARE
   V_ID   SELF.SELF_PRSN_CHNG_RQST.RQST_ID%TYPE;
BEGIN
   SELECT   SELF.SELF_PRSN_CHNG_RQST_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.RQST_ID := V_ID;
END SELF_PRSN_CHNG_RQST_TRG;