/* Formatted on 12-17-2018 4:50:32 PM (QP5 v5.126.903.23003) */
DROP TABLE SELF.SELF_PRSN_RELATIVES CASCADE CONSTRAINTS PURGE;

CREATE TABLE SELF.SELF_PRSN_RELATIVES (
   PERSON_ID           NUMBER NOT NULL,
   RELATIVE_PRSN_ID    NUMBER,
   RELATIONSHIP_TYPE   VARCHAR2 (100),
   CREATED_BY          NUMBER NOT NULL,
   CREATION_DATE       VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY      NUMBER NOT NULL,
   LAST_UPDATE_DATE    VARCHAR2 (21) NOT NULL,
   RLTV_ID             NUMBER NOT NULL,
   CONSTRAINT PK_RLTV_ID PRIMARY KEY (RLTV_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX SELF.IDX_PR_PERSON_ID
   ON SELF.SELF_PRSN_RELATIVES (PERSON_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SELF.IDX_PR_RELATIVE_PRSN_ID
   ON SELF.SELF_PRSN_RELATIVES (RELATIVE_PRSN_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SELF.SELF_PRSN_RELATIVES_SEQ;

CREATE SEQUENCE SELF.SELF_PRSN_RELATIVES_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER SELF.SELF_PRSN_RELATIVES_TRG
   BEFORE INSERT
   ON SELF.SELF_PRSN_RELATIVES
   FOR EACH ROW
   WHEN (NEW.RLTV_ID IS NULL)
DECLARE
   V_ID   SELF.SELF_PRSN_RELATIVES.RLTV_ID%TYPE;
BEGIN
   SELECT   SELF.SELF_PRSN_RELATIVES_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.RLTV_ID := V_ID;
END SELF_PRSN_RELATIVES_TRG;