/* Formatted on 12-18-2018 9:09:13 AM (QP5 v5.126.903.23003) */
DROP TABLE SELF.SELF_SURVEYS CASCADE CONSTRAINTS PURGE;

CREATE TABLE SELF.SELF_SURVEYS (
   SRVY_ID                  NUMBER NOT NULL,
   SRVY_NAME                VARCHAR2 (100),
   SRVY_DESC                CLOB,
   SRVY_INSTRCTNS           CLOB,
   CREATED_BY               NUMBER,
   CREATION_DATE            VARCHAR2 (21),
   LAST_UPDATE_BY           NUMBER,
   LAST_UPDATE_DATE         VARCHAR2 (21),
   SRVY_START_DATE          VARCHAR2 (21),
   SRVY_END_DATE            VARCHAR2 (21),
   ELIGIBLE_PRSN_SET_ID     INTEGER DEFAULT -1 NOT NULL,
   SURVEY_TYPE              VARCHAR2 (100) NOT NULL,            -- ELECTION...
   EXCLSN_LST_PRSN_SET_ID   INTEGER DEFAULT -1 NOT NULL,
   CONSTRAINT PK_SRVY_ID PRIMARY KEY (SRVY_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX SELF.IDX_SS_SRVY_NAME
   ON SELF.SELF_SURVEYS (SRVY_NAME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SELF.IDX_SS_ELIGIBLE_PRSN_SET_ID
   ON SELF.SELF_SURVEYS (ELIGIBLE_PRSN_SET_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SELF.SELF_SURVEYS_SEQ;

CREATE SEQUENCE SELF.SELF_SURVEYS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER SELF.SELF_SURVEYS_TRG
   BEFORE INSERT
   ON SELF.SELF_SURVEYS
   FOR EACH ROW
   WHEN (NEW.SRVY_ID IS NULL)
DECLARE
   V_ID   SELF.SELF_SURVEYS.SRVY_ID%TYPE;
BEGIN
   SELECT   SELF.SELF_SURVEYS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.SRVY_ID := V_ID;
END SELF_SURVEYS_TRG;