/* Formatted on 12-17-2018 1:22:37 PM (QP5 v5.126.903.23003) */
DROP TABLE SELF.SELF_PRSN_ALL_OTHER_INFO_TABLE CASCADE CONSTRAINTS PURGE;

CREATE TABLE SELF.SELF_PRSN_ALL_OTHER_INFO_TABLE (
   DFLT_ROW_ID               NUMBER NOT NULL,
   TBL_OTHR_INF_COMBNTN_ID   NUMBER NOT NULL,
   ROW_PK_ID_VAL             NUMBER NOT NULL,
   OTHER_INFO_VALUE          CLOB,
   CREATED_BY                NUMBER NOT NULL,
   CREATION_DATE             VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY            NUMBER NOT NULL,
   LAST_UPDATE_DATE          VARCHAR2 (21) NOT NULL,
   OTHER_INFO_LABEL          CLOB,
   OTHER_INFO_CATEGORY       VARCHAR2 (200) NOT NULL,
   CONSTRAINT PK_DFLT_ROW_ID_OI PRIMARY KEY (DFLT_ROW_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX SELF.IDX_PA_TBL_OTHR_INF_COMBNTN_ID
   ON SELF.SELF_PRSN_ALL_OTHER_INFO_TABLE (TBL_OTHR_INF_COMBNTN_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SELF.IDX_PA_ROW_PK_ID_VAL
   ON SELF.SELF_PRSN_ALL_OTHER_INFO_TABLE (ROW_PK_ID_VAL)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SELF.SELF_PRSN_ALL_OTHER_INFO_TABLE_SEQ;

CREATE SEQUENCE SELF.SELF_PRSN_ALL_OTHER_INFO_TABLE_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER SELF.SELF_PRSN_ALL_OTHER_INFO_TABLE_TRG
   BEFORE INSERT
   ON SELF.SELF_PRSN_ALL_OTHER_INFO_TABLE
   FOR EACH ROW
   WHEN (NEW.DFLT_ROW_ID IS NULL)
DECLARE
   V_ID   SELF.SELF_PRSN_ALL_OTHER_INFO_TABLE.DFLT_ROW_ID%TYPE;
BEGIN
   SELECT   SELF.SELF_PRSN_ALL_OTHER_INFO_TABLE_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.DFLT_ROW_ID := V_ID;
END SELF_PRSN_ALL_OTHER_INFO_TABLE_TRG;