/* Formatted on 12-17-2018 11:16:06 AM (QP5 v5.126.903.23003) */
DROP TABLE SELF.SELF_ARTICLE_CMMNTS  CASCADE CONSTRAINTS PURGE;

CREATE TABLE SELF.SELF_ARTICLE_CMMNTS (
   POSTED_CMNT_ID        NUMBER NOT NULL,
   ARTICLE_ID            NUMBER DEFAULT -1 NOT NULL,
   COMMENT_OR_POST       CLOB,
   IN_RSPNS_TO_CMNT_ID   NUMBER DEFAULT -1 NOT NULL,
   CREATED_BY            NUMBER DEFAULT -1 NOT NULL,
   CREATION_DATE         VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY        NUMBER DEFAULT -1 NOT NULL,
   LAST_UPDATE_DATE      VARCHAR2 (21) NOT NULL,
   LOGIN_NUMBER          NUMBER DEFAULT -1 NOT NULL,
   CONSTRAINT PK_POSTED_CMNT_ID PRIMARY KEY (POSTED_CMNT_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX SELF.IDX_ARTICLE_ID
   ON SELF.SELF_ARTICLE_CMMNTS (ARTICLE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SELF.IDX_IN_RSPNS_TO_CMNT_ID
   ON SELF.SELF_ARTICLE_CMMNTS (IN_RSPNS_TO_CMNT_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SELF.IDX_LOGIN_NUMBER
   ON SELF.SELF_ARTICLE_CMMNTS (LOGIN_NUMBER)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SELF.SELF_ARTICLE_CMMNTS_SEQ;

CREATE SEQUENCE SELF.SELF_ARTICLE_CMMNTS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER SELF.SELF_ARTICLE_CMMNTS_TRG
   BEFORE INSERT
   ON SELF.SELF_ARTICLE_CMMNTS
   FOR EACH ROW
   WHEN (NEW.POSTED_CMNT_ID IS NULL)
DECLARE
   V_ID   SELF.SELF_ARTICLE_CMMNTS.POSTED_CMNT_ID%TYPE;
BEGIN
   SELECT   SELF.SELF_ARTICLE_CMMNTS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.POSTED_CMNT_ID := V_ID;
END SELF_ARTICLE_CMMNTS_TRG;