/* Formatted on 12-17-2018 4:31:36 PM (QP5 v5.126.903.23003) */
DROP TABLE SELF.SELF_PRSN_INTRNL_PYMNTS_HDR CASCADE CONSTRAINTS PURGE;

CREATE TABLE SELF.SELF_PRSN_INTRNL_PYMNTS_HDR (
   PYMNT_REQ_HDR_ID     NUMBER NOT NULL,
   MASS_PAY_HDR_ID      NUMBER DEFAULT -1 NOT NULL,
   WKF_MSG_ID           NUMBER DEFAULT -1 NOT NULL,
   PYMNT_REQ_HDR_DESC   VARCHAR2 (400) NOT NULL,
   PAYMENT_DATE         VARCHAR2 (21) NOT NULL,
   CREATED_BY           NUMBER DEFAULT -1 NOT NULL,
   CREATION_DATE        VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY       NUMBER DEFAULT -1 NOT NULL,
   LAST_UPDATE_DATE     VARCHAR2 (21) NOT NULL,
   ATTACHMENTS          CLOB NOT NULL,
   STATUS               VARCHAR2 (20) NOT NULL,
   CONSTRAINT PK_PYMNT_REQ_HDR_ID PRIMARY KEY (PYMNT_REQ_HDR_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX SELF.IDX_IPH_MASS_PAY_HDR_ID
   ON SELF.SELF_PRSN_INTRNL_PYMNTS_HDR (MASS_PAY_HDR_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SELF.IDX_IPH_WKF_MSG_ID
   ON SELF.SELF_PRSN_INTRNL_PYMNTS_HDR (WKF_MSG_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SELF.SELF_PRSN_INTRNL_PYMNTS_HDR_SEQ;

CREATE SEQUENCE SELF.SELF_PRSN_INTRNL_PYMNTS_HDR_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER SELF.SELF_PRSN_INTRNL_PYMNTS_HDR_TRG
   BEFORE INSERT
   ON SELF.SELF_PRSN_INTRNL_PYMNTS_HDR
   FOR EACH ROW
   WHEN (NEW.PYMNT_REQ_HDR_ID IS NULL)
DECLARE
   V_ID   SELF.SELF_PRSN_INTRNL_PYMNTS_HDR.PYMNT_REQ_HDR_ID%TYPE;
BEGIN
   SELECT   SELF.SELF_PRSN_INTRNL_PYMNTS_HDR_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PYMNT_REQ_HDR_ID := V_ID;
END SELF_PRSN_INTRNL_PYMNTS_HDR_TRG;