/* Formatted on 12-17-2018 1:27:33 PM (QP5 v5.126.903.23003) */
DROP TABLE SELF.SELF_PRSN_AUDIT_TRAIL_TBL CASCADE CONSTRAINTS PURGE;

CREATE TABLE SELF.SELF_PRSN_AUDIT_TRAIL_TBL (
   USER_ID          NUMBER NOT NULL,
   ACTION_TYPE      VARCHAR2 (30),
   ACTION_DETAILS   CLOB,
   ACTION_TIME      VARCHAR2 (21),
   LOGIN_NUMBER     NUMBER,
   DFLT_ROW_ID      NUMBER NOT NULL,
   CONSTRAINT PK_DFLT_ROW_ID PRIMARY KEY (DFLT_ROW_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX SELF.IDX_AT_LOGIN_NUMBER
   ON SELF.SELF_PRSN_AUDIT_TRAIL_TBL (LOGIN_NUMBER)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SELF.IDX_AT_USER_ID
   ON SELF.SELF_PRSN_AUDIT_TRAIL_TBL (USER_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SELF.SELF_PRSN_AUDIT_TRAIL_TBL_SEQ;

CREATE SEQUENCE SELF.SELF_PRSN_AUDIT_TRAIL_TBL_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER SELF.SELF_PRSN_AUDIT_TRAIL_TBL_TRG
   BEFORE INSERT
   ON SELF.SELF_PRSN_AUDIT_TRAIL_TBL
   FOR EACH ROW
   WHEN (NEW.DFLT_ROW_ID IS NULL)
DECLARE
   V_ID   SELF.SELF_PRSN_AUDIT_TRAIL_TBL.DFLT_ROW_ID%TYPE;
BEGIN
   SELECT   SELF.SELF_PRSN_AUDIT_TRAIL_TBL_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.DFLT_ROW_ID := V_ID;
END SELF_PRSN_AUDIT_TRAIL_TBL_TRG;