/* Formatted on 12-17-2018 3:47:24 PM (QP5 v5.126.903.23003) */
DROP TABLE SELF.SELF_PRSN_EXTRA_DATA CASCADE CONSTRAINTS PURGE;

CREATE TABLE SELF.SELF_PRSN_EXTRA_DATA (
   EXTRA_DATA_ID      NUMBER NOT NULL,
   PERSON_ID          NUMBER NOT NULL,
   DATA_COL1          CLOB,
   DATA_COL2          CLOB,
   DATA_COL3          CLOB,
   DATA_COL4          CLOB,
   DATA_COL5          CLOB,
   DATA_COL6          CLOB,
   DATA_COL7          CLOB,
   DATA_COL8          CLOB,
   DATA_COL9          CLOB,
   DATA_COL10         CLOB,
   DATA_COL11         CLOB,
   DATA_COL12         CLOB,
   DATA_COL13         CLOB,
   DATA_COL14         CLOB,
   DATA_COL15         CLOB,
   DATA_COL16         CLOB,
   DATA_COL17         CLOB,
   DATA_COL18         CLOB,
   DATA_COL19         CLOB,
   DATA_COL20         CLOB,
   DATA_COL21         CLOB,
   DATA_COL22         CLOB,
   DATA_COL23         CLOB,
   DATA_COL24         CLOB,
   DATA_COL25         CLOB,
   DATA_COL26         CLOB,
   DATA_COL27         CLOB,
   DATA_COL28         CLOB,
   DATA_COL29         CLOB,
   DATA_COL30         CLOB,
   DATA_COL31         CLOB,
   DATA_COL32         CLOB,
   DATA_COL33         CLOB,
   DATA_COL34         CLOB,
   DATA_COL35         CLOB,
   DATA_COL36         CLOB,
   DATA_COL37         CLOB,
   DATA_COL38         CLOB,
   DATA_COL39         CLOB,
   DATA_COL40         CLOB,
   DATA_COL41         CLOB,
   DATA_COL42         CLOB,
   DATA_COL43         CLOB,
   DATA_COL44         CLOB,
   DATA_COL45         CLOB,
   DATA_COL46         CLOB,
   DATA_COL47         CLOB,
   DATA_COL48         CLOB,
   DATA_COL49         CLOB,
   DATA_COL50         CLOB,
   CREATED_BY         NUMBER NOT NULL,
   CREATION_DATE      VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY     NUMBER NOT NULL,
   LAST_UPDATE_DATE   VARCHAR2 (21) NOT NULL,
   CONSTRAINT PK_EXTRA_DATA_ID PRIMARY KEY (EXTRA_DATA_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX SELF.IDX_EX_PERSON_ID
   ON SELF.SELF_PRSN_EXTRA_DATA (PERSON_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SELF.SELF_PRSN_EXTRA_DATA_SEQ;

CREATE SEQUENCE SELF.SELF_PRSN_EXTRA_DATA_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER SELF.SELF_PRSN_EXTRA_DATA_TRG
   BEFORE INSERT
   ON SELF.SELF_PRSN_EXTRA_DATA
   FOR EACH ROW
   WHEN (NEW.EXTRA_DATA_ID IS NULL)
DECLARE
   V_ID   SELF.SELF_PRSN_EXTRA_DATA.EXTRA_DATA_ID%TYPE;
BEGIN
   SELECT   SELF.SELF_PRSN_EXTRA_DATA_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.EXTRA_DATA_ID := V_ID;
END SELF_PRSN_EXTRA_DATA_TRG;