/* Formatted on 12-17-2018 3:35:30 PM (QP5 v5.126.903.23003) */
DROP TABLE SELF.SELF_PRSN_EDUCATION CASCADE CONSTRAINTS PURGE;

CREATE TABLE SELF.SELF_PRSN_EDUCATION (
   PERSON_ID            NUMBER NOT NULL,
   COURSE_NAME          VARCHAR2 (200),
   SCHOOL_INSTITUTION   VARCHAR2 (200),
   SCHOOL_LOCATION      VARCHAR2 (200),
   CERT_OBTAINED        VARCHAR2 (200),
   COURSE_START_DATE    VARCHAR2 (12) NOT NULL,
   COURSE_END_DATE      VARCHAR2 (12) NOT NULL,
   DATE_CERT_AWARDED    VARCHAR2 (12),
   CREATED_BY           NUMBER NOT NULL,
   CREATION_DATE        VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY       NUMBER NOT NULL,
   LAST_UPDATE_DATE     VARCHAR2 (21) NOT NULL,
   CERT_TYPE            VARCHAR2 (200),
   EDUC_ID              NUMBER NOT NULL,
   CONSTRAINT PK_EDUC_ID PRIMARY KEY (EDUC_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX SELF.IDX_PE_PERSON_ID
   ON SELF.SELF_PRSN_EDUCATION (PERSON_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX SELF.IDX_PE_COURSE_NAME
   ON SELF.SELF_PRSN_EDUCATION (COURSE_NAME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE SELF.SELF_PRSN_EDUCATION_SEQ;

CREATE SEQUENCE SELF.SELF_PRSN_EDUCATION_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER SELF.SELF_PRSN_EDUCATION_TRG
   BEFORE INSERT
   ON SELF.SELF_PRSN_EDUCATION
   FOR EACH ROW
   WHEN (NEW.EDUC_ID IS NULL)
DECLARE
   V_ID   SELF.SELF_PRSN_EDUCATION.EDUC_ID%TYPE;
BEGIN
   SELECT   SELF.SELF_PRSN_EDUCATION_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.EDUC_ID := V_ID;
END SELF_PRSN_EDUCATION_TRG;