/* Formatted on 10/6/2014 2:23:59 AM (QP5 v5.126.903.23003) */
-- FUNCTION: APLAPPS.GET_CSTMR_SPLR_NAME(BIGINT)

-- DROP FUNCTION APLAPPS.GET_CSTMR_SPLR_NAME(BIGINT);

CREATE OR REPLACE FUNCTION APLAPPS.GET_CSTMR_SPLR_NAME (CSTMRSPLRID NUMBER)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200 BYTE) := '';
BEGIN
   SELECT   CUST_SUP_NAME
     INTO   L_RESULT
     FROM   SCM.SCM_CSTMR_SUPLR
    WHERE   CUST_SUP_ID = CSTMRSPLRID;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/