/* Formatted on 10/6/2014 2:23:44 AM (QP5 v5.126.903.23003) */
-- FUNCTION: APLAPPS.GET_CSTMR_SPLR_SITE_NAME(NUMBER)

-- DROP FUNCTION APLAPPS.GET_CSTMR_SPLR_SITE_NAME(NUMBER);

CREATE OR REPLACE FUNCTION APLAPPS.GET_CSTMR_SPLR_SITE_NAME (
   CSTMRSPLRSITEID NUMBER
)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200 BYTE) := '';
BEGIN
   SELECT   SITE_NAME
     INTO   L_RESULT
     FROM   SCM.SCM_CSTMR_SUPLR_SITES
    WHERE   CUST_SUP_SITE_ID = CSTMRSPLRSITEID;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/