/* Formatted on 10/6/2014 2:16:34 AM (QP5 v5.126.903.23003) */
-- FUNCTION: APLAPPS.GET_LTST_ITEM_BALS(NUMBER, VARCHAR2)

-- DROP FUNCTION APLAPPS.GET_LTST_ITEM_BALS(NUMBER, VARCHAR2);

CREATE OR REPLACE FUNCTION APLAPPS.GET_LTST_ITEM_BALS (ITMID      NUMBER,
                                                       BALSDTE    VARCHAR2)
   RETURN NUMBER
AS
   L_RESULT   NUMBER := 0.00;
BEGIN
     SELECT   SUM (APLAPPS.GET_LTST_STOCK_BALS1 (A.STOCK_ID, BALSDTE))
       INTO   L_RESULT
       FROM   INV.INV_STOCK A
      WHERE   (A.ITM_ID = ITMID)
   GROUP BY   A.ITM_ID;

   RETURN NVL (L_RESULT, 0);
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN 0.00;
END;
/