/* Formatted on 10/6/2014 2:21:17 AM (QP5 v5.126.903.23003) */
-- FUNCTION: APLAPPS.GET_DOC_SMRY_TYP_AMNT(NUMBER, VARCHAR2, VARCHAR2)

-- DROP FUNCTION APLAPPS.GET_DOC_SMRY_TYP_AMNT(NUMBER, VARCHAR2, VARCHAR2);

CREATE OR REPLACE FUNCTION APLAPPS.GET_DOC_SMRY_TYP_AMNT (
   DOCID      NUMBER,
   DOCTYP     VARCHAR2,
   SMRYTYP    VARCHAR2
)
   RETURN NUMBER
AS
   L_RESULT   NUMBER := 0.00;
BEGIN
   SELECT   A.SMMRY_AMNT
     INTO   L_RESULT
     FROM   SCM.SCM_DOC_AMNT_SMMRYS A
    WHERE       A.SRC_DOC_HDR_ID = DOCID
            AND A.SRC_DOC_TYPE = DOCTYP
            AND A.SMMRY_TYPE = SMRYTYP;

   RETURN NVL (L_RESULT, 0);
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN 0.00;
END;
/