/* Formatted on 10/6/2014 12:51:45 AM (QP5 v5.126.903.23003) */
-- FUNCTION: APLAPPS.ISTAXWTHHLDNG(NUMBER)

-- DROP FUNCTION APLAPPS.ISTAXWTHHLDNG(NUMBER);

CREATE OR REPLACE FUNCTION APLAPPS.ISTAXWTHHLDNG (TXCODEID NUMBER)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (50 BYTE) := '0';
BEGIN
   SELECT   IS_WITHLDNG_TAX
     INTO   L_RESULT
     FROM   SCM.SCM_TAX_CODES
    WHERE   CODE_ID = TXCODEID;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/