/* Formatted on 10/6/2014 12:56:27 AM (QP5 v5.126.903.23003) */
-- FUNCTION: APLAPPS.GET_SRC_DOC_NUM(NUMBER, VARCHAR2)

-- DROP FUNCTION APLAPPS.GET_SRC_DOC_NUM(NUMBER, VARCHAR2);

CREATE OR REPLACE FUNCTION APLAPPS.GET_SCM_SRC_DOC_NUM (
   SRCDOCID      NUMBER,
   SRCDOCTYPE    VARCHAR2
)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200 BYTE) := '';
BEGIN
   IF    SRCDOCTYPE LIKE '%Sales%'
      OR SRCDOCTYPE LIKE '%Invoice%'
      OR SRCDOCTYPE LIKE '%Item%Issue%'
      OR SRCDOCTYPE LIKE '%Item%Request%'
   THEN
      SELECT   INVC_NUMBER
        INTO   L_RESULT
        FROM   SCM.SCM_SALES_INVC_HDR
       WHERE   INVC_HDR_ID = SRCDOCID;
   ELSIF SRCDOCTYPE LIKE '%Purchase%'
   THEN
      SELECT   PURCHASE_DOC_NUM
        INTO   L_RESULT
        FROM   SCM.SCM_PRCHS_DOCS_HDR
       WHERE   PRCHS_DOC_HDR_ID = SRCDOCID;
   ELSE
      L_RESULT := TRIM (TO_CHAR (SRCDOCID, '9999999999999999999999999'));
   END IF;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/