/* Formatted on 10/6/2014 6:19:02 PM (QP5 v5.126.903.23003) */
CREATE TABLE ACA.ACA_ASSESSMENT_PERIODS (
   ASSMNT_PERIOD_ID     NUMBER NOT NULL,
   ASSMNT_PERIOD_NAME   VARCHAR2 (200 BYTE),
   ASSMNT_PERIOD_DESC   VARCHAR2 (300 BYTE),
   PERIOD_START_DATE    VARCHAR2 (21 BYTE),
   PERIOD_END_DATE      VARCHAR2 (21 BYTE),
   CREATED_BY           NUMBER NOT NULL,
   CREATION_DATE        VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY       NUMBER NOT NULL,
   LAST_UPDATE_DATE     VARCHAR2 (21 BYTE) NOT NULL,
   PERIOD_STATUS        VARCHAR2 (10 BYTE),
   ORG_ID               NUMBER
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX ACA.IDX_ASSMNT_PERIOD_ID
   ON ACA.ACA_ASSESSMENT_PERIODS (ASSMNT_PERIOD_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE ACA.ACA_ASSESSMENT_PERIODS ADD (
  CONSTRAINT PK_ASSMNT_PERIOD_ID
 PRIMARY KEY
 (ASSMNT_PERIOD_ID));

CREATE SEQUENCE ACA.ACA_ASSESSMENT_PERIODS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ACA.ACA_ASSESSMENT_PERIODS_TRG
   BEFORE INSERT
   ON ACA.ACA_ASSESSMENT_PERIODS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.ASSMNT_PERIOD_ID IS NULL)
DECLARE
   V_ID   ACA.ACA_ASSESSMENT_PERIODS.ASSMNT_PERIOD_ID%TYPE;
BEGIN
   SELECT   ACA.ACA_ASSESSMENT_PERIODS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.ASSMNT_PERIOD_ID := V_ID;
END ACA_ASSESSMENT_PERIODS_TRG;