/* Formatted on 10/6/2014 6:19:24 PM (QP5 v5.126.903.23003) */
--DROP TABLE ACA.ACA_ASSESSMENT_TYPES;

CREATE TABLE ACA.ACA_ASSESSMENT_TYPES (ASSMNT_TYP_ID      NUMBER NOT NULL,
                                       ASSMNT_TYP_NM      VARCHAR (200 BYTE),
                                       ASSMNT_TYP_DESC    VARCHAR (300 BYTE),
                                       CREATED_BY         NUMBER,
                                       CREATION_DATE      VARCHAR (21 BYTE),
                                       LAST_UPDATE_BY     NUMBER,
                                       LAST_UPDATE_DATE   VARCHAR (21 BYTE),
                                       IS_ENABLED         VARCHAR (1 BYTE))
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX ACA.IDX_ASSMNT_TYP_ID
   ON ACA.ACA_ASSESSMENT_TYPES (ASSMNT_TYP_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE ACA.ACA_ASSESSMENT_TYPES ADD (
  CONSTRAINT PK_ASSMNT_TYP_ID
 PRIMARY KEY
 (ASSMNT_TYP_ID));

CREATE SEQUENCE ACA.ACA_ASSESSMENT_TYPES_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ACA.ACA_ASSESSMENT_TYPES_TRG
   BEFORE INSERT
   ON ACA.ACA_ASSESSMENT_TYPES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.ASSMNT_TYP_ID IS NULL)
DECLARE
   V_ID   ACA.ACA_ASSESSMENT_TYPES.ASSMNT_TYP_ID%TYPE;
BEGIN
   SELECT   ACA.ACA_ASSESSMENT_TYPES_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.ASSMNT_TYP_ID := V_ID;
END ACA_ASSESSMENT_TYPES_TRG;