/* Formatted on 10/6/2014 6:19:59 PM (QP5 v5.126.903.23003) */
CREATE TABLE ACA.ACA_CLASSES (CLASS_ID            NUMBER NOT NULL,
                              CLASS_NAME          VARCHAR2 (200 BYTE),
                              CLASS_DESC          VARCHAR2 (300 BYTE),
                              IS_ENABLED          VARCHAR2 (1 BYTE),
                              CREATED_BY          NUMBER NOT NULL,
                              CREATION_DATE       VARCHAR2 (21 BYTE) NOT NULL,
                              LAST_UPDATE_BY      NUMBER NOT NULL,
                              LAST_UPDATE_DATE    VARCHAR2 (21 BYTE) NOT NULL,
                              ASSESSMENT_TYP_ID   NUMBER NOT NULL)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX ACA.IDX_CLASS_ID
   ON ACA.ACA_CLASSES (CLASS_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE ACA.ACA_CLASSES ADD (
  CONSTRAINT PK_CLASS_ID
 PRIMARY KEY
 (CLASS_ID));

CREATE SEQUENCE ACA.ACA_CLASSES_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ACA.ACA_CLASSES_TRG
   BEFORE INSERT
   ON ACA.ACA_CLASSES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.CLASS_ID IS NULL)
DECLARE
   V_ID   ACA.ACA_CLASSES.CLASS_ID%TYPE;
BEGIN
   SELECT   ACA.ACA_CLASSES_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.CLASS_ID := V_ID;
END ACA_CLASSES_TRG;