/* Formatted on 10/6/2014 6:55:08 PM (QP5 v5.126.903.23003) */
CREATE TABLE ACA.ACA_PRSN_ASSMNT_COL_VALS (
   ASSMNT_COL_VAL_ID     NUMBER NOT NULL,
   AC_STTNGS_SBJCTS_ID   NUMBER NOT NULL,
   COLUMN_ID             NUMBER NOT NULL,
   COL_VALUE             NUMBER NOT NULL,
   CREATED_BY            NUMBER NOT NULL,
   CREATION_DATE         VARCHAR (21 BYTE) NOT NULL,
   LAST_UPDATE_BY        NUMBER NOT NULL,
   LAST_UPDATE_DATE      VARCHAR (21 BYTE) NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX ACA.IDX_ASSMNT_COL_VAL_ID
   ON ACA.ACA_PRSN_ASSMNT_COL_VALS (ASSMNT_COL_VAL_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE ACA.ACA_PRSN_ASSMNT_COL_VALS ADD (
  CONSTRAINT PK_ASSMNT_COL_VAL_ID
 PRIMARY KEY
 (ASSMNT_COL_VAL_ID));

CREATE SEQUENCE ACA.ACA_PRSN_ASSMNT_COL_VALS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ACA.ACA_PRSN_ASSMNT_COL_VALS_TRG
   BEFORE INSERT
   ON ACA.ACA_PRSN_ASSMNT_COL_VALS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.ASSMNT_COL_VAL_ID IS NULL)
DECLARE
   V_ID   ACA.ACA_PRSN_ASSMNT_COL_VALS.ASSMNT_COL_VAL_ID%TYPE;
BEGIN
   SELECT   ACA.ACA_PRSN_ASSMNT_COL_VALS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.ASSMNT_COL_VAL_ID := V_ID;
END ACA_PRSN_ASSMNT_COL_VALS;