/* Formatted on 10/6/2014 6:55:49 PM (QP5 v5.126.903.23003) */
CREATE TABLE ACA.ACA_SUBJECTS (SUBJECT_ID         NUMBER NOT NULL,
                               SUBJECT_NAME       VARCHAR (300),
                               SUBJECT_DESC       VARCHAR (500),
                               CREATED_BY         NUMBER NOT NULL,
                               CREATION_DATE      VARCHAR (21) NOT NULL,
                               LAST_UPDATE_BY     NUMBER NOT NULL,
                               LAST_UPDATE_DATE   VARCHAR (21),
                               SUBJECT_CODE       VARCHAR (100) NOT NULL)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX ACA.IDX_SUBJECT_ID
   ON ACA.ACA_SUBJECTS (SUBJECT_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE ACA.ACA_SUBJECTS ADD (
  CONSTRAINT PK_SUBJECT_ID
 PRIMARY KEY
 (SUBJECT_ID ));

CREATE SEQUENCE ACA.ACA_SUBJECTS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ACA.ACA_SUBJECTS_TRG
   BEFORE INSERT
   ON ACA.ACA_SUBJECTS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.SUBJECT_ID IS NULL)
DECLARE
   V_ID   ACA.ACA_SUBJECTS.SUBJECT_ID%TYPE;
BEGIN
   SELECT   ACA.ACA_SUBJECTS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.SUBJECT_ID := V_ID;
END ACA_SUBJECTS_TRG;