/* Formatted on 10/6/2014 6:56:19 PM (QP5 v5.126.903.23003) */
--DROP TABLE ACA_ASSESS_SHEET_HDR;

CREATE TABLE ACA.ACA_ASSESS_SHEET_HDR (
   ASSESS_SHEET_HDR_ID   NUMBER NOT NULL,
   ASSESS_SHEET_NAME     VARCHAR2 (200 BYTE),
   CLASS_ID              NUMBER,
   ASSESSMENT_TYPE_ID    NUMBER,
   COURSE_ID             NUMBER,
   SUBJECT_ID            NUMBER,
   TUTOR_PERSON_ID       NUMBER,
   CREATED_BY            NUMBER NOT NULL,
   CREATION_DATE         VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY        NUMBER NOT NULL,
   LAST_UPDATE_DATE      VARCHAR2 (21 BYTE) NOT NULL,
   ACADEMIC_PERIOD_ID    NUMBER
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX ACA.ASSESS_SHEET_HDR_ID_IDX
   ON ACA.ACA_ASSESS_SHEET_HDR (ASSESS_SHEET_HDR_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE ACA.ACA_ASSESS_SHEET_HDR ADD (
  CONSTRAINT PK_ASSESS_SHEET_HDR_ID
 PRIMARY KEY
 (ASSESS_SHEET_HDR_ID));

CREATE SEQUENCE ACA.ACA_ASSESS_SHEET_HDR_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ACA.ACA_ASSESS_SHEET_HDR_TRG
   BEFORE INSERT
   ON ACA.ACA_ASSESS_SHEET_HDR
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.ASSESS_SHEET_HDR_ID IS NULL)
DECLARE
   V_ID   ACA.ACA_ASSESS_SHEET_HDR.ASSESS_SHEET_HDR_ID%TYPE;
BEGIN
   SELECT   ACA.ACA_ASSESS_SHEET_HDR_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.ASSESS_SHEET_HDR_ID := V_ID;
END ACA_ASSESS_SHEET_HDR_TRG;