/* Formatted on 10/6/2014 6:57:00 PM (QP5 v5.126.903.23003) */
--DROP TABLE ACA.ACA_ASSESSMENT_COLUMNS;

CREATE TABLE ACA.ACA_ASSESSMENT_COLUMNS (
   COLUMN_ID            NUMBER NOT NULL,
   ASSMNT_TYP_ID        NUMBER,
   COLUMN_NAME          VARCHAR2 (200 BYTE),
   COLUMN_DESC          VARCHAR2 (300 BYTE),
   COLUMN_HEADER_TEXT   VARCHAR2 (200 BYTE),
   IS_FORMULA_COLUMN    VARCHAR2 (1 BYTE),
   COLUMN_FORMULAR      VARCHAR2 (500 BYTE),
   CREATED_BY           NUMBER NOT NULL,
   CREATION_DATE        VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY       NUMBER NOT NULL,
   LAST_UPDATE_DATE     VARCHAR2 (21 BYTE) NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX ACA.IDX_COLUMN_ID
   ON ACA.ACA_ASSESSMENT_COLUMNS (COLUMN_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE ACA.ACA_ASSESSMENT_COLUMNS ADD (
  CONSTRAINT PK_COLUMN_ID
 PRIMARY KEY
 (COLUMN_ID));

CREATE SEQUENCE ACA.ACA_ASSESSMENT_COLUMNS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ACA.ACA_ASSESSMENT_COLUMNS_TRG
   BEFORE INSERT
   ON ACA.ACA_ASSESSMENT_COLUMNS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.COLUMN_ID IS NULL)
DECLARE
   V_ID   ACA.ACA_ASSESSMENT_COLUMNS.COLUMN_ID%TYPE;
BEGIN
   SELECT   ACA.ACA_ASSESSMENT_COLUMNS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.COLUMN_ID := V_ID;
END ACA_ASSESSMENT_COLUMNS_TRG;