/* Formatted on 12-15-2018 8:33:28 AM (QP5 v5.126.903.23003) */
DROP TABLE ORG.ORG_SEGMENT_VALUES  CASCADE CONSTRAINTS PURGE;

CREATE TABLE ORG.ORG_SEGMENT_VALUES (
   SEGMENT_VALUE_ID        NUMBER NOT NULL,
   SEGMENT_ID              INTEGER NOT NULL,
   SEGMENT_VALUE           VARCHAR2 (200),
   SEGMENT_DESCRIPTION     VARCHAR2 (300),
   ALLWD_GROUP_TYPE        VARCHAR2 (200),
   ALLWD_GROUP_VALUE       VARCHAR2 (200),
   IS_ENABLED              VARCHAR2 (1),
   PRNT_SEGMENT_VALUE_ID   INTEGER DEFAULT -1 NOT NULL,
   CREATED_BY              NUMBER DEFAULT -1 NOT NULL,
   CREATION_DATE           VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY          NUMBER DEFAULT -1 NOT NULL,
   LAST_UPDATE_DATE        VARCHAR2 (21) NOT NULL,
   ORG_ID                  INTEGER,
   IS_CONTRA               VARCHAR2 (1),
   ACCNT_TYPE              VARCHAR2 (2),                         -- ASSET-A...
   IS_PRNT_ACCNT           VARCHAR2 (1),
   IS_RETAINED_EARNINGS    VARCHAR2 (1) DEFAULT 0 NOT NULL,
   IS_NET_INCOME           VARCHAR2 (1) DEFAULT 0 NOT NULL,
   ACCNT_TYP_ID            INTEGER DEFAULT 1 NOT NULL,
   REPORT_LINE_NO          INTEGER DEFAULT 100 NOT NULL,
   HAS_SUB_LEDGERS         VARCHAR2 (1) DEFAULT '0' NOT NULL,
   CONTROL_ACCOUNT_ID      INTEGER DEFAULT -1 NOT NULL,
   CRNCY_ID                INTEGER DEFAULT -1 NOT NULL,
   IS_SUSPENS_ACCNT        VARCHAR2 (1) DEFAULT '0' NOT NULL,
   ACCOUNT_CLSFCTN         VARCHAR2 (200),
   MAPPED_GRP_ACCNT_ID     INTEGER DEFAULT -1 NOT NULL,
   ENABLE_CMBNTNS          VARCHAR2 (1) DEFAULT '1' NOT NULL,
   DPNDNT_SGMNT_VAL_ID     INTEGER DEFAULT -1 NOT NULL,
   LNKD_SITE_LOC_ID        INTEGER DEFAULT -1 NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX ORG.IDX_PK_SEGMENT_VALUE_ID
   ON ORG.ORG_SEGMENT_VALUES (SEGMENT_VALUE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE ORG.ORG_SEGMENT_VALUES ADD (
  CONSTRAINT PK_SEGMENT_VALUE_ID
 PRIMARY KEY
 (SEGMENT_VALUE_ID));

CREATE INDEX ORG.IDX_SV_ALLWD_GROUP_TYPE
   ON ORG.ORG_SEGMENT_VALUES (ALLWD_GROUP_TYPE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ORG.IDX_SV_ALLWD_GROUP_VALUE
   ON ORG.ORG_SEGMENT_VALUES (ALLWD_GROUP_VALUE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ORG.IDX_SV_DPNDNT_SGMNT_VAL_ID
   ON ORG.ORG_SEGMENT_VALUES (DPNDNT_SGMNT_VAL_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ORG.IDX_SV_IS_ENABLED
   ON ORG.ORG_SEGMENT_VALUES (IS_ENABLED)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ORG.IDX_SV_LNKD_SITE_LOC_ID
   ON ORG.ORG_SEGMENT_VALUES (LNKD_SITE_LOC_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ORG.IDX_SV_PRNT_SEGMENT_VALUE_ID
   ON ORG.ORG_SEGMENT_VALUES (PRNT_SEGMENT_VALUE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ORG.IDX_SV_ORG_ID
   ON ORG.ORG_SEGMENT_VALUES (ORG_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ORG.IDX_SV_SEGMENT_DESCRIPTION
   ON ORG.ORG_SEGMENT_VALUES (SEGMENT_DESCRIPTION)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ORG.IDX_SV_SEGMENT_ID
   ON ORG.ORG_SEGMENT_VALUES (SEGMENT_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ORG.IDX_SV_SEGMENT_VALUE
   ON ORG.ORG_SEGMENT_VALUES (SEGMENT_VALUE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE ORG.ORG_SEGMENT_VALUES_SEQ;

CREATE SEQUENCE ORG.ORG_SEGMENT_VALUES_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;


CREATE OR REPLACE TRIGGER ORG.ORG_SEGMENT_VALUES_TRG
   BEFORE INSERT
   ON ORG.ORG_SEGMENT_VALUES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.SEGMENT_VALUE_ID IS NULL)
DECLARE
   V_ID   ORG.ORG_SEGMENT_VALUES.SEGMENT_VALUE_ID%TYPE;
BEGIN
   SELECT   ORG.ORG_SEGMENT_VALUES_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.SEGMENT_VALUE_ID := V_ID;
END ORG_SEGMENT_VALUES_TRG;