/* Formatted on 12-15-2018 8:03:25 AM (QP5 v5.126.903.23003) */
DROP TABLE ORG.ORG_GTHRNG_TYPES  CASCADE CONSTRAINTS PURGE;

CREATE TABLE ORG.ORG_GTHRNG_TYPES (
   GTHRNG_TYP_ID      NUMBER NOT NULL,
   GTHRNG_TYP_NAME    VARCHAR2 (200 BYTE),
   GTHRNG_TYP_DESC    VARCHAR2 (500 BYTE),
   ORG_ID             NUMBER,
   IS_ENABLED         VARCHAR2 (1 BYTE),
   CREATED_BY         NUMBER NOT NULL,
   CREATION_DATE      VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY     NUMBER NOT NULL,
   LAST_UPDATE_DATE   VARCHAR2 (21 BYTE) NOT NULL,
   GATH_START_TIME    VARCHAR2 (9 BYTE),
   GATH_END_TIME      VARCHAR2 (9 BYTE)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX ORG.IDX_GTHRNG_TYP_ID
   ON ORG.ORG_GTHRNG_TYPES (GTHRNG_TYP_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE ORG.ORG_GTHRNG_TYPES_SEQ;

CREATE SEQUENCE ORG.ORG_GTHRNG_TYPES_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

ALTER TABLE ORG.ORG_GTHRNG_TYPES ADD (
  CONSTRAINT PK_GTHRNG_TYP_ID
 PRIMARY KEY
 (GTHRNG_TYP_ID));

CREATE INDEX ORG.IDX_GTHRNG_TYP_DESC
   ON ORG.ORG_GTHRNG_TYPES (GTHRNG_TYP_DESC)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE INDEX ORG.IDX_GTHRNG_TYP_NAME
   ON ORG.ORG_GTHRNG_TYPES (GTHRNG_TYP_NAME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE OR REPLACE TRIGGER ORG.ORG_GTHRNG_TYPES_TRG
   BEFORE INSERT
   ON ORG.ORG_GTHRNG_TYPES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.GTHRNG_TYP_ID IS NULL)
DECLARE
   V_ID   ORG.ORG_GTHRNG_TYPES.GTHRNG_TYP_ID%TYPE;
BEGIN
   SELECT   ORG.ORG_GTHRNG_TYPES_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.GTHRNG_TYP_ID := V_ID;
END ORG_GTHRNG_TYPES_TRG;