/* Formatted on 12-15-2018 8:10:20 AM (QP5 v5.126.903.23003) */
DROP TABLE ORG.ORG_PAY_ITEMS_VALUES  CASCADE CONSTRAINTS PURGE;

CREATE TABLE ORG.ORG_PAY_ITEMS_VALUES (
   PSSBL_VALUE_ID          NUMBER NOT NULL,
   ITEM_ID                 NUMBER,
   PSSBL_AMOUNT            NUMBER,
   PSSBL_VALUE_SQL         CLOB,
   CREATED_BY              NUMBER NOT NULL,
   CREATION_DATE           VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY          NUMBER NOT NULL,
   LAST_UPDATE_DATE        VARCHAR2 (21 BYTE) NOT NULL,
   PSSBL_VALUE_CODE_NAME   VARCHAR2 (21 BYTE) NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX ORG.IDX_PSSBL_VALUE_ID
   ON ORG.ORG_PAY_ITEMS_VALUES (PSSBL_VALUE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE ORG.ORG_PAY_ITEMS_VALUES ADD (
  CONSTRAINT PK_PSSBL_VAL_ID
 PRIMARY KEY
 (PSSBL_VALUE_ID));

CREATE INDEX ORG.IDX_PSSBL_VALUE_CODE_NAME
   ON ORG.ORG_PAY_ITEMS_VALUES (PSSBL_VALUE_CODE_NAME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;



CREATE INDEX ORG.IDX_VAL_ITEM_ID
   ON ORG.ORG_PAY_ITEMS_VALUES (ITEM_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE ORG.ORG_PAY_ITEMS_VALUES_SEQ;

CREATE SEQUENCE ORG.ORG_PAY_ITEMS_VALUES_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;


CREATE OR REPLACE TRIGGER ORG.ORG_PAY_ITEMS_VALUES_TRG
   BEFORE INSERT
   ON ORG.ORG_PAY_ITEMS_VALUES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.PSSBL_VALUE_ID IS NULL)
DECLARE
   V_ID   ORG.ORG_PAY_ITEMS_VALUES.PSSBL_VALUE_ID%TYPE;
BEGIN
   SELECT   ORG.ORG_PAY_ITEMS_VALUES_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PSSBL_VALUE_ID := V_ID;
END ORG_PAY_ITEMS_VALUES_TRG;