/* Formatted on 12-15-2018 7:38:21 AM (QP5 v5.126.903.23003) */
DROP TABLE ORG.ORG_ACCOUNT_CLSFCTNS  CASCADE CONSTRAINTS PURGE;

CREATE TABLE ORG.ORG_ACCOUNT_CLSFCTNS (ACCOUNT_CLSFCTN_ID   NUMBER NOT NULL,
                                       ACCOUNT_ID           INTEGER,
                                       MAJ_RPT_CTGRY        VARCHAR2 (200),
                                       MIN_RPT_CTGRY        VARCHAR2 (200),
                                       CREATED_BY           NUMBER,
                                       CREATION_DATE        VARCHAR2 (21),
                                       LAST_UPDATE_BY       NUMBER,
                                       LAST_UPDATE_DATE     VARCHAR2 (21))
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX ORG.IDX_ACCOUNT_CLSFCTN_ID
   ON ORG.ORG_ACCOUNT_CLSFCTNS (ACCOUNT_CLSFCTN_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE ORG.ORG_ACCOUNT_CLSFCTNS ADD (
  CONSTRAINT PK_ACCOUNT_CLSFCTN_ID
 PRIMARY KEY
 (ACCOUNT_CLSFCTN_ID));

CREATE INDEX ORG.IDX_ACB_MAJ_RPT_CTGRY
   ON ORG.ORG_ACCOUNT_CLSFCTNS (MAJ_RPT_CTGRY)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE INDEX ORG.IDX_ACB_MIN_RPT_CTGRY
   ON ORG.ORG_ACCOUNT_CLSFCTNS (MIN_RPT_CTGRY)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ORG.IDX_ACF_ACCOUNT_ID
   ON ORG.ORG_ACCOUNT_CLSFCTNS (ACCOUNT_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ORG.IDX_ACF_CREATED_BY
   ON ORG.ORG_ACCOUNT_CLSFCTNS (CREATED_BY)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ORG.IDX_ACF_LAST_UPDATE_BY
   ON ORG.ORG_ACCOUNT_CLSFCTNS (LAST_UPDATE_BY)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE ORG.ORG_ACCOUNT_CLSFCTNS_SEQ;
CREATE SEQUENCE ORG.ORG_ACCOUNT_CLSFCTNS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER ORG.ORG_ACCOUNT_CLSFCTNS_TRG
   BEFORE INSERT
   ON ORG.ORG_ACCOUNT_CLSFCTNS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.ACCOUNT_CLSFCTN_ID IS NULL)
DECLARE
   V_ID   ORG.ORG_ACCOUNT_CLSFCTNS.ACCOUNT_CLSFCTN_ID%TYPE;
BEGIN
   SELECT   ORG.ORG_ACCOUNT_CLSFCTNS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.ACCOUNT_CLSFCTN_ID := V_ID;
END ORG_ACCOUNT_CLSFCTNS_TRG;