/* Formatted on 12-15-2018 8:11:21 AM (QP5 v5.126.903.23003) */
DROP TABLE ORG.ORG_PAY_ITM_FEEDS  CASCADE CONSTRAINTS PURGE;

CREATE TABLE ORG.ORG_PAY_ITM_FEEDS (
   FEED_ID            NUMBER NOT NULL,
   BALANCE_ITEM_ID    NUMBER,
   FED_BY_ITM_ID      NUMBER NOT NULL,
   ADDS_SUBTRACTS     VARCHAR2 (10 BYTE) NOT NULL,
   CREATED_BY         NUMBER NOT NULL,
   CREATION_DATE      VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY     NUMBER NOT NULL,
   LAST_UPDATE_DATE   VARCHAR2 (21 BYTE) NOT NULL,
   SCALE_FACTOR       NUMBER DEFAULT 1 NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX ORG.IDX_FEED_ID
   ON ORG.ORG_PAY_ITM_FEEDS (FEED_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE ORG.ORG_PAY_ITM_FEEDS ADD (
  CONSTRAINT PK_FEED_ID
 PRIMARY KEY
 (FEED_ID));

CREATE INDEX ORG.IDX_BALS_ITM_ID
   ON ORG.ORG_PAY_ITM_FEEDS (BALANCE_ITEM_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ORG.IDX_FED_BY_ITM_ID
   ON ORG.ORG_PAY_ITM_FEEDS (FED_BY_ITM_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE ORG.ORG_PAY_ITM_FEEDS_SEQ;

CREATE SEQUENCE ORG.ORG_PAY_ITM_FEEDS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;


CREATE OR REPLACE TRIGGER ORG.ORG_PAY_ITM_FEEDS_TRG
   BEFORE INSERT
   ON ORG.ORG_PAY_ITM_FEEDS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.FEED_ID IS NULL)
DECLARE
   V_ID   ORG.ORG_PAY_ITM_FEEDS.FEED_ID%TYPE;
BEGIN
   SELECT   ORG.ORG_PAY_ITM_FEEDS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.FEED_ID := V_ID;
END ORG_PAY_ITM_FEEDS_TRG;