/* Formatted on 12-15-2018 8:44:47 AM (QP5 v5.126.903.23003) */
DROP TABLE ORG.ORG_WRKN_HRS_DETAILS  CASCADE CONSTRAINTS PURGE;

CREATE TABLE ORG.ORG_WRKN_HRS_DETAILS (
   WORK_HOURS_ID          NUMBER,
   DAY_OF_WEEK            VARCHAR2 (100 BYTE),
   DFLT_NRML_START_TIME   VARCHAR2 (21 BYTE) NOT NULL,
   DFLT_NRML_CLOSE_TIME   VARCHAR2 (21 BYTE),
   CREATED_BY             NUMBER NOT NULL,
   CREATION_DATE          VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY         NUMBER NOT NULL,
   LAST_UPDATE_DATE       VARCHAR2 (21 BYTE) NOT NULL,
   DFLT_ROW_ID            NUMBER NOT NULL,
   DAY_OF_WK_NO           NUMBER DEFAULT (-1) NOT NULL
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX ORG.IDX_DFLT_ROW_ID_WH
   ON ORG.ORG_WRKN_HRS_DETAILS (DFLT_ROW_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE ORG.ORG_WRKN_HRS_DETAILS ADD (
CONSTRAINT PK_DFLT_ROW_ID_WH
PRIMARY KEY
(DFLT_ROW_ID));

CREATE INDEX ORG.IDX_DAY_OF_WK_NO
   ON ORG.ORG_WRKN_HRS_DETAILS (DAY_OF_WK_NO)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE INDEX ORG.IDX_DET_WORK_HOURS_ID
   ON ORG.ORG_WRKN_HRS_DETAILS (WORK_HOURS_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE ORG.ORG_WRKN_HRS_DETAILS_SEQ;

CREATE SEQUENCE ORG.ORG_WRKN_HRS_DETAILS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER ORG.ORG_WRKN_HRS_DETAILS_TRG
   BEFORE INSERT
   ON ORG.ORG_WRKN_HRS_DETAILS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.DFLT_ROW_ID IS NULL)
DECLARE
   V_ID   ORG.ORG_WRKN_HRS_DETAILS.DFLT_ROW_ID%TYPE;
BEGIN
   SELECT   ORG.ORG_WRKN_HRS_DETAILS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.DFLT_ROW_ID := V_ID;
END ORG_WRKN_HRS_DETAILS_TRG;