/* Formatted on 12-15-2018 8:08:36 AM (QP5 v5.126.903.23003) */
DROP TABLE ORG.ORG_PAY_ITEMS  CASCADE CONSTRAINTS PURGE;

CREATE TABLE ORG.ORG_PAY_ITEMS (
   ITEM_ID                NUMBER NOT NULL,
   ITEM_CODE_NAME         VARCHAR2 (200 BYTE),
   ITEM_DESC              VARCHAR2 (300 BYTE),
   ITEM_MAJ_TYPE          VARCHAR2 (50 BYTE),
   ITEM_MIN_TYPE          VARCHAR2 (50 BYTE),
   ITEM_VALUE_UOM         VARCHAR2 (10 BYTE),
   USES_SQL_FORMULAS      VARCHAR2 (1 BYTE),
   COST_ACCNT_ID          NUMBER,
   BALS_ACCNT_ID          NUMBER,
   IS_ENABLED             VARCHAR2 (1 BYTE),
   ORG_ID                 NUMBER,
   CREATED_BY             NUMBER NOT NULL,
   CREATION_DATE          VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY         NUMBER NOT NULL,
   LAST_UPDATE_DATE       VARCHAR2 (21 BYTE) NOT NULL,
   PAY_FREQUENCY          VARCHAR2 (50 BYTE) DEFAULT 'Monthly' NOT NULL,
   LOCAL_CLASSFCTN        VARCHAR2 (200 BYTE) DEFAULT '1' NOT NULL,
   PAY_RUN_PRIORITY       NUMBER DEFAULT 500 NOT NULL,
   INCRS_DCRS_COST_ACNT   VARCHAR2 (50 BYTE),
   INCRS_DCRS_BALS_ACNT   VARCHAR2 (50 BYTE),
   BALANCE_TYPE           VARCHAR2 (50 BYTE),
   REPORT_LINE_NO         NUMBER DEFAULT 100 NOT NULL,
   IS_RETRO_ELEMENT       VARCHAR2 (1) DEFAULT '0' NOT NULL,
   RETRO_ITEM_ID          INTEGER DEFAULT -1 NOT NULL,
   INV_ITEM_ID            INTEGER DEFAULT -1 NOT NULL,
   ALLOW_VALUE_EDITING    VARCHAR2 (1) DEFAULT 1 NOT NULL,
   CREATES_ACCOUNTING     VARCHAR2 (1) DEFAULT '1' NOT NULL,
   EFFCT_ON_ORG_DEBT      VARCHAR2 (50)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX ORG.IDX_ITEM_ID
   ON ORG.ORG_PAY_ITEMS (ITEM_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE ORG.ORG_PAY_ITEMS ADD (
  CONSTRAINT PK_ITEM_ID
 PRIMARY KEY
 (ITEM_ID));

CREATE INDEX ORG.IDX_ITEM_CODE_NAME
   ON ORG.ORG_PAY_ITEMS (ITEM_CODE_NAME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ORG.IDX_ITEM_DESC
   ON ORG.ORG_PAY_ITEMS (ITEM_DESC)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

DROP SEQUENCE ORG.ORG_PAY_ITEMS_SEQ;

CREATE SEQUENCE ORG.ORG_PAY_ITEMS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER ORG.ORG_PAY_ITEMS_TRG
   BEFORE INSERT
   ON ORG.ORG_PAY_ITEMS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.ITEM_ID IS NULL)
DECLARE
   V_ID   ORG.ORG_PAY_ITEMS.ITEM_ID%TYPE;
BEGIN
   SELECT   ORG.ORG_PAY_ITEMS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.ITEM_ID := V_ID;
END ORG_PAY_ITEMS_TRG;