/* Formatted on 12-19-2018 6:21:35 PM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION PRS.IS_DATE_WEEKEND (P_DATE VARCHAR2)
   RETURN VARCHAR2
AS
   VALAMNT   NUMERIC := 0.00;
   PDAY      VARCHAR2 (21) := '';
BEGIN
   SELECT   TRIM (UPPER (TO_CHAR (TO_DATE (P_DATE, 'YYYY-MM-DD'), 'DAY')))
     INTO   PDAY
     FROM   DUAL;

   SELECT   DISTINCT 1
     INTO   VALAMNT
     FROM   GST.GEN_STP_LOV_NAMES A, GST.GEN_STP_LOV_VALUES B
    WHERE   ( (    A.VALUE_LIST_ID = B.VALUE_LIST_ID
               AND B.IS_ENABLED = '1'
               AND VALUE_LIST_NAME = 'Weekend Days'))
            AND TRIM (PDAY) = UPPER (TRIM (PSSBL_VALUE));

   IF VALAMNT > 0
   THEN
      RETURN 'TRUE';
   ELSE
      RETURN 'FALSE';
   END IF;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      IF UPPER (PDAY) IN ('SATURDAY', 'SUNDAY')
      THEN
         RETURN 'TRUE';
      ELSE
         RETURN 'FALSE';
      END IF;
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.PUT_LINE ('ERROR ' || SQLCODE || CHR (10) || SQLERRM);
      RETURN 'FALSE';
END;
/

SELECT   UPPER (TO_CHAR (TO_DATE ('31-DEC-2018'), 'DAY')) FROM DUAL;

SELECT   PRS.IS_DATE_WEEKEND ('2018-12-31') FROM DUAL;