/* Formatted on 12-19-2018 5:38:46 PM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION PRS.GET_PRSN_NTNL_ID (P_PERSONID    NUMBER,
                                                 P_ID_TYPE     VARCHAR2)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200 BYTE) := '';
BEGIN
   SELECT   COALESCE (A.ID_NUMBER, '')
     INTO   L_RESULT
     FROM   PRS.PRSN_NATIONAL_IDS A
    WHERE   A.PERSON_ID = P_PERSONID
            AND UPPER (A.NATIONAL_ID_TYP) = UPPER (P_ID_TYPE);

   RETURN COALESCE (L_RESULT, '');
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/