/* Formatted on 12-19-2018 5:26:56 PM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION PRS.GET_ACCRUAL_PLN_BALS_INFO (
   P_PLANEXCTNID    NUMBER,
   P_INFOTYPE       VARCHAR2
)
   RETURN NUMBER
AS
   BID    NUMBER := 0;
   BID1   NUMBER := 0;
   BID2   NUMBER := 0;
BEGIN
   IF P_INFOTYPE = 'Entitled'
   THEN
      SELECT   DAYS_ENTITLED
        INTO   BID
        FROM   PRS.HR_ACCRUAL_PLAN_EXCTNS
       WHERE   PLAN_EXECUTION_ID = P_PLANEXCTNID;
   ELSIF P_INFOTYPE IN ('Taken', 'Scheduled', 'Requested')
   THEN
      SELECT   SUM (COALESCE (NO_OF_DAYS, 0))
        INTO   BID
        FROM   PRS.HR_PERSON_ABSENCES
       WHERE   PLAN_EXECUTION_ID = P_PLANEXCTNID
               AND ABSENCE_STATUS = P_INFOTYPE;
   ELSIF P_INFOTYPE IN ('UnRequested')
   THEN
      SELECT   DAYS_ENTITLED
        INTO   BID1
        FROM   PRS.HR_ACCRUAL_PLAN_EXCTNS
       WHERE   PLAN_EXECUTION_ID = P_PLANEXCTNID;

      SELECT   SUM (COALESCE (NO_OF_DAYS, 0))
        INTO   BID2
        FROM   PRS.HR_PERSON_ABSENCES
       WHERE   PLAN_EXECUTION_ID = P_PLANEXCTNID;

      BID := BID1 - BID2;
   END IF;

   RETURN COALESCE (BID, 0);
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN 0;
END;
/