/* Formatted on 12-19-2018 5:00:29 PM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION PRS.GET_ACCRUAL_PLAN_NAME (P_PLANID NUMBER)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200 BYTE);
BEGIN
   L_RESULT := '';

   SELECT   ACCRUAL_PLAN_NAME
     INTO   L_RESULT
     FROM   PRS.HR_ACCRUAL_PLANS
    WHERE   ACCRUAL_PLAN_ID = P_PLANID;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/