/* Formatted on 12-19-2018 5:28:29 PM (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION PRS.GET_PRSN_ID (P_PRSNLOCID    VARCHAR2,
                                            P_INORGID      INTEGER)
   RETURN NUMBER
AS
   L_RESULT   NUMBER;
BEGIN
   SELECT   PERSON_ID
     INTO   L_RESULT
     FROM   PRS.PRSN_NAMES_NOS
    WHERE   upper(LOCAL_ID_NO) = upper(P_PRSNLOCID) AND ORG_ID = P_INORGID;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN -1;
END;
/