/* Formatted on 12-6-2018 5:24:24 PM (QP5 v5.126.903.23003) */
--DROP USER ACCB CASCADE;TKP
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
ALTER DATABASE DEFAULT TABLESPACE RHODB;
CREATE USER TKP
  IDENTIFIED BY GHANA1234
  --DEFAULT TABLESPACE RHODB
  --TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  CREATE USER HOTL
  IDENTIFIED BY GHANA1234
  --DEFAULT TABLESPACE RHODB
  --TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  CREATE USER MNLS
  IDENTIFIED BY GHANA1234
  --DEFAULT TABLESPACE RHODB
  --TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  CREATE USER HOSP
  IDENTIFIED BY GHANA1234
  DEFAULT TABLESPACE RHODB
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  CREATE USER WKF
  IDENTIFIED BY GHANA1234
  DEFAULT TABLESPACE RHODB
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  CREATE USER MCF
  IDENTIFIED BY GHANA1234
  DEFAULT TABLESPACE RHODB
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  CREATE USER INV
  IDENTIFIED BY GHANA1234
  DEFAULT TABLESPACE RHODB
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  CREATE USER ATTN
  IDENTIFIED BY GHANA1234
  DEFAULT TABLESPACE RHODB
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  CREATE USER ALRT
  IDENTIFIED BY GHANA1234
  DEFAULT TABLESPACE RHODB
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  CREATE USER ACA
  IDENTIFIED BY GHANA1234
  DEFAULT TABLESPACE RHODB
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
CREATE USER ACCB
  IDENTIFIED BY GHANA1234
  DEFAULT TABLESPACE RHODB
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  CREATE USER GST
  IDENTIFIED BY GHANA1234
  DEFAULT TABLESPACE RHODB
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  CREATE USER ORG
  IDENTIFIED BY GHANA1234
  DEFAULT TABLESPACE RHODB
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  CREATE USER PASN
  IDENTIFIED BY GHANA1234
  DEFAULT TABLESPACE RHODB
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
    CREATE USER PAY
  IDENTIFIED BY GHANA1234
  DEFAULT TABLESPACE RHODB
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
    CREATE USER PRS
  IDENTIFIED BY GHANA1234
  DEFAULT TABLESPACE RHODB
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
    CREATE USER RPT
  IDENTIFIED BY GHANA1234
  DEFAULT TABLESPACE RHODB
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
    CREATE USER SCM
  IDENTIFIED BY GHANA1234
  DEFAULT TABLESPACE RHODB
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
    CREATE USER SEC
  IDENTIFIED BY GHANA1234
  DEFAULT TABLESPACE RHODB
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  CREATE USER EPAY
  IDENTIFIED BY GHANA1234
  DEFAULT TABLESPACE RHODB
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  CREATE USER SELF
  IDENTIFIED BY GHANA1234
  DEFAULT TABLESPACE RHODB
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  CREATE USER BOG
  IDENTIFIED BY GHANA1234
  DEFAULT TABLESPACE RHODB
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  
  CREATE USER PUBLC
  IDENTIFIED BY GHANA1234
  DEFAULT TABLESPACE RHODB
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;