/* Formatted on 10/6/2014 7:41:39 PM (QP5 v5.126.903.23003) */
CREATE TABLE HOTL.CHECK_IN_PAYMENTS (
   CHECK_IN_PAYMNTS_ID        NUMBER NOT NULL,
   PAYMENT_DATE               VARCHAR2 (100 BYTE),
   ACTUAL_CHCK_IN_PYMT_MTHD   VARCHAR2 (100 BYTE),
   CREDIT_DEBIT_CARD_NO       VARCHAR2 (100 BYTE),
   SIGNATURE_CODE             VARCHAR2 (100 BYTE),
   AMOUNT_DEPOSITED           VARCHAR2 (100 BYTE),
   CREATED_BY                 VARCHAR2 (21 BYTE),
   CREATION_DATE              VARCHAR2 (21 BYTE),
   LAST_UPDATE_BY             VARCHAR2 (21 BYTE),
   LAST_UPDATE_DATE           VARCHAR2 (21 BYTE),
   CHECK_IN_ID                NUMBER
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX HOTL.IDX_CHECK_IN_PAYMNTS_ID
   ON HOTL.CHECK_IN_PAYMENTS (CHECK_IN_PAYMNTS_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE HOTL.CHECK_IN_PAYMENTS ADD (
  CONSTRAINT PK_CHECK_IN_PAYMNTS_ID
 PRIMARY KEY
 (CHECK_IN_PAYMNTS_ID));
ALTER TABLE HOTL.CHECK_IN_PAYMENTS ADD (
  CONSTRAINT CHCK_IN_PYMNT_FKEY FOREIGN KEY (CHECK_IN_ID)
      REFERENCES HOTL.CHECK_IN (CHECK_IN_ID));


CREATE SEQUENCE HOTL.CHECK_IN_PAYMENTS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER HOTL.CHECK_IN_PAYMENTS_TRG
   BEFORE INSERT
   ON HOTL.CHECK_IN_PAYMENTS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.CHECK_IN_PAYMNTS_ID IS NULL)
DECLARE
   V_ID   HOTL.CHECK_IN_PAYMENTS.CHECK_IN_PAYMNTS_ID%TYPE;
BEGIN
   SELECT   HOTL.CHECK_IN_PAYMENTS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.CHECK_IN_PAYMNTS_ID := V_ID;
END CHECK_IN_PAYMENTS_TRG;