/* Formatted on 10/6/2014 7:42:00 PM (QP5 v5.126.903.23003) */
CREATE TABLE HOTL.REQUESTED_SERVICE_TYPE (
   REQSTD_SERV_TYPE_ID         NUMBER NOT NULL,
   REQSTD_SERV_TYPE            VARCHAR2 (100 BYTE),
   RESERVED_ROOM_NO            VARCHAR2 (100 BYTE),
   ACTUAL_RESVTN_PYMNT_METHD   VARCHAR2 (100 BYTE),
   AMOUNT_DEPOSITED            VARCHAR2 (100 BYTE),
   DATE_OF_PAYMENT             VARCHAR2 (100 BYTE),
   INTENDED_CHEKIN_DATE        VARCHAR2 (100 BYTE),
   INTENDED_CHECKOUT_DATE      VARCHAR2 (100 BYTE),
   RESERVATION_STATUS          VARCHAR2 (100 BYTE),
   GENDER                      VARCHAR2 (1 BYTE),
   NATIONALITY                 VARCHAR2 (100 BYTE),
   IDENTIFICATION              VARCHAR2 (100 BYTE),
   IDENTIFICATION_NO           VARCHAR2 (100 BYTE),
   CREATED_BY                  VARCHAR2 (21 BYTE),
   CREATION_DATE               VARCHAR2 (21 BYTE),
   LAST_UPDATE_BY              VARCHAR2 (21 BYTE),
   LAST_UPDATE_DATE            VARCHAR2 (21 BYTE),
   APPLICATION_ID              NUMBER
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX HOSP.IDX_REQSTD_SERV_TYPE_ID
   ON HOTL.REQUESTED_SERVICE_TYPE (REQSTD_SERV_TYPE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE HOTL.REQUESTED_SERVICE_TYPE ADD (
  CONSTRAINT PK_REQSTD_SERV_TYPE_ID
 PRIMARY KEY
 (REQSTD_SERV_TYPE_ID));
 ALTER TABLE HOTL.REQUESTED_SERVICE_TYPE ADD (
  CONSTRAINT REQ_SERV_TYPE_FKEY FOREIGN KEY (APPLICATION_ID)
      REFERENCES HOTL.APPLICATION (APPLICATION_ID));

CREATE SEQUENCE HOTL.REQUESTED_SERVICE_TYPE_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER HOTL.REQUESTED_SERVICE_TYPE_TRG
   BEFORE INSERT
   ON HOTL.REQUESTED_SERVICE_TYPE
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.REQSTD_SERV_TYPE_ID IS NULL)
DECLARE
   V_ID   HOTL.REQUESTED_SERVICE_TYPE.REQSTD_SERV_TYPE_ID%TYPE;
BEGIN
   SELECT   HOTL.REQUESTED_SERVICE_TYPE_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.REQSTD_SERV_TYPE_ID := V_ID;
END REQUESTED_SERVICE_TYPE_TRG;