/* Formatted on 10/6/2014 7:42:23 PM (QP5 v5.126.903.23003) */
CREATE TABLE HOTL.ROOMS (ROOM_ID            NUMBER NOT NULL,
                         ROOM_NAME          VARCHAR2 (200 BYTE),
                         DESCRIPTION        VARCHAR2 (500 BYTE),
                         CREATED_BY         VARCHAR2 (21 BYTE),
                         CREATION_DATE      VARCHAR2 (21 BYTE),
                         LAST_UPDATE_BY     VARCHAR2 (21 BYTE),
                         LAST_UPDATE_DATE   VARCHAR2 (21 BYTE),
                         IS_ENABLED         VARCHAR2 (1),
                         SERVICE_TYPE_ID    NUMBER)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX HOSP.IDX_ROOM_ID
   ON HOTL.ROOMS (ROOM_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE HOTL.ROOMS ADD (
  CONSTRAINT PK_ROOM_ID
 PRIMARY KEY
 (ROOM_ID));


CREATE SEQUENCE HOTL.ROOMS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER HOTL.ROOMS_TRG
   BEFORE INSERT
   ON HOTL.ROOMS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.ROOM_ID IS NULL)
DECLARE
   V_ID   HOTL.ROOMS.ROOM_ID%TYPE;
BEGIN
   SELECT   HOTL.ROOMS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.ROOM_ID := V_ID;
END ROOMS_TRG;