/* Formatted on 10/6/2014 7:43:03 PM (QP5 v5.126.903.23003) */
CREATE TABLE HOTL.SERVICE_TYPES (SERVICE_TYPE_ID     NUMBER NOT NULL,
                                 SERVICE_TYPE_NAME   VARCHAR2 (300 BYTE),
                                 DESCRIPTION         VARCHAR2 (500 BYTE),
                                 INVENTORY_ITEM_ID   VARCHAR2 (100 BYTE),
                                 CREATED_BY          VARCHAR2 (21 BYTE),
                                 CREATION_DATE       VARCHAR2 (21 BYTE),
                                 LAST_UPDATE_BY      VARCHAR2 (21 BYTE),
                                 LAST_UPDATE_DATE    VARCHAR2 (21 BYTE),
                                 IS_ENABLED          VARCHAR2 (1 BYTE))
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX HOTL.IDX_SERVICE_TYPE_ID
   ON HOTL.SERVICE_TYPES (SERVICE_TYPE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

ALTER TABLE HOTL.SERVICE_TYPES ADD (
  CONSTRAINT PK_SERVICE_TYPE_ID
 PRIMARY KEY
 (SERVICE_TYPE_ID));

CREATE SEQUENCE HOTL.SERVICE_TYPES_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER HOTL.SERVICE_TYPES_TRG
   BEFORE INSERT
   ON HOTL.SERVICE_TYPES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.SERVICE_TYPE_ID IS NULL)
DECLARE
   V_ID   HOTL.SERVICE_TYPES.SERVICE_TYPE_ID%TYPE;
BEGIN
   SELECT   HOTL.SERVICE_TYPES_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.SERVICE_TYPE_ID := V_ID;
END SERVICE_TYPES_TRG;