/* Formatted on 10/6/2014 2:24:25 AM (QP5 v5.126.903.23003) */
-- FUNCTION: APLAPPS.GET_CSGMT_LST_TOT_BLS(BIGINT)

-- DROP FUNCTION APLAPPS.GET_CSGMT_LST_TOT_BLS(BIGINT);

CREATE OR REPLACE FUNCTION APLAPPS.GET_CSGMT_LST_TOT_BLS (CNSGMNTID NUMBER)
   RETURN NUMBER
AS
   L_RESULT   NUMBER := 0.00;
BEGIN
   SELECT   TBL1.TOTQTY
     INTO   L_RESULT
     FROM   (  SELECT   NVL (A.CONSGMT_TOT_QTY, 0) TOTQTY
                 FROM   INV.INV_CONSGMT_DAILY_BALS A
                WHERE   (TO_TIMESTAMP (A.BALS_DATE, 'YYYY-MM-DD') <=
                            SYSTIMESTAMP
                         AND A.CONSGMT_ID = CNSGMNTID)
             ORDER BY   TO_TIMESTAMP (A.BALS_DATE, 'YYYY-MM-DD') DESC) TBL1
    WHERE   ROWNUM < 2;

   --DESC LIMIT 1 OFFSET 0;
   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN 0.00;
END;
/