/* Formatted on 18/09/2014 09:23:16 (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION APLAPPS.GET_PAYITM_VALNM (P_PSBLVALID NUMBER)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200 BYTE);
BEGIN
   L_RESULT := '';

   SELECT   PSSBL_VALUE_CODE_NAME
     INTO   L_RESULT
     FROM   ORG.ORG_PAY_ITEMS_VALUES
    WHERE   PSSBL_VALUE_ID = P_PSBLVALID;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN '';
END;
/