/* Formatted on 10/3/2014 3:50:35 PM (QP5 v5.126.903.23003) */
-- FUNCTION: APLAPPS.GET_PYMNT_MTHD_NAME(BIGINT)

-- DROP FUNCTION APLAPPS.GET_PYMNT_MTHD_NAME(BIGINT);

CREATE OR REPLACE FUNCTION APLAPPS.GET_PYMNT_MTHD_NAME (P_PYMNTMTHDID NUMBER)
   RETURN VARCHAR2
AS
   L_RESULT   VARCHAR2 (200) := '';
BEGIN
   SELECT   PYMNT_MTHD_NAME
     INTO   L_RESULT
     FROM   ACCB.ACCB_PAYMNT_MTHDS
    WHERE   PAYMNT_MTHD_ID = P_PYMNTMTHDID;

   RETURN L_RESULT;
END;