/* Formatted on 10/5/2014 9:50:49 PM (QP5 v5.126.903.23003) */
-- FUNCTION: APLAPPS.GET_LTST_BLSITM_BALS(BIGINT, BIGINT, VARCHAR2)

-- DROP FUNCTION APLAPPS.GET_LTST_BLSITM_BALS(BIGINT, BIGINT, VARCHAR2);

CREATE OR REPLACE FUNCTION APLAPPS.GET_LTST_BLSITM_BALS (
   P_PERSONID       NUMBER,
   P_BALS_ITM_ID    NUMBER,
   P_BALS_DATE      VARCHAR2
)
   RETURN NUMBER
AS
   L_RESULT   NUMBER := 0.00;
BEGIN
   SELECT   TBL1.BALS_AMOUNT
     INTO   L_RESULT
     FROM   (  SELECT   A.BALS_AMOUNT
                 FROM   PAY.PAY_BALSITM_BALS A
                WHERE   A.PERSON_ID = P_PERSONID
                        AND A.BALS_ITM_ID = P_BALS_ITM_ID
                        AND TO_DATE (A.BALS_DATE, 'YYYY-MM-DD') <=
                              TO_DATE (P_BALS_DATE, 'YYYY-MM-DD')
             ORDER BY   TO_DATE (A.BALS_DATE, 'YYYY-MM-DD') DESC) TBL1
    WHERE   ROWNUM = 1;

   RETURN NVL (L_RESULT, 0);
END;