/* Formatted on 18/09/2014 09:26:28 (QP5 v5.126.903.23003) */
CREATE OR REPLACE FUNCTION APLAPPS.GET_SNIIT_EMPLYER (P_PERSONID NUMBER)
   RETURN NUMBER
AS
   L_RESULT   NUMBER (20, 2);
BEGIN
   L_RESULT := 0;

   SELECT   0.13 * APLAPPS.GET_BASIC_SALARY (P_PERSONID) INTO L_RESULT FROM DUAL;

   RETURN L_RESULT;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN 0;
END;