/* Formatted on 9/22/2014 12:56:15 PM (QP5 v5.126.903.23003) */
-- TABLE: ACCB.ACCB_BUDGET_DETAILS

-- DROP TABLE ACCB.ACCB_BUDGET_DETAILS;

CREATE TABLE ACCB.ACCB_BUDGET_DETAILS (
   BUDGET_DET_ID            NUMBER NOT NULL,
   BUDGET_ID                NUMBER,
   ACCNT_ID                 NUMBER,
   LIMIT_AMOUNT             NUMBER,
   START_DATE               VARCHAR2 (21 BYTE),
   END_DATE                 VARCHAR2 (21 BYTE),
   CREATED_BY               NUMBER NOT NULL,
   CREATION_DATE            VARCHAR2 (21 BYTE) NOT NULL,
   LAST_UPDATE_BY           NUMBER NOT NULL,
   LAST_UPDATE_DATE         VARCHAR2 (21 BYTE) NOT NULL,
   ACTION_IF_LIMIT_EXCDED   VARCHAR2 (100 BYTE),        -- POSSIBLE ACTIONS...
   CONSTRAINT PK_BUDGET_DET_ID PRIMARY KEY (BUDGET_DET_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX ACCB.IDX_ACCNT_ID_BDGT
   ON ACCB.ACCB_BUDGET_DETAILS (ACCNT_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_BDGT_END_DATE
   ON ACCB.ACCB_BUDGET_DETAILS (END_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_BDGT_START_DATE
   ON ACCB.ACCB_BUDGET_DETAILS (START_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE INDEX ACCB.IDX_BUDGET_ID
   ON ACCB.ACCB_BUDGET_DETAILS (BUDGET_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE SEQUENCE ACCB.ACCB_BUDGET_DETAILS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ACCB.ACCB_BUDGET_DETAILS_TRG
   BEFORE INSERT
   ON ACCB.ACCB_BUDGET_DETAILS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.BUDGET_DET_ID IS NULL)
DECLARE
   V_ID   ACCB.ACCB_BUDGET_DETAILS.BUDGET_DET_ID%TYPE;
BEGIN
   SELECT   ACCB.ACCB_BUDGET_DETAILS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.BUDGET_DET_ID := V_ID;
END ACCB_BUDGET_DETAILS_TRG;