/* Formatted on 9/22/2014 1:21:36 PM (QP5 v5.126.903.23003) */
-- TABLE: ACCB.ACCB_CHART_OF_ACCNTS

-- DROP TABLE ACCB.ACCB_CHART_OF_ACCNTS;

CREATE TABLE ACCB.ACCB_CHART_OF_ACCNTS (
   ACCNT_ID               NUMBER NOT NULL,
   ACCNT_NUM              VARCHAR2 (25),
   ACCNT_NAME             VARCHAR2 (100),
   ACCNT_DESC             VARCHAR2 (200),
   IS_CONTRA              VARCHAR2 (1),
   PRNT_ACCNT_ID          NUMBER,
   BALANCE_DATE           VARCHAR2 (21),
   CREATED_BY             NUMBER NOT NULL,
   CREATION_DATE          VARCHAR2 (21),
   LAST_UPDATE_BY         NUMBER NOT NULL,
   LAST_UPDATE_DATE       VARCHAR2 (21),
   ORG_ID                 NUMBER,
   ACCNT_TYPE             VARCHAR2 (2),                          -- ASSET-A...
   IS_PRNT_ACCNT          VARCHAR2 (1),
   DEBIT_BALANCE          NUMBER,
   CREDIT_BALANCE         NUMBER,
   IS_ENABLED             VARCHAR2 (1),
   NET_BALANCE            NUMBER,
   IS_RETAINED_EARNINGS   VARCHAR2 (1) DEFAULT '0' NOT NULL,
   IS_NET_INCOME          VARCHAR2 (1) DEFAULT '0' NOT NULL,
   ACCNT_TYP_ID           NUMBER DEFAULT 1 NOT NULL,
   REPORT_LINE_NO         NUMBER DEFAULT 100 NOT NULL,
   HAS_SUB_LEDGERS        VARCHAR2 (1) DEFAULT '0' NOT NULL,
   CONTROL_ACCOUNT_ID     NUMBER DEFAULT -1 NOT NULL,
   CRNCY_ID               NUMBER DEFAULT -1 NOT NULL,
   IS_SUSPENS_ACCNT       VARCHAR2 (1) DEFAULT '0' NOT NULL,
   CONSTRAINT PK_ACCNT_ID PRIMARY KEY (ACCNT_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX ACCB.IDX_ACCNT_DESC
   ON ACCB.ACCB_CHART_OF_ACCNTS (ACCNT_DESC)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_ACCNT_NAME
   ON ACCB.ACCB_CHART_OF_ACCNTS (ACCNT_NAME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_ACCNT_NUM
   ON ACCB.ACCB_CHART_OF_ACCNTS (ACCNT_NUM)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_ACCNT_TYP_ID
   ON ACCB.ACCB_CHART_OF_ACCNTS (ACCNT_TYP_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_BALANCE_DATE
   ON ACCB.ACCB_CHART_OF_ACCNTS (BALANCE_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_COA_CRNCY_ID
   ON ACCB.ACCB_CHART_OF_ACCNTS (CRNCY_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_REPORT_LINE_NO
   ON ACCB.ACCB_CHART_OF_ACCNTS (REPORT_LINE_NO)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE ACCB.ACCB_CHART_OF_ACCNTS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ACCB.ACCB_CHART_OF_ACCNTS_TRG
   BEFORE INSERT
   ON ACCB.ACCB_CHART_OF_ACCNTS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.ACCNT_ID IS NULL)
DECLARE
   V_ID   ACCB.ACCB_CHART_OF_ACCNTS.ACCNT_ID%TYPE;
BEGIN
   SELECT   ACCB.ACCB_CHART_OF_ACCNTS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.ACCNT_ID := V_ID;
END ACCB_CHART_OF_ACCNTS_TRG;