/* Formatted on 9/22/2014 1:24:16 PM (QP5 v5.126.903.23003) */
-- TABLE: ACCB.ACCB_DOC_TMPLTS_DET

-- DROP TABLE ACCB.ACCB_DOC_TMPLTS_DET;

CREATE TABLE ACCB.ACCB_DOC_TMPLTS_DET (
   DOC_TMPLT_DET_ID    NUMBER NOT NULL,
   DOC_TMPLTS_HDR_ID   NUMBER,
   LINE_ITEM_TYPE      VARCHAR2 (100),
   LINE_DESCRIPTION    VARCHAR2 (300),
   AUTO_CALC           VARCHAR2 (1),
   INCRS_DCRS          VARCHAR2 (15),
   COSTING_ACCNT_ID    NUMBER,
   CREATED_BY          NUMBER DEFAULT -1 NOT NULL,
   CREATION_DATE       VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY      NUMBER NOT NULL,
   LAST_UPDATE_DATE    VARCHAR2 (21),
   CODE_BEHIND_ID      NUMBER DEFAULT -1 NOT NULL,
   CONSTRAINT PK_DOC_TMPLT_DET_ID PRIMARY KEY (DOC_TMPLT_DET_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX ACCB.IDX_CODE_BEHIND_ID
   ON ACCB.ACCB_DOC_TMPLTS_DET (CODE_BEHIND_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_COSTING_ACCNT_ID
   ON ACCB.ACCB_DOC_TMPLTS_DET (COSTING_ACCNT_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_DOC_TMPLTS_HDR_ID1
   ON ACCB.ACCB_DOC_TMPLTS_DET (DOC_TMPLTS_HDR_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_LINE_ITEM_TYPE
   ON ACCB.ACCB_DOC_TMPLTS_DET (LINE_ITEM_TYPE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE ACCB.ACCB_DOC_TMPLTS_DET_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ACCB.ACCB_DOC_TMPLTS_DET_TRG
   BEFORE INSERT
   ON ACCB.ACCB_DOC_TMPLTS_DET
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.DOC_TMPLT_DET_ID IS NULL)
DECLARE
   V_ID   ACCB.ACCB_DOC_TMPLTS_DET.DOC_TMPLT_DET_ID%TYPE;
BEGIN
   SELECT   ACCB.ACCB_DOC_TMPLTS_DET_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.DOC_TMPLT_DET_ID := V_ID;
END ACCB_DOC_TMPLTS_DET_TRG;