/* Formatted on 12-14-2018 6:53:55 PM (QP5 v5.126.903.23003) */
DROP TABLE ACCB.ACCB_PYBLS_INVC_HDR  CASCADE CONSTRAINTS PURGE;

CREATE TABLE ACCB.ACCB_PYBLS_INVC_HDR (
   PYBLS_INVC_HDR_ID        NUMBER NOT NULL,
   PYBLS_INVC_DATE          VARCHAR2 (21),
   CREATED_BY               NUMBER,
   CREATION_DATE            VARCHAR2 (50),
   LAST_UPDATE_BY           NUMBER,
   LAST_UPDATE_DATE         VARCHAR2 (50),
   PYBLS_INVC_NUMBER        VARCHAR2 (100),
   PYBLS_INVC_TYPE          VARCHAR2 (50),
   COMMENTS_DESC            VARCHAR2 (300),
   SRC_DOC_HDR_ID           NUMBER,
   SUPPLIER_ID              NUMBER,
   SUPPLIER_SITE_ID         NUMBER,
   APPROVAL_STATUS          VARCHAR2 (100),
   NEXT_APROVAL_ACTION      VARCHAR2 (100),
   ORG_ID                   NUMBER,
   INVOICE_AMOUNT           NUMBER,
   PAYMENT_TERMS            CLOB,
   SRC_DOC_TYPE             VARCHAR2 (200),
   PYMNY_METHOD_ID          NUMBER,
   AMNT_PAID                NUMBER,
   GL_BATCH_ID              NUMBER,
   SPPLRS_INVC_NUM          VARCHAR2 (100),
   DOC_TMPLT_CLSFCTN        VARCHAR2 (200),
   INVC_CURR_ID             NUMBER,
   INVC_AMNT_APPLD_ELSWHR   NUMBER DEFAULT 0 NOT NULL,
   debt_gl_batch_id         NUMBER DEFAULT -1 NOT NULL,
   event_rgstr_id           NUMBER DEFAULT -1 NOT NULL,
   evnt_cost_category       VARCHAR2 (200),
   event_doc_type           VARCHAR2 (100),
   balancing_accnt_id       INTEGER DEFAULT -1 NOT NULL,
   advc_pay_ifo_doc_id      NUMBER DEFAULT -1 NOT NULL,
   advc_pay_ifo_doc_typ     VARCHAR2 (200),
   next_part_payment        NUMERIC DEFAULT 0 NOT NULL,
   firts_cheque_num         VARCHAR2 (200)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX ACCB.IDX_PYBLS_INVC_HDR_ID
   ON ACCB.ACCB_PYBLS_INVC_HDR (PYBLS_INVC_HDR_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_PYBLS_INVC_DATE
   ON ACCB.ACCB_PYBLS_INVC_HDR (PYBLS_INVC_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_PYBLS_INVC_NUMBER
   ON ACCB.ACCB_PYBLS_INVC_HDR (PYBLS_INVC_NUMBER)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_PYBLS_INVC_TYPE
   ON ACCB.ACCB_PYBLS_INVC_HDR (PYBLS_INVC_TYPE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_S_APPROVAL_STATUS
   ON ACCB.ACCB_PYBLS_INVC_HDR (APPROVAL_STATUS)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_S_CREATED_BY
   ON ACCB.ACCB_PYBLS_INVC_HDR (CREATED_BY)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_S_LAST_UPDATE_BY
   ON ACCB.ACCB_PYBLS_INVC_HDR (LAST_UPDATE_BY)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_S_SRC_DOC_HDR_ID
   ON ACCB.ACCB_PYBLS_INVC_HDR (SRC_DOC_HDR_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_SUPPLIER_ID
   ON ACCB.ACCB_PYBLS_INVC_HDR (SUPPLIER_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_SUPPLIER_SITE_ID
   ON ACCB.ACCB_PYBLS_INVC_HDR (SUPPLIER_SITE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;
DROP SEQUENCE ACCB.ACCB_PYBLS_INVC_HDR_SEQ;
CREATE SEQUENCE ACCB.ACCB_PYBLS_INVC_HDR_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   NOCACHE
   ORDER;

CREATE OR REPLACE TRIGGER ACCB.ACCB_PYBLS_INVC_HDR_TRG
   BEFORE INSERT
   ON ACCB.ACCB_PYBLS_INVC_HDR
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.PYBLS_INVC_HDR_ID IS NULL)
DECLARE
   V_ID   ACCB.ACCB_PYBLS_INVC_HDR.PYBLS_INVC_HDR_ID%TYPE;
BEGIN
   SELECT   ACCB.ACCB_PYBLS_INVC_HDR_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PYBLS_INVC_HDR_ID := V_ID;
END ACCB_PYBLS_INVC_HDR_TRG;