/* Formatted on 9/22/2014 3:39:22 PM (QP5 v5.126.903.23003) */
-- TABLE: ACCB.ACCB_MEMO_ACCOUNTS

--DROP TABLE ACCB.ACCB_MEMO_ACCOUNTS;

CREATE TABLE ACCB.ACCB_MEMO_ACCOUNTS (
   MEMO_ACCNT_ID        NUMBER NOT NULL,
   MEMO_ACCNT_NUM       VARCHAR2 (25),
   MEMO_ACCNT_NAME      VARCHAR2 (100),
   MEMO_ACCNT_DESC      VARCHAR2 (200),
   IS_ENABLED           VARCHAR2 (1),
   ORG_ID               NUMBER,
   ACCNT_TYPE           VARCHAR2 (2),
   ACCNT_TYPE_ID        NUMBER,
   CRNCY_ID             NUMBER,
   DFLT_COST_ACCNT_ID   NUMBER,
   DFLT_BALS_ACCNT_ID   NUMBER,
   USES_SQL             VARCHAR2 (1),
   SQL_FORMULAR         CLOB,
   CREATED_BY           NUMBER NOT NULL,
   CREATION_DATE        VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY       NUMBER NOT NULL,
   LAST_UPDATE_DATE     VARCHAR2 (21) NOT NULL,
   CONSTRAINT PK_MEMO_ACCNT_ID PRIMARY KEY (MEMO_ACCNT_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX ACCB.IDX_MEMO_ACCNT_NUM
   ON ACCB.ACCB_MEMO_ACCOUNTS (MEMO_ACCNT_NUM)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_MEMO_ACCNT_NAME
   ON ACCB.ACCB_MEMO_ACCOUNTS (MEMO_ACCNT_NAME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE ACCB.ACCB_MEMO_ACCOUNTS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ACCB.ACCB_MEMO_ACCOUNTS_TRG
   BEFORE INSERT
   ON ACCB.ACCB_MEMO_ACCOUNTS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.MEMO_ACCNT_ID IS NULL)
DECLARE
   V_ID   ACCB.ACCB_MEMO_ACCOUNTS.MEMO_ACCNT_ID%TYPE;
BEGIN
   SELECT   ACCB.ACCB_MEMO_ACCOUNTS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.MEMO_ACCNT_ID := V_ID;
END ACCB_MEMO_ACCOUNTS_TRG;