/* Formatted on 9/22/2014 4:54:49 PM (QP5 v5.126.903.23003) */
-- TABLE: ACCB.ACCB_PAYMNT_MTHDS

-- DROP TABLE ACCB.ACCB_PAYMNT_MTHDS;

CREATE TABLE ACCB.ACCB_PAYMNT_MTHDS (
   PAYMNT_MTHD_ID         NUMBER NOT NULL,
   PYMNT_MTHD_NAME        VARCHAR2 (200),
   PYMNT_MTHD_DESC        VARCHAR2 (300),
   CURRENT_ASST_ACNT_ID   NUMBER,
   CREATED_BY             NUMBER NOT NULL,
   CREATION_DATE          VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY         NUMBER NOT NULL,
   LAST_UPDATE_DATE       VARCHAR2 (21) NOT NULL,
   SUPPORTED_DOC_TYPE     VARCHAR2 (100),
   BCKGRND_PROCESS_NAME   VARCHAR2 (200),
   ORG_ID                 NUMBER,
   IS_ENABLED             VARCHAR2 (1),
   CONSTRAINT PK_PYMNT_MTHD_ID PRIMARY KEY (PAYMNT_MTHD_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX ACCB.IDX_BCKGRND_PROCESS_NAME
   ON ACCB.ACCB_PAYMNT_MTHDS (BCKGRND_PROCESS_NAME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_CURRENT_ASST_ACNT_ID
   ON ACCB.ACCB_PAYMNT_MTHDS (CURRENT_ASST_ACNT_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_IS_ENABLED
   ON ACCB.ACCB_PAYMNT_MTHDS (IS_ENABLED)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_ORG_ID1
   ON ACCB.ACCB_PAYMNT_MTHDS (ORG_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE INDEX ACCB.IDX_PYMNT_MTHD_NAME
   ON ACCB.ACCB_PAYMNT_MTHDS (PYMNT_MTHD_NAME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_SUPPORTED_DOC_TYPE
   ON ACCB.ACCB_PAYMNT_MTHDS (SUPPORTED_DOC_TYPE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE ACCB.ACCB_PAYMNT_MTHDS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ACCB.ACCB_PAYMNT_MTHDS_TRG
   BEFORE INSERT
   ON ACCB.ACCB_PAYMNT_MTHDS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.PAYMNT_MTHD_ID IS NULL)
DECLARE
   V_ID   ACCB.ACCB_PAYMNT_MTHDS.PAYMNT_MTHD_ID%TYPE;
BEGIN
   SELECT   ACCB.ACCB_PAYMNT_MTHDS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PAYMNT_MTHD_ID := V_ID;
END ACCB_PAYMNT_MTHDS_TRG;