/* Formatted on 24/09/2014 14:23:49 (QP5 v5.126.903.23003) */
-- TABLE: ACCB.ACCB_PERIOD_CLOSE_DATES

-- DROP TABLE ACCB.ACCB_PERIOD_CLOSE_DATES;

CREATE TABLE ACCB.ACCB_PERIOD_CLOSE_DATES (
   PERIOD_CLOSE_ID            NUMBER NOT NULL,
   PERIOD_CLOSE_DATE          VARCHAR2 (21) NOT NULL,
   RUN_BY                     NUMBER NOT NULL,
   RUN_DATE                   VARCHAR2 (21),
   PERIOD_CLOSE_DESCRIPTION   VARCHAR2 (300),
   ORG_ID                     NUMBER,
   IS_POSTED                  VARCHAR2 (1) NOT NULL,
   GL_BATCH_ID                NUMBER DEFAULT (-1) NOT NULL,
   CONSTRAINT PK_PERIOD_CLOSE_ID PRIMARY KEY (PERIOD_CLOSE_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX ACCB.IDX_GL_BATCH_ID
   ON ACCB.ACCB_PERIOD_CLOSE_DATES (GL_BATCH_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_IS_POSTED
   ON ACCB.ACCB_PERIOD_CLOSE_DATES (IS_POSTED)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_ORG_ID2
   ON ACCB.ACCB_PERIOD_CLOSE_DATES (ORG_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_PERIOD_CLOSE_DATE
   ON ACCB.ACCB_PERIOD_CLOSE_DATES (PERIOD_CLOSE_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_RUN_BY
   ON ACCB.ACCB_PERIOD_CLOSE_DATES (RUN_BY)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_RUN_DATE
   ON ACCB.ACCB_PERIOD_CLOSE_DATES (RUN_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE ACCB.ACCB_PERIOD_CLOSE_DATES_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ACCB.ACCB_PERIOD_CLOSE_DATES_TRG
   BEFORE INSERT
   ON ACCB.ACCB_PERIOD_CLOSE_DATES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.PERIOD_CLOSE_ID IS NULL)
DECLARE
   V_ID   ACCB.ACCB_PERIOD_CLOSE_DATES.PERIOD_CLOSE_ID%TYPE;
BEGIN
   SELECT   ACCB.ACCB_PERIOD_CLOSE_DATES_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PERIOD_CLOSE_ID := V_ID;
END ACCB_PERIOD_CLOSE_DATES_TRG;