/* Formatted on 24/09/2014 15:20:01 (QP5 v5.126.903.23003) */
-- TABLE: ACCB.ACCB_PERIODS_DET

-- DROP TABLE ACCB.ACCB_PERIODS_DET;

CREATE TABLE ACCB.ACCB_PERIODS_DET (
   PERIOD_DET_ID       NUMBER NOT NULL,
   PERIOD_HDR_ID       NUMBER,
   PERIOD_START_DATE   VARCHAR2 (21),
   PERIOD_END_DATE     VARCHAR2 (21),
   CREATED_BY          NUMBER NOT NULL,
   CREATION_DATE       CHARACTER (21) NOT NULL,
   LAST_UPDATE_BY      NUMBER NOT NULL,
   LAST_UPDATE_DATE    VARCHAR2 (21) NOT NULL,
   PERIOD_DET_NAME     VARCHAR2 (200),
   PERIOD_STATUS       VARCHAR2 (100),
   CONSTRAINT PK_PERIOD_DET_ID PRIMARY KEY (PERIOD_DET_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX ACCB.IDX_PERIOD_DET_NAME
   ON ACCB.ACCB_PERIODS_DET (PERIOD_DET_NAME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_PERIOD_END_DATE
   ON ACCB.ACCB_PERIODS_DET (PERIOD_END_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_PERIOD_HDR_ID1
   ON ACCB.ACCB_PERIODS_DET (PERIOD_HDR_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_PERIOD_START_DATE
   ON ACCB.ACCB_PERIODS_DET (PERIOD_START_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_PERIOD_STATUS
   ON ACCB.ACCB_PERIODS_DET (PERIOD_STATUS)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE ACCB.ACCB_PERIODS_DET_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ACCB.ACCB_PERIODS_DET_TRG
   BEFORE INSERT
   ON ACCB.ACCB_PERIODS_DET
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.PERIOD_DET_ID IS NULL)
DECLARE
   V_ID   ACCB.ACCB_PERIODS_DET.PERIOD_DET_ID%TYPE;
BEGIN
   SELECT   ACCB.ACCB_PERIODS_DET_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PERIOD_DET_ID := V_ID;
END ACCB_PERIODS_DET_TRG;