/* Formatted on 25/09/2014 12:43:28 (QP5 v5.126.903.23003) */
-- TABLE: ACCB.ACCB_PYBLS_AMNT_SMMRYS

-- DROP TABLE ACCB.ACCB_PYBLS_AMNT_SMMRYS;

CREATE TABLE ACCB.ACCB_PYBLS_AMNT_SMMRYS (
   PYBLS_SMMRY_ID          NUMBER NOT NULL,
   PYBLS_SMMRY_TYPE        VARCHAR2 (100) NOT NULL,
   PYBLS_SMMRY_DESC        VARCHAR2 (200),
   PYBLS_SMMRY_AMNT        NUMBER,
   CODE_ID_BEHIND          NUMBER,
   SRC_PYBLS_TYPE          VARCHAR2 (100),
   SRC_PYBLS_HDR_ID        NUMBER,
   CREATED_BY              NUMBER,
   CREATION_DATE           VARCHAR2 (21),
   LAST_UPDATE_BY          NUMBER,
   LAST_UPDATE_DATE        VARCHAR2 (21),
   AUTO_CALC               VARCHAR2 (1) DEFAULT '1' NOT NULL,
   INCRS_DCRS1             VARCHAR2 (15),
   ASSET_EXPNS_ACNT_ID     NUMBER,
   INCRS_DCRS2             VARCHAR2 (15),
   LIABILITY_ACNT_ID       NUMBER,
   APPLD_PREPYMNT_DOC_ID   NUMBER,
   VALIDTY_STATUS          VARCHAR2 (10) DEFAULT '1' NOT NULL,
   ORGNL_LINE_ID           NUMBER DEFAULT (-1) NOT NULL,
   ENTRD_CURR_ID           NUMBER,
   FUNC_CURR_ID            NUMBER,
   ACCNT_CURR_ID           NUMBER,
   FUNC_CURR_RATE          NUMBER,
   ACCNT_CURR_RATE         NUMBER,
   FUNC_CURR_AMOUNT        NUMBER,
   ACCNT_CURR_AMNT         NUMBER,
   CONSTRAINT PK_PYBLS_SMMRY_ID PRIMARY KEY (PYBLS_SMMRY_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX ACCB.IDX_CODE_ID_BEHIND
   ON ACCB.ACCB_PYBLS_AMNT_SMMRYS (CODE_ID_BEHIND)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_PYBLS_SMMRY_DESC
   ON ACCB.ACCB_PYBLS_AMNT_SMMRYS (PYBLS_SMMRY_DESC)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_PYBLS_SMMRY_TYPE
   ON ACCB.ACCB_PYBLS_AMNT_SMMRYS (PYBLS_SMMRY_TYPE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_SMRY_SRC_PYBLS_HDR_ID
   ON ACCB.ACCB_PYBLS_AMNT_SMMRYS (SRC_PYBLS_HDR_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_SMRY_SRC_PYBLS_TYPE
   ON ACCB.ACCB_PYBLS_AMNT_SMMRYS (SRC_PYBLS_TYPE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE ACCB.ACCB_PYBLS_AMNT_SMMRYS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ACCB.ACCB_PYBLS_AMNT_SMMRYS_TRG
   BEFORE INSERT
   ON ACCB.ACCB_PYBLS_AMNT_SMMRYS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.PYBLS_SMMRY_ID IS NULL)
DECLARE
   V_ID   ACCB.ACCB_PYBLS_AMNT_SMMRYS.PYBLS_SMMRY_ID%TYPE;
BEGIN
   SELECT   ACCB.ACCB_PYBLS_AMNT_SMMRYS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PYBLS_SMMRY_ID := V_ID;
END ACCB_PYBLS_AMNT_SMMRYS_TRG;