/* Formatted on 25/09/2014 15:38:39 (QP5 v5.126.903.23003) */
-- TABLE: ACCB.ACCB_RCVBLS_INVC_HDR

-- DROP TABLE ACCB.ACCB_RCVBLS_INVC_HDR;

CREATE TABLE ACCB.ACCB_RCVBLS_INVC_HDR (
   RCVBLS_INVC_HDR_ID       NUMBER NOT NULL,
   RCVBLS_INVC_DATE         VARCHAR2 (21),
   CREATED_BY               NUMBER,
   CREATION_DATE            VARCHAR2 (50),
   LAST_UPDATE_BY           NUMBER,
   LAST_UPDATE_DATE         VARCHAR2 (50),
   RCVBLS_INVC_NUMBER       VARCHAR2 (100),
   RCVBLS_INVC_TYPE         VARCHAR2 (50),
   COMMENTS_DESC            VARCHAR2 (300),
   SRC_DOC_HDR_ID           NUMBER,
   CUSTOMER_ID              NUMBER,
   CUSTOMER_SITE_ID         NUMBER,
   APPROVAL_STATUS          VARCHAR2 (100),
   NEXT_APROVAL_ACTION      VARCHAR2 (100),
   ORG_ID                   NUMBER,
   INVOICE_AMOUNT           NUMBER,
   PAYMENT_TERMS            CLOB,
   SRC_DOC_TYPE             VARCHAR2 (200),
   PYMNY_METHOD_ID          NUMBER,
   AMNT_PAID                NUMBER,
   GL_BATCH_ID              NUMBER,
   CSTMRS_DOC_NUM           VARCHAR2 (100),
   DOC_TMPLT_CLSFCTN        VARCHAR2 (200),
   INVC_CURR_ID             NUMBER,
   INVC_AMNT_APPLD_ELSWHR   NUMBER,
   BALANCING_ACCNT_ID       NUMBER DEFAULT (-1) NOT NULL,
   CONSTRAINT PK_RCVBLS_INVC_HDR_ID PRIMARY KEY (RCVBLS_INVC_HDR_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX ACCB.IDX_CUSTOMER_ID
   ON ACCB.ACCB_RCVBLS_INVC_HDR (CUSTOMER_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_CUSTOMER_SITE_ID
   ON ACCB.ACCB_RCVBLS_INVC_HDR (CUSTOMER_SITE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_R_APPROVAL_STATUS
   ON ACCB.ACCB_RCVBLS_INVC_HDR (APPROVAL_STATUS)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_R_CREATED_BY
   ON ACCB.ACCB_RCVBLS_INVC_HDR (CREATED_BY)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_R_LAST_UPDATE_BY
   ON ACCB.ACCB_RCVBLS_INVC_HDR (LAST_UPDATE_BY)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_R_SRC_DOC_HDR_ID
   ON ACCB.ACCB_RCVBLS_INVC_HDR (SRC_DOC_HDR_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_RCVBLS_INVC_DATE
   ON ACCB.ACCB_RCVBLS_INVC_HDR (RCVBLS_INVC_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_RCVBLS_INVC_NUMBER
   ON ACCB.ACCB_RCVBLS_INVC_HDR (RCVBLS_INVC_NUMBER)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_RCVBLS_INVC_TYPE
   ON ACCB.ACCB_RCVBLS_INVC_HDR (RCVBLS_INVC_TYPE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE SEQUENCE ACCB.ACCB_RCVBLS_INVC_HDR_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ACCB.ACCB_RCVBLS_INVC_HDR_TRG
   BEFORE INSERT
   ON ACCB.ACCB_RCVBLS_INVC_HDR
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.RCVBLS_INVC_HDR_ID IS NULL)
DECLARE
   V_ID   ACCB.ACCB_RCVBLS_INVC_HDR.RCVBLS_INVC_HDR_ID%TYPE;
BEGIN
   SELECT   ACCB.ACCB_RCVBLS_INVC_HDR_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.RCVBLS_INVC_HDR_ID := V_ID;
END ACCB_RCVBLS_INVC_HDR_TRG;