/* Formatted on 25/09/2014 15:49:45 (QP5 v5.126.903.23003) */
-- TABLE: ACCB.ACCB_RUNNING_PRCSES

--DROP TABLE ACCB.ACCB_RUNNING_PRCSES;

CREATE TABLE ACCB.ACCB_RUNNING_PRCSES (
   PROCESS_ID              NUMBER NOT NULL,
   WHICH_PROCESS_IS_RNNG   NUMBER DEFAULT (-1) NOT NULL,
   LAST_ACTIVE_TIME        VARCHAR2 (21),
   PROCESS_TYPE            VARCHAR2 (200) DEFAULT '' NOT NULL,
   CONSTRAINT PK_PRCSS_ID PRIMARY KEY (PROCESS_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX ACCB.IDX_LAST_ACTIVE_TIME
   ON ACCB.ACCB_RUNNING_PRCSES (LAST_ACTIVE_TIME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_PROCESS_TYPE1
   ON ACCB.ACCB_RUNNING_PRCSES (PROCESS_TYPE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_WHICH_PROCESS_IS_RNNG
   ON ACCB.ACCB_RUNNING_PRCSES (WHICH_PROCESS_IS_RNNG)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE ACCB.ACCB_RUNNING_PRCSES_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ACCB.ACCB_RUNNING_PRCSES_TRG
   BEFORE INSERT
   ON ACCB.ACCB_RUNNING_PRCSES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.PROCESS_ID IS NULL)
DECLARE
   V_ID   ACCB.ACCB_RUNNING_PRCSES.PROCESS_ID%TYPE;
BEGIN
   SELECT   ACCB.ACCB_RUNNING_PRCSES_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.PROCESS_ID := V_ID;
END ACCB_RUNNING_PRCSES_TRG;