/* Formatted on 25/09/2014 15:54:08 (QP5 v5.126.903.23003) */
-- TABLE: ACCB.ACCB_TRNSCTN_AMNT_BREAKDOWN

--DROP TABLE ACCB.ACCB_TRNSCTN_AMNT_BREAKDOWN;

CREATE TABLE ACCB.ACCB_TRNSCTN_AMNT_BREAKDOWN (
   TRANSACTION_ID      NUMBER,
   DESCRIPTION         VARCHAR2 (300),
   QUANTITY            NUMBER,
   UNIT_AMNT           NUMBER,
   TTL_AMNT            NUMBER,
   CREATED_BY          NUMBER NOT NULL,
   CREATION_DATE       VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY      NUMBER NOT NULL,
   LAST_UPDATE_DATE    VARCHAR2 (21) NOT NULL,
   TRNS_AMNT_DET_ID    NUMBER NOT NULL,
   LNKD_PSSBL_VAL_ID   INTEGER DEFAULT (-1) NOT NULL,
   CONSTRAINT PK_TRNS_AMNT_DET_ID PRIMARY KEY (TRNS_AMNT_DET_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX ACCB.IDX_DESCRIPTION1
   ON ACCB.ACCB_TRNSCTN_AMNT_BREAKDOWN (DESCRIPTION)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE INDEX ACCB.IDX_LNKD_PSSBL_VAL_ID
   ON ACCB.ACCB_TRNSCTN_AMNT_BREAKDOWN (LNKD_PSSBL_VAL_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_TRANSACTION_ID1
   ON ACCB.ACCB_TRNSCTN_AMNT_BREAKDOWN (TRANSACTION_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE ACCB.ACCB_TRNS_AMNT_BRKDWN_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ACCB.ACCB_TRNS_AMNT_BRKDWN_TRG
   BEFORE INSERT
   ON ACCB.ACCB_TRNSCTN_AMNT_BREAKDOWN
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.TRNS_AMNT_DET_ID IS NULL)
DECLARE
   V_ID   ACCB.ACCB_TRNSCTN_AMNT_BREAKDOWN.TRNS_AMNT_DET_ID%TYPE;
BEGIN
   SELECT   ACCB.ACCB_TRNS_AMNT_BRKDWN_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.TRNS_AMNT_DET_ID := V_ID;
END ACCB_TRNS_AMNT_BRKDWN_TRG;