/* Formatted on 25/09/2014 16:01:51 (QP5 v5.126.903.23003) */
-- TABLE: ACCB.ACCB_TRNSCTN_BATCHES

-- DROP TABLE ACCB.ACCB_TRNSCTN_BATCHES;

CREATE TABLE ACCB.ACCB_TRNSCTN_BATCHES (
   BATCH_ID             NUMBER NOT NULL,
   BATCH_NAME           VARCHAR2 (300) NOT NULL,
   BATCH_DESCRIPTION    VARCHAR2 (500),
   CREATED_BY           NUMBER NOT NULL,
   CREATION_DATE        VARCHAR2 (21) NOT NULL,
   ORG_ID               NUMBER,
   BATCH_STATUS         VARCHAR2 (1),
   LAST_UPDATE_BY       NUMBER NOT NULL,
   LAST_UPDATE_DATE     VARCHAR2 (21) NOT NULL,
   BATCH_SOURCE         VARCHAR2 (200) DEFAULT 'Manual' NOT NULL,
   BATCH_VLDTY_STATUS   VARCHAR2 (5) DEFAULT 'VALID' NOT NULL,
   SRC_BATCH_ID         NUMBER DEFAULT -1 NOT NULL,
   AVLBL_FOR_POSTNG     VARCHAR2 (1) DEFAULT '0' NOT NULL,
   CONSTRAINT PK_BATCH_ID PRIMARY KEY (BATCH_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX ACCB.IDX_AVLBL_FOR_POSTNG
   ON ACCB.ACCB_TRNSCTN_BATCHES (AVLBL_FOR_POSTNG)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_BATCH_DESCRIPTION
   ON ACCB.ACCB_TRNSCTN_BATCHES (BATCH_DESCRIPTION)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_BATCH_NAME
   ON ACCB.ACCB_TRNSCTN_BATCHES (BATCH_NAME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_BATCH_SOURCE
   ON ACCB.ACCB_TRNSCTN_BATCHES (BATCH_SOURCE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_BATCH_STATUS
   ON ACCB.ACCB_TRNSCTN_BATCHES (BATCH_STATUS)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_BATCH_VLDTY_STATUS1
   ON ACCB.ACCB_TRNSCTN_BATCHES (BATCH_VLDTY_STATUS)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_ORG_ID4
   ON ACCB.ACCB_TRNSCTN_BATCHES (ORG_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_SRC_BATCH_ID
   ON ACCB.ACCB_TRNSCTN_BATCHES (SRC_BATCH_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE ACCB.ACCB_TRNSCTN_BATCHES_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ACCB.ACCB_TRNSCTN_BATCHES_TRG
   BEFORE INSERT
   ON ACCB.ACCB_TRNSCTN_BATCHES
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.BATCH_ID IS NULL)
DECLARE
   V_ID   ACCB.ACCB_TRNSCTN_BATCHES.BATCH_ID%TYPE;
BEGIN
   SELECT   ACCB.ACCB_TRNSCTN_BATCHES_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.BATCH_ID := V_ID;
END ACCB_TRNSCTN_BATCHES_TRG;