/* Formatted on 25/09/2014 16:08:42 (QP5 v5.126.903.23003) */
-- TABLE: ACCB.ACCB_TRNSCTN_DETAILS

-- DROP TABLE ACCB.ACCB_TRNSCTN_DETAILS;

CREATE TABLE ACCB.ACCB_TRNSCTN_DETAILS (
   TRANSCTN_ID             NUMBER NOT NULL,
   ACCNT_ID                NUMBER,
   TRANSACTION_DESC        VARCHAR2 (500) NOT NULL,
   DBT_AMOUNT              NUMBER DEFAULT 0.00 NOT NULL,
   TRNSCTN_DATE            VARCHAR2 (21),
   FUNC_CUR_ID             NUMBER,
   CREATED_BY              NUMBER NOT NULL,
   CREATION_DATE           VARCHAR2 (21),
   BATCH_ID                NUMBER NOT NULL,
   CRDT_AMOUNT             NUMBER DEFAULT 0.00 NOT NULL,
   LAST_UPDATE_BY          NUMBER NOT NULL,
   LAST_UPDATE_DATE        VARCHAR2 (21) NOT NULL,
   NET_AMOUNT              NUMBER DEFAULT 0.00 NOT NULL,
   TRNS_STATUS             VARCHAR2 (1) DEFAULT 0 NOT NULL,
   SOURCE_TRNS_IDS         CLOB DEFAULT ',' NOT NULL,
   ENTERED_AMNT            NUMBER DEFAULT 0 NOT NULL,
   ENTERED_AMT_CRNCY_ID    NUMBER DEFAULT (-1) NOT NULL,
   ACCNT_CRNCY_AMNT        NUMBER DEFAULT 0 NOT NULL,
   ACCNT_CRNCY_ID          NUMBER DEFAULT (-1) NOT NULL,
   FUNC_CUR_EXCHNG_RATE    NUMERIC DEFAULT 1 NOT NULL,
   ACCNT_CUR_EXCHNG_RATE   NUMERIC DEFAULT 1 NOT NULL,
   DBT_OR_CRDT             VARCHAR2 (1) DEFAULT 'U' NOT NULL,
   CONSTRAINT PK_TRNS_ID PRIMARY KEY (TRANSCTN_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX ACCB.IDX_TRANSACTION_DESC
   ON ACCB.ACCB_TRNSCTN_DETAILS (TRANSACTION_DESC)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_TRNS_ACCNT_ID
   ON ACCB.ACCB_TRNSCTN_DETAILS (ACCNT_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_TRNS_BATCH_ID
   ON ACCB.ACCB_TRNSCTN_DETAILS (BATCH_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_TRNSCTN_DATE
   ON ACCB.ACCB_TRNSCTN_DETAILS (TRNSCTN_DATE)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE ACCB.ACCB_TRNSCTN_DETAILS_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ACCB.ACCB_TRNSCTN_DETAILS_TRG
   BEFORE INSERT
   ON ACCB.ACCB_TRNSCTN_DETAILS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.TRANSCTN_ID IS NULL)
DECLARE
   V_ID   ACCB.ACCB_TRNSCTN_DETAILS.TRANSCTN_ID%TYPE;
BEGIN
   SELECT   ACCB.ACCB_TRNSCTN_DETAILS_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.TRANSCTN_ID := V_ID;
END ACCB_TRNSCTN_DETAILS_TRG;