/* Formatted on 25/09/2014 16:14:26 (QP5 v5.126.903.23003) */
-- TABLE: ACCB.ACCB_TRNSCTN_TEMPLATES_DET

-- DROP TABLE ACCB.ACCB_TRNSCTN_TEMPLATES_DET;

CREATE TABLE ACCB.ACCB_TRNSCTN_TEMPLATES_DET (
   DETAIL_ID           NUMBER NOT NULL,
   TEMPLATE_ID         NUMBER,
   ACCNT_ID            NUMBER,
   INCREASE_DECREASE   VARCHAR2 (1),
   TRNSTN_DESC         VARCHAR2 (200),
   CREATED_BY          NUMBER NOT NULL,
   CREATION_DATE       VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY      NUMBER NOT NULL,
   LAST_UPDATE_DATE    VARCHAR2 (21) NOT NULL,
   CONSTRAINT PK_DETAIL_ID PRIMARY KEY (DETAIL_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX ACCB.IDX_D_TEMPLATE_ID
   ON ACCB.ACCB_TRNSCTN_TEMPLATES_DET (TEMPLATE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_DT_ACCNT_ID
   ON ACCB.ACCB_TRNSCTN_TEMPLATES_DET (ACCNT_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_DT_TRNSTN_DESC
   ON ACCB.ACCB_TRNSCTN_TEMPLATES_DET (TRNSTN_DESC)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE SEQUENCE ACCB.ACCB_TRNSCTN_TEMPLATES_DET_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ACCB.ACCB_TRNSCTN_TEMPLATES_DET_TRG
   BEFORE INSERT
   ON ACCB.ACCB_TRNSCTN_TEMPLATES_DET
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.DETAIL_ID IS NULL)
DECLARE
   V_ID   ACCB.ACCB_TRNSCTN_TEMPLATES_DET.DETAIL_ID%TYPE;
BEGIN
   SELECT   ACCB.ACCB_TRNSCTN_TEMPLATES_DET_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.DETAIL_ID := V_ID;
END ACCB_TRNSCTN_TEMPLATES_DET_TRG;