/* Formatted on 25/09/2014 16:22:52 (QP5 v5.126.903.23003) */
-- TABLE: ACCB.ACCB_TRNSCTN_TEMPLATES_HDR

-- DROP TABLE ACCB.ACCB_TRNSCTN_TEMPLATES_HDR;

CREATE TABLE ACCB.ACCB_TRNSCTN_TEMPLATES_HDR (
   TEMPLATE_ID            NUMBER NOT NULL,
   TEMPLATE_NAME          VARCHAR2 (200),
   TEMPLATE_DESCRIPTION   VARCHAR2 (200),
   CREATED_BY             NUMBER NOT NULL,
   CREATION_DATE          VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY         NUMBER NOT NULL,
   LAST_UPDATE_DATE       VARCHAR2 (21) NOT NULL,
   ORG_ID                 NUMBER,
   CONSTRAINT PK_TEMPLATE_ID PRIMARY KEY (TEMPLATE_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX ACCB.IDX_TEMPLATE_DESCRIPTION
   ON ACCB.ACCB_TRNSCTN_TEMPLATES_HDR (TEMPLATE_DESCRIPTION)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_TEMPLATE_NAME
   ON ACCB.ACCB_TRNSCTN_TEMPLATES_HDR (TEMPLATE_NAME)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE SEQUENCE ACCB.ACCB_TRNSCTN_TEMPLATES_HDR_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ACCB.ACCB_TRNSCTN_TEMPLATES_HDR_TRG
   BEFORE INSERT
   ON ACCB.ACCB_TRNSCTN_TEMPLATES_HDR
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.TEMPLATE_ID IS NULL)
DECLARE
   V_ID   ACCB.ACCB_TRNSCTN_TEMPLATES_HDR.TEMPLATE_ID%TYPE;
BEGIN
   SELECT   ACCB.ACCB_TRNSCTN_TEMPLATES_HDR_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.TEMPLATE_ID := V_ID;
END ACCB_TRNSCTN_TEMPLATES_HDR_TRG;