/* Formatted on 10/6/2014 7:17:42 PM (QP5 v5.126.903.23003) */
-- TABLE: ACCB.ACCB_TRNSCTN_TEMPLATES_USRS

-- DROP TABLE ACCB.ACCB_TRNSCTN_TEMPLATES_USRS;

CREATE TABLE ACCB.ACCB_TRNSCTN_TEMPLATES_USRS (
   ROW_ID             NUMBER NOT NULL,
   TEMPLATE_ID        NUMBER,
   USER_ID            NUMBER,
   VALID_START_DATE   VARCHAR2 (21) NOT NULL,
   VALID_END_DATE     VARCHAR2 (21) NOT NULL,
   CREATED_BY         NUMBER NOT NULL,
   CREATION_DATE      VARCHAR2 (21) NOT NULL,
   LAST_UPDATE_BY     NUMBER NOT NULL,
   LAST_UPDATE_DATE   VARCHAR2 (21) NOT NULL,
   CONSTRAINT PK_ROW_ID PRIMARY KEY (ROW_ID)
)
TABLESPACE RHODB
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX ACCB.IDX_US_TEMPLATE_ID
   ON ACCB.ACCB_TRNSCTN_TEMPLATES_USRS (TEMPLATE_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;

CREATE INDEX ACCB.IDX_US_USER_ID
   ON ACCB.ACCB_TRNSCTN_TEMPLATES_USRS (USER_ID)
   LOGGING
   TABLESPACE RHODB
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (PCTINCREASE 0 BUFFER_POOL DEFAULT)
   NOPARALLEL;


CREATE SEQUENCE ACCB.ACCB_TRNSCTN_TEMPLATES_USR_SEQ
   START WITH 1
   MAXVALUE 9223372036854775807
   MINVALUE 1
   NOCYCLE
   CACHE 20
   ORDER;

CREATE OR REPLACE TRIGGER ACCB.ACCB_TRNSCTN_TEMPLATES_USR_TRG
   BEFORE INSERT
   ON ACCB.ACCB_TRNSCTN_TEMPLATES_USRS
   FOR EACH ROW
   -- OPTIONALLY RESTRICT THIS TRIGGER TO FIRE ONLY WHEN REALLY NEEDED
   WHEN (NEW.ROW_ID IS NULL)
DECLARE
   V_ID   ACCB.ACCB_TRNSCTN_TEMPLATES_USRS.ROW_ID%TYPE;
BEGIN
   SELECT   ACCB.ACCB_TRNSCTN_TEMPLATES_USR_SEQ.NEXTVAL INTO V_ID FROM DUAL;

   :NEW.ROW_ID := V_ID;
END ACCB_TRNSCTN_TEMPLATES_USR_TRG;